import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata, breadcrumbJsonLd, SITE_URL } from '@/lib/seo';
import { kidsLabCategories, kidsLabSeries, KIDS_LAB_LEVELS, KIDS_LAB_TARGET_ITEMS } from '@/lib/capabilities/kids-lab-catalog';
import { attentionActivityCount } from '@/lib/capabilities/attention-lab';
import { memoryActivityCount } from '@/lib/capabilities/memory-lab';
import { executiveActivityCount } from '@/lib/capabilities/executive-functions-lab';
import { visualPerceptionActivityCount } from '@/lib/capabilities/visual-perception-lab';
import { bilateralActivities } from '@/lib/capabilities/bilateral-tracks';
import styles from './kids-lab.module.css';

export const metadata=buildSeoMetadata({title:'مختبر الأنشطة والاختبارات للأطفال | لنرتقي بقدراتهم',description:'مكتبة عربية متدرجة لأنشطة الأطفال القابلة للطباعة: 67 سلسلة مهارية، خمسة مستويات، تدريبان واختبار إتقان لكل مستوى، مع تصنيف حسب العمر والمهارة.',path:'/capabilities/kids-lab/',index:true,keywords:['أنشطة أطفال قابلة للطباعة','أوراق عمل للأطفال','اختبارات مهارات للأطفال','الانتباه والتركيز','الذاكرة','الوظائف التنفيذية','الإدراك البصري','المهارات الحركية']});

const flow=[['1','اختر السلسلة','ابدأ من المهارة المطلوبة والعمر المناسب، لا من اسم التشخيص وحده.'],['2','ابدأ بالمستوى المناسب','كل سلسلة تتدرج من مهام واضحة وبسيطة إلى مهام تتطلب استقلالًا ومرونة أكبر.'],['3','تدريبان ثم اختبار','لكل مستوى نشاطان تدريبيان ثم اختبار مختلف بصريًا لقياس الإتقان بدل حفظ الورقة.'],['4','انتقل بناءً على الأداء','إذا أتقن الطفل المهارة انتقل للمستوى التالي، وإلا استخدم تدريبًا إضافيًا أو تكييفًا مناسبًا.']];

export default function KidsLabPage(){const completed=attentionActivityCount+memoryActivityCount+executiveActivityCount+visualPerceptionActivityCount+bilateralActivities.length;const breadcrumbs=breadcrumbJsonLd([{name:'الرئيسية',path:'/'},{name:'لنرتقي بقدراتهم',path:'/sectors/capabilities'},{name:'مختبر الأنشطة والاختبارات للأطفال',path:'/capabilities/kids-lab/'}]);const collection={'@context':'https://schema.org','@type':'CollectionPage','@id':`${SITE_URL}/capabilities/kids-lab/#collection`,url:`${SITE_URL}/capabilities/kids-lab/`,name:'مختبر الأنشطة والاختبارات للأطفال',inLanguage:'ar',isAccessibleForFree:true,numberOfItems:kidsLabSeries.length,description:'سلاسل مهارية متدرجة للأطفال، لكل مستوى تدريبان واختبار إتقان قابلان للمعاينة والطباعة.'};return <><SiteHeader/><main className={styles.shell}>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([breadcrumbs,collection]).replace(/</g,'\\u003c')}}/><nav className="breadcrumbs" aria-label="مسار الصفحة"><Link href="/">الرئيسية</Link><span>/</span><Link href="/sectors/capabilities">لنرتقي بقدراتهم</Link><span>/</span><span aria-current="page">مختبر الأطفال</span></nav>
<section className={styles.hero}><span className={styles.kicker}>أنشطة جميلة، متدرجة، قابلة للطباعة</span><h1>مختبر الأنشطة والاختبارات للأطفال</h1><p className={styles.lead}>ليس مستودع أوراق عشوائيًا. كل مهارة تتحول إلى سلسلة من خمسة مستويات، وكل مستوى يحتوي تدريبين ثم اختبار إتقان مستقل. ألوان واضحة، مساحة عمل كبيرة، تعليمات قصيرة، ومعاينة كاملة قبل الطباعة.</p><div className={styles.stats}><div className={styles.stat}><strong>{kidsLabSeries.length}</strong><span>سلسلة مهارية مخططة</span></div><div className={styles.stat}><strong>{KIDS_LAB_LEVELS}</strong><span>مستويات لكل سلسلة</span></div><div className={styles.stat}><strong>{completed}</strong><span>عنصرًا مكتملًا فعليًا</span></div><div className={styles.stat}><strong>{KIDS_LAB_TARGET_ITEMS}</strong><span>نشاط واختبار مستهدف</span></div></div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><h2>كيف يعمل التدرج؟</h2><p>لا ينتقل الطفل لأنه أنهى الورقة، بل لأن أداءه في اختبار المستوى يدل على جاهزية مناسبة للمهمة التالية.</p></div></div><div className={styles.flow}>{flow.map(([n,t,b])=><article className={styles.flowCard} key={n}><span className={styles.flowNumber}>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>
<section className={styles.section}><div className={styles.launchCard}><div><span className={styles.kicker}>المجال الأول مكتمل</span><h2>الانتباه والتركيز - {attentionActivityCount} عنصرًا</h2><p>8 سلاسل من الانتباه الانتقائي والمستمر إلى تبديل القاعدة وسرعة المعالجة والانتباه المزدوج.</p><div className={styles.actions}><Link className={styles.primaryButton} href="/capabilities/kids-lab/attention/">افتح مجال الانتباه</Link></div></div><div className={styles.launchVisual} aria-hidden="true"><div className={styles.track}/><div className={`${styles.track} ${styles.trackBlue}`}/></div></div></section>
<section className={styles.section}><div className={styles.launchCard}><div><span className={styles.kicker}>المجال الثاني مكتمل</span><h2>الذاكرة - {memoryActivityCount} عنصرًا</h2><p>7 سلاسل تفصل الذاكرة البصرية والمكانية والتسلسلية والسمعية والترابطية وذاكرة التعليمات والتذكر بعد التداخل.</p><div className={styles.actions}><Link className={styles.primaryButton} href="/capabilities/kids-lab/memory/">افتح مجال الذاكرة</Link></div></div><div className={styles.launchVisual} aria-hidden="true"><div className={styles.track}/><div className={`${styles.track} ${styles.trackBlue}`}/></div></div></section>
<section className={styles.section}><div className={styles.launchCard}><div><span className={styles.kicker}>المجال الثالث مكتمل</span><h2>الوظائف التنفيذية - {executiveActivityCount} عنصرًا</h2><p>8 سلاسل: كبح الاستجابة، المرونة المعرفية، التخطيط، ترتيب الخطوات، مراقبة الأخطاء، بدء المهمة، الاستمرار، واكتشاف القاعدة.</p><div className={styles.actions}><Link className={styles.primaryButton} href="/capabilities/kids-lab/executive-functions/">افتح الوظائف التنفيذية</Link></div></div><div className={styles.launchVisual} aria-hidden="true"><div className={styles.track}/><div className={`${styles.track} ${styles.trackBlue}`}/></div></div></section>
<section className={styles.section}><div className={styles.launchCard}><div><span className={styles.kicker}>المجال الرابع مكتمل</span><h2>الإدراك البصري - {visualPerceptionActivityCount} عنصرًا</h2><p>7 سلاسل: التمييز البصري، الشكل والخلفية، الإغلاق البصري، العلاقات المكانية، ثبات الشكل، الدوران والمطابقة، والجزء والكل.</p><div className={styles.actions}><Link className={styles.primaryButton} href="/capabilities/kids-lab/visual-perception/">افتح الإدراك البصري</Link></div></div><div className={styles.launchVisual} aria-hidden="true"><div className={styles.track}/><div className={`${styles.track} ${styles.trackBlue}`}/></div></div></section>
<section className={styles.section}><div className={styles.launchCard}><div><span className={styles.kicker}>سلسلة حركية مكتملة</span><h2>43. مسارا اليدين المتزامنان - {bilateralActivities.length} عنصرًا</h2><p>خمسة مستويات من المسارات المتماثلة إلى المسارات المختلفة وإشارات التوقف والبطء والقواعد المتغيرة.</p><div className={styles.actions}><Link className={styles.primaryButton} href="/capabilities/kids-lab/bilateral-tracks/">افتح السلسلة</Link></div></div><div className={styles.launchVisual} aria-hidden="true"><div className={styles.track}/><div className={`${styles.track} ${styles.trackBlue}`}/></div></div></section>
<section className={styles.section}><div className={styles.sectionHead}><div><h2>خريطة السلاسل الـ67</h2><p>السلاسل 1-30 والسلسلة 43 مفعلة الآن. بقية السلاسل مثبتة في الكتالوج لتنتج بنفس العقد التصميمي والعلمي.</p></div></div><div className={styles.categoryGrid}>{kidsLabCategories.map((category)=><article className={styles.categoryCard} style={{'--category-color':category.color} as React.CSSProperties} key={category.slug}><h3>{category.title}</h3><p>{category.summary}</p><div className={styles.seriesList}>{category.series.map((series)=>category.slug==='attention'?<Link href={`/capabilities/kids-lab/attention/${series.slug}/`} className={styles.seriesActive} key={series.slug}><span className={styles.seriesNumber}>{series.number}</span><span><strong>{series.title}</strong><small>{series.example}</small></span><span className={styles.readyBadge}>جاهزة</span></Link>:category.slug==='memory'?<Link href={`/capabilities/kids-lab/memory/${series.slug}/`} className={styles.seriesActive} key={series.slug}><span className={styles.seriesNumber}>{series.number}</span><span><strong>{series.title}</strong><small>{series.example}</small></span><span className={styles.readyBadge}>جاهزة</span></Link>:category.slug==='executive-functions'?<Link href={`/capabilities/kids-lab/executive-functions/${series.slug}/`} className={styles.seriesActive} key={series.slug}><span className={styles.seriesNumber}>{series.number}</span><span><strong>{series.title}</strong><small>{series.example}</small></span><span className={styles.readyBadge}>جاهزة</span></Link>:category.slug==='visual-perception'?<Link href={`/capabilities/kids-lab/visual-perception/${series.slug}/`} className={styles.seriesActive} key={series.slug}><span className={styles.seriesNumber}>{series.number}</span><span><strong>{series.title}</strong><small>{series.example}</small></span><span className={styles.readyBadge}>جاهزة</span></Link>:series.slug==='bilateral-tracks'?<Link href="/capabilities/kids-lab/bilateral-tracks/" className={styles.seriesActive} key={series.slug}><span className={styles.seriesNumber}>{series.number}</span><span><strong>{series.title}</strong><small>{series.example}</small></span><span className={styles.readyBadge}>جاهزة</span></Link>:<div className={styles.seriesItem} key={series.slug}><span className={styles.seriesNumber}>{series.number}</span><span><strong>{series.title}</strong><small>{series.example}</small></span><span className={styles.badge}>{series.ages}</span></div>)}</div></article>)}</div></section>
<section className={styles.section}><div className={styles.note}><strong>قاعدة علمية ثابتة:</strong> اختبارات المستوى تقيس إتقان المهمة داخل السلسلة، ولا تُستخدم لتشخيص ADHD أو التوحد أو اضطراب تعلم أو أي حالة طبية أو نفسية. اسم التشخيص وحده لا يحدد الورقة المناسبة.</div></section>
</main><SiteFooter/></>}
