import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata, breadcrumbJsonLd, SITE_URL } from '@/lib/seo';
import { socialActivities, socialActivityCount, socialSeriesPlans, socialTestCount } from '@/lib/capabilities/social-skills-lab';
import styles from '../kids-lab.module.css';

export const metadata=buildSeoMetadata({title:'المهارات الاجتماعية للأطفال | أنشطة واختبارات متدرجة',description:'ثلاث سلاسل متدرجة لفهم الإشارات الاجتماعية، الدور والمنظور، وحل المواقف الاجتماعية، بعد تنقيح التكرار ودون فرض قالب اجتماعي واحد أو تشجيع المسايرة.',path:'/capabilities/kids-lab/social-skills/',index:true,keywords:['المهارات الاجتماعية للأطفال','فهم الإشارات الاجتماعية','أخذ المنظور','حل المشكلات الاجتماعية','حدود شخصية']});

export default function SocialSkillsPage(){const breadcrumbs=breadcrumbJsonLd([{name:'الرئيسية',path:'/'},{name:'مختبر الأطفال',path:'/capabilities/kids-lab/'},{name:'المهارات الاجتماعية',path:'/capabilities/kids-lab/social-skills/'}]);const collection={'@context':'https://schema.org','@type':'CollectionPage','@id':`${SITE_URL}/capabilities/kids-lab/social-skills/#collection`,url:`${SITE_URL}/capabilities/kids-lab/social-skills/`,name:'المهارات الاجتماعية للأطفال',inLanguage:'ar',isAccessibleForFree:true,numberOfItems:socialActivityCount};return <><SiteHeader/><main className={styles.shell}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([breadcrumbs,collection]).replace(/</g,'\\u003c')}}/><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><span>المهارات الاجتماعية</span></nav><section className={styles.hero}><span className={styles.kicker}>المجال الحادي عشر - المهارات الاجتماعية</span><h1>فهم السياق والمنظور والحدود بدل حفظ «التصرف الصحيح»</h1><p className={styles.lead}>ثلاث سلاسل تبني قراءة الأدلة، تتبع الدور والمنظور، وتوليد حلول اجتماعية متعددة مع احترام الرفض والحدود والأمان.</p><div className={styles.stats}><div className={styles.stat}><strong>{socialSeriesPlans.length}</strong><span>سلاسل</span></div><div className={styles.stat}><strong>5</strong><span>مستويات</span></div><div className={styles.stat}><strong>{socialTestCount}</strong><span>اختبار إتقان</span></div><div className={styles.stat}><strong>{socialActivityCount}</strong><span>عنصرًا</span></div></div></section><section className={styles.section}><div className={styles.categoryGrid}>{socialSeriesPlans.map(s=>{const count=socialActivities.filter(a=>a.seriesSlug===s.slug).length;return <article className={styles.categoryCard} style={{'--category-color':'#84CC16'} as React.CSSProperties} key={s.slug}><span className={styles.kicker}>السلسلة {s.number}</span><h3>{s.title}</h3><p>{s.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>{s.ages}</span><span className={styles.metaChip}>{s.duration}</span><span className={styles.metaChip}>{count} عنصرًا</span></div><div className={styles.actions}><Link className={styles.primaryButton} href={`/capabilities/kids-lab/social-skills/${s.slug}/`}>افتح السلسلة</Link></div></article>})}</div></section><section className={styles.section}><div className={styles.note}><strong>حدود الاستخدام:</strong> هذه مهام تعلم وملاحظة وليست اختبارًا معياريًا أو تشخيصيًا. لا تُستخدم لفرض تواصل بصري أو تعبير وجهي أو سلوك اجتماعي نمطي، ولا لمكافأة إخفاء الاحتياجات أو المشاعر.</div></section></main><SiteFooter/></>}
