import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import LegacyPreservedRoute, { preservedRouteMetadata } from '@/components/legacy-preserved-route';
import { breadcrumbJsonLd, buildSeoMetadata } from '@/lib/seo';
import registry from '@/data/cochrane/resources-v1.json';

type Params = Promise<{ slug?: string[] }>;
type OfficialResource = (typeof registry.official_resources)[number];
type MsReview = (typeof registry.ms_reviews)[number];

export const dynamic = 'force-dynamic';

const nativePages: Record<string, { title: string; description: string; keywords: string[] }> = {
  '': { title: 'موارد كوكرين وقراءة الدليل بالعربية', description: 'بوابة عربية مستقلة في منصة روافد لتنظيم الوصول إلى موارد كوكرين وفهم المراجعات المنهجية ودرجة اليقين وتتبع مراجعات التصلب المتعدد المستخدمة في المسار التجريبي.', keywords: ['كوكرين بالعربية', 'Cochrane Arabic', 'المراجعات المنهجية', 'درجة اليقين', 'GRADE', 'التصلب المتعدد'] },
  resources: { title: 'خريطة موارد كوكرين الرسمية', description: 'خريطة عربية منظمة لموارد كوكرين الرسمية: البحث في الأدلة، أساسيات المراجعات المنهجية، التدريب المجاني، GRADE، المجموعات والاستراتيجية العلمية.', keywords: ['موارد كوكرين', 'Cochrane resources', 'Evidence Essentials', 'Cochrane Handbook', 'Cochrane Groups'] },
  'read-review': { title: 'كيف تقرأ مراجعة منهجية من كوكرين؟', description: 'منهج عملي عربي لقراءة سؤال المراجعة، حداثة البحث، الدراسات المشمولة، الفائدة والضرر، اليقين، النتائج المفقودة وقابلية نقل الدليل.', keywords: ['قراءة مراجعة منهجية', 'Cochrane review', 'تفسير الدليل', 'البحث المنهجي', 'النتائج الصحية'] },
  certainty: { title: 'درجة اليقين في الدليل: GRADE بالعربية', description: 'شرح عربي دقيق لمستويات GRADE الأربعة وعوامل خفض اليقين وكيفية صياغة الاستنتاجات دون تضخيم قوة الدليل.', keywords: ['GRADE بالعربية', 'يقين الدليل', 'جودة الدليل', 'Cochrane Handbook', 'risk of bias'] },
  ms: { title: 'دليل كوكرين والتصلب المتعدد: ثلاث مراجعات مترابطة', description: 'قراءة عربية مستقلة لثلاث مراجعات كوكرين حول الآزاثيوبرين، أضرار العلاجات المناعية والتدخلات الغذائية في التصلب المتعدد، مع اليقين والحدود والروابط الأصلية.', keywords: ['كوكرين التصلب المتعدد', 'multiple sclerosis Cochrane', 'آزاثيوبرين', 'العلاجات المناعية', 'الغذاء والتصلب المتعدد'] },
  'arabic-pilot': { title: 'حالة المسار التجريبي لترجمة مواد كوكرين إلى العربية', description: 'سجل شفاف لحالة مسار ترجمة ثلاث مواد كوكرين عن التصلب المتعدد إلى العربية، وما أُنجز وما لم يُنجز بعد، ومعايير الجودة المطلوبة قبل النشر.', keywords: ['ترجمة كوكرين العربية', 'Arabic translation pilot', 'RTL', 'back translation', 'ضبط جودة الترجمة'] },
};

function route(slug: string[] = []) { return `/${['cochrane', ...slug].join('/')}/`; }
function nativeKey(slug: string[] = []) { return slug.join('/'); }

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const { slug } = await params;
  const key = nativeKey(slug);
  const native = nativePages[key];
  if (!native) return preservedRouteMetadata(route(slug));
  return buildSeoMetadata({ title: native.title, description: native.description, path: route(slug), index: true, follow: true, type: key === '' || key === 'resources' ? 'website' : 'article', keywords: native.keywords, relatedTerms: ['Cochrane', 'المراجعة المنهجية', 'الطب المبني على الدليل', 'منصة روافد'] });
}

function SourceBoundary() {
  return <aside className="rawafid-empty" aria-label="حدود النسب والاعتماد"><h2>حدود النسب والاعتماد</h2><p>{registry.scope_ar}</p><p><strong>حالة الترجمة الحالية:</strong> {registry.arabic_pilot.public_status_ar}</p></aside>;
}

function ExternalSource({ resource }: { resource: OfficialResource }) {
  return <article className="institutional-sector-card"><span className="eyebrow">{resource.kind}</span><h3>{resource.title_ar}</h3><p><span lang="en" dir="ltr">{resource.title_en}</span></p><p>{resource.scope_ar}</p><div className="sector-metrics"><span>{resource.audience_ar.join(' · ')}</span></div><a className="sector-open" href={resource.url} target="_blank" rel="noopener noreferrer">فتح المصدر الرسمي لدى Cochrane ↗</a></article>;
}

function PageFrame({ current, eyebrow, title, intro, children }: { current: string; eyebrow: string; title: string; intro: string; children: ReactNode }) {
  const path = current ? `/cochrane/${current}/` : '/cochrane/';
  const crumbs = current ? [{ name: 'الرئيسية', path: '/' }, { name: 'موارد كوكرين', path: '/cochrane/' }, { name: title, path }] : [{ name: 'الرئيسية', path: '/' }, { name: 'موارد كوكرين', path: '/cochrane/' }];
  return <><SiteHeader /><main className="site-shell sector-page-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd(crumbs)).replace(/</g, '\\u003c') }} /><nav className="breadcrumbs" aria-label="مسار الصفحة"><Link href="/">الرئيسية</Link><span>/</span>{current ? <><Link href="/cochrane/">موارد كوكرين</Link><span>/</span></> : null}<span aria-current="page">{title}</span></nav><section className="public-index-hero" aria-labelledby="cochrane-page-title"><span className="eyebrow">{eyebrow}</span><h1 id="cochrane-page-title">{title}</h1><p>{intro}</p><div className="public-stat-strip"><span>المصدر الأولي قابل للتتبع</span><span>درجة اليقين ظاهرة</span><span>الحدود وعدم اليقين لا تُخفى</span></div></section>{children}</main><SiteFooter /></>;
}

function HubPage() {
  const cards = [
    ['/cochrane/resources/', 'Resource map', 'خريطة الموارد الرسمية', 'مسارات مختارة من مواقع كوكرين الرسمية: الأدلة، التدريب، المنهجية، المجموعات والاستراتيجية والتواصل.'],
    ['/cochrane/read-review/', 'Evidence literacy', 'كيف تقرأ مراجعة منهجية؟', 'ثماني طبقات تمنع القفز من عنوان المراجعة إلى قرار: السؤال، الحداثة، التصميم، الأثر، الضرر، اليقين، الفجوات والقابلية للنقل.'],
    ['/cochrane/certainty/', 'GRADE', 'فهم درجة اليقين', 'ماذا تعني مرتفعة أو متوسطة أو منخفضة أو منخفضة جداً؟ ولماذا لا تعني درجة اليقين حجم الفائدة؟'],
    ['/cochrane/ms/', 'Worked evidence map', 'ثلاث مراجعات في التصلب المتعدد', 'الآزاثيوبرين، أضرار العلاجات المناعية والتدخلات الغذائية؛ مع تاريخ البحث واليقين والحدود.'],
    ['/cochrane/arabic-pilot/', 'Transparent status', 'حالة المسار التجريبي العربي', 'سجل علني دقيق لما استُلم وما لم يُنجز بعد، وخطوات QA والترجمة العكسية والمراجعة قبل أي نشر بوصفه ترجمة كوكرين.'],
    ['/cochrane/evidence-academy/', 'Preserved academy', 'أكاديمية قراءة الدليل', 'المسار التعليمي القائم في روافد لقراءة الفعالية والأضرار والإنصاف ونقل الدليل إلى السياقات العربية.'],
  ];
  const pipeline = ['ابدأ بالمصدر الأصلي وDOI أو الصفحة الرسمية.','ثبّت سؤال السكان والتدخل والمقارنة والنتائج.','افحص تاريخ آخر بحث قبل الحكم على حداثة الدليل.','افصل حجم الأثر عن درجة اليقين في الأثر.','اقرأ الضرر والانسحاب والنتائج غير المبلغ عنها مثلما تقرأ الفائدة.','سجّل التباين وعدم الدقة وخطر التحيز وعدم المباشرة.','اختبر قابلية نقل النتائج للسياق المحلي والموارد المتاحة.','ارجع إلى المصدر عند القرار؛ ملخص روافد أداة تنقل لا بديل عن المراجعة.'];
  return <PageFrame current="" eyebrow="Cochrane evidence navigation · Arabic RTL" title="موارد كوكرين وقراءة الدليل بالعربية" intro="طبقة عربية مستقلة تنظّم الطريق إلى مصادر كوكرين الأصلية وتحوّلها إلى مسارات قراءة قابلة للتتبع. الهدف ليس إعادة نشر مراجعات كوكرين، بل مساعدة القارئ العربي على فهم السؤال والنتيجة ودرجة اليقين والحدود قبل العودة إلى المصدر الأصلي."><section><div className="section-mini-heading"><div><span className="eyebrow">ستة مسارات مترابطة</span><h2>ابدأ من حاجتك، لا من قائمة روابط</h2></div><span>{registry.official_resources.length} موارد رسمية · {registry.ms_reviews.length} مراجعات تطبيقية · API عام</span></div><div className="institutional-sector-grid">{cards.map(([href, eyebrow, title, body]) => <Link className="institutional-sector-card" href={href} key={href}><span className="eyebrow">{eyebrow}</span><h3>{title}</h3><p>{body}</p><span className="sector-open">فتح المسار ←</span></Link>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Evidence-to-use pipeline</span><h2>كيف تتحول المراجعة إلى معرفة قابلة للاستخدام؟</h2></div></div><div className="institutional-sector-grid">{pipeline.map((value, index) => <article className="institutional-sector-card" key={value}><span className="sector-number">{String(index + 1).padStart(2, '0')}</span><h3>{value}</h3></article>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">قواعد التحرير</span><h2>حواجز تمنع التضخيم وسوء النسب</h2></div></div><div className="institutional-sector-grid">{registry.principles_ar.map((value) => <article className="institutional-sector-card" key={value}><p>{value}</p></article>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Machine-readable</span><h2>البيانات نفسها متاحة بصيغة منظمة</h2></div></div><div className="institutional-sector-grid"><Link className="institutional-sector-card" href="/api/v1/cochrane-resource-hub"><span className="eyebrow">JSON · schema versioned</span><h3>واجهة بيانات قسم كوكرين</h3><p>سجل الموارد وDOI والمراجعات الثلاث وتواريخ الدليل ودرجة اليقين وحالة المسار التجريبي.</p><span className="sector-open">فتح JSON ←</span></Link></div></section><SourceBoundary /></PageFrame>;
}

function ResourcesPage() {
  return <PageFrame current="resources" eyebrow="Official-source map" title="خريطة موارد كوكرين الرسمية" intro="اختيار منظم لمصادر كوكرين الأصلية بحسب الوظيفة: العثور على الدليل، تعلم قراءة المراجعات، فهم GRADE، استكشاف الشبكة ومتابعة الاستراتيجية وموارد التواصل. لا ننسخ محتوى المصدر؛ نشرح لماذا قد تحتاجه ونقودك إليه مباشرة."><section><div className="section-mini-heading"><div><span className="eyebrow">Primary sources</span><h2>الموارد حسب الغرض</h2></div><span>كل رابط يقود إلى Cochrane أو منصته التدريبية.</span></div><div className="institutional-sector-grid">{registry.official_resources.map((resource) => <ExternalSource resource={resource} key={resource.id} />)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">2025–2030</span><h2>كيف نقرأ اتجاه كوكرين العلمي؟</h2></div></div><div className="institutional-sector-grid"><article className="institutional-sector-card"><h3>أولويات موضوعية</h3><p>تضع الاستراتيجية الحالية تركيزاً على صحة الأم والوليد والطفل، والحالات المزمنة المتعددة، والأمراض المعدية، والمناخ والاستدامة. هذه خريطة اتجاه لا حكم على أهمية المجالات الأخرى.</p></article><article className="institutional-sector-card"><h3>التزامات عابرة للموضوعات</h3><p>الابتكار المنهجي، والإنصاف الصحي، والتعاون وإشراك أصحاب المصلحة، ونزاهة البحث؛ وهي عدسات مهمة عند نقل الدليل إلى العربية والسياقات متفاوتة الموارد.</p></article><ExternalSource resource={registry.official_resources.find((item) => item.id === 'scientific-strategy-2025-2030')!} /></div></section><SourceBoundary /></PageFrame>;
}

function ReadReviewPage() {
  const steps = [
    ['حدّد السؤال قبل النتيجة', 'ثبّت السكان والتدخل والمقارنة والنتائج؛ عنوان واسع مثل «هل يعمل العلاج؟» لا يصف ما اختبرته المراجعة فعلاً.'],
    ['ثبّت تاريخ آخر بحث', 'تاريخ النشر ليس تاريخ حداثة الأدلة؛ سجّل التاريخين عندما يكونان متاحين.'],
    ['افهم نوع الدراسات', 'التجارب العشوائية قوية لأسئلة فعالية كثيرة، لكنها ليست دائماً المصدر الوحيد أو الأفضل لضرر نادر أو متأخر.'],
    ['لا تقرأ الاتجاه وحده', 'افحص حجم الأثر ومجال الثقة وعدد الأحداث والمشاركين؛ الاتجاه وحده قد يخفي عدم دقة كبيرة.'],
    ['افصل النتيجة عن اليقين', 'قد يكون الأثر كبيراً واليقين منخفضاً، أو صغيراً واليقين مرتفعاً. GRADE يصف الثقة في التقدير.'],
    ['اقرأ الأضرار والانسحاب', 'قلة الأحداث في تجربة قصيرة لا تثبت انعدام الخطر؛ افحص طريقة الجمع والمدة والانسحاب ونقص الإبلاغ.'],
    ['ابحث عما لم يُقَس', 'جودة الحياة والوظيفة والإدراك وعبء الأسرة والنتائج طويلة المدى قد تكون مهمة لكنها غائبة؛ الغياب فجوة معرفة.'],
    ['اختبر قابلية النقل', 'قارن السكان والجرعات والخدمات والمتابعة والتكلفة والبدائل بالسياق المحلي قبل نقل الاستنتاج.'],
  ];
  return <PageFrame current="read-review" eyebrow="Critical appraisal pathway" title="كيف تقرأ مراجعة منهجية من كوكرين؟" intro="المراجعة المنهجية تقلل الانتقائية، لكنها لا تعفي القارئ من التفكير. هذه ثماني نقاط فحص بين عنوان المراجعة وأي استنتاج عملي، مع أمثلة من مراجعات التصلب المتعدد الثلاث."><section><div className="section-mini-heading"><div><span className="eyebrow">8-point protocol</span><h2>بروتوكول القراءة</h2></div></div><div className="institutional-sector-grid">{steps.map(([title, body], index) => <article className="institutional-sector-card" key={title}><span className="sector-number">{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Worked examples</span><h2>ثلاثة أخطاء تمنعها هذه الطريقة</h2></div></div><div className="institutional-sector-grid"><article className="institutional-sector-card"><h3>«لم تظهر زيادة واضحة في الضرر» ≠ «العلاج آمن»</h3><p>الأحداث الخطيرة قد تكون نادرة والإبلاغ عنها ناقصاً؛ عدم كشف فرق موثوق قد يكون نقص بيانات لا برهان سلامة.</p></article><article className="institutional-sector-card"><h3>«قد يقلل الانتكاس» ≠ «ثبت أنه أفضل»</h3><p>إشارة الآزاثيوبرين إلى خفض الانتكاسات تأتي مع يقين منخفض وعدم يقين أكبر في بعض نتائج الإعاقة والضرر.</p></article><article className="institutional-sector-card"><h3>«لم يثبت أثر الحمية» ≠ «كل غذاء بلا قيمة»</h3><p>مراجعة الغذاء تسأل عن نتائج مرتبطة بالتصلب المتعدد، وبحثها كان محدثاً حتى مايو 2019؛ النطاق والحداثة جزء من التفسير.</p></article></div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Primary methods</span><h2>انتقل إلى المنهج الرسمي</h2></div></div><div className="institutional-sector-grid">{registry.official_resources.filter((item) => ['systematic-reviews', 'evidence-essentials', 'grade-chapter-14'].includes(item.id)).map((resource) => <ExternalSource resource={resource} key={resource.id} />)}</div></section><SourceBoundary /></PageFrame>;
}

function CertaintyPage() {
  const grades = [['مرتفع','ثقة كبيرة بأن الأثر الحقيقي قريب من التقدير.','لا يعني أن الأثر كبير أو مناسب لكل شخص.'],['متوسط','ثقة متوسطة؛ قد يختلف الأثر الحقيقي بصورة مهمة.','أظهر سبب عدم اليقين ولا تصغه كحقيقة مطلقة.'],['منخفض','الثقة محدودة وقد يختلف الأثر الحقيقي بصورة مهمة.','استخدم «قد» واشرح سبب خفض اليقين.'],['منخفض جداً','الثقة في التقدير ضئيلة جداً.','قل إن الدليل شديد عدم اليقين وتجنب «ثبت» و«لا يعمل».']];
  const domains = [['خطر التحيز','هل تصميم الدراسات أو تنفيذها أو فقد المشاركين أو قياس النتائج قد يزيح التقدير؟'],['عدم الاتساق','هل تختلف النتائج بين الدراسات بدرجة لا يفسرها اختلاف معقول؟'],['عدم المباشرة','هل السكان أو التدخل أو المقارنة أو النتيجة تختلف عن سؤالنا؟'],['عدم الدقة','هل عدد المشاركين والأحداث ومجال الثقة يسمح باستنتاج مفيد؟'],['تحيز النشر','هل يحتمل أن دراسات أو نتائج غير ملائمة بقيت غير منشورة أو أقل ظهوراً؟']];
  return <PageFrame current="certainty" eyebrow="GRADE · certainty of evidence" title="درجة اليقين في الدليل: GRADE بالعربية" intro="درجة اليقين لا تعطي العلاج علامة جودة ولا تخبرك بحجم الفائدة وحدها. هي حكم منظم على مقدار الثقة في تقدير الأثر لنتيجة محددة، وقد تختلف داخل المراجعة نفسها."><section><div className="section-mini-heading"><div><span className="eyebrow">Four levels</span><h2>المستويات الأربعة</h2></div></div><div className="institutional-sector-grid">{grades.map(([level, meaning, guard]) => <article className="institutional-sector-card" key={level}><span className="eyebrow">{level}</span><h3>{meaning}</h3><p><strong>حاجز تفسير:</strong> {guard}</p></article>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Downgrading domains</span><h2>خمسة أسباب أساسية قد تخفض اليقين</h2></div></div><div className="institutional-sector-grid">{domains.map(([title, body]) => <article className="institutional-sector-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">لغة مرتبطة باليقين</span><h2>لا تجعل العربية أقوى من الدليل</h2></div></div><div className="institutional-sector-grid"><article className="institutional-sector-card"><h3>منخفض</h3><p>«قد يزيد»، «قد يقلل»، «قد يكون الفرق محدوداً» ثم شرح سبب عدم الثقة.</p></article><article className="institutional-sector-card"><h3>منخفض جداً</h3><p>«الدليل شديد عدم اليقين بشأن…» بدلاً من تحويل النتيجة غير الحاسمة إلى إثبات أو نفي.</p></article><article className="institutional-sector-card"><h3>قاعدة ثابتة</h3><p>«لا يوجد دليل على فرق» لا يساوي «يوجد دليل على عدم وجود فرق»؛ الأولى قد تعكس نقص المعلومات.</p></article></div></section><section><div className="institutional-sector-grid">{registry.official_resources.filter((item) => item.id === 'grade-chapter-14').map((resource) => <ExternalSource resource={resource} key={resource.id} />)}</div></section><SourceBoundary /></PageFrame>;
}

function ReviewCard({ review }: { review: MsReview }) {
  return <article className="institutional-sector-card" id={review.id}><span className="eyebrow">{review.id} · DOI {review.doi}</span><h3>{review.title_ar}</h3><p><span lang="en" dir="ltr">{review.title_en}</span></p><div className="sector-metrics"><span>نُشرت: {review.published_on}</span><span>الدليل محدث حتى: {review.evidence_current_to}</span></div><p><strong>السؤال:</strong> {review.question_ar}</p><p><strong>قاعدة الدليل:</strong> {review.evidence_base_ar}</p><h4>الرسائل الرئيسية</h4><ul>{review.key_messages_ar.map((message) => <li key={message}>{message}</li>)}</ul><p><strong>اليقين:</strong> {review.certainty_ar}</p><p><strong>استخدام روافد:</strong> {review.rawafid_use_ar}</p><div className="sector-metrics"><a href={review.cochrane_url} target="_blank" rel="noopener noreferrer">الملخص الرسمي ↗</a><a href={review.library_url} target="_blank" rel="noopener noreferrer">Cochrane Library ↗</a></div></article>;
}

function MsPage() {
  return <PageFrame current="ms" eyebrow="Multiple sclerosis · three primary reviews" title="دليل كوكرين والتصلب المتعدد: ثلاث مراجعات مترابطة" intro="هذه الصفحة ليست ترجمة للـBlogshots التي استلمناها. إنها خريطة تفسير عربية مستقلة مبنية على المراجعات الأصلية الثلاث: سؤال كل مراجعة، تاريخ حداثة الدليل، الرسائل الرئيسية، درجة اليقين، والفجوات التي يجب ألا تختفي عند التبسيط."><section><div className="section-mini-heading"><div><span className="eyebrow">ثلاث زوايا مختلفة</span><h2>الفائدة والضرر ونمط الحياة لا تجيب عن السؤال نفسه</h2></div></div><div className="institutional-sector-grid"><article className="institutional-sector-card"><h3>دواء محدد</h3><p>الآزاثيوبرين يكشف فجوة بين إشارة الانتكاس وعدم اليقين في الإعاقة والضرر.</p></article><article className="institutional-sector-card"><h3>سلامة فئة علاجية</h3><p>التحليل الشبكي يوضح صعوبة ترتيب السلامة مع ندرة الأحداث والإبلاغ غير المكتمل.</p></article><article className="institutional-sector-card"><h3>تدخلات غذائية</h3><p>التغاير بين الحميات والمكملات والنتائج يجعل التعميم صعباً، وحداثة البحث يجب أن تبقى ظاهرة.</p></article></div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Evidence records</span><h2>السجلات الثلاثة</h2></div></div><div className="institutional-sector-grid">{registry.ms_reviews.map((review) => <ReviewCard review={review} key={review.id} />)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Cross-review synthesis</span><h2>ما الذي يظهر عند قراءتها معاً؟</h2></div></div><div className="institutional-sector-grid"><article className="institutional-sector-card"><h3>لا توجد إجابة واحدة للتصلب المتعدد</h3><p>الأسئلة والتدخلات والأزمنة والنتائج مختلفة؛ جمعها في خلاصة علاجية واحدة خطأ منهجي.</p></article><article className="institutional-sector-card"><h3>السلامة أوسع من التجارب</h3><p>الأضرار النادرة والمتأخرة قد تحتاج بيانات رصد ومتابعة دوائية أيضاً.</p></article><article className="institutional-sector-card"><h3>الحداثة جزء من الدليل</h3><p>نسجل «الدليل محدث حتى» ولا نكتفي بتاريخ نشر الصفحة.</p></article><article className="institutional-sector-card"><h3>النتائج المهمة قد تكون مفقودة</h3><p>جودة الحياة والإدراك والأثر طويل المدى قد تحد القرار المشترك عند غيابها.</p></article></div></section><aside className="rawafid-empty"><h2>حد الاستخدام السريري</h2><p>لا تختار دواءً أو توقفه ولا تغيّر حمية علاجية اعتماداً على هذه الصفحة. المراجعة جزء من القرار، ويجب ربطها بحالة الشخص وخيارات العلاج الحالية والسلامة والتفضيلات والإرشادات المحدثة.</p></aside><SourceBoundary /></PageFrame>;
}

function PilotPage() {
  const status = [['تحديد ثلاث مواد للمرحلة الأولى','مكتمل'],['استلام ملفات PowerPoint قابلة للتحرير','مكتمل'],['استلام إرشادات إنتاج Blogshots','مكتمل'],['مسودة عربية كاملة للمواد الثلاث','غير مكتمل'],['مراجعة عربية/إنجليزية مستقلة','غير مكتمل'],['ترجمة عكسية وسجل فروق','غير مكتمل'],['مراجعة المحتوى والنسب النهائية','غير مكتمل'],['نشر ترجمة عربية مراجعة','غير مكتمل']];
  const done = ['النص العربي يحافظ على اتجاه وحجم عدم اليقين ولا يقوي الاستنتاج الأصلي.','كل رقم أو مدة أو مقارنة أو قيد قابل للمطابقة مع المصدر.','المصطلحات الحساسة مسجلة بالعربية والإنجليزية بقرار استخدام ثابت.','الترجمة العكسية لا تكشف تغيراً جوهرياً في السؤال أو النتيجة أو اليقين.','RTL مقروء على الهاتف وسطح المكتب ولا يقلب ترتيب المقارنات.','المصدر والنسب والروابط والهوية محفوظة وفق التوجيه المتفق عليه.','المراجعة المطلوبة اكتملت ولا توجد ملاحظات جوهرية مفتوحة.'];
  return <PageFrame current="arabic-pilot" eyebrow="Status: materials received · translations not complete" title="حالة المسار التجريبي لترجمة مواد كوكرين إلى العربية" intro="هذه صفحة حالة لا صفحة تسويق. لدينا ثلاث مواد مصدر قابلة للتحرير ومسار جودة متفق على ملامحه، لكن الترجمة والمراجعة والترجمة العكسية لم تكتمل؛ لذلك لا توجد هنا أي مادة نوصفها بأنها ترجمة عربية معتمدة من كوكرين."><section><div className="section-mini-heading"><div><span className="eyebrow">Current state</span><h2>ما أُنجز وما لم يُنجز</h2></div><span>آخر تحديث: {registry.updated_on}</span></div><div className="institutional-sector-grid">{status.map(([item, state], index) => <article className="institutional-sector-card" key={item}><span className="sector-number">{String(index + 1).padStart(2, '0')}</span><span className="eyebrow">{state}</span><h3>{item}</h3></article>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Phase 1 inputs</span><h2>المواد الثلاث التي ستختبر المسار</h2></div></div><div className="institutional-sector-grid">{registry.ms_reviews.map((review) => <article className="institutional-sector-card" key={review.id}><span className="eyebrow">{review.id}</span><h3>{review.title_ar}</h3><Link className="sector-open" href={`/cochrane/ms/#${review.id}`}>قراءة سجل الدليل ←</Link></article>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">QA / RTL / back-translation</span><h2>مسار الجودة قبل النشر</h2></div></div><div className="institutional-sector-grid">{registry.arabic_pilot.workflow_ar.map((step, index) => <article className="institutional-sector-card" key={step}><span className="sector-number">{String(index + 1).padStart(2, '0')}</span><h3>{step}</h3></article>)}</div></section><section><div className="section-mini-heading"><div><span className="eyebrow">Definition of done</span><h2>متى نعتبر المادة جاهزة؟</h2></div></div><div className="institutional-sector-grid">{done.map((item) => <article className="institutional-sector-card" key={item}><p>{item}</p></article>)}</div></section><aside className="rawafid-empty"><h2>حارس النشر</h2><p>{registry.arabic_pilot.publication_guard_ar}</p></aside><SourceBoundary /></PageFrame>;
}

export default async function CochraneLanding({ params }: { params: Params }) {
  const { slug } = await params;
  const key = nativeKey(slug);
  if (key === '') return <HubPage />;
  if (key === 'resources') return <ResourcesPage />;
  if (key === 'read-review') return <ReadReviewPage />;
  if (key === 'certainty') return <CertaintyPage />;
  if (key === 'ms') return <MsPage />;
  if (key === 'arabic-pilot') return <PilotPage />;
  return <LegacyPreservedRoute route={route(slug)} />;
}
