import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata } from '@/lib/seo';
import styles from '../audiences.module.css';

type Role={title:string;lead:string;start:string[];avoid:string[];links:[string,string][]};
const roles:Record<string,Role>={
 person:{title:'مسار الفرد: أفهم ما يحدث لي دون تشخيص ذاتي',lead:'ابدأ بتحديد السؤال أو التغير الذي تريد فهمه، ثم افصل بين التثقيف العام وبين التشخيص الفردي. استخدم المحتوى لترتيب الملاحظات والأسئلة، لا لإصدار حكم نهائي على نفسك.',start:['اكتب ما الذي تغيّر عن خطك المعتاد ومتى بدأ.','صف الأثر في النوم والدراسة أو العمل والعلاقات والعناية بالنفس.','دوّن الأدوية أو الحالات الصحية أو الضغوط المهمة قبل افتراض تفسير نفسي واحد.','حدد السؤال الذي تريد أن تجيب عنه القراءة أو الزيارة المهنية.'],avoid:['مطابقة تجربة واحدة مع قائمة أعراض ثم إعلان التشخيص.','إيقاف دواء أو تغييره بسبب مقال أو أداة إلكترونية.','تأخير طلب المساعدة عند وجود خطر أو تعطيل شديد.'],links:[['المعرفة والموسوعة','/sectors/knowledge'],['الصحة النفسية','/sectors/mental-health'],['الأسئلة الاسترشادية','/guided-assessment'],['المختصون','/specialists']]},
 family:{title:'مسار الأسرة ومقدمي الرعاية',lead:'حوّل الأوصاف العامة إلى ملاحظات محددة: متى يحدث الأمر، في أي سياق، ما أثره، وما الذي يساعد. حافظ على كرامة الشخص واستقلاله، واطلب دعمًا مهنيًا عندما تتجاوز الحاجة قدرة الأسرة وحدها.',start:['ابدأ بوصف السلوك أو الحاجة دون وصم أو تفسير النية.','قارن بين السياقات: المنزل، المدرسة، المجتمع، والبيئات الحسية المختلفة.','سجل ما الذي يساعد وما الذي يزيد الحمل أو الارتباك.','أدخل الشخص نفسه في القرار بقدر ما تسمح قدرته وعمره ووسيلة تواصله.'],avoid:['تحويل التشخيص إلى هوية كاملة أو توقع ثابت للمستقبل.','استخدام العقاب لمعالجة حاجات تواصل أو حسية أو نمائية غير مفهومة.','مشاركة معلومات خاصة أكثر مما يحتاجه مقدم الخدمة أو المدرسة.'],links:[['الطفل والأسرة والمدرسة','/sectors/child-family-education'],['الاحتياجات الخاصة والتربية الدامجة','/sectors/special-needs-inclusion'],['أدلة الرعاية','/care-guides'],['المراكز','/centers']]},
 teacher:{title:'مسار المعلم والمرشد المدرسي',lead:'ابدأ بالحاجز في المهمة أو البيئة بدل تفسير الصعوبة كصفة في الطالب. جرّب تكييفًا واضحًا، راقب أثره، وسجّل ملاحظات موضوعية يمكن مناقشتها مع الأسرة والفريق المختص.',start:['حدد متطلبات المهمة التي يتعثر عندها الطالب بدقة.','غيّر عاملًا واحدًا يمكن قياس أثره: زمن، تعليمات، عرض بصري، مكان جلوس أو تقسيم المهمة.','اجمع ملاحظات من أكثر من موقف بدل الاعتماد على حصة واحدة.','فرّق بين التكييف الذي يزيل حاجزًا وبين خفض التوقعات التعليمية بلا مبرر.'],avoid:['وصف الطالب بالكسل أو العناد بدل وصف السلوك والسياق.','استخدام اختبار غير مقنن لتسمية حالة تشخيصية.','نشر معلومات الطالب الصحية أو النمائية خارج الحاجة التعليمية المشروعة.'],links:[['التربية الدامجة','/sectors/special-needs-inclusion'],['الطفل والأسرة والمدرسة','/sectors/child-family-education'],['مختبر القدرات','/cognitive-lab'],['الموارد العملية','/resources']]},
 student:{title:'مسار الطالب والمتعلم',lead:'سمِّ الصعوبة بطريقة قابلة للشرح: تركيز، نوم، قلق، فهم تعليمات، تنظيم وقت أو عبء دراسي. الصعوبة الدراسية ليست حكمًا على القيمة أو الذكاء، وطلب التيسير أو الدعم جزء من حل المشكلة.',start:['حدد مادة أو مهمة واحدة بدل عبارة عامة مثل «لا أستطيع الدراسة».','راقب الوقت والمكان والنوم والمقاطعات وحجم المهمة قبل الحكم على قدرتك.','قسّم المطلوب إلى ناتج واضح يمكن إنهاؤه ومراجعته.','اطلب تيسيرًا أو شرحًا إضافيًا عندما تكون المشكلة في الوصول إلى المهمة لا في الهدف التعليمي نفسه.'],avoid:['قياس قيمتك بدرجة أو اختبار واحد.','السهر المزمن ثم تفسير كل صعوبة على أنها ضعف تركيز دائم.','استخدام أدوات الموقع كبديل عن تقييم مناسب عندما تكون الصعوبة مستمرة ومؤثرة.'],links:[['الطفل والأسرة والمدرسة','/sectors/child-family-education'],['مختبر القدرات','/cognitive-lab'],['البحث في روافد','/search'],['الأسئلة الاسترشادية','/guided-assessment']]},
 professional:{title:'مسار المختص والمتدرب',lead:'استخدم روافد كطبقة تثقيف وإحالة ومراجعة مصادر، مع فحص نوع المصدر وتاريخ المراجعة وحدود الصفحة. المحتوى العام لا يحل محل الحكم المهني أو الأدوات المقننة أو متطلبات الترخيص المحلية.',start:['ابدأ بسؤال مهني محدد وحدد مستوى الدليل المطلوب للإجابة عنه.','افحص المصدر الأصلي لا عدد المراجع فقط، وميّز الإرشاد السريري عن الدراسة الفردية أو المحتوى التثقيفي.','استخدم الصفحات العامة لتثقيف المستفيد لا لتوثيق تشخيص أو قرار علاجي منفرد.','عند استخدام أداة قياس تحقق من الترخيص والنسخة اللغوية والفئة وطريقة التسجيل والتفسير.'],avoid:['نقل جرعات أو قرارات علاجية من محتوى عام خارج سياق الرعاية.','استخدام ترجمة غير موثقة لمقياس مقنن وكأنها النسخة الرسمية.','الخلط بين محتوى روافد وبين سجل طبي أو استشارة مهنية رسمية.'],links:[['المعرفة والموسوعة','/sectors/knowledge'],['المتدربون والمتطوعون','/sectors/trainees-volunteers'],['منهجية المراجعة العلمية','/medical-review-policy'],['المصادر','/sources']]}
};
const slugs=Object.keys(roles);
export const dynamicParams=false;
export function generateStaticParams(){return slugs.map((slug)=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const role=roles[slug];if(!role)return{};return buildSeoMetadata({title:role.title,description:role.lead,path:`/audiences/${slug}`,index:true,follow:true})}
export default async function AudiencePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const role=roles[slug];if(!role)notFound();return <><SiteHeader/><main className={styles.page}><section className={styles.hero}><div className={styles.shell}><nav className={styles.breadcrumbs}><Link href="/">الرئيسية</Link><span>/</span><Link href="/audiences">الجمهور</Link><span>/</span><span>{role.title}</span></nav><span className={styles.eyebrow}>صفحة منقولة من المسار التاريخي</span><h1>{role.title}</h1><p>{role.lead}</p></div></section><section className={`${styles.shell} ${styles.content}`}><article className={styles.card}><h2>من أين تبدأ؟</h2><ol>{role.start.map(x=><li key={x}>{x}</li>)}</ol></article><article className={styles.card}><h2>ما الذي نتجنبه؟</h2><ul>{role.avoid.map(x=><li key={x}>{x}</li>)}</ul></article><article className={styles.card}><h2>مسارات مناسبة داخل روافد</h2><div className={styles.links}>{role.links.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</div></article><article className={styles.note}><strong>لم يعد هذا المسار redirect.</strong><p>المحتوى موجود فعليًا في هذا العنوان داخل التطبيق الجديد. صفحة «ابدأ هنا» تبقى خريطة عامة، بينما هذه الصفحة تحتفظ بقيمة المسار المتخصص لكل جمهور.</p></article></section></main><SiteFooter/></>}
