import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import KidsLabPrintButton from '@/components/kids-lab-print-button';
import { buildSeoMetadata } from '@/lib/seo';
import { getSensorySelfActivity,sensorySelfActivities } from '@/lib/capabilities/sensory-self-regulation-lab';
import styles from '../../../kids-lab.module.css';
type Props={params:Promise<{series:string;activity:string}>};
export function generateStaticParams(){return sensorySelfActivities.map(a=>({series:a.seriesSlug,activity:a.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const p=await params;const a=getSensorySelfActivity(p.series,p.activity);if(!a)return{};return buildSeoMetadata({title:a.title,description:a.purpose,path:`/capabilities/kids-lab/sensory-self-regulation/${a.seriesSlug}/${a.slug}/`,index:true,keywords:[a.seriesTitle,'تنظيم ذاتي للأطفال','نشاط قابل للطباعة']});}
export default async function Page({params}:Props){const p=await params;const a=getSensorySelfActivity(p.series,p.activity);if(!a)notFound();const img=`/capabilities/kids-lab/sensory-self-regulation/${a.seriesSlug}/${a.slug}/image`;return <><SiteHeader/><main className={styles.shell}><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><Link href="/capabilities/kids-lab/sensory-self-regulation/">الوعي الحسي والتنظيم الذاتي</Link><span>/</span><Link href={`/capabilities/kids-lab/sensory-self-regulation/${a.seriesSlug}/`}>{a.seriesTitle}</Link><span>/</span><span>{a.label}</span></nav><section className={styles.hero}><span className={styles.kicker}>المستوى {a.level} · {a.label}</span><h1>{a.seriesTitle}</h1><p className={styles.lead}>{a.instruction}</p><div className={styles.metaRow}><span className={styles.metaChip}>{a.age}</span><span className={styles.metaChip}>{a.duration}</span></div></section><section className={styles.section}><div className={styles.activityLayout}><div className={styles.previewCard}><img src={img} alt={`${a.seriesTitle} - ${a.label}`} /></div><div className={styles.sidePanel}><h2>الهدف</h2><p>{a.purpose}</p><h3>تدرج المستوى</h3><p>{a.progression}</p><h3>{a.kind==='test'?'معيار الإتقان':'ما الذي نلاحظه؟'}</h3><p>{a.kind==='test'?a.mastery:a.observation}</p><div className={styles.actions}><KidsLabPrintButton/><a className={styles.secondaryButton} href={img} download={`${a.seriesSlug}-${a.slug}.svg`}>تنزيل SVG</a></div></div></div></section><section className={styles.section}><div className={styles.note}><strong>مهم:</strong> هذه المهمة تساعد على الملاحظة الذاتية واختيار دعم يومي منخفض المخاطر. لا توجد إجابة شخصية واحدة تناسب الجميع، ولا تُستخدم كورقة تشخيص.</div></section></main><SiteFooter/></>}
