import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound,redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { reportConversation,sendMessage,setConversationArchived,setUserBlock } from '../actions';

export const dynamic='force-dynamic';
export const metadata:Metadata={title:'محادثة خاصة',robots:{index:false,follow:false,noarchive:true}};
type Params=Promise<{id:string}>;type SearchParams=Promise<{error?:string;reported?:string}>;
type Detail={conversation_id:string;subject:string|null;specialist_id:string|null;center_id:string|null;counterpart_user_id:string;counterpart_name:string;counterpart_title:string|null;counterpart_slug:string|null;blocked_by_me:boolean;blocked_me:boolean;archived_at:string|null;closed_at:string|null;created_at:string};
type Message={message_id:string;sender_id:string;sender_name:string;body:string|null;attachments:unknown;message_type:string;created_at:string;edited_at:string|null;deleted_at:string|null;is_mine:boolean;read_by_other:boolean};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i;
function date(value:string){try{return new Intl.DateTimeFormat('ar',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return''}}

export default async function ConversationPage({params,searchParams}:{params:Params;searchParams:SearchParams}){
 const {id}=await params;if(!UUID_RE.test(id))notFound();const query=await searchParams;const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();if(!claims?.claims?.sub)redirect(`/login?next=${encodeURIComponent(`/messages/${id}`)}`);
 const [{data:detailRows,error:detailError},{data:messageRows,error:messageError}]=await Promise.all([supabase.rpc('get_conversation_detail',{p_conversation_id:id}),supabase.rpc('get_conversation_messages',{p_conversation_id:id,p_limit:100,p_before:null})]);
 if(detailError||!Array.isArray(detailRows)||!detailRows[0])notFound();const detail=detailRows[0] as Detail;const messages:Array<Message>=Array.isArray(messageRows)?messageRows as Message[]:[];
 await supabase.rpc('mark_conversation_read',{p_conversation_id:id});
 const blocked=detail.blocked_by_me||detail.blocked_me||Boolean(detail.closed_at);const appointmentHref=detail.specialist_id?`/appointments/new?specialist=${detail.specialist_id}&conversation=${id}`:`/appointments/new?center=${detail.center_id}&conversation=${id}`;const profileHref=detail.counterpart_slug?(detail.specialist_id?`/specialists/${detail.counterpart_slug}`:`/centers/${detail.counterpart_slug}`):null;
 return <><SiteHeader/><main className="communication-shell conversation-shell">
 <nav className="breadcrumbs" aria-label="مسار الصفحة"><Link href="/">الرئيسية</Link><span>/</span><Link href="/messages">الرسائل</Link><span>/</span><span aria-current="page">{detail.counterpart_name}</span></nav>
 <section className="conversation-header"><div className="conversation-person"><div className="inbox-avatar" aria-hidden="true">{detail.counterpart_name.slice(0,1)}</div><div><span className="verified-label">محادثة خاصة</span><h1>{detail.counterpart_name}</h1><p>{detail.counterpart_title||'مستخدم روافد'}{detail.subject?` · ${detail.subject}`:''}</p></div></div><div className="communication-actions"><Link className="button" href="/messages">صندوق الرسائل</Link>{profileHref&&<Link className="button" href={profileHref}>ملف الجهة</Link>}{!blocked&&<Link className="button" href={appointmentHref}>طلب موعد</Link>}<form action={setConversationArchived}><input type="hidden" name="conversation_id" value={id}/><input type="hidden" name="archived" value={detail.archived_at?'false':'true'}/><button className="button" type="submit">{detail.archived_at?'إلغاء الأرشفة':'أرشفة'}</button></form></div></section>
 <nav className="communication-service-nav" aria-label="مسارات الخدمة"><Link href="/appointments">المواعيد</Link><Link href="/specialists">المختصون</Link><Link href="/centers">المراكز</Link><Link href="/care-guides/">أدلة الرعاية</Link></nav>
 {query.reported==='1'&&<div className="system-message success">تم إرسال البلاغ للمراجعة دون مشاركة المحادثة خارج نظام الإشراف.</div>}{query.error&&<div className="system-message error">تعذر تنفيذ العملية المطلوبة.</div>}
 {detail.blocked_by_me&&<div className="portal-notice warning"><strong>أنت تحظر هذا المستخدم.</strong><span>لن يمكن تبادل رسائل أو طلب مواعيد حتى إلغاء الحظر.</span></div>}{detail.blocked_me&&<div className="portal-notice warning"><strong>التواصل غير متاح حاليًا.</strong><span>تم إيقاف تبادل الرسائل لهذه المحادثة.</span></div>}{detail.closed_at&&<div className="portal-notice"><strong>المحادثة مغلقة.</strong><span>يمكن قراءة السجل السابق دون إرسال رسائل جديدة.</span></div>}
 {messageError&&<div className="search-state error"><h2>تعذر تحميل سجل الرسائل</h2></div>}
 <section className="message-thread" aria-label="سجل المحادثة">{messages.length===0&&!messageError&&<div className="empty-thread"><h2>ابدأ الرسالة الأولى</h2><p>اكتب استفسارك بوضوح، وتجنب إرسال معلومات حساسة لا تلزم لتقديم الخدمة.</p></div>}{messages.map((message)=><article className={`message-bubble ${message.is_mine?'mine':'theirs'} ${message.message_type==='system'?'system':''}`} key={message.message_id}><div className="message-author"><strong>{message.is_mine?'أنت':message.sender_name}</strong><time dateTime={message.created_at}>{date(message.created_at)}</time></div>{message.deleted_at?<p className="deleted-message">تم حذف هذه الرسالة.</p>:<p>{message.body}</p>}{message.is_mine&&!message.deleted_at&&<small>{message.read_by_other?'تمت القراءة':'تم الإرسال'}{message.edited_at?' · معدلة':''}</small>}</article>)}</section>
 {!blocked&&<form action={sendMessage} className="message-composer"><input type="hidden" name="conversation_id" value={id}/><label className="sr-only" htmlFor="message-body">نص الرسالة</label><textarea id="message-body" name="body" required maxLength={4000} rows={3} placeholder="اكتب رسالتك..."/><button className="primary-action" type="submit">إرسال</button><small>الحد الأقصى 4000 حرف. المرفقات ستتاح فقط بعد تفعيل تخزين الملفات الخاص وسياسات فحصها.</small></form>}
 <section className="conversation-safety"><div><h2>الخصوصية والسلامة</h2><p>يمكنك إيقاف التواصل أو الإبلاغ عن إساءة. لا يظهر نص الرسائل في Audit Log الإداري.</p></div><div className="safety-actions"><form action={setUserBlock}><input type="hidden" name="conversation_id" value={id}/><input type="hidden" name="user_id" value={detail.counterpart_user_id}/><input type="hidden" name="blocked" value={detail.blocked_by_me?'false':'true'}/><button className="button danger" type="submit">{detail.blocked_by_me?'إلغاء الحظر':'حظر المستخدم'}</button></form><details className="report-box"><summary>إبلاغ</summary><form action={reportConversation}><input type="hidden" name="conversation_id" value={id}/><input type="hidden" name="reported_user_id" value={detail.counterpart_user_id}/><label>سبب البلاغ<select name="reason" required defaultValue="spam"><option value="spam">رسائل مزعجة</option><option value="harassment">مضايقة</option><option value="unsafe">محتوى غير آمن</option><option value="impersonation">انتحال</option><option value="privacy">مشكلة خصوصية</option><option value="other">أخرى</option></select></label><label>تفاصيل اختيارية<textarea name="details" maxLength={2000} rows={4}/></label><button className="primary-action" type="submit">إرسال البلاغ</button></form></details></div></section>
 </main><SiteFooter/></>;
}
