import type { InstrumentCrosswalkRecord } from '@/lib/core-outcome-sets/instrument-crosswalk';

const AUTISM_SOURCE = 'https://www.ichom.org/patient-centered-outcome-measure/autism-spectrum-disorder/';

export const autismInstrumentMappings: readonly InstrumentCrosswalkRecord[] = [
  {
    id: 'rbs-r-autism',
    instrument: 'Repetitive Behavior Scale-Revised',
    acronym: 'RBS-R',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Autism Track A وTrack B؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'ICHOM يدرجه في مساري التنفيذ، لكن وصف Track B بأنه free/low-cost لا يُعامل كإذن إعادة نشر. شروط الأداة نفسها تحتاج تدقيقًا مستقلًا.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'النسخة العربية المطابقة لم تُدقق بعد',
    arabicEvidenceNote: 'لم نثبت بعد ترجمة عربية مرخصة وخصائص سيكومترية ملائمة للفئة العمرية والسياق المقصود.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — current implementation Track A/Track B; Joseph et al., 2024, DOI 10.1016/j.rasd.2024.102451',
    lastVerified: '2026-09-06',
  },
  {
    id: 'srs-autism',
    instrument: 'Social Responsiveness Scale — ICHOM page lists SRS; the 2024 publication references SRS-2',
    acronym: 'SRS / SRS-2',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track A؛ الإصدار التنفيذي الدقيق يحتاج تثبيتًا',
    rightsStatus: 'owner-conditions',
    rightsNote: 'Track A يضم أدوات ذات كلفة، وSRS/SRS-2 أداة مالك/ناشر. لا ننسخ البنود أو نساوي بين SRS وSRS-2 دون تثبيت الإصدار.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الإصدار العربي المطابق لم يُدقق بعد',
    arabicEvidenceNote: 'الخطوة التالية هي تحديد الإصدار المقصود ثم مراجعة الترجمة المرخصة وخصائصها العربية، لا الاستدلال من الاسم العام.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set; Joseph et al., 2024, DOI 10.1016/j.rasd.2024.102451 — exact edition preserved as unresolved',
    lastVerified: '2026-09-06',
  },
  {
    id: 'vineland-autism',
    instrument: 'Vineland Adaptive Behavior Scales',
    acronym: 'VABS',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track A وTrack B؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'owner-conditions',
    rightsNote: 'Vineland أداة مالك/ناشر؛ ينبغي تثبيت الإصدار المطلوب وشروط الترخيص قبل أي تشغيل. وجودها في Track B لا يحولها إلى مادة حرة لإعادة النشر.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الإصدار العربي المطابق لم يُدقق بعد',
    arabicEvidenceNote: 'يلزم تحديد إصدار Vineland المقصود وتدقيق الترجمة العربية والخصائص السيكومترية الخاصة به.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — implementation Track A/Track B',
    lastVerified: '2026-09-06',
  },
  {
    id: 'pac-autism',
    instrument: 'Preferences for Activities of Children',
    acronym: 'PAC',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track A؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'كون الأداة مذكورة في Track A لا يثبت شروط إعادة نشرها؛ يلزم owner/version audit.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'لم يُدقق عربيًا',
    arabicEvidenceNote: 'لا توجد في سجل روافد الحالي مراجعة عربية موثقة لهذه الأداة.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — implementation Track A',
    lastVerified: '2026-09-06',
  },
  {
    id: 'cfql-2-autism',
    instrument: 'Child and Family Quality of Life — second edition',
    acronym: 'CFQL-2',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track A وTrack B؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'تحتاج النسخة الثانية إلى تدقيق مصدر وحقوق مستقل قبل إعادة النشر أو البرمجة.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'لم يُدقق عربيًا',
    arabicEvidenceNote: 'لا ننقل دليل إصدار آخر من CFQL إلى CFQL-2 دون exact-version review.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — implementation Track A/Track B',
    lastVerified: '2026-09-06',
  },
  {
    id: 'mcmaster-fad-autism',
    instrument: 'McMaster Family Assessment Device',
    acronym: 'FAD',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track A؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'يلزم تحديد النسخة/المقاييس الفرعية وشروط الاستخدام قبل التشغيل.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'لم يُدقق عربيًا',
    arabicEvidenceNote: 'وجود ترجمات محتملة لا يكفي دون مطابقة النسخة والغرض والسياق.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — implementation Track A',
    lastVerified: '2026-09-06',
  },
  {
    id: 'panas-autism',
    instrument: 'Positive and Negative Affect Schedule / child version where applicable',
    acronym: 'PANAS / PANAS-C',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track A؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'يجب تثبيت إصدار PANAS المناسب للعمر وشروط الاستخدام؛ لا ندمج adult/child forms في نموذج واحد.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الإصدار العربي المطابق لم يُدقق بعد',
    arabicEvidenceNote: 'أي دراسة عربية يجب ربطها بإصدار PANAS نفسه والفئة العمرية المقابلة قبل اعتمادها.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — implementation Track A',
    lastVerified: '2026-09-06',
  },
  {
    id: 'cbcl-autism',
    instrument: 'Child Behavior Checklist',
    acronym: 'CBCL',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track A؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'owner-conditions',
    rightsNote: 'CBCL أداة محكومة بشروط مالك؛ لا ننشر البنود أو scoring من مصادر ثانوية.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'النسخة العربية المرخصة لم تُدقق بعد',
    arabicEvidenceNote: 'يلزم التحقق من form/age band والترجمة المرخصة وخصائصها في المجتمع المستهدف.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — implementation Track A',
    lastVerified: '2026-09-06',
  },
  {
    id: 'bisq-autism',
    instrument: 'Brief Infant Sleep Questionnaire',
    acronym: 'BISQ',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track A؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'يلزم تدقيق الإصدار والفئة العمرية وشروط الاستخدام قبل النشر.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'لم يُدقق عربيًا',
    arabicEvidenceNote: 'لا نعتبر أي مقياس نوم بديل مكافئًا لـBISQ دون مصدر صريح.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — implementation Track A',
    lastVerified: '2026-09-06',
  },
  {
    id: 'phq-2-autism',
    instrument: 'Patient Health Questionnaire-2',
    acronym: 'PHQ-2',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track B؛ غير مضاف كأداة مستقلة إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'وجود PHQ-9 في روافد لا يجعل PHQ-2 سجلًا تشغيليًا مستقلًا تلقائيًا؛ يلزم تثبيت provenance وطريقة الاستخدام الخاصة بالنسخة ذات البندين.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'دليل PHQ-2 العربي لم يُدقق هنا',
    arabicEvidenceNote: 'لا ننقل خصائص PHQ-9 العربية تلقائيًا إلى PHQ-2؛ يلزم دليل النسخة المختصرة نفسها.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — Global Track B',
    lastVerified: '2026-09-06',
  },
  {
    id: 'faces-autism',
    instrument: 'Family Adaptability and Cohesion Evaluation Scale',
    acronym: 'FACES',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track B؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'Track B يصف الأدوات بأنها free/low-cost للتطبيق العالمي، لكنه لا يحدد في الصفحة وحدها كل شروط النسخة؛ يلزم exact-version/rights audit.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الإصدار العربي المطابق لم يُدقق بعد',
    arabicEvidenceNote: 'عائلة FACES لها إصدارات متعددة؛ لا نربط دليل إصدار بآخر.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — Global Track B',
    lastVerified: '2026-09-06',
  },
  {
    id: 'empathy-quotient-autism',
    instrument: 'Empathy Quotient',
    acronym: 'EQ (Empathy Quotient)',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track B؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'اختصار EQ هنا يعني Empathy Quotient وليس EQ-5D؛ لذلك يحفظ السجل الاسم الكامل لتجنب خلط الأداتين.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'النسخة العربية المطابقة لم تُدقق بعد',
    arabicEvidenceNote: 'يلزم تثبيت الإصدار والفئة العمرية والترجمة قبل الاستخدام.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — Global Track B',
    lastVerified: '2026-09-06',
  },
  {
    id: 'psq-autism',
    instrument: 'Pediatric Sleep Questionnaire',
    acronym: 'PSQ',
    linkedCosSlugs: ['autism-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'مدرج في ICHOM Track B؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'يجب تحديد form/subscale وشروط الاستخدام قبل التشغيل؛ اسم PSQ وحده لا يكفي لتكوين نموذج.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الإصدار العربي المطابق لم يُدقق بعد',
    arabicEvidenceNote: 'أي دليل عربي يجب أن يطابق النسخة/الغرض الموصى بهما في المسار التنفيذي.',
    evidenceUrl: AUTISM_SOURCE,
    evidenceCitation: 'ICHOM Autism Spectrum Disorder Set — Global Track B',
    lastVerified: '2026-09-06',
  },
];
