import type { InstrumentCrosswalkRecord } from '@/lib/core-outcome-sets/instrument-crosswalk';

const ADDICTION_SOURCE = 'https://www.mdpi.com/2077-0383/13/7/2154';
const PROMIS_SOURCE = 'https://www.healthmeasures.net/explore-measurement-systems/promis/obtain-administer-measures';

export const addictionInstrumentMappings: readonly InstrumentCrosswalkRecord[] = [
  {
    id: 'top-addiction-ichom',
    instrument: 'Treatment Outcome Profile — frequency/quantity items as adapted in the ICHOM addiction Standard Set',
    acronym: 'TOP',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به في ICHOM؛ غير مضاف بعد إلى مكتبة روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'وجود TOP في ICHOM لا يثبت حق نسخ البنود أو تشغيل النسخة المعدلة. يلزم تثبيت مصدر النسخة وشروط استخدامها قبل أي نموذج تفاعلي.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'النسخة العربية المطابقة لم تُدقق بعد',
    arabicEvidenceNote: 'لم نثبت بعد ترجمة عربية مطابقة لبنود TOP/التعديلات المستخدمة في Standard Set ولا خصائصها السيكومترية في خدمات الإدمان العربية.',
    evidenceUrl: ADDICTION_SOURCE,
    evidenceCitation: 'Black et al., Journal of Clinical Medicine, 2024; Table 1; DOI 10.3390/jcm13072154',
    lastVerified: '2026-09-06',
  },
  {
    id: 'promis-alcohol-use-7a',
    instrument: 'PROMIS Alcohol Use — Short Form 7a',
    acronym: 'PROMIS Alcohol Use 7a',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به في ICHOM؛ غير مضاف بعد إلى مكتبة روافد',
    rightsStatus: 'license-or-permission-required',
    rightsNote: 'ICHOM يوصي بهذه النسخة لعبء أعراض اضطراب استخدام الكحول. HealthMeasures يتحكم في الترجمات والتنفيذ الإلكتروني وشروط الاستخدام؛ لا ننشر البنود من المقالة.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'توفر النسخة العربية الدقيقة لم يُثبت بعد',
    arabicEvidenceNote: 'وجود PROMIS كنظام متعدد اللغات لا يثبت توفر Alcohol Use 7a بالعربية أو تكافؤها في مجتمع عربي محدد.',
    evidenceUrl: PROMIS_SOURCE,
    evidenceCitation: 'Black et al., 2024, ICHOM addiction Standard Set; HealthMeasures PROMIS permissions/translation workflow',
    lastVerified: '2026-09-06',
  },
  {
    id: 'promis-substance-use-7a',
    instrument: 'PROMIS Severity of Substance Use — Past 30 Days, Short Form 7a',
    acronym: 'PROMIS Substance Use 7a',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به في ICHOM؛ غير مضاف بعد إلى مكتبة روافد',
    rightsStatus: 'license-or-permission-required',
    rightsNote: 'أداة PROMIS محددة في Standard Set لاضطرابات المواد؛ الترجمات والاستخدام الإلكتروني تخضع لمسار HealthMeasures.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'توفر النسخة العربية الدقيقة لم يُثبت بعد',
    arabicEvidenceNote: 'يلزم التحقق من short form 7a نفسها، لا من PROMIS عام أو أداة أخرى في عائلة Substance Use.',
    evidenceUrl: PROMIS_SOURCE,
    evidenceCitation: 'Black et al., 2024, ICHOM addiction Standard Set; HealthMeasures PROMIS permissions/translation workflow',
    lastVerified: '2026-09-06',
  },
  {
    id: 'promis-nicotine-dependence-8a',
    instrument: 'PROMIS Nicotine Dependence for All Smokers — Short Form 8a',
    acronym: 'PROMIS Nicotine Dependence 8a',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به في ICHOM؛ غير مضاف بعد إلى مكتبة روافد',
    rightsStatus: 'license-or-permission-required',
    rightsNote: 'يوصى به لعبء أعراض اضطراب استخدام التبغ، مع Heaviness of Smoking Index في Standard Set. حقوق وترجمات PROMIS تُراجع عبر HealthMeasures.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'توفر النسخة العربية الدقيقة لم يُثبت بعد',
    arabicEvidenceNote: 'لا ننقل دليل نسخة PROMIS أخرى أو مقياس اعتماد نيكوتين آخر إلى هذه النسخة ذات 8 بنود.',
    evidenceUrl: PROMIS_SOURCE,
    evidenceCitation: 'Black et al., 2024, ICHOM addiction Standard Set; HealthMeasures PROMIS permissions/translation workflow',
    lastVerified: '2026-09-06',
  },
  {
    id: 'heaviness-of-smoking-index',
    instrument: 'Heaviness of Smoking Index',
    acronym: 'HSI',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به في ICHOM؛ غير مضاف بعد إلى مكتبة روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'Standard Set يقرنه بقياس اعتماد النيكوتين. يجب تثبيت نص البنود وطريقة scoring ومصدر الاستخدام قبل النشر.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الدليل العربي للإصدار المقصود لم يُدقق بعد',
    arabicEvidenceNote: 'نحتاج مراجعة مستقلة للترجمة والعتبات والأداء السيكومتري في مجتمعات عربية قبل وصفه بأنه جاهز عربيًا.',
    evidenceUrl: ADDICTION_SOURCE,
    evidenceCitation: 'Black et al., Journal of Clinical Medicine, 2024; Table 1; DOI 10.3390/jcm13072154',
    lastVerified: '2026-09-06',
  },
  {
    id: 'pgsi',
    instrument: 'Problem Gambling Severity Index',
    acronym: 'PGSI',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به في ICHOM؛ غير مضاف بعد إلى مكتبة روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'موصى به لعبء أعراض اضطراب المقامرة. إعادة نشر البنود والتشغيل تحتاج مراجعة provenance/rights مستقلة.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الدليل العربي المطابق لم يُدقق بعد',
    arabicEvidenceNote: 'لا يكفي وجود دراسات عربية للمقامرة؛ يلزم تثبيت ترجمة PGSI نفسها وسياقها وخصائصها.',
    evidenceUrl: ADDICTION_SOURCE,
    evidenceCitation: 'Black et al., Journal of Clinical Medicine, 2024; Table 1; DOI 10.3390/jcm13072154',
    lastVerified: '2026-09-06',
  },
  {
    id: 'igdt-10',
    instrument: 'Internet Gaming Disorder Test — 10 item',
    acronym: 'IGDT-10',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به في ICHOM؛ غير مضاف بعد إلى مكتبة روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'موصى به لعبء أعراض اضطراب الألعاب. يلزم تدقيق حق إعادة النشر والنسخة الدقيقة قبل أي تطبيق تفاعلي.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الدليل العربي المطابق لم يُدقق بعد',
    arabicEvidenceNote: 'يلزم تدقيق IGDT-10 تحديدًا بدل الاستدلال من مقاييس ألعاب أخرى أو ترجمات غير موثقة.',
    evidenceUrl: ADDICTION_SOURCE,
    evidenceCitation: 'Black et al., Journal of Clinical Medicine, 2024; Table 1; DOI 10.3390/jcm13072154',
    lastVerified: '2026-09-06',
  },
  {
    id: 'whodas-addiction-source-level',
    instrument: 'WHO Disability Assessment Schedule — ICHOM addiction recommendation; publication does not specify a length/version in the recommendation table',
    acronym: 'WHODAS (addiction source-level)',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به في ICHOM على مستوى العائلة؛ الإصدار الدقيق يحتاج حسمًا',
    rightsStatus: 'license-or-permission-required',
    rightsNote: 'WHO تضع مسار ترخيص لإعادة إنتاج WHODAS أو دمجه إلكترونيًا. لا نربط توصية الإدمان تلقائيًا بسجل WHODAS-12 الحالي لأن طول/إصدار الأداة غير محدد في جدول ICHOM المنشور.',
    arabicEvidence: 'official-or-linguistic-translation',
    arabicEvidenceLabel: 'العربية متاحة لعائلة WHODAS؛ exact-version غير محسوم هنا',
    arabicEvidenceNote: 'وجود العربية في موارد WHO لا يحل مسألة أي إصدار استُخدم في Standard Set ولا يثبت الخصائص السيكومترية لسياق الإدمان العربي.',
    evidenceUrl: 'https://www.who.int/classifications/international-classification-of-functioning-disability-and-health/who-disability-assessment-schedule',
    evidenceCitation: 'Black et al., 2024; WHO WHODAS 2.0 resources/licensing — exact-version deliberately unresolved',
    lastVerified: '2026-09-06',
  },
  {
    id: 'sure-addiction',
    instrument: 'Substance Use Recovery Evaluator',
    acronym: 'SURE',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى به لبعض اضطرابات المواد؛ غير مضاف بعد إلى روافد',
    rightsStatus: 'not-reviewed',
    rightsNote: 'ICHOM يستخدم SURE كقياس condition-specific في مسار التعافي من اضطرابات الكحول/المخدرات؛ نطاقه لا يُعمم تلقائيًا على المقامرة أو الألعاب أو التبغ.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'النسخة العربية المطابقة لم تُدقق بعد',
    arabicEvidenceNote: 'يجب تدقيق الترجمة وملاءمة مفهوم recovery في السياق العربي وحقوق البنود قبل التشغيل.',
    evidenceUrl: ADDICTION_SOURCE,
    evidenceCitation: 'Black et al., Journal of Clinical Medicine, 2024; Table 1; DOI 10.3390/jcm13072154',
    lastVerified: '2026-09-06',
  },
  {
    id: 'promis-global-health-addiction-items',
    instrument: 'PROMIS Global Health — selected overall physical and mental health items used by the ICHOM addiction Standard Set',
    acronym: 'PROMIS Global Health items',
    linkedCosSlugs: ['addiction-ichom-standard-set'],
    rawafidStatus: 'not-in-library',
    rawafidStatusLabel: 'موصى بها كبنود مختارة؛ غير مضافة بعد إلى روافد',
    rightsStatus: 'license-or-permission-required',
    rightsNote: 'ICHOM يختار بندًا للصحة الجسدية وبندين للصحة النفسية من PROMIS Global Health. لا نعيد تكوين البنود من المقالة؛ التنفيذ والترجمة يمران عبر HealthMeasures.',
    arabicEvidence: 'not-audited',
    arabicEvidenceLabel: 'الترجمة العربية للبنود المحددة لم تُثبت بعد',
    arabicEvidenceNote: 'وجود ترجمة PROMIS Global Health لا يكفي دون مطابقة البنود والإصدار وطريقة scoring المطلوبة في Standard Set.',
    evidenceUrl: PROMIS_SOURCE,
    evidenceCitation: 'Black et al., 2024, ICHOM addiction Standard Set; HealthMeasures PROMIS permissions/translation workflow',
    lastVerified: '2026-09-06',
  },
];
