import type { CSSProperties } from 'react';
import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata, breadcrumbJsonLd, SITE_URL } from '@/lib/seo';
import { mathLogicActivities, mathLogicActivityCount, mathLogicSeriesPlans, mathLogicTestCount } from '@/lib/capabilities/math-logic-lab';
import styles from '../kids-lab.module.css';

export const metadata=buildSeoMetadata({title:'التفكير الرياضي والمنطقي للأطفال | أنشطة واختبارات متدرجة',description:'خمس سلاسل متدرجة للأنماط والتصنيف والكمية والمقارنة والترتيب والمنطق البصري، بعد تنقيح التكرار مع الحفاظ على اختبارات الإتقان.',path:'/capabilities/kids-lab/math-logic/',index:true,keywords:['رياضيات مبكرة للأطفال','الأنماط للأطفال','التصنيف','الكمية والمقارنة','الترتيب والتسلسل','المنطق البصري']});
const principles=[['القاعدة قبل الإجابة','نقيس اكتشاف العلاقة أو القاعدة، لا مجرد الوصول إلى خانة صحيحة بالصدفة.'],['افصل العدد عن المظهر','تتغير أحجام العناصر وتوزيعاتها حتى لا يساوي الطفل بين المساحة البصرية والكمية.'],['غيّر بُعدًا ثم بُعدين','التصنيف والأنماط ينتقلان من خاصية واحدة إلى قواعد تجمع الشكل واللون والحجم تدريجيًا.'],['ألغاز قابلة للحل','شبكات المنطق مولدة من بناء لاتيني صحيح؛ الفراغات تحذف من حل صالح بدل إنشاء شبكة عشوائية.']];
export default function MathLogicPage(){const breadcrumbs=breadcrumbJsonLd([{name:'الرئيسية',path:'/'},{name:'مختبر الأطفال',path:'/capabilities/kids-lab/'},{name:'التفكير الرياضي والمنطقي',path:'/capabilities/kids-lab/math-logic/'}]);const collection={'@context':'https://schema.org','@type':'CollectionPage','@id':`${SITE_URL}/capabilities/kids-lab/math-logic/#collection`,url:`${SITE_URL}/capabilities/kids-lab/math-logic/`,name:'أنشطة التفكير الرياضي والمنطقي للأطفال',inLanguage:'ar',isAccessibleForFree:true,numberOfItems:mathLogicActivityCount};return <><SiteHeader/><main className={styles.shell}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([breadcrumbs,collection]).replace(/</g,'\\u003c')}}/><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><span>الرياضيات والمنطق</span></nav><section className={styles.hero}><span className={styles.kicker}>المجال التاسع - التفكير الرياضي والمنطقي</span><h1>قواعد، علاقات، كميات واستدلال بصري متدرج</h1><p className={styles.lead}>خمس سلاسل مختلفة فعليًا: اكتشاف النمط، تغيير قاعدة التصنيف، مقارنة العدد بعيدًا عن خداع الحجم والتوزيع، بناء ترتيب كامل، وحل شبكات منطقية قابلة للاستدلال.</p><div className={styles.stats}><div className={styles.stat}><strong>{mathLogicSeriesPlans.length}</strong><span>سلاسل</span></div><div className={styles.stat}><strong>5</strong><span>مستويات</span></div><div className={styles.stat}><strong>{mathLogicTestCount}</strong><span>اختبار إتقان</span></div><div className={styles.stat}><strong>{mathLogicActivityCount}</strong><span>عنصرًا</span></div></div></section><section className={styles.section}><div className={styles.categoryGrid}>{mathLogicSeriesPlans.map(s=>{const count=mathLogicActivities.filter(a=>a.seriesSlug===s.slug).length;return <article className={styles.categoryCard} style={{'--category-color':'#F59E0B'} as CSSProperties} key={s.slug}><span className={styles.kicker}>السلسلة {s.number}</span><h3>{s.title}</h3><p>{s.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>{s.ages}</span><span className={styles.metaChip}>{s.duration}</span><span className={styles.metaChip}>{count} عنصرًا</span></div><div className={styles.actions}><Link className={styles.primaryButton} href={`/capabilities/kids-lab/math-logic/${s.slug}/`}>افتح السلسلة</Link></div></article>})}</div></section><section className={styles.section}><div className={styles.flow}>{principles.map(([t,b],i)=><article className={styles.flowCard} key={t}><span className={styles.flowNumber}>{i+1}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section><section className={styles.section}><div className={styles.note}><strong>حدود الاستخدام:</strong> هذه مهام تعليمية لمتابعة إتقان مهارات محددة، وليست اختبار ذكاء أو اختبار تحصيل رياضي معياري. نستخدم الأداء لتحديد مستوى التدريب التالي فقط.</div></section></main><SiteFooter/></>}
