import { sitemapResponse } from '@/lib/sitemap-xml';
import { infographics } from '@/lib/practical-resources';
import { assessmentSlugs } from '@/lib/assessment-lab/catalog';

export async function GET() {
  return sitemapResponse([
    { path:'/', changeFrequency:'weekly', priority:1 },
    { path:'/sectors', changeFrequency:'weekly', priority:.92 },
    { path:'/sections', changeFrequency:'weekly', priority:.9 },
    { path:'/quick-info/', changeFrequency:'weekly', priority:.84 },
    { path:'/encyclopedia/', changeFrequency:'weekly', priority:.88 },
    { path:'/magazine/', changeFrequency:'daily', priority:.84 },
    { path:'/care-guides/', changeFrequency:'weekly', priority:.86 },
    { path:'/evidence-guides/', changeFrequency:'weekly', priority:.86 },
    { path:'/addiction', changeFrequency:'weekly', priority:.82 },
    { path:'/specialists', changeFrequency:'weekly', priority:.78 },
    { path:'/centers', changeFrequency:'weekly', priority:.78 },
    { path:'/cognitive-lab', changeFrequency:'monthly', priority:.8 },
    { path:'/community', changeFrequency:'weekly', priority:.65 },
    { path:'/about', changeFrequency:'monthly', priority:.7 },
    { path:'/institutions', changeFrequency:'monthly', priority:.72 },
    { path:'/en/institutions', changeFrequency:'monthly', priority:.68 },
    { path:'/institutions/arabic-rtl-assurance', changeFrequency:'monthly', priority:.68 },
    { path:'/institutions/terminology-qa', changeFrequency:'monthly', priority:.68 },
    { path:'/institutions/open-source', changeFrequency:'monthly', priority:.66 },
    { path:'/start-here', changeFrequency:'monthly', priority:.78 },
    { path:'/guided-assessment', changeFrequency:'monthly', priority:.68 },
    { path:'/assessment-lab', changeFrequency:'monthly', priority:.76 },
    ...assessmentSlugs.map((slug) => ({ path:`/assessment-lab/${slug}`, changeFrequency:'monthly' as const, priority:.7 })),
    { path:'/resources', changeFrequency:'weekly', priority:.68 },
    { path:'/resources/worksheets', changeFrequency:'monthly', priority:.66 },
    { path:'/resources/infographics', changeFrequency:'monthly', priority:.7 },
    ...infographics.map((item) => ({ path:`/resources/infographics/${item.slug}`, changeFrequency:'monthly' as const, priority:.68 })),
    { path:'/tools', changeFrequency:'weekly', priority:.7 },
    { path:'/tools/compare', changeFrequency:'monthly', priority:.64 },
    { path:'/tools/quiz', changeFrequency:'monthly', priority:.64 },
    { path:'/tools/daily-term', changeFrequency:'daily', priority:.64 },
    { path:'/audiences', changeFrequency:'monthly', priority:.66 },
    { path:'/capabilities/ideas/', changeFrequency:'monthly', priority:.68 },
    { path:'/capabilities/printables/', changeFrequency:'monthly', priority:.68 },
    { path:'/downloads', changeFrequency:'weekly', priority:.62 },
    { path:'/citation', changeFrequency:'monthly', priority:.58 },
    { path:'/sources', changeFrequency:'monthly', priority:.62 },
    { path:'/join', changeFrequency:'monthly', priority:.55 },
    { path:'/join/specialist', changeFrequency:'monthly', priority:.5 },
    { path:'/join/center', changeFrequency:'monthly', priority:.5 },
    { path:'/medical-review-policy', changeFrequency:'monthly', priority:.6 },
    { path:'/editorial-policy', changeFrequency:'monthly', priority:.6 },
    { path:'/disclaimer', changeFrequency:'monthly', priority:.45 },
    { path:'/privacy', changeFrequency:'monthly', priority:.4 },
    { path:'/terms', changeFrequency:'monthly', priority:.4 },
  ]);
}
