import { sitemapResponse } from '@/lib/sitemap-xml';
import { infographics } from '@/lib/practical-resources';
import { assessmentSlugs } from '@/lib/assessment-lab/catalog';
import { assessmentMeasureCategories, assessmentMeasureSlugs } from '@/lib/assessment-measures-catalog';
import { coreOutcomeRegistrySlugs } from '@/lib/core-outcome-sets/registry';
import { bilateralActivities } from '@/lib/capabilities/bilateral-tracks';
import { bilateralLabActivities, bilateralLabSeriesPlans } from '@/lib/capabilities/bilateral-lab';
import { attentionActivities, attentionSeriesPlans } from '@/lib/capabilities/attention-lab';
import { memoryActivities, memorySeriesPlans } from '@/lib/capabilities/memory-lab';
import { executiveActivities, executiveSeriesPlans } from '@/lib/capabilities/executive-functions-lab';
import { visualPerceptionActivities, visualPerceptionSeriesPlans } from '@/lib/capabilities/visual-perception-lab';
import { visualMotorActivities, visualMotorSeriesPlans } from '@/lib/capabilities/visual-motor-lab';
import { fineMotorActivities, fineMotorSeriesPlans } from '@/lib/capabilities/fine-motor-lab';
import { languageReadingActivities, languageReadingSeriesPlans } from '@/lib/capabilities/language-reading-lab';
import { mathLogicActivities, mathLogicSeriesPlans } from '@/lib/capabilities/math-logic-lab';

export async function GET(){return sitemapResponse([
{path:'/',changeFrequency:'weekly',priority:1},{path:'/sectors',changeFrequency:'weekly',priority:.92},{path:'/sections',changeFrequency:'weekly',priority:.9},{path:'/magazine/',changeFrequency:'daily',priority:.84},{path:'/addiction',changeFrequency:'weekly',priority:.82},{path:'/about',changeFrequency:'monthly',priority:.7},{path:'/press',changeFrequency:'monthly',priority:.66},{path:'/start-here',changeFrequency:'monthly',priority:.78},{path:'/campaigns/all-families-reading-challenge-2026',changeFrequency:'weekly',priority:.78},{path:'/guided-assessment',changeFrequency:'monthly',priority:.68},{path:'/assessment-lab',changeFrequency:'monthly',priority:.76},
...assessmentSlugs.map((slug)=>({path:`/assessment-lab/${slug}`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/core-outcome-sets/',changeFrequency:'monthly',priority:.8},{path:'/core-outcome-sets/instrument-crosswalk/',changeFrequency:'monthly',priority:.8},...coreOutcomeRegistrySlugs.map((slug)=>({path:`/core-outcome-sets/${slug}/`,changeFrequency:'monthly' as const,priority:.78})),
{path:'/assessment-measures/',changeFrequency:'weekly',priority:.84},{path:'/assessment-measures/compare/',changeFrequency:'monthly',priority:.72},{path:'/assessment-measures/methodology/',changeFrequency:'monthly',priority:.7},{path:'/assessment-measures/rights-register/',changeFrequency:'monthly',priority:.68},{path:'/assessment-measures/rights-review/',changeFrequency:'monthly',priority:.66},...assessmentMeasureSlugs.map((slug)=>({path:`/assessment-measures/${slug}/`,changeFrequency:'monthly' as const,priority:.74})),...assessmentMeasureCategories.map((category)=>({path:`/assessment-measures/category/${category.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/resources',changeFrequency:'weekly',priority:.68},{path:'/resources/worksheets',changeFrequency:'monthly',priority:.66},{path:'/resources/infographics',changeFrequency:'monthly',priority:.7},...infographics.map((item)=>({path:`/resources/infographics/${item.slug}`,changeFrequency:'monthly' as const,priority:.68})),
{path:'/tools',changeFrequency:'weekly',priority:.7},{path:'/tools/compare',changeFrequency:'monthly',priority:.64},{path:'/tools/quiz',changeFrequency:'monthly',priority:.64},{path:'/tools/daily-term',changeFrequency:'daily',priority:.64},{path:'/audiences',changeFrequency:'monthly',priority:.66},{path:'/capabilities/ideas/',changeFrequency:'monthly',priority:.68},{path:'/capabilities/printables/',changeFrequency:'monthly',priority:.68},
{path:'/capabilities/kids-lab/',changeFrequency:'weekly',priority:.8},
{path:'/capabilities/kids-lab/attention/',changeFrequency:'weekly',priority:.8},...attentionSeriesPlans.map((series)=>({path:`/capabilities/kids-lab/attention/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...attentionActivities.map((activity)=>({path:`/capabilities/kids-lab/attention/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/memory/',changeFrequency:'weekly',priority:.8},...memorySeriesPlans.map((series)=>({path:`/capabilities/kids-lab/memory/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...memoryActivities.map((activity)=>({path:`/capabilities/kids-lab/memory/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/executive-functions/',changeFrequency:'weekly',priority:.8},...executiveSeriesPlans.map((series)=>({path:`/capabilities/kids-lab/executive-functions/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...executiveActivities.map((activity)=>({path:`/capabilities/kids-lab/executive-functions/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/visual-perception/',changeFrequency:'weekly',priority:.8},...visualPerceptionSeriesPlans.map((series)=>({path:`/capabilities/kids-lab/visual-perception/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...visualPerceptionActivities.map((activity)=>({path:`/capabilities/kids-lab/visual-perception/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/visual-motor/',changeFrequency:'weekly',priority:.8},...visualMotorSeriesPlans.map((series)=>({path:`/capabilities/kids-lab/visual-motor/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...visualMotorActivities.map((activity)=>({path:`/capabilities/kids-lab/visual-motor/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/fine-motor/',changeFrequency:'weekly',priority:.8},...fineMotorSeriesPlans.map((series)=>({path:`/capabilities/kids-lab/fine-motor/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...fineMotorActivities.map((activity)=>({path:`/capabilities/kids-lab/fine-motor/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/bilateral/',changeFrequency:'weekly',priority:.8},...bilateralLabSeriesPlans.map((series)=>({path:`/capabilities/kids-lab/bilateral/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...bilateralLabActivities.map((activity)=>({path:`/capabilities/kids-lab/bilateral/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/bilateral-tracks/',changeFrequency:'weekly',priority:.76},...bilateralActivities.map((activity)=>({path:`/capabilities/kids-lab/bilateral-tracks/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/language-reading/',changeFrequency:'weekly',priority:.8},...languageReadingSeriesPlans.map((series)=>({path:`/capabilities/kids-lab/language-reading/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...languageReadingActivities.map((activity)=>({path:`/capabilities/kids-lab/language-reading/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/capabilities/kids-lab/math-logic/',changeFrequency:'weekly',priority:.8},...mathLogicSeriesPlans.map((series)=>({path:`/capabilities/kids-lab/math-logic/${series.slug}/`,changeFrequency:'weekly' as const,priority:.76})),...mathLogicActivities.map((activity)=>({path:`/capabilities/kids-lab/math-logic/${activity.seriesSlug}/${activity.slug}/`,changeFrequency:'monthly' as const,priority:.7})),
{path:'/downloads',changeFrequency:'weekly',priority:.62},{path:'/citation',changeFrequency:'monthly',priority:.58},{path:'/sources',changeFrequency:'monthly',priority:.62},{path:'/developers',changeFrequency:'weekly',priority:.64},{path:'/open-source',changeFrequency:'weekly',priority:.68},{path:'/open-source/arabic-rtl-a11y-toolkit',changeFrequency:'weekly',priority:.66},{path:'/join',changeFrequency:'monthly',priority:.55},{path:'/join/specialist',changeFrequency:'monthly',priority:.5},{path:'/join/center',changeFrequency:'monthly',priority:.5},{path:'/medical-review-policy',changeFrequency:'monthly',priority:.6},{path:'/editorial-policy',changeFrequency:'monthly',priority:.6},{path:'/disclaimer',changeFrequency:'monthly',priority:.45},{path:'/privacy',changeFrequency:'monthly',priority:.4},{path:'/terms',changeFrequency:'monthly',priority:.4}
]);}
