import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata } from '@/lib/seo';
import { fineMotorSeriesPlans,getFineMotorActivitiesForSeries,getFineMotorSeries } from '@/lib/capabilities/fine-motor-lab';
import styles from '../../kids-lab.module.css';

type Props={params:Promise<{series:string}>};
export function generateStaticParams(){return fineMotorSeriesPlans.map(series=>({series:series.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {series:slug}=await params;const series=getFineMotorSeries(slug);if(!series)return{};const count=getFineMotorActivitiesForSeries(slug).length;return buildSeoMetadata({title:`${series.title} للأطفال | 5 مستويات و${count} عنصرًا`,description:`${series.purpose} خمسة مستويات متدرجة مع تدريب واختبارات إتقان منقحة لتقليل التكرار.`,path:`/capabilities/kids-lab/fine-motor/${series.slug}/`,index:true,keywords:[series.title,'المهارات الحركية الدقيقة للأطفال','ما قبل الكتابة','أنشطة قابلة للطباعة']});}
export default async function FineMotorSeriesPage({params}:Props){const {series:slug}=await params;const series=getFineMotorSeries(slug);if(!series)notFound();const activities=getFineMotorActivitiesForSeries(slug);return <><SiteHeader/><main className={styles.shell}><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><Link href="/capabilities/kids-lab/fine-motor/">الحركية الدقيقة</Link><span>/</span><span>{series.title}</span></nav><section className={styles.hero}><span className={styles.kicker}>السلسلة {series.number}</span><h1>{series.title}</h1><p className={styles.lead}>{series.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>العمر: {series.ages}</span><span className={styles.metaChip}>المدة: {series.duration}</span><span className={styles.metaChip}>5 مستويات</span><span className={styles.metaChip}>{activities.length} عنصرًا</span></div></section><section className={styles.section}><div className={styles.flow}>{Array.from({length:5},(_,i)=>i+1).map(level=>{const items=activities.filter(a=>a.level===level);return <article className={styles.flowCard} key={level}><span className={styles.flowNumber}>{level}</span><h3>المستوى {level}</h3><p>{series.progression[level-1]}</p><div className={styles.seriesList}>{items.map(a=><Link className={a.kind==='test'?styles.seriesActive:styles.seriesItem} href={`/capabilities/kids-lab/fine-motor/${series.slug}/${a.slug}/`} key={a.slug}><span><strong>{a.label}</strong><small>{a.title}</small></span>{a.kind==='test'&&<span className={styles.readyBadge}>اختبار</span>}</Link>)}</div></article>})}</div></section><section className={styles.section}><div className={styles.note}><strong>ما الذي نراقبه؟</strong> {series.observation}</div></section></main><SiteFooter/></>}
