'use client';
import { useEffect, useMemo, useState } from 'react';
import styles from '@/app/sectors/calendars/calendar.module.css';

type Task={id:string;title:string;due:string;minutes:number;priority:'low'|'medium'|'high';done:boolean};
type State={tasks:Task[];topic:string;energy:'low'|'medium'|'high'};
const KEY='rawafid:student-calendar:v1';
const empty:State={tasks:[],topic:'',energy:'medium'};
const reviewDays=[1,3,7,14,30];
function datePlus(days:number){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function escapeIcs(value:string){return value.replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\n/g,'\\n')}
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export default function StudentCalendarPlanner(){
 const [state,setState]=useState<State>(empty);const [title,setTitle]=useState('');const [due,setDue]=useState('');const [minutes,setMinutes]=useState(45);const [priority,setPriority]=useState<Task['priority']>('medium');const [timerMinutes,setTimerMinutes]=useState(45);const [seconds,setSeconds]=useState(45*60);const [running,setRunning]=useState(false);
 useEffect(()=>{try{const parsed=JSON.parse(localStorage.getItem(KEY)||'null');if(parsed&&Array.isArray(parsed.tasks))setState({...empty,...parsed,tasks:parsed.tasks.slice(0,200)})}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}},[state]);
 useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setSeconds((value)=>{if(value<=1){setRunning(false);return 0}return value-1}),1000);return()=>window.clearInterval(id)},[running]);
 const sessionLength=state.energy==='low'?25:state.energy==='high'?60:45;const openTasks=useMemo(()=>state.tasks.filter((task)=>!task.done).sort((a,b)=>Number(b.priority==='high')-Number(a.priority==='high')||a.due.localeCompare(b.due)),[state.tasks]);
 function update(next:State){setState(next)}
 function addTask(){const clean=title.trim().slice(0,160);if(!clean)return;update({...state,tasks:[...state.tasks,{id:crypto.randomUUID(),title:clean,due,minutes:Math.min(Math.max(Number(minutes)||15,5),600),priority,done:false}].slice(-200)});setTitle('');setDue('')}
 function setTimer(value:number){setRunning(false);setTimerMinutes(value);setSeconds(value*60)}
 function exportIcs(){const events=state.tasks.filter((task)=>task.due).map((task,index)=>{const d=task.due.replaceAll('-','');return ['BEGIN:VEVENT',`UID:rawafid-task-${index}-${d}@local`,`DTSTART;VALUE=DATE:${d}`,`SUMMARY:${escapeIcs(task.title)}`,'END:VEVENT'].join('\r\n')});const reviews=state.topic.trim()?reviewDays.map((days,index)=>{const d=datePlus(days).replaceAll('-','');return ['BEGIN:VEVENT',`UID:rawafid-review-${index}-${d}@local`,`DTSTART;VALUE=DATE:${d}`,`SUMMARY:${escapeIcs(`مراجعة: ${state.topic.trim()}`)}`,'END:VEVENT'].join('\r\n')}):[];download('rawafid-study-calendar.ics',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Rawafid//Student Calendar//AR',...events,...reviews,'END:VCALENDAR'].join('\r\n'),'text/calendar;charset=utf-8')}
 function exportJson(){download('rawafid-student-calendar.json',JSON.stringify(state,null,2),'application/json')}
 const display=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
 return <div className={styles.grid}>
  <section className={styles.tool}><h2>إعداد الطالب وخطة اليوم</h2><div className={styles.form}><label>طاقتك المتاحة اليوم<select value={state.energy} onChange={(e)=>update({...state,energy:e.target.value as State['energy']})}><option value="low">منخفضة — جلسات أقصر</option><option value="medium">متوسطة</option><option value="high">جيدة — جلسات أطول</option></select></label><p>طول الجلسة المقترح: <strong>{sessionLength} دقيقة</strong>. هو اقتراح تنظيمي قابل للتعديل، وليس قياسًا لقدرتك.</p><label>مهمة أو مادة<input value={title} onChange={(e)=>setTitle(e.target.value)} maxLength={160}/></label><label>موعد التسليم<input type="date" value={due} onChange={(e)=>setDue(e.target.value)}/></label><label>الوقت المتوقع بالدقائق<input type="number" min="5" max="600" value={minutes} onChange={(e)=>setMinutes(Number(e.target.value))}/></label><label>الأولوية<select value={priority} onChange={(e)=>setPriority(e.target.value as Task['priority'])}><option value="low">منخفضة</option><option value="medium">متوسطة</option><option value="high">مرتفعة</option></select></label><button type="button" onClick={addTask}>إضافة المهمة</button></div><h3>المهام المفتوحة</h3>{openTasks.length?<ul className={styles.list}>{openTasks.map((task)=><li key={task.id}><div className={styles.taskRow}><div><strong>{task.title}</strong><div className={styles.taskMeta}>{task.due||'دون موعد'} · {task.minutes} دقيقة · {task.priority==='high'?'أولوية مرتفعة':task.priority==='medium'?'متوسطة':'منخفضة'}</div></div><div className={styles.taskButtons}><button type="button" onClick={()=>update({...state,tasks:state.tasks.map((item)=>item.id===task.id?{...item,done:true}:item)})}>تم</button><button type="button" onClick={()=>update({...state,tasks:state.tasks.filter((item)=>item.id!==task.id)})}>حذف</button></div></div></li>)}</ul>:<p>لا توجد مهام مفتوحة بعد.</p>}</section>
  <section className={`${styles.tool} ${styles.timer}`}><h2>مؤقت جلسة الدراسة</h2><p>اختر مدة واقعية، واعتبر انتهاء الجلسة نقطة مراجعة لا اختبارًا لقوة الإرادة.</p><div className={styles.time} aria-live="polite">{display}</div><div className={styles.actions}>{[25,45,60,90].map((value)=><button type="button" className={styles.secondary} key={value} onClick={()=>setTimer(value)}>{value} دقيقة</button>)}</div><div className={styles.actions}><button type="button" className={styles.button} onClick={()=>setRunning((value)=>!value)}>{running?'إيقاف مؤقت':'بدء'}</button><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={()=>setTimer(timerMinutes)}>إعادة ضبط</button></div></section>
  <section className={styles.tool}><h2>المراجعة المتباعدة</h2><p>أدخل موضوعًا لتوليد نقاط مراجعة بعد 1 و3 و7 و14 و30 يومًا. عدّل الجدول وفق المادة والاختبارات وتغذية المدرس الراجعة.</p><div className={styles.form}><label>موضوع المراجعة<input value={state.topic} onChange={(e)=>update({...state,topic:e.target.value.slice(0,160)})} maxLength={160}/></label></div>{state.topic.trim()?<div className={styles.reviewGrid}>{reviewDays.map((days)=><span key={days}><strong>+{days}</strong><br/>{datePlus(days)}</span>)}</div>:null}</section>
  <section className={styles.tool}><h2>التذكيرات والنسخ الاحتياطي</h2><p>أنشئ ملف ICS للمهام ذات المواعيد ومراجعات الموضوع الحالي، أو نسخة JSON من بيانات التنظيم المحلية.</p><div className={styles.actions}><button type="button" className={styles.button} onClick={exportIcs}>تنزيل تقويم ICS</button><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={exportJson}>نسخة JSON</button><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={()=>{localStorage.removeItem(KEY);setState(empty)}}>مسح البيانات المحلية</button></div><div className={styles.notice}><strong>الخصوصية:</strong> المهام والطاقة والمراجعات تُحفظ في هذا المتصفح فقط. هذا المكوّن لا يرسلها إلى الخادم.</div></section>
 </div>
}
