'use client';
import { useEffect,useState } from 'react';import styles from '@/app/sectors/calendars/calendar.module.css';
type Entry={date:string;mood:number;energy:number;pain:number;bleeding:'none'|'light'|'moderate'|'heavy';notes:string};const KEY='rawafid:women-calendar:v1';
function download(content:string){const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='rawafid-women-calendar.json';a.click();URL.revokeObjectURL(url)}
export default function WomenCalendarTracker(){const [entries,setEntries]=useState<Entry[]>([]);const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10));const [mood,setMood]=useState(3);const [energy,setEnergy]=useState(3);const [pain,setPain]=useState(0);const [bleeding,setBleeding]=useState<Entry['bleeding']>('none');const [notes,setNotes]=useState('');
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(value))setEntries(value.slice(0,400))}catch{}},[]);useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(entries))}catch{}},[entries]);
 function save(){const clean=notes.trim().slice(0,800);const next:Entry={date,mood,energy,pain,bleeding,notes:clean};setEntries((current)=>[next,...current.filter((entry)=>entry.date!==date)].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,400));setNotes('')}
 const label={none:'لا يوجد',light:'خفيف',moderate:'متوسط',heavy:'غزير'} as const;
 return <div className={styles.grid}><section className={styles.tool}><h2>إضافة متابعة يومية</h2><div className={styles.form}><label>التاريخ<input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></label><div className={styles.metricGrid}><label>المزاج 1–5<input type="number" min="1" max="5" value={mood} onChange={(e)=>setMood(Math.min(5,Math.max(1,Number(e.target.value)||1)))}/></label><label>الطاقة 1–5<input type="number" min="1" max="5" value={energy} onChange={(e)=>setEnergy(Math.min(5,Math.max(1,Number(e.target.value)||1)))}/></label><label>الألم 0–10<input type="number" min="0" max="10" value={pain} onChange={(e)=>setPain(Math.min(10,Math.max(0,Number(e.target.value)||0)))}/></label><label>النزف<select value={bleeding} onChange={(e)=>setBleeding(e.target.value as Entry['bleeding'])}><option value="none">لا يوجد</option><option value="light">خفيف</option><option value="moderate">متوسط</option><option value="heavy">غزير</option></select></label></div><label>ملاحظة اختيارية<textarea rows={4} maxLength={800} value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="مثال: أثر الألم في النوم أو الدراسة أو العمل، وأي سياق تريد تذكره عند زيارة المختص."/></label><button type="button" onClick={save}>حفظ في هذا الجهاز</button></div><div className={styles.notice}><strong>خصوصية حساسة:</strong> هذه البيانات تبقى في localStorage على هذا المتصفح ولا تُرسل إلى روافد. أي شخص يستخدم ملف المتصفح نفسه قد يستطيع الوصول إليها.</div></section><section className={styles.tool}><h2>السجل الأخير</h2>{entries.length?<div className={styles.entries}>{entries.slice(0,30).map((entry)=><article className={styles.entry} key={entry.date}><div className={styles.taskRow}><strong>{entry.date}</strong><button type="button" className={styles.secondary} onClick={()=>setEntries((current)=>current.filter((item)=>item.date!==entry.date))}>حذف</button></div><dl><div><dt>المزاج</dt><dd>{entry.mood}/5</dd></div><div><dt>الطاقة</dt><dd>{entry.energy}/5</dd></div><div><dt>الألم</dt><dd>{entry.pain}/10</dd></div><div><dt>النزف</dt><dd>{label[entry.bleeding]}</dd></div></dl>{entry.notes?<p>{entry.notes}</p>:null}</article>)}</div>:<p>لا توجد إدخالات محفوظة بعد.</p>}<div className={styles.actions}><button type="button" className={styles.button} onClick={()=>download(JSON.stringify(entries,null,2))}>نسخة JSON محلية</button><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={()=>{localStorage.removeItem(KEY);setEntries([])}}>مسح السجل</button></div></section></div>
}
