import type { AssessmentMeasure } from '@/lib/assessment-measures';

export const assessmentMeasuresWave5: AssessmentMeasure[] = [
  {
    slug: 'ptsd-checklist-for-dsm5',
    nameAr: 'قائمة اضطراب ما بعد الصدمة لـDSM-5',
    nameEn: 'PTSD Checklist for DSM-5',
    acronym: 'PCL-5',
    version: 'DSM-5 — 20-item PCL-5',
    summary: 'مقياس تقرير ذاتي من 20 بندًا لتقدير شدة أعراض اضطراب ما بعد الصدمة وفق DSM-5، ويستخدم للفحص ومتابعة التغير مع ضرورة التقييم السريري عند التشخيص.',
    purpose: 'رصد شدة أعراض PTSD ومتابعة التغير أثناء العلاج أو بعده، ودعم الفحص الأولي ضمن مسار تقييم سريري مناسب.',
    construct: 'شدة أعراض اضطراب ما بعد الصدمة وفق مجموعات أعراض DSM-5',
    populations: ['البالغون المعرضون لأحداث صادمة', 'العسكريون والمدنيون ومجتمعات العلاج النفسي والبحوث بحسب النسخة والسياق'],
    settings: ['خدمات الصدمة', 'الصحة النفسية', 'الرعاية المتدرجة', 'البحوث السريرية'],
    categories: ['trauma-stress', 'mental-health', 'symptom-burden'],
    administrationMode: 'تقرير ذاتي عن مقدار الانزعاج من 20 عرضًا خلال الفترة المرجعية المحددة، ويمكن استخدامه بصيغ مختلفة مع أو دون تقييم Criterion A.',
    administrationTime: 'نحو 5–10 دقائق وفق National Center for PTSD.',
    equipment: ['نسخة PCL-5 الرسمية المطابقة للفترة المرجعية', 'خطة سلامة ومسار تقييم عند الاستخدام السريري'],
    scoring: 'يمكن جمع البنود إلى درجة شدة كلية من 0 إلى 80، كما يمكن حساب مجموعات الأعراض. توجد طريقة خوارزمية لفحص نمط DSM-5، لكن أي تشخيص ناتج يبقى مؤقتًا ويحتاج تقييمًا سريريًا منظمًا.',
    interpretation: 'المركز الوطني لـPTSD يذكر أن القطع بين 31 و33 استُخدم في أبحاث عديدة، لكنه يشدد على اختيار العتبة وفق المجتمع وغرض التقييم. بيانات عربية حديثة واسعة أظهرت حساسية مرتفعة للعتبات المنخفضة لكن نوعية محدودة، ما يدعم الفحص والمتابعة أكثر من التشخيص المنفرد.',
    limitations: ['مقياس تقرير ذاتي وليس المعيار الذهبي للتشخيص.', 'أداء العتبات يختلف باختلاف المجتمع وانتشار PTSD وطيف الشدة.', 'الأعراض قد تتداخل مع الاكتئاب والقلق ومشكلات النوم وحالات أخرى.', 'التقييم الدقيق لCriterion A والسياق يحتاج مقابلة إضافية.'],
    administrationSteps: ['حدد الفترة المرجعية والصيغة الرسمية المستخدمة.', 'تأكد من توفر بيئة آمنة وخيار التوقف إذا أثارت البنود ضيقًا شديدًا.', 'اجمع الاستجابات وفق مقياس 0–4 دون تغيير المراسي.', 'احسب الدرجة الكلية أو المجموعات وفق دليل PCL-5.', 'إذا كان الهدف تشخيصًا أو قرارًا عالي المخاطر، أكمل بمقابلة سريرية منظمة مثل CAPS-5 أو مسار مكافئ مناسب.'],
    safetyNotes: ['أي إفصاح عن خطر انتحار أو عنف أو خطر حالي يحتاج تقييم سلامة مستقلًا ولا ينتظر نتيجة المقياس.', 'التعرض للصدمة والأسئلة المرتبطة به قد تثير ضيقًا شديدًا؛ يجب أن يكون خيار التوقف والدعم واضحين.', 'الدرجة لا تبرر تشخيص PTSD تلقائيًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — مؤكد من National Center for PTSD وCDISC',
    rightsNote: 'National Center for PTSD ينص صراحة على أن PCL-5 طوره موظفوه وأنه في المجال العام وغير محمي بحقوق النشر، وCDISC يدرجه كذلك Public Domain. هذا لا يجعل أي ترجمة عربية من طرف ثالث تلقائيًا Public Domain.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد دراسات تحقق عربية منشورة حديثة',
    arabicNote: 'توجد دراسة عربية لدى جنود تونسيين ودراسة 2026 واسعة لدى ناطقين بالعربية من منطقة SWANA. الأخيرة وجدت بنية وموثوقية جيدتين لكن دقة تشخيصية محدودة نسبيًا، وأوصت باستخدام PCL-5 للفحص ومتابعة الأعراض مع متابعة سريرية بدل التشخيص المنفرد.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الأصل الإنجليزي Public Domain، لكن روافد لا ينشر نص ترجمة عربية كاملة قبل تثبيت مصدر الترجمة نفسها وحقوقها ومطابقتها للدراسة المستخدمة.',
    sources: [
      { label: 'VA National Center for PTSD — official PCL-5 page and Public Domain statement', url: 'https://www.ptsd.va.gov/professional/assessment/adult-sr/ptsd-checklist.asp', role: 'rights' },
      { label: 'CDISC QRS — PCL-5 Public Domain', url: 'https://www.cdisc.org/standards/foundational/qrs', role: 'original' },
      { label: 'PubMed — Arabic PCL-5 validation in a large treatment-seeking SWANA sample (2026)', url: 'https://pubmed.ncbi.nlm.nih.gov/42314405/', role: 'translation' },
      { label: 'PubMed — literary Arabic PCL-5 validation in Tunisian soldiers', url: 'https://pubmed.ncbi.nlm.nih.gov/36451716/', role: 'translation' },
    ],
    related: ['life-events-checklist-dsm5-standard', 'combat-exposure-scale', 'patient-health-questionnaire-9', 'generalized-anxiety-disorder-7'],
  },
  {
    slug: 'hamilton-anxiety-rating-scale',
    nameAr: 'مقياس هاملتون لتقدير القلق',
    nameEn: 'Hamilton Anxiety Rating Scale',
    acronym: 'HAM-A',
    version: '14-item clinician-rated HAM-A',
    summary: 'مقياس سريري من 14 بندًا لتقدير شدة أعراض القلق النفسية والجسدية، واسع الاستخدام في الدراسات العلاجية لكنه يحتاج تدريبًا وتفسيرًا حذرًا.',
    purpose: 'تقدير شدة القلق ومتابعة التغير بمرور الوقت ضمن تقييم سريري أو بحثي، خصوصًا في دراسات العلاج.',
    construct: 'شدة أعراض القلق النفسية والجسدية',
    populations: ['البالغون المصابون باضطرابات أو أعراض قلق', 'بعض المجتمعات البحثية الأخرى مع تحقق منفصل'],
    settings: ['الطب النفسي', 'العيادات النفسية', 'التجارب السريرية', 'بحوث العلاج'],
    categories: ['mental-health', 'symptom-burden'],
    administrationMode: 'تقدير بواسطة فاحص سريري مدرب بعد مقابلة وتقييم للأعراض النفسية والجسدية.',
    administrationTime: 'نحو 15–30 دقيقة بحسب تنظيم المقابلة وخبرة المقيّم.',
    equipment: ['نموذج HAM-A المحدد', 'تعريفات ومراسي تسجيل واضحة', 'تدريب يحد من اختلاف المقيمين'],
    scoring: 'تتكون النسخة الشائعة من 14 بندًا بتقدير شدة رتبي لكل بند ثم تجمع الدرجات. لا ينبغي استخدام عتبات محلية أو تقسيمات شدة غير موثقة كتشخيص مستقل.',
    interpretation: 'الدرجة الأعلى تعكس قلقًا أشد، لكن دراسات القياس تشير إلى تداخل واضح بين القلق الجسدي والآثار الجانبية أو أعراض الاكتئاب. جودة التقدير تتأثر باتساق المقيمين وطريقة المقابلة.',
    limitations: ['لا يميز بصورة مثالية بين التأثيرات المضادة للقلق والمضادة للاكتئاب.', 'البنود الجسدية قد تتأثر بمرض طبي أو آثار دوائية.', 'الاتفاق بين المقيمين يحتاج تدريبًا ومراسي واضحة.', 'المجموع وحده لا يحدد اضطراب القلق النوعي.'],
    administrationSteps: ['حدد النسخة وتعريفات البنود قبل التطبيق.', 'أجر مقابلة تغطي الفترة المرجعية والمجالات النفسية والجسدية.', 'استخدم المراسي نفسها عبر الزيارات والمقيمين.', 'راجع التناقضات المحتملة بين البنود قبل تثبيت الدرجة.', 'فسر التغير مع السياق التشخيصي والدوائي والوظيفي.'],
    safetyNotes: ['أعراض مثل ألم الصدر أو ضيق النفس أو الإغماء تحتاج تقييمًا طبيًا عند وجود مؤشرات خطر ولا تنسب تلقائيًا للقلق.', 'وجود خطر انتحار أو هياج شديد يحتاج مسار سلامة منفصلًا.', 'المقياس لا يثبت تشخيص اضطراب القلق بمفرده.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Hamilton Anxiety Rating Scale بحالة Public Domain. الأدلة أو المقابلات المنظمة المشتقة لاحقًا مثل SIGH-A قد يكون لها وضع حقوق مختلف، لذلك لا نخلطها مع HAM-A الأصلية.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'توجد استخدامات عربية، لكن النسخة المرجعية تحتاج تثبيتًا مستقلًا',
    arabicNote: 'وجدنا دراسات عربية تستخدم HAM-A كمقياس مقارن، لكن ذلك لا يكفي لتحديد ترجمة عربية مرجعية للـ14 بندًا أو حقوقها. لذلك نبقي النص العربي الكامل محجوبًا إلى أن نوثق نسخة محددة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تعرض روافد البنية والحدود والمراجع، ولا تنشر نص HAM-A العربي كاملًا قبل تثبيت نسخة لغوية موثقة.',
    sources: [
      { label: 'CDISC QRS — Hamilton Anxiety Rating Scale Public Domain', url: 'https://www.cdisc.org/standards/foundational/qrs/hamilton-anxiety-rating-scale', role: 'rights' },
      { label: 'PubMed — reliability, validity and sensitivity to change of HAM-A', url: 'https://pubmed.ncbi.nlm.nih.gov/2963053/', role: 'evidence' },
      { label: 'PubMed — consistency checks across 40,349 HAM-A administrations', url: 'https://pubmed.ncbi.nlm.nih.gov/36638966/', role: 'evidence' },
      { label: 'PubMed — structured interview guide reliability study', url: 'https://pubmed.ncbi.nlm.nih.gov/11413563/', role: 'evidence' },
    ],
    related: ['generalized-anxiety-disorder-7', 'hamilton-depression-rating-scale-24', 'general-clinical-global-impression'],
  },
];
