export type MeasureRightsStatus = 'public-domain' | 'open-reuse';
export type ArabicMeasureStatus = 'validated-version-reported' | 'translation-reported' | 'protocol-localizable' | 'version-review-required';

export type AssessmentMeasureSource = {
  label: string;
  url: string;
  role: 'evidence' | 'rights' | 'original' | 'translation';
};

export type AssessmentMeasure = {
  slug: string;
  nameAr: string;
  nameEn: string;
  acronym: string;
  version: string;
  summary: string;
  purpose: string;
  construct: string;
  populations: string[];
  settings: string[];
  categories: string[];
  administrationMode: string;
  administrationTime: string;
  equipment: string[];
  scoring: string;
  interpretation: string;
  limitations: string[];
  administrationSteps: string[];
  safetyNotes: string[];
  rightsStatus: MeasureRightsStatus;
  rightsLabel: string;
  rightsNote: string;
  rightsVerifiedOn: string;
  arabicStatus: ArabicMeasureStatus;
  arabicLabel: string;
  arabicNote: string;
  fullArabicFormPublished: boolean;
  fullArabicFormNote: string;
  sources: AssessmentMeasureSource[];
  related: string[];
};

export const assessmentMeasureCategories = [
  { slug: 'mobility-walking', name: 'الحركة والمشي', description: 'اختبارات سرعة المشي، التحمل الحركي والتنقل الوظيفي.' },
  { slug: 'balance-falls', name: 'التوازن وخطر السقوط', description: 'أدوات الأداء الوظيفي المرتبطة بالتوازن والتنقل وخطر السقوط ضمن سياق سريري.' },
  { slug: 'neurological-outcomes', name: 'النتائج العصبية والسكتة الدماغية', description: 'مقاييس الإعاقة والنتائج العامة بعد السكتة والأمراض العصبية.' },
  { slug: 'brain-injury', name: 'إصابات الدماغ والارتجاج', description: 'أدوات النتائج والعجز والأعراض بعد إصابات الدماغ والارتجاج.' },
  { slug: 'mental-health', name: 'الصحة النفسية', description: 'مقاييس فحص الأعراض النفسية والمتابعة؛ لا تعمل كتشخيص مستقل.' },
  { slug: 'pain-function', name: 'الألم والوظيفة الجسدية', description: 'مقاييس الأثر الوظيفي المرتبط بالألم والحالات العضلية الهيكلية.' },
  { slug: 'participation', name: 'المشاركة والاستقلال الوظيفي', description: 'أدوات المشاركة المجتمعية والاستقلال والنتائج الوظيفية طويلة المدى.' },
  { slug: 'older-adults', name: 'كبار السن', description: 'أدوات شائعة في تقييم الحركة والتوازن والأعراض لدى كبار السن.' },
  { slug: 'rehabilitation-outcomes', name: 'نتائج التأهيل', description: 'مقاييس تُستخدم لتتبع النتائج والوظيفة عبر برامج التأهيل.' },
] as const;

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';
const RMD_BASE = 'https://www.sralab.org/rehabilitation-measures';

export const assessmentMeasures: AssessmentMeasure[] = [
  {
    slug: 'roland-morris-disability-questionnaire-24',
    nameAr: 'استبيان رولاند–موريس للعجز (24 بندًا)',
    nameEn: 'Roland-Morris Disability Questionnaire — 24 items',
    acronym: 'RMDQ-24',
    version: '24-item original',
    summary: 'استبيان تقرير ذاتي يقيس أثر ألم أسفل الظهر في الأداء والأنشطة اليومية.',
    purpose: 'تقدير العجز الوظيفي المرتبط بألم أسفل الظهر ومتابعة التغير مع الزمن أو العلاج.',
    construct: 'العجز الوظيفي المرتبط بألم أسفل الظهر',
    populations: ['البالغون المصابون بألم أسفل الظهر', 'برامج العلاج الطبيعي والتأهيل العضلي الهيكلي'],
    settings: ['العيادات الخارجية', 'العلاج الطبيعي', 'البحوث السريرية', 'متابعة النتائج'],
    categories: ['pain-function', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير ذاتي؛ 24 عبارة مرتبطة بالوظيفة في اليوم الحالي.',
    administrationTime: 'نحو 5 دقائق عادةً، بحسب القدرة القرائية والسياق.',
    equipment: ['النموذج المعتمد للنسخة المستخدمة', 'وسيلة تسجيل الدرجة'],
    scoring: 'النسخة الأصلية من 24 بندًا تُنتج درجة من 0 إلى 24؛ الدرجة الأعلى تعكس عجزًا وظيفيًا أكبر. يجب استخدام قواعد النسخة المطابقة وعدم خلط الإصدارات.',
    interpretation: 'تُفسَّر الدرجة مع خط الأساس، شدة الحالة والسياق السريري. التغير المهم سريريًا يعتمد على المجتمع والسياق ولا ينبغي تثبيت عتبة واحدة لكل الاستخدامات.',
    limitations: ['لا يحدد سبب ألم الظهر أو التشخيص الطبي.', 'قد تظهر تأثيرات أرضية/سقفية في بعض درجات الشدة.', 'المقارنة عبر اللغات تتطلب نسخة لغوية موثقة ومتطابقة.'],
    administrationSteps: ['تأكيد أن النسخة واللغة مناسبتان للمستخدم.', 'تطبيق النموذج وفق تعليمات النسخة دون تعديل البنود أثناء القياس.', 'حساب الدرجة طبقًا لقواعد RMDQ-24.', 'تسجيل النسخة واللغة والتاريخ عند المقارنة الطولية.'],
    safetyNotes: ['المقياس لا يستبدل فحص العلامات الحمراء أو التقييم الطبي عند وجود أعراض عصبية حادة أو تدهور سريع.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — إعادة الاستخدام موثقة',
    rightsNote: 'RMD وMapi/ePROVIDE يقدمان أساسًا واضحًا لإتاحة RMDQ-24، مع توثيق أن الأصل وترجماته متاحة ضمن المجال العام. تبقى مطابقة النص العربي المحدد ومصدره خطوة إلزامية قبل نشر نسخة عربية كاملة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد نسخ عربية منشورة/متحقق منها',
    arabicNote: 'توجد أعمال عربية منشورة؛ يجب ربط الصفحة بالنسخة المحددة ودراستها وعدم دمج صياغات من ترجمات مختلفة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'حق إعادة الاستخدام قوي، لكن النص العربي الكامل لا يُنشر حتى مطابقة نسخة عربية بعينها حرفيًا مع مصدرها ودراسة التحقق الخاصة بها.',
    sources: [
      { label: 'RMD — Roland Morris Disability Questionnaire', url: `${RMD_BASE}/roland-morris-disability-questionnaire`, role: 'evidence' },
      { label: 'Mapi Research Trust / ePROVIDE — RMDQ-24', url: 'https://eprovide.mapi-trust.org/instruments/roland-morris-disability-questionnaire-24-items', role: 'rights' },
    ],
    related: ['berg-balance-scale', 'timed-up-and-go', '10-meter-walk-test'],
  },
  {
    slug: 'berg-balance-scale',
    nameAr: 'مقياس بيرغ للتوازن',
    nameEn: 'Berg Balance Scale',
    acronym: 'BBS',
    version: '14-item performance measure',
    summary: 'مقياس أداء من 14 مهمة وظيفية لتقدير التوازن الثابت والديناميكي.',
    purpose: 'وصف أداء التوازن ومتابعة تغيره خلال التأهيل، خصوصًا في المجتمعات العصبية وكبار السن.',
    construct: 'التوازن الوظيفي',
    populations: ['كبار السن', 'السكتة الدماغية', 'اضطرابات عصبية وتأهيلية متعددة'],
    settings: ['العلاج الطبيعي', 'التأهيل العصبي', 'العيادات', 'البحوث'],
    categories: ['balance-falls', 'older-adults', 'neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'اختبار أداء مباشر بواسطة فاحص، 14 مهمة بدرجات متدرجة.',
    administrationTime: 'نحو 15–20 دقيقة عادةً.',
    equipment: ['كرسيان مناسبـان', 'مسطرة أو شريط قياس', 'ساعة/مؤقت', 'درجة أو منصة منخفضة عند الحاجة وفق البروتوكول'],
    scoring: 'كل مهمة تُسجل عادةً من 0 إلى 4، بمجموع أقصى 56؛ الدرجة الأعلى تعكس أداء توازن أفضل.',
    interpretation: 'لا ينبغي استخدام حد واحد عالمي للتنبؤ بالسقوط. دقة التفسير والـMDC/MCID تختلف باختلاف المجتمع والسياق.',
    limitations: ['قد يظهر تأثير سقفي لدى ذوي الأداء المرتفع.', 'يتطلب تطبيقًا موحدًا وتقديرًا مباشرًا.', 'خطر السقوط متعدد العوامل ولا يُختزل في BBS وحده.'],
    administrationSteps: ['فحص سلامة البيئة وقدرة الشخص على محاولة المهام.', 'اتباع ترتيب وتعليمات النسخة المعتمدة.', 'توفير الحراسة القريبة عند وجود خطر سقوط.', 'تسجيل درجات البنود والمجموع مع أي مساعدة مطلوبة.'],
    safetyNotes: ['اختبار أداء؛ يجب منع السقوط وعدم دفع الشخص إلى مهمة غير آمنة.', 'توقف عند دوار شديد، ألم حاد، ضيق نفس أو علامة طبية مقلقة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — الأصل قابل لإعادة الاستخدام',
    rightsNote: 'سجل RMD يصف الأداة بأنها متاحة دون تكلفة ويورد وضع الإتاحة؛ إعادة نشر ترجمة عربية بعينها تبقى منفصلة عن حق الأصل.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد دراسات تحقق عربية',
    arabicNote: 'توجد دراسات عربية في مجتمعات عربية؛ لا تُعرض صياغة ترجمة محددة قبل التحقق من صاحبها وشروطها.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الصفحة تعرض بروتوكول الاستخدام والمعلومات العلمية؛ نشر نص ترجمة عربية كاملة ينتظر توثيق حقوق النسخة المحددة.',
    sources: [
      { label: 'RMD — Berg Balance Scale', url: `${RMD_BASE}/berg-balance-scale`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['timed-up-and-go', '10-meter-walk-test', '6-minute-walk-test'],
  },
  {
    slug: 'timed-up-and-go',
    nameAr: 'اختبار النهوض والمشي الموقّت',
    nameEn: 'Timed Up and Go',
    acronym: 'TUG',
    version: 'standard timed protocol',
    summary: 'اختبار قصير للتنقل الوظيفي يجمع النهوض من الكرسي والمشي والدوران والجلوس.',
    purpose: 'قياس زمن تنفيذ سلسلة حركية وظيفية سريعة ومتابعة التنقل مع الزمن.',
    construct: 'التنقل الوظيفي والتوازن الديناميكي',
    populations: ['كبار السن', 'السكتة الدماغية', 'باركنسون', 'مجتمعات تأهيلية متعددة'],
    settings: ['العيادات', 'التأهيل', 'الرعاية المجتمعية', 'البحوث'],
    categories: ['mobility-walking', 'balance-falls', 'older-adults', 'rehabilitation-outcomes'],
    administrationMode: 'اختبار أداء موقّت؛ نهوض من كرسي، مشي لمسافة 3 أمتار، دوران، عودة وجلوس.',
    administrationTime: 'أقل من 5 دقائق في الغالب، مع وقت إعداد قصير.',
    equipment: ['كرسي ثابت مناسب', 'مسار 3 أمتار محدد', 'مؤقت', 'وسيلة مساعدة معتادة إن كان البروتوكول يسمح ويُوثق استخدامها'],
    scoring: 'النتيجة الأساسية هي الزمن بالثواني. يجب توثيق شروط الاختبار والوسيلة المساعدة وسرعة الأداء المطلوبة.',
    interpretation: 'الأزمنة الأسرع تعكس أداءً أفضل عادةً، لكن الحدود المستخدمة لخطر السقوط أو الإعاقة تختلف باختلاف المجتمع ولا يجوز تعميم رقم واحد.',
    limitations: ['الزمن وحده لا يصف جودة المشي أو سبب البطء.', 'يتأثر بالكرسي والتعليمات والمساعدة والمسار.', 'لا يكفي منفردًا لتقدير خطر السقوط.'],
    administrationSteps: ['تحديد مسار 3 أمتار وكرسي ثابت.', 'توحيد تعليمات السرعة والوسيلة المساعدة.', 'بدء التوقيت وفق نقطة البدء المحددة في البروتوكول.', 'إيقاف التوقيت عند إكمال الجلوس وتسجيل الزمن والشروط.'],
    safetyNotes: ['استخدم حراسة قريبة عند خطر السقوط.', 'لا يُجرى الاختبار إذا كانت محاولة المشي نفسها غير آمنة طبيًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — بروتوكول قابل للاستخدام',
    rightsNote: 'سجل CDISC QRS يدرج الأداة ضمن المواد ذات حالة إذن موثقة. لا تعني الإتاحة حرية إعادة نشر مواد تدريبية تابعة لجهة أخرى.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'بروتوكول إجرائي قابل للتقديم بالعربية',
    arabicNote: 'المحتوى إجرائي قصير؛ ينبغي توحيد الصياغة العربية وعدم تغيير خطوات القياس.',
    fullArabicFormPublished: true,
    fullArabicFormNote: 'تتضمن صفحة روافد دليل التطبيق العربي للبروتوكول مع الحفاظ على حدود التفسير.',
    sources: [
      { label: 'RMD — Timed Up and Go', url: `${RMD_BASE}/timed-and-go`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['berg-balance-scale', '10-meter-walk-test', '6-minute-walk-test'],
  },
  {
    slug: '10-meter-walk-test',
    nameAr: 'اختبار المشي لمسافة 10 أمتار',
    nameEn: '10 Meter Walk Test',
    acronym: '10MWT',
    version: 'timed gait-speed protocol',
    summary: 'اختبار أداء قصير لقياس سرعة المشي على مسافة معيارية.',
    purpose: 'تقدير سرعة المشي ومتابعة التغير في الحركة خلال التأهيل.',
    construct: 'سرعة المشي',
    populations: ['السكتة الدماغية', 'إصابة الحبل الشوكي', 'باركنسون', 'التأهيل العصبي والحركي'],
    settings: ['العلاج الطبيعي', 'التأهيل العصبي', 'العيادات', 'البحوث'],
    categories: ['mobility-walking', 'neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'اختبار أداء موقّت؛ تُحسب سرعة المشي بالمتر/ثانية وفق بروتوكول محدد.',
    administrationTime: 'نحو 5 دقائق مع الإعداد والتكرارات.',
    equipment: ['مسار مستقيم محدد', 'شريط قياس', 'مؤقت', 'وسيلة مساعدة معتادة عند السماح بها وتوثيقها'],
    scoring: 'النتيجة الأساسية سرعة المشي بالمتر/ثانية. يجب تحديد ما إذا كان التوقيت لمسافة 10 أمتار كاملة أو لمسافة وسطية مع تسارع/تباطؤ.',
    interpretation: 'تُفسر السرعة بالنسبة لخط الأساس والمجتمع والهدف. لا يجوز خلط نتائج بروتوكولات مختلفة في المقارنة.',
    limitations: ['توجد اختلافات بروتوكولية مهمة بين الدراسات.', 'لا يقيس التحمل أو جودة النمط الحركي كاملًا.', 'المساعدة والوسيلة المساعدة تؤثران في النتيجة.'],
    administrationSteps: ['تحديد طول المسار ومناطق التسارع/التباطؤ إن استُخدمت.', 'اختيار سرعة المشي المطلوبة وتوحيدها.', 'تسجيل الوقت لمسافة القياس المحددة.', 'حساب السرعة وتوثيق البروتوكول والوسيلة المساعدة.'],
    safetyNotes: ['الحراسة عند الحاجة ومنع الاختبار إذا كانت المشية غير آمنة.', 'إيقاف الاختبار عند أعراض قلبية/تنفسية أو عصبية حادة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — بروتوكول قابل للاستخدام',
    rightsNote: 'إتاحة الاستخدام موثقة في قواعد المقاييس؛ يجب الحفاظ على وصف البروتوكول المستخدم لأن الاسم يغطي تطبيقات إجرائية متقاربة وليست متطابقة دائمًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'بروتوكول إجرائي قابل للتقديم بالعربية',
    arabicNote: 'لا توجد بنود تقرير ذاتي؛ التركيز على ترجمة التعليمات التشغيلية بدقة وتوثيق نسخة البروتوكول.',
    fullArabicFormPublished: true,
    fullArabicFormNote: 'تعرض الصفحة بروتوكولًا عربيًا واضحًا مع التنبيه إلى اختلافات المسافة الموقّتة بين البروتوكولات.',
    sources: [
      { label: 'RMD — 10 Meter Walk Test', url: `${RMD_BASE}/10-meter-walk-test`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['6-minute-walk-test', 'timed-up-and-go', 'berg-balance-scale'],
  },
  {
    slug: '6-minute-walk-test',
    nameAr: 'اختبار المشي لمدة 6 دقائق',
    nameEn: '6 Minute Walk Test',
    acronym: '6MWT',
    version: 'standard endurance walk protocol',
    summary: 'اختبار أداء تحت أقصى لقياس المسافة التي يستطيع الشخص مشيها خلال ست دقائق وفق بروتوكول موحد.',
    purpose: 'تقدير القدرة الوظيفية على المشي والتحمل ومتابعة الاستجابة للتأهيل أو العلاج.',
    construct: 'القدرة الوظيفية على المشي والتحمل',
    populations: ['أمراض قلبية ورئوية', 'أمراض عصبية', 'مجتمعات تأهيلية متعددة'],
    settings: ['التأهيل القلبي والرئوي', 'العلاج الطبيعي', 'البحوث', 'العيادات'],
    categories: ['mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'اختبار مشي موقّت لمدة ست دقائق في مسار معياري مع تعليمات وتشجيع موحدين.',
    administrationTime: '6 دقائق للاختبار نفسه مع وقت إضافي للفحص والإعداد والتعافي.',
    equipment: ['ممر/مسار معياري', 'مؤقت', 'علامات للمسافة', 'معدات مراقبة وسلامة بحسب الحالة والبروتوكول'],
    scoring: 'النتيجة الأساسية إجمالي المسافة بالمتر خلال ست دقائق؛ يجب تسجيل التوقفات والأعراض والمساعدة وفق البروتوكول.',
    interpretation: 'المسافة الأعلى تعكس قدرة وظيفية أكبر عادةً. القيم المرجعية والتغير المهم سريريًا تختلف بحسب المرض والعمر والبروتوكول.',
    limitations: ['يتأثر بطول الممر والتشجيع والتعلم.', 'لا يحدد سبب انخفاض التحمل.', 'المقارنة تتطلب بروتوكولًا متسقًا.'],
    administrationSteps: ['فحص موانع الاختبار والاحتياطات حسب الحالة.', 'إعداد المسار والمعدات وتوثيق الأدوية/الأكسجين إن كانت مؤثرة.', 'تقديم التعليمات والتشجيع المعياريين.', 'تسجيل المسافة والتوقفات والأعراض والمتغيرات المساندة المطلوبة.'],
    safetyNotes: ['يتطلب تقييم السلامة مسبقًا خاصة لدى المرضى القلبيين/الرئويين.', 'يوقف عند ألم صدري، ضيق نفس غير محتمل، دوار/إغماء، شحوب شديد أو علامات خطورة أخرى وفق البروتوكول السريري.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — بروتوكول متاح للاستخدام',
    rightsNote: 'إتاحة المقياس موثقة، لكن إرشادات جمعيات مهنية أو مواد تدريبية منشورة حوله قد تحمل حقوقًا مستقلة ولا تُنسخ تلقائيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'بروتوكول إجرائي قابل للتقديم بالعربية',
    arabicNote: 'يمكن تقديم دليل عربي للإجراء مع إحالة واضحة إلى المعايير المهنية الحالية وعدم نسخ مواد محمية.',
    fullArabicFormPublished: true,
    fullArabicFormNote: 'تعرض الصفحة خطوات التطبيق العربية والحدود السريرية دون نسخ إرشادات مهنية محمية حرفيًا.',
    sources: [
      { label: 'RMD — 6 Minute Walk Test', url: `${RMD_BASE}/6-minute-walk-test`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['10-meter-walk-test', 'timed-up-and-go'],
  },
  {
    slug: 'rivermead-post-concussion-questionnaire',
    nameAr: 'استبيان ريفرميد لأعراض ما بعد الارتجاج',
    nameEn: 'Rivermead Post-Concussion Symptoms Questionnaire',
    acronym: 'RPQ',
    version: '16 symptom items',
    summary: 'مقياس تقرير ذاتي لأعراض شائعة بعد إصابة الرأس/الارتجاج مقارنة بالحالة قبل الإصابة.',
    purpose: 'تنظيم متابعة شدة أعراض ما بعد الارتجاج عبر مجموعة أعراض جسدية ومعرفية وانفعالية.',
    construct: 'عبء أعراض ما بعد الارتجاج',
    populations: ['إصابات الدماغ الرضحية الخفيفة', 'متابعة ما بعد الارتجاج'],
    settings: ['إعادة التأهيل العصبي', 'عيادات إصابات الدماغ', 'البحوث'],
    categories: ['brain-injury', 'neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير ذاتي قصير يقارن الأعراض بوضع ما قبل الإصابة.',
    administrationTime: 'نحو 5 دقائق عادةً.',
    equipment: ['النموذج المعتمد للنسخة المستخدمة'],
    scoring: 'توجد قواعد نشر مختلفة في الأدبيات للتعامل مع الاستجابات والمجاميع؛ يجب استخدام قاعدة النسخة/الدراسة المحددة بدل اختراع مجموع محلي.',
    interpretation: 'يصف عبء الأعراض ولا يثبت وحده تشخيص الارتجاج أو سببية كل عرض. يجب ربط النتائج بالتاريخ والفحص والسياق.',
    limitations: ['الأعراض غير نوعية وقد تظهر لأسباب متعددة.', 'الاستجابة قد تتأثر بالتذكر والحالة النفسية.', 'طرق التجميع تختلف بين بعض الاستخدامات البحثية.'],
    administrationSteps: ['تحديد الفترة المرجعية وطريقة المقارنة قبل الإصابة.', 'استخدام النسخة القياسية دون إعادة صياغة البنود أثناء القياس.', 'اتباع قاعدة التسجيل المعلنة للنسخة المستخدمة.', 'مراجعة الأعراض ذات الخطورة سريريًا خارج مجموع الدرجة.'],
    safetyNotes: ['أعراض عصبية متدهورة، صداع شديد متفاقم، قيء متكرر، اختلاجات، ضعف/خدر جديد أو تغير وعي تستدعي تقييمًا عاجلًا ولا تنتظر نتيجة الاستبيان.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — الأصل موثق الإتاحة',
    rightsNote: 'حالة الإذن للأصل موثقة في سجلات المقاييس. أي ترجمة عربية بعينها تحتاج مراجعة حقوق النسخة اللغوية قبل عرض نصها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'يلزم توثيق النسخة العربية المحددة',
    arabicNote: 'لا ندمج ترجمة غير موثقة أو نولد ترجمة جديدة ثم نسميها نسخة محققة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'صفحة الاستخدام والمصادر منشورة؛ نص البنود العربي الكامل ينتظر إثبات نسخة عربية وحقوقها.',
    sources: [
      { label: 'RMD — Rivermead Post-Concussion Symptoms Questionnaire', url: `${RMD_BASE}/rivermead-post-concussion-symptom-questionnaire`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['disability-rating-scale', 'glasgow-outcome-scale-extended'],
  },
  {
    slug: 'disability-rating-scale',
    nameAr: 'مقياس تصنيف العجز بعد إصابة الدماغ',
    nameEn: 'Disability Rating Scale',
    acronym: 'DRS',
    version: 'TBI outcome measure',
    summary: 'مقياس سريري لتتبع التعافي والعجز بعد إصابات الدماغ الرضحية عبر مراحل متعددة.',
    purpose: 'توصيف مستوى العجز العام ومتابعة التغير من الغيبوبة إلى الاندماج المجتمعي.',
    construct: 'العجز العام ونتيجة التعافي بعد إصابة الدماغ',
    populations: ['إصابة الدماغ الرضحية المتوسطة والشديدة', 'التأهيل العصبي'],
    settings: ['التأهيل الداخلي', 'العيادات العصبية', 'متابعة النتائج', 'البحوث'],
    categories: ['brain-injury', 'neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'تقدير سريري منظم يعتمد على الملاحظة والمعلومات المتاحة.',
    administrationTime: 'قصير نسبيًا عند توفر المعلومات السريرية.',
    equipment: ['النموذج القياسي', 'معلومات سريرية/وظيفية كافية'],
    scoring: 'يتكون من مجالات متعددة ويُجمع إلى درجة إجمالية؛ الدرجات الأعلى تعكس عجزًا أشد. يجب اتباع تعريفات البنود الأصلية.',
    interpretation: 'مفيد للتتبع العام لكنه لا يصف كل التفاصيل المعرفية أو النفسية أو نوعية الحياة.',
    limitations: ['مقياس عالمي وقد لا يلتقط التغيرات الدقيقة في الأداء المرتفع.', 'يتطلب معرفة سياق المريض.', 'لا يستبدل التقييمات المتخصصة للمجالات المحددة.'],
    administrationSteps: ['جمع معلومات كافية عن الوعي، القدرة المعرفية والاعتماد الوظيفي.', 'تطبيق تعريفات البنود القياسية.', 'حساب الدرجة وتوثيق مصدر المعلومات.', 'استخدام مقاييس مجال إضافية عند الحاجة.'],
    safetyNotes: ['أي تغير حاد في الوعي أو الوظيفة بعد إصابة دماغية هو مسألة طبية قبل أن يكون مسألة قياس نتائج.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — الأصل موثق الإتاحة',
    rightsNote: 'حالة الأصل موثقة عبر سجلات المقاييس؛ الترجمة العربية المنشورة يجب أن تُراجع ككيان حقوقي/لغوي مستقل.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد نسخة/دراسة عربية منشورة',
    arabicNote: 'وجود دراسة عربية لا يعني تلقائيًا حق إعادة نشر نصها؛ يلزم تثبيت المصدر والحقوق قبل إدخال البنود.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تُعرض البنود العربية الكاملة حتى التحقق من النسخة العربية المحددة.',
    sources: [
      { label: 'RMD — Disability Rating Scale', url: `${RMD_BASE}/disability-rating-scale-tbi`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['glasgow-outcome-scale-extended', 'rivermead-post-concussion-questionnaire'],
  },
  {
    slug: 'glasgow-outcome-scale-extended',
    nameAr: 'مقياس غلاسكو الموسّع للنتائج',
    nameEn: 'Glasgow Outcome Scale — Extended',
    acronym: 'GOS-E',
    version: '8-category global outcome scale',
    summary: 'مقياس عالمي للنتيجة بعد إصابة الدماغ يصنف التعافي/العجز في ثماني فئات مرتبة.',
    purpose: 'تلخيص النتيجة الوظيفية العامة بعد إصابة الدماغ للاستخدام السريري والبحثي.',
    construct: 'النتيجة الوظيفية العامة بعد إصابة الدماغ',
    populations: ['إصابات الدماغ الرضحية'],
    settings: ['التأهيل العصبي', 'المتابعة', 'التجارب والبحوث'],
    categories: ['brain-injury', 'neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'مقابلة/تصنيف منظم؛ النسخة المنظمة تقلل اختلاف المقيمين.',
    administrationTime: 'قصير إلى متوسط بحسب المقابلة والمعلومات المتاحة.',
    equipment: ['هيكل المقابلة/التصنيف المعتمد'],
    scoring: 'ثماني فئات مرتبة من الوفاة إلى التعافي الجيد الأعلى؛ يجب الحفاظ على تعريفات الفئات الأصلية وعدم تحويلها إلى نسبة مئوية.',
    interpretation: 'مقياس رتبي عالمي؛ الانتقال بين الفئات مهم لكنه لا يساوي مسافات عددية متكافئة بين جميع الدرجات.',
    limitations: ['يلخص النتيجة العامة وقد يفقد تفاصيل المجالات.', 'يتأثر بموثوقية المقابلة والمعلومات.', 'الدرجات الرتبية لا تُعامل كقياس مستمر بلا مبرر.'],
    administrationSteps: ['جمع معلومات وظيفية من الشخص/الأسرة/السجل عند الحاجة.', 'استخدام المقابلة المنظمة أو تعريفات الفئات القياسية.', 'تحديد الفئة الأدق وتوثيق مصدر المعلومات.', 'عدم استنتاج تشخيص أو احتياج علاجي تفصيلي من الفئة وحدها.'],
    safetyNotes: ['القياس للنتائج ولا يحل محل التقييم العصبي أو الطبي عند التغير الحاد.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — حالة إذن الأصل موثقة',
    rightsNote: 'حالة الإذن للأصل مدرجة في سجلات المقاييس. ترجمة مقابلة منظمة قد تحمل حقوقًا مستقلة وتحتاج مراجعة قبل النسخ.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج تثبيتًا',
    arabicNote: 'نربط بأي نسخة عربية محققة بعد تحديد النص والدراسة والحقوق بدقة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يُنشر الشرح والهيكل؛ النص العربي الكامل للمقابلة ينتظر مراجعة النسخة المحددة.',
    sources: [
      { label: 'RMD — Glasgow Outcome Scale Extended', url: `${RMD_BASE}/glasgow-outcome-scale-extended`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['disability-rating-scale', 'rivermead-post-concussion-questionnaire'],
  },
  {
    slug: 'modified-rankin-scale',
    nameAr: 'مقياس رانكن المعدّل',
    nameEn: 'Modified Rankin Scale',
    acronym: 'mRS',
    version: '0–6 global disability scale',
    summary: 'مقياس رتبي عالمي للإعاقة/الاعتماد يُستخدم على نطاق واسع في السكتة الدماغية.',
    purpose: 'تصنيف مستوى الإعاقة والاعتماد الوظيفي العام، خصوصًا بعد السكتة الدماغية.',
    construct: 'الإعاقة والاعتماد الوظيفي العام',
    populations: ['السكتة الدماغية', 'مجتمعات عصبية أخرى في بعض الدراسات'],
    settings: ['وحدات السكتة', 'التأهيل العصبي', 'التجارب السريرية', 'المتابعة'],
    categories: ['neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'تصنيف سريري/مقابلة؛ استخدام مقابلة منظمة يحسن الاتساق.',
    administrationTime: 'دقائق قليلة عادةً.',
    equipment: ['تعريفات الدرجات أو المقابلة المنظمة المعتمدة'],
    scoring: 'درجات رتبية من 0 إلى 6؛ 0 دون أعراض و6 وفاة. لا تُحوَّل الدرجات إلى نسب مئوية أو متوسطات فردية ذات معنى سريري مباشر.',
    interpretation: 'مفيد للنتيجة العالمية، لكن يجب الانتباه إلى اختلاف المقيمين والتفاصيل التي لا يلتقطها المقياس.',
    limitations: ['فئات واسعة نسبيًا.', 'قد يختلف التصنيف بين المقيمين دون تدريب/مقابلة منظمة.', 'لا يحدد نوع الإعاقة أو سببها.'],
    administrationSteps: ['جمع وصف الوظائف والأنشطة قبل تحديد الدرجة.', 'استخدام تعريفات المقياس القياسية.', 'اختيار الدرجة الأقرب للحالة الفعلية.', 'تسجيل توقيت القياس بالنسبة للحدث السريري.'],
    safetyNotes: ['المقياس للنتائج وليس لتقرير أهلية علاج حاد أو استبعاد تقييم طبي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — المقياس الأساسي موثق الإتاحة',
    rightsNote: 'حالة إذن المقياس الأساسي موثقة في CDISC QRS؛ بعض المقابلات المنظمة/المواد التدريبية قد تكون لها شروط مختلفة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'translation-reported',
    arabicLabel: 'توجد استخدامات وترجمات عربية منشورة',
    arabicNote: 'يجب تحديد النسخة العربية ودليلها قبل نشر نص مقابلة عربية كاملة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تعريف الدرجات والشرح متاحان وفق حقوق الأصل؛ أي نص مقابلة مترجم يراجع منفصلًا.',
    sources: [
      { label: 'RMD — Modified Rankin Scale', url: `${RMD_BASE}/modified-rankin-handicap-scale`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['berg-balance-scale', '10-meter-walk-test', '6-minute-walk-test'],
  },
  {
    slug: 'geriatric-depression-scale',
    nameAr: 'مقياس اكتئاب كبار السن',
    nameEn: 'Geriatric Depression Scale',
    acronym: 'GDS',
    version: 'original/short-form family — version must be stated',
    summary: 'عائلة مقاييس فحص أعراض الاكتئاب المصممة لكبار السن، وتتضمن النسخة الأصلية ونسخًا قصيرة.',
    purpose: 'فحص أعراض قد تستدعي تقييمًا مهنيًا للاكتئاب لدى كبار السن؛ ليس أداة تشخيص منفردة.',
    construct: 'أعراض الاكتئاب لدى كبار السن',
    populations: ['كبار السن؛ مع مراعاة القدرة المعرفية واللغوية'],
    settings: ['الرعاية الأولية', 'طب الشيخوخة', 'الصحة النفسية', 'البحوث'],
    categories: ['mental-health', 'older-adults'],
    administrationMode: 'تقرير ذاتي أو مقابلة بحسب النسخة والقدرة؛ يجب ذكر طول النسخة المستخدمة.',
    administrationTime: 'قصير إلى متوسط؛ يختلف بوضوح بين النسخة القصيرة والأصلية.',
    equipment: ['النموذج المطابق للنسخة المحددة'],
    scoring: 'تعتمد الدرجة وحدودها على نسخة GDS المستخدمة؛ لا يجوز خلط GDS-15 وGDS-30 أو نقل عتبات بينهما.',
    interpretation: 'نتيجة فحص وليست تشخيصًا. يلزم تقييم سريري عند النتيجة المقلقة أو وجود أعراض مؤثرة وظيفيًا.',
    limitations: ['قد تقل الملاءمة مع ضعف معرفي شديد.', 'الأعراض الطبية والأدوية والفقد قد تؤثر في العرض السريري.', 'تختلف قواعد التسجيل حسب النسخة.'],
    administrationSteps: ['اختيار نسخة محددة ومناسبة للسياق.', 'تطبيقها كما نُشرت دون مزج البنود.', 'حساب الدرجة وفق دليل النسخة.', 'ربط النتيجة بتقييم سريري ووظيفي عند الحاجة.'],
    safetyNotes: ['أي إفصاح عن أفكار انتحارية أو خطر ذاتي يحتاج استجابة مباشرة وفق مسار السلامة، بصرف النظر عن الدرجة الكلية.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — مقياس GDS متاح للاستخدام',
    rightsNote: 'المقياس الأصلي متاح للاستخدام العام بحسب مواد المؤلف/المصادر الأكاديمية. حقوق ترجمة عربية بعينها تُراجع منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد نسخ عربية محققة منشورة',
    arabicNote: 'يجب تحديد هل الصفحة تعرض GDS-15 أو GDS-30 وربط النسخة العربية بالدراسة الصحيحة قبل نشر البنود.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الشرح متاح؛ النص العربي الكامل ينتظر مطابقة نسخة محددة وحقوقها.',
    sources: [
      { label: 'RMD — Geriatric Depression Scale', url: `${RMD_BASE}/geriatric-depression-scale`, role: 'evidence' },
      { label: 'GDS author resource (Stanford)', url: 'https://web.stanford.edu/~yesavage/GDS.html', role: 'rights' },
    ],
    related: ['patient-health-questionnaire-9'],
  },
  {
    slug: 'patient-health-questionnaire-9',
    nameAr: 'استبيان صحة المريض — 9 بنود',
    nameEn: 'Patient Health Questionnaire-9',
    acronym: 'PHQ-9',
    version: '9-item depression screener',
    summary: 'أداة فحص ومتابعة من تسعة بنود لأعراض الاكتئاب خلال الأسبوعين السابقين.',
    purpose: 'فحص شدة أعراض الاكتئاب ومتابعتها ضمن تقييم سريري أوسع.',
    construct: 'أعراض الاكتئاب',
    populations: ['البالغون في الرعاية الأولية والصحة النفسية ومجتمعات سريرية متعددة'],
    settings: ['الرعاية الأولية', 'الصحة النفسية', 'البحوث', 'متابعة النتائج'],
    categories: ['mental-health', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير ذاتي أو مقابلة عند الحاجة؛ 9 بنود عن آخر أسبوعين.',
    administrationTime: 'دقائق قليلة عادةً.',
    equipment: ['نسخة PHQ-9 المعتمدة للغة المستخدمة'],
    scoring: 'كل بند يُسجل من 0 إلى 3، بمجموع 0–27. مستويات الشدة الشائعة تساعد في الفحص لكنها لا تستبدل الحكم السريري.',
    interpretation: 'النتيجة تشير إلى عبء الأعراض وتساعد في المتابعة. التشخيص يحتاج تقييم المعايير والسياق والاستبعاد التفريقي.',
    limitations: ['أداة فحص وليست تشخيصًا منفردًا.', 'الأمراض الجسدية قد تتداخل مع بعض الأعراض.', 'يجب التعامل مع بند أفكار إيذاء النفس بصورة مستقلة عن المجموع.'],
    administrationSteps: ['تأكيد الفترة المرجعية: الأسبوعان السابقان.', 'تطبيق البنود التسعة بالنسخة المعتمدة.', 'حساب المجموع ومراجعة أثر الأعراض وظيفيًا.', 'مراجعة بند إيذاء النفس فورًا وفق بروتوكول السلامة.'],
    safetyNotes: ['أي استجابة تشير إلى أفكار موت/إيذاء نفس تستلزم تقييم سلامة مباشرًا؛ لا تنتظر المجموع أو مستوى الشدة.', 'الخطر الوشيك يتطلب خدمات الطوارئ/الأزمة المحلية.'],
    rightsStatus: 'open-reuse',
    rightsLabel: 'إعادة الاستخدام المجاني موثقة من صاحب الحقوق',
    rightsNote: 'Pfizer أتاحت PHQ ومقاييسه للاستخدام العام دون رسوم/طلب إذن بحسب إعلانها وموقع PHQ Screeners. يجب استخدام ترجمة رسمية أو موثقة وعدم إنشاء نسخة عربية غير محققة ثم نسبها للأداة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'تتوفر نسخ عربية مستخدمة ومحققة',
    arabicNote: 'قبل تضمين النموذج كاملًا تُطابق النسخة العربية مع المصدر الرسمي/الدراسة والنسخة المسموح بها.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الإتاحة العامة للأداة موثقة، لكن روافد لا يعرض النص العربي الكامل حتى تثبيت النسخة العربية المصدرية حرفيًا.',
    sources: [
      { label: 'RMD — Patient Health Questionnaire-9', url: `${RMD_BASE}/patient-health-questionnaire-9`, role: 'evidence' },
      { label: 'PHQ Screeners — official distribution resource', url: 'https://www.phqscreeners.com/', role: 'rights' },
      { label: 'Pfizer public-access announcement', url: 'https://www.pfizer.com/news/press-release/press-release-detail/pfizer_to_offer_free_public_access_to_mental_health_assessment_tools_to_improve_diagnosis_and_patient_care', role: 'rights' },
    ],
    related: ['geriatric-depression-scale'],
  },
  {
    slug: 'chart-short-form',
    nameAr: 'استبيان كريغ للمشاركة والإعاقة — النسخة القصيرة',
    nameEn: 'Craig Handicap Assessment and Reporting Technique — Short Form',
    acronym: 'CHART-SF',
    version: 'short form',
    summary: 'مقياس نتائج يصف جوانب المشاركة والاستقلال والأدوار في المجتمع بعد الإعاقة.',
    purpose: 'تقدير المشاركة المجتمعية وبعض أبعاد الاستقلال والاندماج كجزء من تقييم نتائج التأهيل.',
    construct: 'المشاركة والاستقلال/الاندماج المجتمعي',
    populations: ['الأشخاص ذوو الإعاقات، خصوصًا في سياقات التأهيل طويل المدى'],
    settings: ['التأهيل', 'المتابعة المجتمعية', 'بحوث النتائج'],
    categories: ['participation', 'rehabilitation-outcomes'],
    administrationMode: 'استبيان/مقابلة منظمة وفق النسخة القصيرة.',
    administrationTime: 'قصير نسبيًا مقارنة بالنسخة الكاملة.',
    equipment: ['النموذج والدليل المطابقان للنسخة القصيرة'],
    scoring: 'يُسجل حسب مجالات المشاركة/الاستقلال وفق قواعد CHART-SF؛ لا تُنشأ درجة تشخيصية محلية أو نسبة واحدة غير موجودة في الدليل.',
    interpretation: 'يصف أبعاد المشاركة ولا يعني أن الدرجة المنخفضة سببها عامل واحد؛ البيئة والدعم والموارد عوامل مهمة.',
    limitations: ['النتيجة حساسة للسياق الاجتماعي والبيئي.', 'لا تستبدل تقييم الاحتياجات الفردية.', 'يجب الالتزام بإصدار الأداة وقواعد تسجيله.'],
    administrationSteps: ['تحديد النسخة القصيرة الصحيحة.', 'جمع الإجابات وفق تعليمات الأداة.', 'حساب درجات المجالات وفق الدليل.', 'استخدام النتائج لتوجيه الاستكشاف لا لإصدار حكم تشخيصي.'],
    safetyNotes: ['الأسئلة حول الاعتماد والمشاركة قد تكشف احتياجات دعم أو إهمال؛ يجب أن يكون مسار الإحالة واضحًا عند ظهور خطر أو حرمان أساسي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — النسخة القصيرة موثقة الإتاحة',
    rightsNote: 'حالة الإذن مدرجة في سجل CDISC QRS. أي ترجمة عربية أو تنسيق منشور من طرف ثالث يراجع منفصلًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج مراجعة',
    arabicNote: 'لم تُعتمد داخل روافد ترجمة عربية بعينها حتى الآن.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الصفحة المرجعية ودليل الاستخدام متاحان؛ نص عربي كامل ينتظر التحقق من النسخة.',
    sources: [
      { label: 'RMD — Craig Handicap Assessment and Reporting Technique', url: `${RMD_BASE}/craig-handicap-assessment-and-reporting-technique`, role: 'evidence' },
      { label: 'CDISC QRS permission registry', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['disability-rating-scale', 'glasgow-outcome-scale-extended'],
  },
];

export const assessmentMeasureSlugs = assessmentMeasures.map((measure) => measure.slug);

export function getAssessmentMeasure(slug: string) {
  return assessmentMeasures.find((measure) => measure.slug === slug) ?? null;
}

export function getAssessmentMeasureCategory(slug: string) {
  return assessmentMeasureCategories.find((category) => category.slug === slug) ?? null;
}

export function getMeasuresByCategory(slug: string) {
  return assessmentMeasures.filter((measure) => measure.categories.includes(slug));
}

export function rightsBadge(status: MeasureRightsStatus) {
  return status === 'public-domain' ? 'Public Domain' : 'إعادة استخدام مجانية موثقة';
}

export function arabicStatusBadge(status: ArabicMeasureStatus) {
  if (status === 'validated-version-reported') return 'نسخة عربية منشورة/محققة';
  if (status === 'translation-reported') return 'ترجمة عربية منشورة';
  if (status === 'protocol-localizable') return 'بروتوكول عربي';
  return 'مراجعة النسخة العربية مطلوبة';
}
