import type { AssessmentMeasure } from '@/lib/assessment-measures';

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';

export const assessmentMeasuresWave4: AssessmentMeasure[] = [
  {
    slug: 'abnormal-involuntary-movement-scale',
    nameAr: 'مقياس الحركات اللاإرادية غير الطبيعية',
    nameEn: 'Abnormal Involuntary Movement Scale',
    acronym: 'AIMS',
    version: 'AIMS clinician-rated scale',
    summary: 'مقياس سريري منظم لرصد شدة الحركات اللاإرادية، ويستخدم خصوصًا في متابعة خلل الحركة المتأخر المرتبط ببعض الأدوية المضادة للذهان.',
    purpose: 'توصيف الحركات غير الطبيعية ومتابعة تغيرها ضمن فحص سريري للحركة والآثار الدوائية.',
    construct: 'شدة وتوزع الحركات اللاإرادية غير الطبيعية',
    populations: ['الأشخاص المعرضون لخلل الحركة المتأخر', 'الأشخاص الذين يتلقون أدوية قد ترتبط باضطرابات الحركة'],
    settings: ['الطب النفسي', 'طب الأعصاب', 'عيادات الأدوية النفسية', 'التجارب السريرية'],
    categories: ['movement-disorders', 'mental-health', 'neurological-outcomes'],
    administrationMode: 'ملاحظة سريرية مباشرة مع مهام فحص بسيطة وتقدير منظم لشدة الحركة.',
    administrationTime: 'عادةً نحو 5–10 دقائق مع اختلاف المدة حسب الحالة وخبرة الفاحص.',
    equipment: ['كرسي مناسب', 'بيئة تسمح بملاحظة الوجه والأطراف والجذع', 'نموذج AIMS المعتمد'],
    scoring: 'تتضمن البنية درجات للحركات في مناطق مختلفة إضافة إلى تقديرات عامة ومعلومات سياقية. يستخدم مجموع بنود الحركة المحددة عند الحاجة البحثية، ولا ينبغي اختراع مجموع محلي يجمع كل البنود دون مرجع.',
    interpretation: 'ارتفاع الدرجة يعكس حركات أشد، لكنه لا يحدد السبب وحده ولا يثبت أن الحركة ناتجة عن دواء بعينه. تفسير التغير يتطلب خط أساس وفحصًا للحركة والسياق الدوائي.',
    limitations: ['الاتفاق بين المقيمين يتأثر بخبرة الفاحص.', 'لا يقيس الأثر الوظيفي أو جودة الحياة بصورة شاملة.', 'قد تتذبذب الحركات باختلاف الوقت والقلق والجرعة الدوائية.'],
    administrationSteps: ['مراجعة التاريخ الدوائي والحركي بإيجاز.', 'ملاحظة الشخص في الراحة وأثناء المهام القياسية المطلوبة.', 'تقدير الحركات بحسب التعريفات القياسية دون استنتاج السبب من الدرجة وحدها.', 'توثيق عوامل مثل توقيت الجرعة أو الأعراض الحادة.'],
    safetyNotes: ['الحركات الحادة المصحوبة بتيبس شديد أو حمى أو اضطراب وعي تحتاج تقييمًا طبيًا عاجلًا ولا تختزل في AIMS.', 'يتطلب التطبيق السريري قدرة على التفريق بين أنماط الحركة المختلفة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج AIMS بحالة Public Domain ويعرّفها بأن الأداة في المجال العام ولا يلزم إذن لاستخدامها. أي ترجمة عربية أو مادة تدريبية مستقلة تراجع حقوقها منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج توثيقًا مستقلًا',
    arabicNote: 'لا تنسب صياغة عربية بعينها إلى النسخة الأصلية قبل تحديد مصدر الترجمة ومنهجها وخصائصها القياسية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تنشر طريقة الاستخدام والحدود العلمية فقط حتى تثبيت نسخة عربية محددة وحقوقها.',
    sources: [
      { label: 'CDISC QRS — AIMS Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — AIMS assessment and inter-rater considerations', url: 'https://pubmed.ncbi.nlm.nih.gov/3998720/', role: 'evidence' },
      { label: 'PubMed — AIMS minimal clinically important difference', url: 'https://pubmed.ncbi.nlm.nih.gov/31234240/', role: 'evidence' },
    ],
    related: ['general-clinical-global-impression', 'brief-psychiatric-rating-scale-anchored'],
  },
  {
    slug: 'brief-psychiatric-rating-scale-anchored',
    nameAr: 'مقياس التقدير النفسي المختصر — النسخة ذات المراسي',
    nameEn: 'Brief Psychiatric Rating Scale — Anchored',
    acronym: 'BPRS-A',
    version: 'Anchored BPRS',
    summary: 'مقياس يقدره المختص لتوصيف شدة مجموعة من الأعراض النفسية، خصوصًا في الاضطرابات الذهانية والحالات النفسية الحادة.',
    purpose: 'قياس شدة الأعراض وتتبع التغير باستخدام أوصاف مرساة تقلل اختلاف التقدير بين الفاحصين.',
    construct: 'شدة الأعراض النفسية متعددة المجالات',
    populations: ['البالغون في خدمات الصحة النفسية', 'الأشخاص المصابون باضطرابات ذهانية أو حالات نفسية حادة'],
    settings: ['المستشفيات النفسية', 'العيادات المتخصصة', 'البحوث السريرية'],
    categories: ['mental-health'],
    administrationMode: 'مقابلة وملاحظة سريرية بواسطة فاحص مدرب مع تقديرات شدة ذات مراس محددة.',
    administrationTime: 'نحو 15–30 دقيقة بحسب النسخة وتعقيد الحالة.',
    equipment: ['نسخة BPRS-A المحددة', 'تعريفات المراسي وقواعد التقدير', 'بيئة مقابلة سريرية مناسبة'],
    scoring: 'توجد نسخ 18 و24 بندًا ومراسي مختلفة تاريخيًا؛ يجب تحديد الإصدار صراحة واستخدام نطاقات الاستجابة ومجموع الدرجة المطابقين لذلك الإصدار فقط.',
    interpretation: 'الدرجة الأعلى تعكس عبئًا عرضيًا أكبر ضمن النسخة المستخدمة. لا تتحول الدرجة إلى تشخيص، وتفسير المحاور الفرعية يجب أن يتبع النموذج المنشور للنسخة نفسها.',
    limitations: ['يتطلب تدريبًا لتحقيق اتفاق مقبول بين المقيمين.', 'تتعدد نسخ BPRS ويؤدي خلطها إلى نتائج غير قابلة للمقارنة.', 'بعض الأعراض تتطلب معلومات من الملاحظة السريرية وليس تقرير المريض وحده.'],
    administrationSteps: ['تحديد نسخة BPRS-A قبل التطبيق.', 'إجراء المقابلة والملاحظة وفق المراسي القياسية.', 'تسجيل كل بند باستخدام تعريف النسخة.', 'توثيق الإصدار والمقيّم والسياق عند المقارنة الزمنية.'],
    safetyNotes: ['وجود ذهان حاد أو هياج أو خطر على الذات أو الآخرين يتطلب مسار سلامة مستقلًا عن الدرجة.', 'المقياس مخصص للتقدير المهني وليس للاستخدام الذاتي التشخيصي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج BPRS-A بحالة Public Domain. يجب مع ذلك تثبيت النسخة ذات المراسي لأن نسخ BPRS ليست متطابقة بنيويًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج تثبيت الإصدار',
    arabicNote: 'أي نسخة عربية يجب أن تربط بعدد البنود والمراسي ومنهج الترجمة ودراسة الاتفاق بين المقيمين.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا يعرض نموذج عربي كامل قبل توثيق الإصدار والترجمة والتدريب المطلوب.',
    sources: [
      { label: 'CDISC QRS — BPRS-A Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — reliability and validity of anchored BPRS', url: 'https://pubmed.ncbi.nlm.nih.gov/11556275/', role: 'evidence' },
    ],
    related: ['general-clinical-global-impression', 'abnormal-involuntary-movement-scale', 'hamilton-depression-rating-scale-24'],
  },
  {
    slug: 'controlled-oral-word-association-test',
    nameAr: 'اختبار التداعي اللفظي المضبوط',
    nameEn: 'Controlled Oral Word Association Test',
    acronym: 'COWAT',
    version: 'Letter verbal fluency paradigm',
    summary: 'اختبار طلاقة لفظية زمنية يقيس إنتاج كلمات وفق حرف أو قاعدة محددة، ويستخدم ضمن التقييم العصبي النفسي للوظائف التنفيذية واللغة.',
    purpose: 'قياس الطلاقة اللفظية والوصول المعجمي والبحث الاستراتيجي ضمن بطارية عصبية نفسية أوسع.',
    construct: 'الطلاقة اللفظية المقيّدة بالحرف والبحث التنفيذي',
    populations: ['البالغون في التقييم العصبي النفسي', 'إصابات الدماغ', 'الشيخوخة واضطرابات عصبية متعددة'],
    settings: ['علم النفس العصبي', 'التأهيل العصبي', 'البحوث المعرفية'],
    categories: ['cognition-neuropsychology', 'brain-injury', 'neurological-outcomes'],
    administrationMode: 'اختبار أداء شفهي موقوت يطلب فيه إنتاج كلمات وفق حرف أو مجموعة حروف وقواعد استبعاد محددة.',
    administrationTime: 'عادةً دقائق قليلة؛ كثير من الصيغ تستخدم دقيقة لكل حرف.',
    equipment: ['مؤقت', 'نموذج تسجيل الكلمات والأخطاء', 'مجموعة الحروف والمعايير المطابقة للغة والسكان'],
    scoring: 'يحسب عدد الاستجابات المقبولة مع توثيق التكرارات والأخطاء وكسر القواعد. لا توجد درجة عربية عالمية لأن الأداء يتأثر باللغة والحروف والعمر والتعليم.',
    interpretation: 'يجب تفسير الأداء مقابل معايير سكانية ولغوية مناسبة. نقل حروف F-A-S أو معايير إنجليزية مباشرة إلى العربية غير صالح منهجيًا.',
    limitations: ['شديد الحساسية للغة والتعليم والثقافة.', 'الاختلاف في الحروف أو الزمن أو قواعد القبول يغير الاختبار.', 'لا يكفي وحده لتشخيص ضعف تنفيذي أو اضطراب عصبي.'],
    administrationSteps: ['اختيار نموذج لغوي ومعايير مناسبة للمجتمع.', 'شرح قواعد الكلمات المقبولة والمرفوضة دون تغييرها بين المشاركين.', 'توقيت كل جولة بدقة وتسجيل الاستجابات.', 'حساب المقبول والأخطاء ثم المقارنة بمعايير النسخة ذاتها.'],
    safetyNotes: ['لا ينبغي استخدام ترجمة حرفية لحروف النسخة الإنجليزية كنسخة عربية.', 'تفسير النتيجة يتطلب خبرة في القياس العصبي النفسي والسياق التعليمي واللغوي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج COWAT بحالة Public Domain. الحقوق لا تحل مشكلة التكافؤ اللغوي؛ اختيار الحروف والمعايير العربية يحتاج دراسة مستقلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لا يجوز تعريب الحروف مباشرة',
    arabicNote: 'النسخة العربية تحتاج بناء أو تحقق لغوي ومعايير سكانية لأن الطلاقة الحرفية تتغير باختلاف بنية اللغة وتواتر الحروف.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننشر بروتوكول حروف عربيًا قبل ربطه بدراسة معيارية عربية مناسبة.',
    sources: [
      { label: 'CDISC QRS — COWAT Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — COWAT reliability and updated norms', url: 'https://pubmed.ncbi.nlm.nih.gov/14588937/', role: 'evidence' },
      { label: 'PubMed — contemporary normative data', url: 'https://pubmed.ncbi.nlm.nih.gov/37849629/', role: 'evidence' },
    ],
    related: ['glasgow-coma-scale-ninds', 'mayo-portland-adaptability-inventory-4'],
  },
  {
    slug: 'combat-exposure-scale',
    nameAr: 'مقياس التعرض للقتال',
    nameEn: 'Combat Exposure Scale',
    acronym: 'CES',
    version: 'Original 7-item CES',
    summary: 'مقياس تقرير ذاتي مختصر يقدّر مقدار التعرض لخبرات قتالية شديدة، وقد طوّر تاريخيًا لدى محاربين قدامى.',
    purpose: 'وصف مستوى التعرض القتالي كعامل سياقي في تقييم الصدمة والبحوث، وليس قياس اضطراب ما بعد الصدمة نفسه.',
    construct: 'التعرض لأحداث قتالية ضاغطة',
    populations: ['العسكريون والمحاربون القدامى ذوو خبرة قتالية'],
    settings: ['الصحة النفسية العسكرية', 'بحوث الصدمة', 'خدمات المحاربين القدامى'],
    categories: ['trauma-stress', 'mental-health'],
    administrationMode: 'تقرير ذاتي قصير عن خبرات قتالية محددة.',
    administrationTime: 'عدة دقائق عادةً.',
    equipment: ['النموذج الأصلي أو النسخة اللغوية الموثقة', 'قواعد التسجيل المطابقة للإصدار'],
    scoring: 'للنسخة الأصلية نظام تسجيل موزون خاص بها. يجب اتباع المفتاح الأصلي وعدم تحويل التعرض إلى تشخيص أو استنتاج سببي عن الأعراض الحالية.',
    interpretation: 'الدرجة الأعلى تعكس تعرضًا قتاليًا أكبر ضمن المجتمع الذي صمم له المقياس. لا تقيس وجود PTSD ولا شدته ولا تعني أن جميع أنواع الصدمة ممثلة.',
    limitations: ['طوّر في سياق تاريخي وعسكري محدد.', 'لا يغطي جميع خبرات الحرب الحديثة أو الصدمات غير القتالية.', 'قد يتأثر التقرير بالذاكرة والمسافة الزمنية عن الحدث.'],
    administrationSteps: ['توضيح أن الأسئلة تتعلق بالتعرض لا بالتشخيص.', 'تطبيق النسخة الموثقة دون توسيع البنود محليًا.', 'استخدام مفتاح التسجيل الخاص بالنسخة فقط.', 'ربط النتيجة بتاريخ التعرض والسياق السريري عند الحاجة.'],
    safetyNotes: ['السؤال عن خبرات قتالية قد يثير ضيقًا؛ يجب توفير خيار التوقف ومسار دعم واضح.', 'وجود أعراض صدمة أو خطر حالي يحتاج تقييمًا مستقلًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Combat Exposure Scale بحالة Public Domain. أي ترجمة عربية أو تكييف لنزاع مختلف يحتاج توثيقًا منفصلًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'التكييف العربي يحتاج تحققًا سياقيًا',
    arabicNote: 'لا يكفي ترجمة البنود؛ اختلاف طبيعة الخدمة العسكرية والنزاعات والسياق الثقافي قد يغير معنى التعرض.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الصفحة مرجعية حتى تثبيت نسخة عربية مناسبة وسياق استخدامها.',
    sources: [
      { label: 'CDISC QRS — Combat Exposure Scale Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — original Combat Exposure Scale development', url: 'https://pubmed.ncbi.nlm.nih.gov/6511942/', role: 'evidence' },
    ],
    related: ['life-events-checklist-dsm5-standard'],
  },
  {
    slug: 'general-clinical-global-impression',
    nameAr: 'الانطباع السريري العالمي العام',
    nameEn: 'General Clinical Global Impression',
    acronym: 'GCGI',
    version: 'General clinical global impression',
    summary: 'تقدير سريري عالمي مختصر يلخص شدة الحالة أو التغير العام وفق حكم المختص، ويستخدم كمرساة مساندة في دراسات كثيرة.',
    purpose: 'تلخيص الانطباع المهني عن الشدة أو التغير بصورة سريعة إلى جانب مقاييس أكثر تفصيلًا.',
    construct: 'الحكم السريري العالمي على الشدة أو التغير',
    populations: ['السكان السريريّون بحسب سياق الدراسة أو العلاج'],
    settings: ['الطب النفسي', 'التجارب السريرية', 'متابعة النتائج'],
    categories: ['mental-health', 'rehabilitation-outcomes'],
    administrationMode: 'تقدير سريري عالمي بواسطة مختص مطلع على حالة الشخص وسياق المقارنة.',
    administrationTime: 'دقائق قليلة بعد توفر المعلومات السريرية اللازمة.',
    equipment: ['تعريفات النسخة المستخدمة', 'سياق سريري كاف للحكم'],
    scoring: 'تستخدم صيغ CGI درجات رتبية للشدة أو التحسن والتغير؛ يجب تحديد الجزء والنسخة المستخدمة وعدم دمج درجات مختلفة في مجموع واحد.',
    interpretation: 'ميزة الأداة البساطة والشمول، لكنها تعتمد على حكم الفاحص وقد تتأثر باختلاف الخبرة والمعلومات المتاحة.',
    limitations: ['أقل تفصيلًا من المقاييس متعددة البنود.', 'الاتفاق بين المقيمين قد يكون محدودًا دون تعريفات وتدريب.', 'لا يحدد أي أعراض تغيرت أو لماذا.'],
    administrationSteps: ['تحديد ما إذا كان المطلوب شدة أم تغيرًا.', 'مراجعة المعلومات السريرية ذات الصلة.', 'اختيار التقدير الأقرب لتعريفات النسخة.', 'تسجيل نقطة المقارنة والزمن عند استخدام مقياس التغير.'],
    safetyNotes: ['لا يستخدم الحكم العالمي بدل تقييم خطر الانتحار أو العنف أو التدهور الطبي الحاد.', 'ينبغي دعمه بمقاييس أكثر تحديدًا عندما يكون القرار السريري حساسًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج General Clinical Global Impression بحالة Public Domain. استخدام صيغ أو تعديلات مشتقة يجب أن يذكر النسخة بوضوح.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'قابل للتوطين مع تثبيت المراسي',
    arabicNote: 'المفهوم العام قابل للتوطين، لكن عبارات المراسي يجب أن تبقى متسقة ولا تبدل بين الزيارات أو المقيمين.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'سنثبت صيغة عربية تشغيلية فقط بعد مراجعة المصطلحات والمراسي وتوافقها مع النسخة المقصودة.',
    sources: [
      { label: 'CDISC QRS — General Clinical Global Impression Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — reliability of global clinical judgments', url: 'https://pubmed.ncbi.nlm.nih.gov/1296220/', role: 'evidence' },
      { label: 'PubMed — CGI reliability and validity work', url: 'https://pubmed.ncbi.nlm.nih.gov/17284321/', role: 'evidence' },
    ],
    related: ['brief-psychiatric-rating-scale-anchored'],
  },
  {
    slug: 'hamilton-depression-rating-scale-24',
    nameAr: 'مقياس هاملتون لتقدير الاكتئاب — 24 بندًا',
    nameEn: 'Hamilton Depression Rating Scale — 24 Item',
    acronym: 'HAMD-24',
    version: '24-item version',
    summary: 'نسخة موسعة من مقياس هاملتون يقدرها مختص لقياس شدة أعراض الاكتئاب ومتابعة التغير.',
    purpose: 'تقدير شدة أعراض الاكتئاب عبر مقابلة سريرية منظمة أو شبه منظمة ومتابعة الاستجابة بمرور الوقت.',
    construct: 'شدة أعراض الاكتئاب متعددة المجالات',
    populations: ['البالغون المصابون بأعراض أو اضطرابات اكتئابية'],
    settings: ['الطب النفسي', 'التجارب السريرية', 'متابعة العلاج'],
    categories: ['mental-health'],
    administrationMode: 'تقدير بواسطة فاحص مدرب اعتمادًا على مقابلة سريرية وتعريفات تسجيل محددة.',
    administrationTime: 'نحو 15–30 دقيقة حسب درجة التنظيم وخبرة الفاحص.',
    equipment: ['نموذج HAMD-24 المحدد', 'دليل المراسي أو المقابلة للنسخة المستخدمة'],
    scoring: 'تختلف نطاقات الاستجابة بين البنود، ويجمع المجموع وفق قواعد نسخة 24 بندًا. لا يجوز استخدام عتبات نسخة 17 أو 21 بندًا باعتبارها مكافئة تلقائيًا.',
    interpretation: 'الدرجة الأعلى تعكس أعراضًا أشد ضمن النسخة المستخدمة. الأدبيات توضح أن نسخ HAMD تختلف في خصائصها؛ يجب ذكر النسخة ونوع المقابلة عند المقارنة.',
    limitations: ['توجد عدة نسخ غير متطابقة من HAMD.', 'الاتفاق بين المقيمين يتحسن مع المقابلات المنظمة والتدريب.', 'بعض البنود الجسدية قد تتأثر بمرض طبي أو علاج آخر.'],
    administrationSteps: ['تثبيت نسخة 24 بندًا قبل التطبيق.', 'إجراء المقابلة وفق دليل النسخة ومراسيها.', 'تسجيل البنود وفق الفترة المرجعية المحددة.', 'توثيق النسخة وطريقة المقابلة والمقيّم.'],
    safetyNotes: ['وجود أفكار انتحارية يستدعي تقييم سلامة مستقلًا وفوريًا، ولا تكفي درجة بند أو مجموع HAMD.', 'المقياس لا يشخص الاضطراب الاكتئابي بمفرده.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — HAMD-24 موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Hamilton Depression Rating Scale 24-Item بحالة Public Domain. يجب التمييز بين النسخة الأصلية وبين المقابلات المنظمة أو الأدلة المطورة لاحقًا التي قد تكون لها شروط منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'الدراسات العربية الأقوى المتاحة تخص نسخًا أقصر',
    arabicNote: 'توجد دراسات عربية جيدة لـHAMD-6 وHAMD-7، لكنها لا تثبت تلقائيًا نسخة عربية HAMD-24.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ينشر HAMD-24 عربي كامل قبل تحديد ترجمة 24 بندًا بعينها ودليلها وحقوقها.',
    sources: [
      { label: 'CDISC QRS — HAMD-24 Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — critical review of HAMD versions', url: 'https://pubmed.ncbi.nlm.nih.gov/32289809/', role: 'evidence' },
      { label: 'PubMed — HAMD-24 and other versions in treatment outcomes', url: 'https://pubmed.ncbi.nlm.nih.gov/34752484/', role: 'evidence' },
      { label: 'PubMed — Arabic HAMD-7 validation (not HAMD-24)', url: 'https://pubmed.ncbi.nlm.nih.gov/30210846/', role: 'translation' },
    ],
    related: ['patient-health-questionnaire-9', 'brief-psychiatric-rating-scale-anchored'],
  },
  {
    slug: 'life-events-checklist-dsm5-standard',
    nameAr: 'قائمة أحداث الحياة لـDSM-5 — النسخة القياسية',
    nameEn: 'Life Events Checklist for DSM-5 — Standard Version',
    acronym: 'LEC-5',
    version: 'Standard self-report',
    summary: 'قائمة تقرير ذاتي من المركز الوطني الأمريكي لاضطراب ما بعد الصدمة لمسح التعرض لأحداث قد تكون صادمة عبر الحياة.',
    purpose: 'تحديد أنواع التعرض المحتمل للصدمة لتوجيه المقابلة أو التقييم اللاحق؛ لا تقيس شدة PTSD ولا تنتج تشخيصًا.',
    construct: 'التعرض لأحداث يحتمل أن تكون صادمة',
    populations: ['البالغون في تقييم الصدمة', 'الخدمات النفسية والبحوث المتعلقة بالتعرض للصدمة'],
    settings: ['الصحة النفسية', 'خدمات الصدمة', 'البحوث'],
    categories: ['trauma-stress', 'mental-health'],
    administrationMode: 'تقرير ذاتي قياسي عن أنواع أحداث وتجارب التعرض عبر الحياة.',
    administrationTime: 'عادةً 5–10 دقائق، وقد تزيد عند الحاجة إلى توضيح السياق.',
    equipment: ['نموذج LEC-5 القياسي الرسمي أو نسخة لغوية موثقة'],
    scoring: 'الجهة المطورة توضح أنه لا توجد درجة كلية رسمية أو بروتوكول تفسير عددي؛ تستخدم الاستجابات لتحديد نوع التعرض وتوجيه تقييم معيار A عند الحاجة.',
    interpretation: 'الاستجابة الإيجابية تعني وجود نوع من التعرض المبلغ عنه، ولا تثبت أن الحدث يحقق معيار الصدمة تشخيصيًا ولا أن الشخص مصاب بـPTSD.',
    limitations: ['لا يقيس الأعراض الحالية.', 'يعتمد على التذكر والإفصاح.', 'قد تحتاج بعض أنواع التعرض إلى مقابلة تفصيلية لتحديد معيار A.'],
    administrationSteps: ['شرح غرض القائمة وحدودها وخيار التوقف.', 'تطبيق النموذج الرسمي دون تحويله إلى اختبار مجموع درجات.', 'مراجعة أنواع التعرض ذات الصلة عند الحاجة السريرية.', 'إجراء تقييم متخصص مستقل إذا كان الهدف تشخيص PTSD.'],
    safetyNotes: ['الأسئلة قد تثير ضيقًا أو ذكريات مؤلمة؛ يجب توفير بيئة آمنة وخيار عدم الإجابة.', 'الإفصاح عن خطر حالي أو عنف مستمر يتطلب مسار حماية مستقلًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS ومتاح رسميًا من VA',
    rightsNote: 'CDISC يدرج LEC-5 Standard Version بحالة Public Domain، كما يوفر المركز الوطني لـPTSD النموذج الرسمي مباشرة. حقوق أي ترجمة غير صادرة عن المركز تراجع بصورة مستقلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لا توجد نسخة عربية رسمية موثقة في مصدر VA الذي راجعناه',
    arabicNote: 'مصدر VA يتيح النسخة الإنجليزية ويشير إلى ترجمة إسبانية بطلب مباشر؛ لذلك لا نفترض وجود نسخة عربية رسمية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'نربط بالنموذج الرسمي ونؤجل النص العربي الكامل حتى التحقق من ترجمة عربية بعينها.',
    sources: [
      { label: 'VA National Center for PTSD — official LEC-5', url: 'https://www.ptsd.va.gov/professional/assessment/te-measures/life_events_checklist.asp', role: 'original' },
      { label: 'CDISC QRS — LEC-5 Public Domain status', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['combat-exposure-scale'],
  },
  {
    slug: 'minnesota-tobacco-withdrawal-scale-revised',
    nameAr: 'مقياس مينيسوتا لأعراض انسحاب التبغ — المنقح',
    nameEn: 'Minnesota Tobacco Withdrawal Scale — Revised',
    acronym: 'MTWS-R',
    version: 'Revised version represented in CDISC QRS',
    summary: 'مقياس لأعراض انسحاب التبغ والنيكوتين يستخدم في بحوث الإقلاع والعلاج لمتابعة تغير أعراض الامتناع.',
    purpose: 'تقدير شدة أعراض الانسحاب ومتابعتها خلال الامتناع أو تدخلات الإقلاع عن التبغ والنيكوتين.',
    construct: 'أعراض انسحاب التبغ والنيكوتين',
    populations: ['مستخدمو التبغ أو النيكوتين خلال محاولات الإقلاع أو الامتناع'],
    settings: ['علاج الاعتماد على التبغ', 'بحوث الإقلاع', 'الصحة السلوكية'],
    categories: ['substance-use-addiction', 'mental-health'],
    administrationMode: 'تقرير عن أعراض الانسحاب وفق نسخة محددة وفترة زمنية محددة.',
    administrationTime: 'عدة دقائق عادةً.',
    equipment: ['نسخة MTWS-R المحددة', 'قواعد التسجيل والفترة المرجعية المطابقة للإصدار'],
    scoring: 'تختلف المراجعات والصيغ؛ يجب استخدام بنود ومراسي الإصدار المحدد وعدم دمجها مع نسخ سابقة. CDISC يمثل نسخة منقحة ضمن تصنيف سريري منظم.',
    interpretation: 'الدرجة الأعلى تعكس أعراض انسحاب أشد، لكنها لا تحدد وحدها جرعة العلاج ولا تميز كل أسباب القلق أو الأرق أو المزاج المتغير.',
    limitations: ['الأعراض غير نوعية وقد تتأثر بالتوتر أو اضطرابات أخرى.', 'النسخ التاريخية ليست متطابقة.', 'التوقيت منذ آخر استخدام للنيكوتين يؤثر في الدرجة.'],
    administrationSteps: ['تحديد تاريخ ووقت آخر استخدام للنيكوتين.', 'تطبيق النسخة والفترة المرجعية نفسها في كل متابعة.', 'تسجيل أعراض الانسحاب دون افتراض أن كل عرض سببه النيكوتين.', 'استخدام النتيجة مع التاريخ السريري وخطة الإقلاع.'],
    safetyNotes: ['الدرجة لا تستبدل تقييم الاكتئاب الشديد أو خطر الانتحار أو أعراض طبية حادة.', 'قرارات العلاج الدوائي تحتاج إشرافًا مناسبًا ولا تبنى على المجموع وحده.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج MTWS-R بحالة Public Domain ويشير في مصطلحاته إلى اعتقاده بأن الأداة ضمن المجال العام؛ ينبغي تثبيت الإصدار عند إعادة الاستخدام.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج تحققًا خاصًا بالإصدار',
    arabicNote: 'لا نستخدم ترجمة لأحد الإصدارات على أنها ترجمة للنسخة المنقحة الحالية دون مطابقة بنيوية وزمنية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الصفحة تشرح القياس وحدوده وتربط بالمصدر؛ النص العربي الكامل مؤجل.',
    sources: [
      { label: 'CDISC QRS — MTWS-R Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'NCI EVS — CDISC terminology for MTWS-R', url: 'https://evs.nci.nih.gov/ftp1/CDISC/SDTM/SDTM%20Terminology.pdf', role: 'original' },
      { label: 'PubMed — example validation of a revised MTWS translation', url: 'https://pubmed.ncbi.nlm.nih.gov/37474294/', role: 'evidence' },
    ],
    related: ['patient-health-questionnaire-15'],
  },
  {
    slug: 'modified-medical-research-council-dyspnea-scale',
    nameAr: 'مقياس مجلس البحوث الطبية المعدل لضيق النفس',
    nameEn: 'Modified Medical Research Council Dyspnea Scale',
    acronym: 'mMRC',
    version: '0–4 ordinal dyspnea disability scale',
    summary: 'مقياس رتبي قصير يصف مقدار تقييد النشاط اليومي بسبب ضيق النفس، ويستخدم على نطاق واسع في الأمراض التنفسية المزمنة.',
    purpose: 'تصنيف أثر ضيق النفس على النشاط والتنقل ومتابعة العبء الوظيفي ضمن التقييم التنفسي.',
    construct: 'العجز الوظيفي المرتبط بضيق النفس',
    populations: ['الأشخاص المصابون بأمراض تنفسية مزمنة', 'مرضى COPD ومجتمعات تنفسية أخرى'],
    settings: ['طب الصدر', 'التأهيل الرئوي', 'الرعاية الأولية', 'البحوث التنفسية'],
    categories: ['respiratory-function', 'rehabilitation-outcomes'],
    administrationMode: 'سؤال أو تصنيف سريري يختار وصف النشاط الأقرب إلى أثر ضيق النفس.',
    administrationTime: 'أقل من عدة دقائق عادةً.',
    equipment: ['صياغة mMRC القياسية للنسخة اللغوية المستخدمة'],
    scoring: 'درجة رتبية من 0 إلى 4؛ الدرجات الأعلى تعكس تقييدًا أكبر للنشاط بسبب ضيق النفس.',
    interpretation: 'المقياس يصف أثر ضيق النفس على النشاط ولا يقيس شدة المرض الرئوي أو الأكسجة مباشرة. التغير يفسر مع وظائف الرئة والأعراض والسياق.',
    limitations: ['مقياس أحادي البعد نسبيًا.', 'لا يميز الآليات المختلفة لضيق النفس.', 'قد يتأثر النشاط بعوامل عضلية أو قلبية أو نفسية غير تنفسية.'],
    administrationSteps: ['تأكيد أن السؤال يتعلق بضيق النفس كسبب للتقييد.', 'عرض الخيارات القياسية دون إعادة صياغة تغير المعنى.', 'اختيار الوصف الأقرب للحالة المعتادة.', 'توثيق الدرجة والسياق السريري.'],
    safetyNotes: ['ضيق النفس الحاد أو ألم الصدر أو الزرقة أو تدهور الوعي يحتاج تقييمًا طبيًا عاجلًا.', 'لا يستخدم المقياس لتحديد حاجة الأكسجين أو العلاج الحاد بمفرده.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج mMRC بحالة Public Domain. يجب تثبيت صياغة النسخة اللغوية لأن فروقًا صغيرة قد تغير الدرجة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'توجد استخدامات عربية لكن النسخة المرجعية تحتاج تثبيتًا',
    arabicNote: 'قبل نشر نص عربي كامل نحتاج اختيار ترجمة موحدة وربطها بدراسة تحقق في مجتمع عربي مناسب.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الشرح متاح، أما الصياغة العربية الكاملة فتنتظر تثبيت نسخة مرجعية.',
    sources: [
      { label: 'CDISC QRS — mMRC Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — mMRC in COPD outcomes', url: 'https://pubmed.ncbi.nlm.nih.gov/26726080/', role: 'evidence' },
    ],
    related: ['6-minute-walk-test'],
  },
  {
    slug: 'pain-intensity-cdisc',
    nameAr: 'تقدير شدة الألم',
    nameEn: 'Pain Intensity',
    acronym: 'PI',
    version: 'CDISC QRS Pain Intensity',
    summary: 'قياس مختصر لشدة الألم يستخدم كمتغير نتيجة شائع؛ يجب تحديد مقياس الاستجابة والفترة المرجعية بدقة لأن الصيغ ليست متطابقة.',
    purpose: 'تقدير شدة الألم الحالية أو خلال فترة مرجعية محددة ومتابعة التغير بمرور الوقت.',
    construct: 'شدة الألم المدركة',
    populations: ['الأشخاص الذين يعانون ألمًا حادًا أو مزمنًا ضمن سياقات سريرية متعددة'],
    settings: ['إدارة الألم', 'الرعاية الأولية', 'الأورام', 'التأهيل', 'البحوث السريرية'],
    categories: ['pain-function', 'symptom-burden'],
    administrationMode: 'تقرير ذاتي باستخدام صيغة الاستجابة المحددة في البروتوكول، وقد تكون رقمية أو وصفية بحسب النسخة.',
    administrationTime: 'أقل من دقيقة غالبًا.',
    equipment: ['مقياس الاستجابة المحدد', 'تعريف واضح للفترة المرجعية مثل الآن أو المتوسط أو الأسوأ'],
    scoring: 'تسجل الاستجابة مباشرة وفق نطاق المقياس المستخدم. لا يجوز مقارنة 0–10 و0–100 أو الحالي والمتوسط والأسوأ دون توحيد وتعريف.',
    interpretation: 'الدرجة تعكس شدة الألم المبلغ عنها لا سبب الألم ولا مقدار الضرر النسيجي. التغير المهم يعتمد على المجتمع والسياق وخط الأساس.',
    limitations: ['مقياس أحادي البند لا يصف طبيعة الألم أو أثره الوظيفي.', 'يتأثر بالفترة المرجعية والتعليمات.', 'لا توجد عتبة واحدة تصلح لكل الأمراض والقرارات.'],
    administrationSteps: ['تحديد نوع الألم والفترة المرجعية المقصودة.', 'استخدام نفس نطاق الاستجابة في المتابعات.', 'تسجيل الدرجة كما أبلغ بها الشخص.', 'دمجها مع الوظيفة والموقع والسياق عند اتخاذ قرار سريري.'],
    safetyNotes: ['ألم جديد شديد أو مصحوب بعلامات طبية مقلقة يتطلب تقييم السبب ولا يدار بالدرجة وحدها.', 'المقياس ليس أداة لتقرير جرعة مسكنات بصورة آلية.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Pain Intensity بحالة Public Domain. يجب عدم خلط هذا السجل العام بمقاييس ألم مملوكة مثل BPI التي لها حالة حقوق مختلفة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'قابل للتوطين مع تثبيت السؤال والمراسي',
    arabicNote: 'اللغة بسيطة نسبيًا لكن صلاحية المقارنة تعتمد على تثبيت الفترة المرجعية ونطاق الاستجابة والصياغة نفسها.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'سننشر بروتوكولًا عربيًا فقط عندما نثبت صيغة محددة دون خلطها بمقاييس أخرى.',
    sources: [
      { label: 'CDISC QRS — Pain Intensity Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — validity of numeric rating for cancer pain', url: 'https://pubmed.ncbi.nlm.nih.gov/9145556/', role: 'evidence' },
      { label: 'PubMed — systematic review of pain intensity measurement properties', url: 'https://pubmed.ncbi.nlm.nih.gov/30099210/', role: 'evidence' },
    ],
    related: ['roland-morris-disability-questionnaire-24'],
  },
  {
    slug: 'patient-health-questionnaire-15',
    nameAr: 'استبيان صحة المريض — 15 عرضًا جسديًا',
    nameEn: 'Patient Health Questionnaire — 15',
    acronym: 'PHQ-15',
    version: 'PHQ-15',
    summary: 'استبيان تقرير ذاتي لقياس شدة مجموعة من الأعراض الجسدية الشائعة، ويستخدم في الرعاية الأولية والبحوث النفسجسدية.',
    purpose: 'تقدير عبء الأعراض الجسدية ومتابعتها؛ لا يثبت أن الأعراض غير مفسرة طبيًا ولا يشخص اضطراب الأعراض الجسدية وحده.',
    construct: 'شدة الأعراض الجسدية المبلغ عنها',
    populations: ['البالغون في الرعاية الأولية', 'العيادات النفسية والجسدية', 'البحوث السكانية'],
    settings: ['الرعاية الأولية', 'الصحة النفسية', 'الطب النفسي الجسدي', 'البحوث'],
    categories: ['symptom-burden', 'mental-health'],
    administrationMode: 'تقرير ذاتي عن مدى الانزعاج من أعراض جسدية خلال الفترة المرجعية.',
    administrationTime: 'نحو 5 دقائق أو أقل عادةً.',
    equipment: ['نموذج PHQ-15 بالنسخة اللغوية المعتمدة'],
    scoring: 'تسجل البنود عادةً على ثلاث درجات وتجمع إلى مجموع من 0 إلى 30. اقترحت الدراسة الأصلية مستويات شدة، لكنها ليست تشخيصًا مستقلًا ولا تعني أن العرض غير مفسر طبيًا.',
    interpretation: 'الدرجة الأعلى تعكس عبئًا أكبر من الأعراض الجسدية. يجب مراجعة الأسباب الطبية والأدوية والحالة النفسية وعدم استخدام المجموع لنفسنة الأعراض.',
    limitations: ['الأعراض غير نوعية وقد تكون ناتجة عن مرض طبي.', 'تتأثر النتائج بالسياق الثقافي والجنس والعمر.', 'لا يحدد المقياس سبب الأعراض.'],
    administrationSteps: ['توضيح الفترة المرجعية وخيارات الاستجابة.', 'إكمال البنود دون استبدال الفحص الطبي عند الحاجة.', 'حساب المجموع وفق قواعد PHQ-15.', 'تفسير الدرجة مع التاريخ الطبي والنفسي والوظيفي.'],
    safetyNotes: ['الأعراض الجسدية الجديدة أو الشديدة أو العلامات الحمراء تحتاج تقييمًا طبيًا مستقلًا.', 'المقياس لا يستخدم لإخبار الشخص أن أعراضه نفسية المنشأ.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج PHQ-15 بحالة Public Domain. النسخ العربية المنشورة يجب أن تنسب إلى دراساتها المحددة عند استخدامها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد نسخ عربية ذات خصائص قياسية منشورة',
    arabicNote: 'نشرت دراسات سعودية ولبنانية خصائص قياسية للنسخة العربية من PHQ-15. لا نعمم البنية العاملية أو الحدود على كل المجتمعات العربية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'قبل نشر النص العربي الكامل سنطابق ترجمة محددة مع الدراسة ومصدر النص وحقوق إعادة نشر تلك الصياغة.',
    sources: [
      { label: 'CDISC QRS — PHQ-15 Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — original PHQ-15 validity study', url: 'https://pubmed.ncbi.nlm.nih.gov/11914441/', role: 'evidence' },
      { label: 'PubMed — Arabic PHQ validation in Saudi Arabia', url: 'https://pubmed.ncbi.nlm.nih.gov/28878812/', role: 'translation' },
      { label: 'PubMed — Arabic PHQ-15 validation in Lebanese adults', url: 'https://pubmed.ncbi.nlm.nih.gov/38271356/', role: 'translation' },
    ],
    related: ['patient-health-questionnaire-9', 'generalized-anxiety-disorder-7'],
  },
  {
    slug: 'visual-function-questionnaire-25',
    nameAr: 'استبيان المعهد الوطني للعين للوظيفة البصرية — 25',
    nameEn: 'National Eye Institute Visual Function Questionnaire — 25',
    acronym: 'NEI-VFQ-25',
    version: '2000 VFQ-25',
    summary: 'استبيان تقرير ذاتي يقيس الحالة الصحية والوظيفية المرتبطة بالبصر لدى الأشخاص المصابين بأمراض عين مزمنة.',
    purpose: 'قياس أثر الرؤية في الأنشطة والأداء والرفاه المرتبط بالبصر ومتابعة النتائج من منظور الشخص.',
    construct: 'الوظيفة ونوعية الحياة المرتبطتان بالبصر',
    populations: ['البالغون المصابون بأمراض عين مزمنة أو ضعف بصري'],
    settings: ['طب العيون', 'تأهيل ضعف البصر', 'البحوث السريرية'],
    categories: ['vision', 'participation', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير ذاتي أو تطبيق بواسطة فاحص وفق النسخة المحددة.',
    administrationTime: 'نحو 10 دقائق عادةً مع اختلاف المدة حسب القدرة البصرية والقرائية.',
    equipment: ['نموذج NEI-VFQ-25 الرسمي', 'دليل التسجيل للنسخة المستخدمة'],
    scoring: 'يتضمن الاستبيان مجالات متعددة؛ يجب تحويل الإجابات وحساب درجات المجالات والدرجة المركبة وفق خوارزمية NEI بدل جمع البنود جمعًا خامًا.',
    interpretation: 'الدرجات الأعلى تعكس وظيفة أو حالة أفضل في المجالات المقاسة. لا تساوي الدرجة حدة البصر المقاسة موضوعيًا ويجب تفسيرها مع الفحص العيني.',
    limitations: ['تقرير ذاتي وقد يتأثر بعوامل صحية ونفسية واجتماعية.', 'بعض البنود قد لا تنطبق ثقافيًا أو وظيفيًا على كل مجتمع.', 'لا يستبدل قياسات حدة البصر أو المجال البصري أو التشخيص العيني.'],
    administrationSteps: ['اختيار نسخة التطبيق الذاتي أو المقابلة المناسبة.', 'استخدام النسخة اللغوية الموثقة.', 'تسجيل الاستجابات ثم تطبيق خوارزمية تحويل الدرجات الرسمية.', 'عرض المجالات والدرجة المركبة مع نتائج الفحص البصري.'],
    safetyNotes: ['فقدان الرؤية المفاجئ أو ألم العين الحاد أو أعراض شبكية طارئة تحتاج رعاية عاجلة.', 'الاستبيان لقياس الأثر الوظيفي وليس لتشخيص مرض العين.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS ومتاح من NEI',
    rightsNote: 'CDISC يدرج نسختي VFQ-25 للتطبيق الذاتي وبواسطة الفاحص بحالة Public Domain، والمعهد الوطني للعين يوفر إصدار 2000 للتنزيل. حقوق ترجمة بعينها توثق مع مصدرها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد نسخة عربية محققة منشورة',
    arabicNote: 'نشرت دراسة متعددة المراكز في مصر تطوير واختبار نسخة عربية من NEI-VFQ-25 وأظهرت اتساقًا داخليًا وثبات إعادة اختبار جيدين، مع ملاحظات على بنود ذات عدم استجابة مرتفع.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننقل نص النسخة العربية كاملًا حتى نثبت مصدر النص وشروط إعادة نشر الترجمة نفسها، رغم أن الأصل Public Domain.',
    sources: [
      { label: 'National Eye Institute — official VFQ-25', url: 'https://www.nei.nih.gov/about/education-and-outreach/outreach-materials/visual-function-questionnaire-25', role: 'original' },
      { label: 'CDISC QRS — VFQ-25 Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — Arabic NEI-VFQ-25 validation', url: 'https://pubmed.ncbi.nlm.nih.gov/25349812/', role: 'translation' },
    ],
    related: ['6-minute-walk-test'],
  },
];
