import type { AssessmentMeasure } from '@/lib/assessment-measures';

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';

export const assessmentMeasuresWave9: AssessmentMeasure[] = [
  {
    slug: 'child-pugh-classification',
    nameAr: 'تصنيف تشايلد–بو لشدة مرض الكبد',
    nameEn: 'Child-Pugh Classification',
    acronym: 'CHILD-PUGH',
    version: 'Five-domain Child-Pugh classification / CDISC QRS',
    summary: 'تصنيف سريري تاريخي واسع الاستخدام لتوصيف شدة تشمع الكبد اعتمادًا على خمسة مجالات مخبرية وسريرية، ويكمل MELD ولا يستبدله أو يحل محل التقييم السريري أو سياسات الزراعة.',
    purpose: 'تقسيم شدة مرض الكبد المزمن إلى فئات إنذارية عامة ودعم التواصل والبحث ومقارنة مجموعات المرضى ضمن سياق سريري محدد.',
    construct: 'شدة القصور الكبدي والإنذار العام في تشمع الكبد',
    populations: ['بالغون مصابون بتشمع/مرض كبد مزمن عندما يكون Child-Pugh مناسبًا للسياق', 'دراسات الكبد والجراحة والعلاج التي توثق نسخة التصنيف'],
    settings: ['أمراض الكبد', 'الجهاز الهضمي', 'الجراحة', 'الأورام الكبدية', 'البحوث السريرية'],
    categories: ['hepatology-liver-disease', 'gastroenterology'],
    administrationMode: 'تجميع خمسة مجالات: البيليروبين، الألبومين، INR/زمن البروثرومبين بحسب النسخة، الاستسقاء، والاعتلال الدماغي الكبدي، ثم تعيين نقاط وفئة.',
    administrationTime: 'دقائق بعد توفر النتائج المخبرية والتقييم السريري.',
    equipment: ['نتائج البيليروبين والألبومين والتخثر', 'تقييم سريري للاستسقاء والاعتلال الدماغي', 'مرجع تعريفات النسخة المستخدمة'],
    scoring: 'تمنح المجالات الخمسة عادة 1–3 نقاط لكل مجال، ثم تجمع لتصنيف A/B/C. يجب توثيق حدود المختبر وتعريفات الاستسقاء والاعتلال الدماغي المستخدمة، لأن بعض التفاصيل تختلف تاريخيًا بين الصيغ والمراجع.',
    interpretation: 'الفئة الأعلى تعكس عادة مرضًا أشد وإنذارًا أسوأ على مستوى المجموعات، لكنها لا تعطي احتمالًا فرديًا حتميًا ولا تساوي MELD أو سياسة تخصيص زراعة الكبد.',
    limitations: ['الاستسقاء والاعتلال الدماغي مكونان يحملان قدرًا من الحكم السريري.', 'توجد اختلافات تاريخية في بعض حدود المتغيرات والتعامل مع INR/زمن البروثرومبين.', 'لا يلتقط جميع أبعاد شدة مرض الكبد أو المضاعفات.', 'الأداء الإنذاري يختلف حسب السياق وقد يكون MELD أو نماذج أحدث أنسب لبعض الأغراض.'],
    administrationSteps: ['حدد نسخة وتعريفات Child-Pugh المستخدمة.', 'اجمع القيم المخبرية ضمن سياق زمني مناسب.', 'قيّم الاستسقاء والاعتلال الدماغي بمعايير واضحة.', 'سجل نقاط كل مجال والمجموع والفئة مع تاريخ القياس.', 'فسر الفئة مع MELD والتقييم السريري والسياسة العلاجية المناسبة.'],
    safetyNotes: ['لا تستخدم Child-Pugh وحده لتحديد أهلية زراعة الكبد أو سحب العلاج أو رفض الجراحة أو وصف جرعة دواء.', 'أي تدهور حاد أو نزف أو اعتلال دماغي شديد أو إنتان يحتاج تقييمًا عاجلًا مستقلًا عن الفئة.', 'لا تحول روافد التصنيف إلى حاسبة قرار علاجي حتمي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Child-Pugh Classification بحالة Public Domain. المقالات والجداول والواجهات التابعة لناشرين أو جهات أخرى تبقى مستقلة حقوقيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف سريري قابل للتوطين مع تثبيت التعريفات',
    arabicNote: 'المصطلحات قابلة للشرح عربيًا، لكن الاستخدام التشغيلي يحتاج تعريفات موحدة للمكونات السريرية والمخبرية وإصدارًا موثقًا.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد حاسبة عامة أو جدول جرعات/قرارات اعتمادًا على Child-Pugh؛ يعرض كمرجع منهجي.',
    sources: [
      { label: 'CDISC QRS — Child-Pugh Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/child-pugh-classification', role: 'rights' },
      { label: 'PubMed — Child-Pugh versus MELD systematic review and meta-analysis', url: 'https://pubmed.ncbi.nlm.nih.gov/26937922/', role: 'evidence' },
      { label: 'PubMed — review of limitations of Child-Pugh classification', url: 'https://pubmed.ncbi.nlm.nih.gov/30634187/', role: 'evidence' },
    ],
    related: ['model-for-end-stage-liver-disease'],
  },
  {
    slug: 'roland-morris-disability-questionnaire',
    nameAr: 'استبيان رولاند–موريس للعجز المرتبط بألم أسفل الظهر',
    nameEn: 'Roland-Morris Disability Questionnaire',
    acronym: 'RMDQ',
    version: 'Original 24-item Roland-Morris / CDISC RDQ',
    summary: 'استبيان تقرير ذاتي من 24 بندًا لقياس محدودية النشاط والوظيفة المرتبطة بألم أسفل الظهر، واسع الاستخدام في التأهيل والبحوث ومتابعة التغير الوظيفي.',
    purpose: 'تكميم العجز الوظيفي المرتبط بألم أسفل الظهر ومتابعة التغير مع الزمن أو العلاج.',
    construct: 'الإعاقة/المحدودية الوظيفية المرتبطة بألم أسفل الظهر',
    populations: ['البالغون ذوو ألم أسفل الظهر القادرون على التقرير الذاتي', 'سياقات التأهيل والبحوث العضلية الهيكلية'],
    settings: ['العلاج الطبيعي', 'التأهيل', 'طب الألم', 'العمود الفقري', 'الرعاية الأولية', 'البحوث السريرية'],
    categories: ['pain-function', 'rehabilitation-outcomes'],
    administrationMode: 'استبيان تقرير ذاتي من 24 عبارة وظيفية مرتبطة بالحالة في الوقت الحالي/الفترة المحددة وفق النسخة المستخدمة.',
    administrationTime: 'عادة بضع دقائق.',
    equipment: ['نسخة RMDQ/RDQ موثقة اللغة والإصدار', 'تعليمات تسجيل ثابتة'],
    scoring: 'تسجل الاستجابات ثنائيًا وفق النسخة الأصلية ويجمع عدد البنود الدالة على العجز إلى نطاق 0–24؛ الأعلى يعكس عجزًا وظيفيًا أكبر. لا يجوز تغيير البنود أو جمع نسخة مختصرة مع معايير النسخة الأصلية.',
    interpretation: 'المجموع يعكس أثر ألم أسفل الظهر على الوظيفة وليس شدة الألم وحدها؛ لذلك يجب تفسيره مع الألم والفحص والوظيفة والأهداف الفردية.',
    limitations: ['يعتمد على التقرير الذاتي وقد يتأثر بالسياق والثقافة.', 'توجد نسخ مختصرة وترجمات متعددة لا ينبغي خلطها.', 'لا يحدد سبب ألم الظهر أو وجود مرض خطير.', 'قد تظهر تأثيرات أرضية/سقفية بحسب شدة العجز.'],
    administrationSteps: ['ثبت النسخة واللغة قبل التطبيق.', 'قدم التعليمات دون إعادة صياغة البنود بشكل يغير معناها.', 'سجل الاستجابات حسب القواعد الأصلية.', 'اجمع الدرجة دون تحويلها إلى نسبة غير معيارية.', 'قارن التغير باستخدام النسخة نفسها وبقية مؤشرات الوظيفة والألم.'],
    safetyNotes: ['RMDQ ليس أداة تشخيص للقرص أو التضيق أو الكسور أو أسباب الألم الخطرة.', 'علامات الإنذار العصبية أو الجهازية تستلزم تقييمًا طبيًا مستقلًا عن الدرجة.', 'لا تستخدم الدرجة وحدها لتقرير تصوير أو جراحة أو حرمان من علاج.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Roland-Morris Disability Questionnaire بحالة Public Domain. حقوق النص الأصلي لا تمنح تلقائيًا حق إعادة نشر ترجمة عربية منشورة لطرف ثالث؛ لذلك تبقى نصوص الترجمات تحت مراجعة منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد نسخة عربية فصحى حديثة محققة ودراسات عربية إضافية',
    arabicNote: 'نشرت دراسة 2014 ترجمة وتكييفًا إلى Modern Standard Arabic واختبرتها لدى 201 مريضًا ناطقًا بالعربية بألم أسفل الظهر، مع ثبات وموثوقية جيدين. توجد أيضًا نسخة مغربية ودليل بنيوي سعودي حديث. هذا دليل على صلاحية نسخ عربية محددة ولا يعني أن روافد يملك حق نسخ نص الترجمة المنشورة حرفيًا.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا يعاد نشر البنود العربية الكاملة حتى مراجعة النسخة العربية المقصودة وحقوق نصها؛ تعرض روافد المنهج والخصائص والمصادر.',
    sources: [
      { label: 'CDISC QRS — RMDQ/RDQ Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/roland-morris-disability-questionnaire', role: 'rights' },
      { label: 'PubMed — Modern Standard Arabic RMDQ validation', url: 'https://pubmed.ncbi.nlm.nih.gov/25271496/', role: 'translation' },
      { label: 'PubMed — Moroccan RMDQ translation and validation', url: 'https://pubmed.ncbi.nlm.nih.gov/17545917/', role: 'translation' },
      { label: 'PubMed — 2026 Saudi structural validity of Arabic RMDQ', url: 'https://pubmed.ncbi.nlm.nih.gov/42355694/', role: 'evidence' },
    ],
    related: ['pain-intensity-cdisc', 'timed-up-and-go'],
  },
  {
    slug: 'rutgeerts-score',
    nameAr: 'درجة روتغيرتس للنكس التنظيري بعد جراحة داء كرون',
    nameEn: 'Rutgeerts Score',
    acronym: 'RUTGEERTS SCORE',
    version: 'Original postoperative i0–i4 endoscopic score / CDISC QRS',
    summary: 'نظام تنظيري لتصنيف شدة النكس بعد الاستئصال اللفائفي/اللفائفي القولوني في داء كرون، يصف الآفات المبكرة في اللفائفي النهائي الجديد وما حول المفاغرة ويرتبط بخطر النكس اللاحق.',
    purpose: 'توحيد توصيف النكس التنظيري بعد جراحة داء كرون ودعم المتابعة والبحوث والتواصل السريري.',
    construct: 'شدة النكس التنظيري بعد الجراحة في داء كرون',
    populations: ['مرضى داء كرون بعد الاستئصال اللفائفي/اللفائفي القولوني مع مفاغرة مناسبة للسياق الأصلي', 'دراسات النكس بعد الجراحة'],
    settings: ['أمراض الجهاز الهضمي', 'التنظير', 'جراحة القولون والمستقيم', 'عيادات أمراض الأمعاء الالتهابية'],
    categories: ['gastroenterology'],
    administrationMode: 'تقييم تنظيري منظم لللفائفي النهائي الجديد والمفاغرة وفق فئات Rutgeerts الأصلية i0–i4.',
    administrationTime: 'يحدد أثناء/بعد مراجعة التنظير؛ الوقت الأساسي مرتبط بإجراء التنظير.',
    equipment: ['تنظير لفائفي قولوني عالي الجودة', 'تعريفات Rutgeerts الأصلية', 'قارئ/مناظر مدرب'],
    scoring: 'تصنف الموجودات من i0 إلى i4 وفق شدة ونمط الآفات. تعديل i2 إلى i2a/i2b هو modified Rutgeerts وليس الفئة الأصلية نفسها؛ يجب تسمية النسخة وعدم خلط تعريفاتها أو نتائجها.',
    interpretation: 'الفئات الأعلى ارتبطت تاريخيًا بخطر أكبر للنكس السريري بعد الجراحة، لكن القرار العلاجي الحديث يدمج عوامل الخطر والدواء والأعراض والمؤشرات الحيوية والتصوير ولا يعتمد على الدرجة وحدها.',
    limitations: ['طُوّر في سياق جراحي وتنظيري محدد ولا يعمم على جميع أنماط كرون.', 'يوجد تباين بين المقيمين خاصة حول i2.', 'التعديل i2a/i2b ليس مكافئًا تلقائيًا للنسخة الأصلية.', 'التنظير لا يلتقط وحده جميع جوانب المرض العابر للجدار أو خارج اللمعة.'],
    administrationSteps: ['ثبت ما إذا كنت تستخدم Rutgeerts الأصلي أم النسخة المعدلة.', 'راجع اللفائفي النهائي الجديد والمفاغرة وفق بروتوكول تنظير مناسب.', 'سجل الآفات ونمطها قبل تعيين الفئة.', 'وثق الفئة والإصدار وأي عدم يقين.', 'فسر النتيجة مع عوامل النكس والمؤشرات السريرية والمخبرية.'],
    safetyNotes: ['لا تستخدم Rutgeerts وحده لبدء أو إيقاف علاج بيولوجي أو لاتخاذ قرار جراحي.', 'سلامة التنظير وملاءمته للمريض تسبق الحاجة للحصول على الدرجة.', 'أعراض انسداد أو نزف أو خراج/إنتان تحتاج تقييمًا مستقلًا وعاجلًا عند اللزوم.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Rutgeerts Score بحالة Public Domain. الصور التنظيرية والأشكال والجداول المقتبسة من المقالات تبقى خاضعة لحقوق ناشريها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف تنظيري قابل للتوطين مع توحيد التعريفات',
    arabicNote: 'القيمة تعتمد على التدريب وتعريف الآفات والفئة أكثر من اللغة؛ يمكن توطين المصطلحات عربيًا بعد تثبيت النسخة الأصلية أو المعدلة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد صورًا أو جداول محمية؛ تعرض تعريفًا منهجيًا وروابط للمصادر.',
    sources: [
      { label: 'CDISC QRS — Rutgeerts Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/rutgeerts-score', role: 'rights' },
      { label: 'PubMed — original postoperative Crohn recurrence study', url: 'https://pubmed.ncbi.nlm.nih.gov/2394349/', role: 'original' },
      { label: 'PubMed — reliability and modified i2a/i2b context', url: 'https://pubmed.ncbi.nlm.nih.gov/31473359/', role: 'evidence' },
    ],
    related: ['simple-endoscopic-score-crohns-disease-v1', 'harvey-bradshaw-index', 'crohns-disease-activity-index-v1'],
  },
  {
    slug: 'covi-anxiety-scale',
    nameAr: 'مقياس كوفي للقلق',
    nameEn: 'Covi Anxiety Scale',
    acronym: 'COVI',
    version: 'Clinician-rated COVI / CDISC QRS',
    summary: 'مقياس قصير يقدره المختص لتوصيف شدة القلق من منظور سريري عالمي، ويستخدم كمؤشر مكمل لا كتشخيص مستقل أو بديل عن مقابلة القلق والمقاييس الأوسع.',
    purpose: 'تكميم شدة القلق سريريًا ومتابعة التغير في الدراسات أو الرعاية عند استخدام نسخة وتعريفات ثابتة.',
    construct: 'شدة القلق المقدرة سريريًا',
    populations: ['بالغون يخضعون لتقييم سريري للقلق ضمن بروتوكول مناسب', 'التجارب النفسية والدوائية التي تحدد COVI بوضوح'],
    settings: ['الطب النفسي', 'الصحة النفسية', 'التجارب السريرية', 'المتابعة العلاجية'],
    categories: ['mental-health'],
    administrationMode: 'تقدير من مختص مدرب باستخدام عناصر ومراسي COVI المحددة، بعد مقابلة أو ملاحظة سريرية كافية.',
    administrationTime: 'بضع دقائق بعد تقييم سريري مناسب.',
    equipment: ['نسخة COVI ومراسيها المحددة', 'معلومات مقابلة سريرية كافية'],
    scoring: 'COVI مقياس سريري قصير ذو عناصر ومراسي رتبية؛ يجب استخدام بنية ومراسي النسخة المرجعية وعدم اختراع مجموع أو عتبة تشخيصية محلية. لا تعرض روافد عتبة تشخيص عالمية لأن المقياس ليس تشخيصًا مستقلًا.',
    interpretation: 'الدرجة الأعلى تعكس قلقًا مقدرًا بدرجة أكبر ضمن المقياس، ويجب تفسيرها مع المقابلة السريرية وأدوات مثل HAM-A أو GAD-7 والسياق الوظيفي.',
    limitations: ['يعتمد على حكم المقيم وتدريبه.', 'قصير وقد لا يلتقط جميع أبعاد القلق أو الاضطرابات المترافقة.', 'لا يحدد نوع اضطراب القلق وحده.', 'لا ينبغي نقل عتبات أو تفسير من دراسة واحدة إلى كل المجتمعات.'],
    administrationSteps: ['ثبت نسخة COVI ومراسيها.', 'أجر تقييمًا سريريًا كافيًا قبل التسجيل.', 'قيّم العناصر وفق التعريفات لا الانطباع العام وحده.', 'وثق الدرجة والوقت وأي عوامل تؤثر في التقييم.', 'فسرها مع مقياس قلق أو مقابلة أكثر تفصيلًا عند الحاجة.'],
    safetyNotes: ['COVI ليس أداة تشخيص مستقلة ولا أداة لاستبعاد اضطراب خطير.', 'خطر إيذاء النفس/الآخرين أو الهياج أو الذهان يحتاج تقييمًا مباشرًا مستقلًا عن درجة القلق.', 'لا تستخدم الدرجة وحدها لبدء أو إيقاف دواء مرتفع المخاطر.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Covi Anxiety Scale بحالة Public Domain. مواد ePROVIDE أو المقالات والواجهات التابعة لطرف ثالث لها شروطها ولا تعاد نشرها حرفيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لا توجد نسخة عربية معيارية معتمدة لدى روافد',
    arabicNote: 'يجب توحيد المصطلحات ومراسي التقدير وتدريب المقيمين قبل اعتماد صياغة عربية؛ ترجمة الأسماء وحدها لا تكفي للتحقق.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر المراسي العربية كاملة قبل مراجعة نسخة محددة والتحقق من اتساق المقيمين.',
    sources: [
      { label: 'CDISC QRS — COVI Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/covi-anxiety-scale', role: 'rights' },
      { label: 'ePROVIDE — Covi Anxiety Scale overview', url: 'https://eprovide.mapi-trust.org/instruments/covi-anxiety-scale', role: 'original' },
      { label: 'PubMed — COVI use in generalized anxiety treatment trial', url: 'https://pubmed.ncbi.nlm.nih.gov/7907097/', role: 'evidence' },
    ],
    related: ['hamilton-anxiety-rating-scale', 'generalized-anxiety-disorder-7', 'clinical-global-impression'],
  },
  {
    slug: 'tanner-scale-boy',
    nameAr: 'مقياس تانر للنضج الجنسي — الأولاد',
    nameEn: 'Tanner Scale Boy',
    acronym: 'TANNER SCALE BOY',
    version: 'Five-stage male sexual maturity rating / CDISC QRS RS v1.0',
    summary: 'تصنيف سريري من خمس مراحل لتوثيق تطور الأعضاء التناسلية والشعر العاني لدى الأولاد ضمن تقييم البلوغ. روافد يعرضه كمرجع سريري نصي فقط بلا صور حساسة أو اختبار ذاتي.',
    purpose: 'توثيق مرحلة النضج الجنسي عند الأولاد ضمن تقييم سريري للنمو والبلوغ والمتابعة الهرمونية أو البحثية.',
    construct: 'مرحلة النضج الجنسي والبلوغ لدى الأولاد',
    populations: ['الأطفال والمراهقون الذكور عندما توجد حاجة سريرية مناسبة لتقييم البلوغ', 'بحوث النمو والبلوغ التي تستخدم تقييمًا مهنيًا وأخلاقيًا'],
    settings: ['طب الأطفال', 'الغدد الصماء للأطفال', 'طب المراهقين', 'البحوث السريرية'],
    categories: ['pediatric-puberty-development'],
    administrationMode: 'تقييم سريري مهني لمجال التطور التناسلي والشعر العاني بصورة منفصلة ضمن خمس مراحل، وفق بروتوكول وخصوصية وموافقة مناسبة.',
    administrationTime: 'قصير ضمن فحص سريري شامل، لكن لا ينبغي استعجال الموافقة والخصوصية والشرح.',
    equipment: ['غرفة فحص خاصة', 'سياسة موافقة/assent ومرافق/مرافقة سريرية حسب العمر والقانون المحلي', 'تعريفات Tanner النصية المرجعية'],
    scoring: 'يسجل التطور التناسلي والشعر العاني ضمن مراحل 1–5 مع التعامل مع المجالين بصورة منفصلة عند الحاجة. لا يُقدَّم كتقييم ذاتي، ولا تستخدم روافد صورًا لاختيار المرحلة.',
    interpretation: 'المرحلة تصف النضج الجسدي ولا تحدد وحدها العمر العظمي أو سبب البلوغ المبكر/المتأخر أو الهوية الجنسية أو الصحة النفسية. توقيت البلوغ يتباين طبيعيًا بين الأفراد والسكان.',
    limitations: ['يتطلب فحصًا حساسًا وقد يتأثر بخبرة الفاحص.', 'التقييم الذاتي لدى المراهقين لا يطابق التقييم السريري دائمًا.', 'الشعر العاني يعكس الأندروجينات ولا يجب اعتباره مطابقًا تمامًا لتطور محور الغدد التناسلية.', 'البدانة والعوامل السكانية قد تؤثر في تقدير بعض المظاهر.'],
    administrationSteps: ['حدد ضرورة الفحص وفائدته السريرية قبل أي تقييم حساس.', 'اشرح الإجراء بلغة مناسبة للعمر واحصل على الموافقة/assent وفق السياسة المحلية.', 'وفر الخصوصية والمرافق/المرافقة السريرية عند اللزوم.', 'قيّم المجالات المطلوبة وفق التعريفات النصية دون تصوير أو تخزين صور.', 'وثق المرحلة والسياق والمجال الذي تم تقييمه، وأحل للغدد عند وجود نمط غير متوقع.'],
    safetyNotes: ['لا تعرض روافد صورًا حساسة لمراحل Tanner ولا تطلب من طفل أو مراهق رفع أو تحميل صور جسدية.', 'لا يُقدَّم كتقييم ذاتي أو اختبار منزلي لتشخيص البلوغ.', 'الفحص السريري يجب أن يكون trauma-informed ويحترم الخصوصية والموافقة والسياسات المحلية.', 'أي قلق من إساءة أو استغلال أو علامات بلوغ غير معتادة يستلزم مسارًا سريريًا مناسبًا مستقلًا عن رقم المرحلة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Tanner Scale Boy بحالة Public Domain. الصور التعليمية والرسوم السريرية المنشورة من جهات أخرى قد تكون محمية ولا تعيد روافد نشرها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'التعريفات قابلة للتوطين النصي دون صور حساسة',
    arabicNote: 'يمكن تقديم تعريفات عربية مهنية مختصرة للمراحل، لكن التطبيق الحقيقي فحص سريري حساس وليس تجربة ذاتية على الموقع.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا توجد صور أو أداة self-staging عربية؛ الصفحة مرجع نصي سريري فقط.',
    sources: [
      { label: 'CDISC QRS — Tanner Scale Boy Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'NCBI Endotext — clinical staging of normal and abnormal puberty', url: 'https://www.ncbi.nlm.nih.gov/books/NBK279024/', role: 'evidence' },
      { label: 'PubMed — systematic review/meta-analysis of adolescent self-assessment accuracy', url: 'https://pubmed.ncbi.nlm.nih.gov/32179891/', role: 'evidence' },
    ],
    related: ['tanner-scale-girl'],
  },
  {
    slug: 'tanner-scale-girl',
    nameAr: 'مقياس تانر للنضج الجنسي — الفتيات',
    nameEn: 'Tanner Scale Girl',
    acronym: 'TANNER SCALE GIRL',
    version: 'Five-stage female sexual maturity rating / CDISC QRS RS v1.0',
    summary: 'تصنيف سريري من خمس مراحل لتوثيق نمو الثدي والشعر العاني لدى الفتيات ضمن تقييم البلوغ. روافد يعرضه كمرجع نصي سريري بلا صور حساسة أو self-staging.',
    purpose: 'توثيق مرحلة النضج الجنسي عند الفتيات ضمن تقييم سريري للنمو والبلوغ والمتابعة الهرمونية أو البحثية.',
    construct: 'مرحلة النضج الجنسي والبلوغ لدى الفتيات',
    populations: ['الأطفال والمراهقات عندما توجد حاجة سريرية مناسبة لتقييم البلوغ', 'بحوث النمو والبلوغ التي تطبق حماية وخصوصية مناسبة'],
    settings: ['طب الأطفال', 'الغدد الصماء للأطفال', 'طب المراهقين', 'البحوث السريرية'],
    categories: ['pediatric-puberty-development'],
    administrationMode: 'تقييم سريري مهني لنمو الثدي والشعر العاني بصورة منفصلة ضمن خمس مراحل، وفق بروتوكول حساس للخصوصية والموافقة.',
    administrationTime: 'قصير ضمن فحص سريري شامل، مع إعطاء الوقت اللازم للشرح والموافقة والخصوصية.',
    equipment: ['غرفة فحص خاصة', 'سياسة موافقة/assent ومرافق/مرافقة سريرية حسب العمر والقانون المحلي', 'تعريفات Tanner النصية المرجعية'],
    scoring: 'يسجل نمو الثدي والشعر العاني ضمن مراحل 1–5 مع تقييم المجالين بصورة منفصلة. لا يُقدَّم كتقييم ذاتي، ولا تستخدم روافد صورًا حساسة لاختيار المرحلة.',
    interpretation: 'المرحلة تصف النضج الجسدي ولا تحدد وحدها سبب البلوغ المبكر/المتأخر أو الخصوبة أو العمر العظمي. نمو الثدي والشعر العاني قد لا يتقدمان بالتزامن ويجب عدم دمجهما في رقم غير موثق.',
    limitations: ['التقييم حساس ويتطلب خبرة وسياقًا أخلاقيًا مناسبًا.', 'التقييم الذاتي قد يكون غير دقيق مقارنة بالفحص المهني.', 'البدانة قد تجعل تقدير نمو الثدي أكثر تحديًا.', 'الشعر العاني لا يعكس وحده تنشيط محور الغدد التناسلية.'],
    administrationSteps: ['أكد الحاجة السريرية للفحص قبل إجرائه.', 'اشرح الإجراء بلغة مناسبة للعمر واحصل على الموافقة/assent حسب السياسة.', 'وفر الخصوصية والمرافق/المرافقة السريرية عند اللزوم.', 'قيّم نمو الثدي والشعر العاني حسب التعريفات النصية دون تصوير.', 'وثق كل مجال بصورة منفصلة وأحل للاختصاصي عند وجود توقيت أو نمط غير متوقع.'],
    safetyNotes: ['لا تعرض روافد صورًا حساسة لمراحل Tanner ولا تطلب من طفلة أو مراهقة رفع أو تحميل صور جسدية.', 'لا يُقدَّم كتقييم ذاتي أو اختبار منزلي لتشخيص البلوغ.', 'الفحص يجب أن يكون trauma-informed ويحترم الخصوصية والموافقة والمرافقة والسياسات المحلية.', 'لا ينبغي استخدام المرحلة لإحراج أو وصم الطفل أو للحكم على النضج النفسي أو الاجتماعي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Tanner Scale Girl بحالة Public Domain. أي صور أو رسوم تعليمية من مصادر أخرى لها حقوق مستقلة ولا تعاد نشرها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'التعريفات قابلة للتوطين النصي دون صور حساسة',
    arabicNote: 'يمكن صياغة تعريفات عربية مهنية، لكن التقييم السريري الحساس لا يتحول إلى أداة ذاتية على الموقع.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا توجد صور أو self-staging؛ الصفحة مرجع نصي سريري فقط.',
    sources: [
      { label: 'CDISC QRS — Tanner Scale Girl Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/tanner-scale-girl', role: 'rights' },
      { label: 'NCBI Endotext — clinical staging of normal and abnormal puberty', url: 'https://www.ncbi.nlm.nih.gov/books/NBK279024/', role: 'evidence' },
      { label: 'PubMed — systematic review/meta-analysis of adolescent self-assessment accuracy', url: 'https://pubmed.ncbi.nlm.nih.gov/32179891/', role: 'evidence' },
    ],
    related: ['tanner-scale-boy'],
  },
  {
    slug: 'observer-global-impression',
    nameAr: 'الانطباع العالمي للمراقب',
    nameEn: 'Observer Global Impression',
    acronym: 'OGI',
    version: 'Observer-reported global impression framework / CDISC QRS QS v1.0',
    summary: 'إطار قصير لتقدير الانطباع العالمي عن شدة مفهوم محدد أو تغيره من منظور مراقب/مقدم رعاية لديه فرصة كافية للملاحظة، ويستخدم كمرساة مكملة لا كبديل عن مقاييس الأداء أو تقرير المريض.',
    purpose: 'تسجيل تقدير المراقب لشدة أو تغير مفهوم قابل للملاحظة ضمن دراسة أو متابعة، خصوصًا عندما يكون التقرير المباشر من المريض محدودًا أو يحتاج منظورًا مكملاً.',
    construct: 'الانطباع العالمي للمراقب عن شدة/تغير مفهوم محدد',
    populations: ['الأطفال أو البالغون عندما يكون للمراقب/مقدم الرعاية معرفة كافية بالسلوك أو الوظيفة المحددة', 'دراسات النتائج المبلغة من المراقبين'],
    settings: ['الصحة النفسية', 'طب الأطفال', 'الأمراض النادرة', 'التجارب السريرية', 'المتابعة الوظيفية'],
    categories: ['mental-health', 'participation'],
    administrationMode: 'سؤال/تقدير من مراقب مؤهل حول مفهوم محدد مع مراسي رتبية خاصة بالنسخة أو الدراسة، وليس حكمًا عامًا غير معرف.',
    administrationTime: 'عادة أقل من بضع دقائق بعد توفر ملاحظة كافية.',
    equipment: ['تعريف واضح للمفهوم والفترة الزمنية', 'نسخة OGI ومراسيها المحددة', 'مراقب لديه فرصة ملاحظة مناسبة'],
    scoring: 'تستخدم مراسي رتبية خاصة بالنسخة لقياس الشدة أو التغير. لا توجد عتبة عالمية واحدة ولا ينبغي جمع OGI مع PGI/CGI كأنها مقياس واحد؛ كل مصدر تقرير مستقل.',
    interpretation: 'النتيجة تعكس منظور المراقب لمفهوم قابل للملاحظة، وقد تختلف عن تقرير المريض أو تقدير الطبيب. الاختلاف نفسه قد يكون معلومة مهمة ولا ينبغي محوه بالمتوسط غير المعياري.',
    limitations: ['المراقب قد لا يستطيع رؤية الأعراض الداخلية مثل القلق أو الألم مباشرة.', 'تتأثر النتيجة بمقدار الوقت الذي يقضيه المراقب مع الشخص.', 'قد توجد تحيزات توقع أو عبء مقدم الرعاية.', 'المراسي والمفهوم المقصود يختلفان بين الدراسات والنسخ.'],
    administrationSteps: ['حدد المفهوم والفترة الزمنية ومَن هو المراقب المؤهل قبل التطبيق.', 'تأكد أن المراقب لديه فرصة ملاحظة كافية للمجال المقصود.', 'استخدم المراسي المحددة دون إعادة صياغة عشوائية.', 'سجل مصدر التقرير والدرجة والزمن.', 'قارن مع PGI أو CGI أو مقياس أداء كمنظور مكمل، لا كبديل تلقائي.'],
    safetyNotes: ['لا تستخدم OGI لتخمين أعراض داخلية لا يستطيع المراقب ملاحظتها مباشرة.', 'OGI ليس تشخيصًا ولا أساسًا منفردًا لتغيير علاج مرتفع المخاطر.', 'في مسائل السلامة أو الألم أو إيذاء النفس يجب أخذ تقرير الشخص والتقييم السريري المباشر متى كان ذلك ممكنًا ومناسبًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Observer Global Impression بحالة Public Domain. أي OGI مخصص لمرض بعينه أو مراسي مطورة من جهة أخرى قد تكون لها شروط منفصلة ويجب تقييمها كنسخة مستقلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'المراسي العربية تعتمد على المفهوم والنسخة',
    arabicNote: 'لا توجد صياغة عربية واحدة تصلح لكل OGI؛ يجب تعريف المفهوم والمراقب والفترة ثم تكييف المراسي والتحقق من فهمها.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد قالب OGI عامًا على أنه نسخة معيارية لكل الأمراض؛ تعرض الإطار وحدود الاستخدام.',
    sources: [
      { label: 'CDISC QRS — OGI Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — meaningful-change work using observer global impression anchors', url: 'https://pubmed.ncbi.nlm.nih.gov/42142559/', role: 'evidence' },
      { label: 'PubMed — observer global impression validation context in PKU', url: 'https://pubmed.ncbi.nlm.nih.gov/34815941/', role: 'evidence' },
    ],
    related: ['patient-global-impression', 'clinical-global-impression'],
  },
];
