import type { AssessmentMeasure } from '@/lib/assessment-measures';

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';

export const assessmentMeasuresWave10: AssessmentMeasure[] = [
  {
    slug: 'jfk-coma-recovery-scale-revised',
    nameAr: 'مقياس JFK للتعافي من الغيبوبة — المنقح',
    nameEn: 'JFK Coma Recovery Scale-Revised',
    acronym: 'CRS-R',
    version: 'CRS-R / CDISC QRS Version 1.0–2.0',
    summary: 'مقياس سريري منظم لتوصيف الاستجابات السمعية والبصرية والحركية والفموية/الحركية والتواصل والاستثارة لدى الأشخاص ذوي اضطرابات الوعي، ويساعد على التمييز السريري بين الغيبوبة ومتلازمة اليقظة غير المستجيبة وحالة الوعي الأدنى عند تطبيقه بصورة متكررة ومهنية.',
    purpose: 'تحسين توصيف مستوى الوعي وتتبع التغير السلوكي بعد إصابة دماغية شديدة أو أذية دماغية مكتسبة ضمن تقييم متعدد المصادر.',
    construct: 'الاستجابة السلوكية المرتبطة بمستوى الوعي والتعافي من اضطرابات الوعي',
    populations: ['الأشخاص ذوو اضطرابات الوعي بعد إصابة دماغية رضحية أو غير رضحية عندما يكون CRS-R مناسبًا سريريًا', 'برامج التأهيل العصبي والرعاية المطولة والبحوث المتخصصة'],
    settings: ['التأهيل العصبي', 'طب الأعصاب', 'الرعاية المطولة', 'إصابات الدماغ', 'البحوث السريرية'],
    categories: ['disorders-of-consciousness', 'brain-injury', 'neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'فحص سريري منظم بستة مقاييس فرعية مع مثيرات وتعليمات وإجراءات تسجيل معيارية، ويفضل تكراره لأن الأداء قد يتذبذب.',
    administrationTime: 'عادة نحو 15–30 دقيقة بحسب حالة المريض وخبرة الفاحص والحاجة لإعادة المحاولات.',
    equipment: ['مواد المثيرات المطلوبة وفق دليل CRS-R', 'بيئة تقلل المشتتات', 'فاحص مدرب على معايير الاستجابة والتسجيل'],
    scoring: 'تسجل أفضل الاستجابات الملاحظة ضمن المقاييس الفرعية الستة وفق معايير الأداة. المجموع العددي مفيد للمتابعة، لكن التشخيص السلوكي يعتمد أيضًا على نمط البنود ذات الدلالة وليس على المجموع وحده.',
    interpretation: 'تفسر الاستجابات على ضوء مستوى اليقظة والحالة الطبية والسمعية والبصرية والحركية والأدوية. التقييم المتكرر يقلل خطر الخطأ الناتج عن تقلب الاستجابة أو عوائق الحركة/اللغة.',
    limitations: ['قد تؤدي اضطرابات الحركة أو السمع أو الرؤية أو التهدئة أو التعب إلى خفض الاستجابة المرصودة.', 'الأداء يتذبذب ولذلك قد تكون جلسة واحدة غير ممثلة.', 'المجموع وحده لا يساوي تشخيصًا ولا تنبؤًا حتميًا بالمآل.', 'يتطلب تدريبًا والتزامًا بالبروتوكول لتقليل اختلاف المقيمين.'],
    administrationSteps: ['راجع العوامل الطبية والأدوية والحواس والحركة التي قد تعوق الاستجابة.', 'هيئ بيئة مناسبة وطبق المقاييس الفرعية وفق ترتيب وتعليمات النسخة.', 'امنح المحاولات والزمن المحددين ولا تستنتج الاستجابة من سلوك غير مطابق للمعيار.', 'سجل البنود والمجموع ونمط الاستجابات ذات الدلالة.', 'كرر التقييم عند الحاجة وادمج النتائج مع الفحص العصبي والسياق السريري.'],
    safetyNotes: ['لا تستخدم CRS-R منفردًا للتنبؤ الحتمي بالمآل أو لتبرير سحب العلاج أو حرمان المريض من التأهيل.', 'أي تدهور مفاجئ في الوعي يستدعي تقييمًا طبيًا عاجلًا لأسباب قابلة للعلاج ولا ينتظر استكمال المقياس.', 'قد يؤدي عدم تكييف الاختبار مع عجز سمعي أو بصري أو حركي إلى تشخيص أقل من المستوى الحقيقي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج JFK Coma Recovery Scale-Revised بحالة Public Domain. حقوق المقالات التدريبية أو الترجمات أو المواد التعليمية التابعة لجهات أخرى تبقى مستقلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'يلزم تثبيت نسخة عربية محققة قبل نشر نموذج عربي كامل',
    arabicNote: 'يمكن شرح البنية والاستخدام بالعربية، لكن روافد لا تفترض أن أي ترجمة متداولة تمثل نسخة معيارية محققة أو قابلة لإعادة النشر. يلزم التحقق من النسخة العربية وخصائصها وحقوق نصها قبل نشر البنود.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تنشر روافد الدليل المنهجي والحدود السريرية فقط إلى أن تثبت نسخة عربية معيارية وحقوق نصها.',
    sources: [
      { label: 'CDISC QRS — CRS-R Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/jfk-coma-recovery-scale-revised', role: 'rights' },
      { label: 'PubMed — CRS-R measurement characteristics and diagnostic utility', url: 'https://pubmed.ncbi.nlm.nih.gov/15083429/', role: 'evidence' },
    ],
    related: ['glasgow-coma-scale-ninds', 'disability-rating-scale', 'glasgow-outcome-scale-extended'],
  },
  {
    slug: 'kdigo-acute-kidney-injury-stage',
    nameAr: 'مراحل إصابة الكلى الحادة وفق KDIGO',
    nameEn: 'Kidney Disease: Improving Global Outcomes — KDIGO AKI Stage',
    acronym: 'KDIGO AKI',
    version: 'KDIGO AKI staging / CDISC QRS Version 1.1',
    summary: 'تصنيف معياري لشدة إصابة الكلى الحادة يعتمد على تغير الكرياتينين في الدم وإدرار البول ضمن نوافذ زمنية محددة، ويستخدم للتوصيف والمتابعة والبحوث ولا يختزل سبب الأذية أو قرار العلاج.',
    purpose: 'توحيد تعريف ومراحل شدة AKI لتسهيل الاكتشاف والتواصل والمقارنة السريرية والبحثية.',
    construct: 'شدة إصابة الكلى الحادة وفق تغير وظيفة الكلى وإدرار البول',
    populations: ['البالغون والأطفال ضمن السياقات التي تطبق تعريفات KDIGO المناسبة', 'المرضى المنومون والحرجون والمعرضون لخطر AKI'],
    settings: ['العناية الحثيثة', 'أمراض الكلى', 'الطب الباطني', 'الطوارئ', 'الجراحة', 'البحوث السريرية'],
    categories: ['acute-kidney-injury', 'critical-care'],
    administrationMode: 'مراجعة متسلسلة للكرياتينين الأساسي/المرجعي والحالي وإدرار البول والزمن، ثم تعيين أعلى مرحلة مستوفاة وفق النسخة المحددة.',
    administrationTime: 'دقائق بعد توفر بيانات موثوقة، لكن التعيين قد يتغير مع مرور الزمن ووصول قياسات جديدة.',
    equipment: ['قيم كرياتينين متسلسلة مع وقت السحب', 'بيانات إدرار بول موثوقة عند استخدامها', 'وزن مناسب لحساب mL/kg/h عند الحاجة', 'مرجع KDIGO للإصدار المستخدم'],
    scoring: 'تحدد المراحل 1–3 بحسب مقدار/نسبة ارتفاع الكرياتينين أو مدة وشدة قلة البول، وتؤخذ المرحلة الأعلى التي يحققها المريض. يجب عدم خلط تعريفات أو نوافذ زمنية من إصدارات أو أنظمة أخرى.',
    interpretation: 'ارتفاع المرحلة يرتبط عادة بخطر أكبر للمضاعفات والوفاة على مستوى المجموعات، لكنه لا يحدد سبب AKI ولا يفرض وحده توقيت أو نوع العلاج أو الإحلال الكلوي.',
    limitations: ['قد يكون الكرياتينين الأساسي مجهولًا أو غير ثابت.', 'إدرار البول يتأثر بالسوائل والمدرات والقياس غير الكامل.', 'الكرياتينين يتأخر عن الأذية البنيوية وقد يتأثر بالكتلة العضلية والحجم.', 'التصنيف لا يحدد المسبب ولا يميز دائمًا الأذية البنيوية من التغير الوظيفي.'],
    administrationSteps: ['ثبت الإصدار المرجعي ومعايير KDIGO المستخدمة.', 'حدد أفضل قيمة كرياتينين أساسية موثقة دون اختلاق baseline غير مبرر.', 'رتب القيم وإدرار البول زمنيًا ضمن النوافذ المحددة.', 'عين المرحلة الأعلى المحققة واذكر معيارها وزمنها.', 'أعد التقييم مع البيانات الجديدة وافصل المرحلة عن تشخيص السبب وخطة العلاج.'],
    safetyNotes: ['لا تستخدم مرحلة KDIGO وحدها لاتخاذ قرار بدء أو إيقاف غسيل الكلى أو لتحديد جرعات دواء أو أهداف السوائل.', 'فرط البوتاسيوم الشديد أو الحماض أو الوذمة الرئوية أو قلة البول مع تدهور سريري حالات تحتاج تقييمًا وعلاجًا عاجلًا بصرف النظر عن رقم المرحلة.', 'لا تحوّل روافد التصنيف إلى حاسبة قرار علاجي فردي دون سياق سريري كامل.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج KDIGO AKI Stage بحالة Public Domain. نصوص إرشادات KDIGO الكاملة والجداول والرسوم التابعة للجهة الناشرة تبقى مواد منفصلة حقوقيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف قابل للتوطين مع تثبيت التعريفات والنوافذ الزمنية',
    arabicNote: 'يمكن عرض المفاهيم والمعايير بالعربية، لكن الاستخدام التشغيلي يحتاج مطابقة الإصدار المرجعي وتوثيق baseline والزمن والوحدات.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يعرض كمرجع منهجي وليس كحاسبة علاجية أو بديل عن تقييم اختصاصي الكلى/العناية الحثيثة.',
    sources: [
      { label: 'CDISC QRS — KDIGO AKI Stage Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/kidney-disease-improving-global-outcomes-kdigo-aki-stage', role: 'rights' },
      { label: 'KDIGO — Acute Kidney Injury guideline resources and 2026 update pathway', url: 'https://kdigo.org/guidelines/acute-kidney-injury/', role: 'original' },
    ],
    related: ['sofa-27mar2024', 'apache-ii'],
  },
  {
    slug: 'expanded-drs-postacute-interview-survivor',
    nameAr: 'مقابلة مقياس العجز الموسع بعد المرحلة الحادة — نسخة الناجي',
    nameEn: 'Expanded Disability Rating Scale — Postacute Interview Survivor Version',
    acronym: 'EXPANDED DRS-PI SURVIVOR',
    version: 'Expanded DRS-PI Survivor Version 1.0',
    summary: 'مقابلة منظمة طُورت لزيادة معيارية تطبيق Disability Rating Scale في المتابعة بعد المرحلة الحادة وإضافة مجالات تقلل تأثير الأرضية لدى الناجين من إصابة الدماغ.',
    purpose: 'توحيد متابعة العجز والاندماج الوظيفي بعد إصابة دماغية عبر مقابلة يمكن تطبيقها هاتفيًا أو عن بعد وفق البروتوكول.',
    construct: 'العجز والوظيفة والمشاركة بعد إصابة الدماغ في المرحلة ما بعد الحادة',
    populations: ['ناجون من إصابة دماغية رضحية في المتابعة ما بعد الحادة والقادرون على تقديم تقرير مناسب', 'دراسات المتابعة طويلة الأمد وبرامج إعادة التأهيل'],
    settings: ['التأهيل العصبي', 'المتابعة المجتمعية', 'الطب الفيزيائي وإعادة التأهيل', 'البحوث الطولية'],
    categories: ['brain-injury', 'rehabilitation-outcomes', 'participation'],
    administrationMode: 'مقابلة منظمة مع الناجي تُشتق منها درجات DRS والعناصر الموسعة وفق الخوارزمية المحددة.',
    administrationTime: 'قصيرة نسبيًا؛ يعتمد الزمن على التعقيد الوظيفي والحاجة للاستفسار المنظم.',
    equipment: ['نسخة Survivor المحددة من Expanded DRS-PI', 'تعليمات المقابلة وخوارزمية التحويل إلى الدرجات'],
    scoring: 'تُسجل إجابات المقابلة ثم تحول إلى عناصر ودرجات وفق الخوارزمية الأصلية؛ لا يجوز خلط أسئلة نسخة الناجي مع نسخة مقدم الرعاية أو مع DRS الأصلي دون توثيق.',
    interpretation: 'تساعد النسخة الموسعة في التمييز بين مستويات أفضل من الأداء في العينات ما بعد الحادة التي قد تظهر تأثيرًا أرضيًا على DRS الأصلي؛ تفسر مع السياق الوظيفي والمشاركة.',
    limitations: ['تعتمد على دقة التقرير الذاتي والذاكرة والاستبصار.', 'قد لا تكون نسخة الناجي مناسبة عندما تمنع اضطرابات الإدراك أو التواصل تقريرًا موثوقًا.', 'ليست بديلًا عن التقييم المباشر عند الحاجة.', 'المقارنة التاريخية مع DRS الأصلي تحتاج توثيق طريقة الاشتقاق.'],
    administrationSteps: ['اختر نسخة الناجي فقط عندما يكون التقرير الذاتي مناسبًا.', 'طبق نص المقابلة وتسلسل الاستفسارات دون حذف انتقائي.', 'اشتق الدرجات بالخوارزمية الأصلية.', 'وثق طريقة التطبيق وهوية المجيب والزمن منذ الإصابة.', 'فسر النتائج مع DRS والتأهيل والمشاركة ولا تساو بين الصيغ دون توثيق.'],
    safetyNotes: ['لا تستخدم الدرجة وحدها لتحديد أهلية خدمات التأهيل أو التعويض أو القدرة القانونية.', 'عندما يكون الاستبصار أو التواصل محدودًا، استخدم مصادر إضافية أو نسخة مقدم الرعاية بدل افتراض دقة التقرير الذاتي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Expanded DRS-PI Survivor Version بحالة Public Domain. أي ترجمة أو دليل تدريبي منشور من طرف ثالث يراجع بصورة مستقلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'تحتاج المقابلة العربية إلى ترجمة معيارية وتحقيق قبل الاستخدام',
    arabicNote: 'لا توجد في سجل روافد الحالي نسخة عربية محققة محددة لهذه الصيغة؛ ترجمة الأسئلة والخوارزمية يجب أن تحافظ على التكافؤ مع نسخة الناجي.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يعرض الدليل والمنهج فقط حتى تثبت نسخة عربية معيارية قابلة لإعادة النشر.',
    sources: [
      { label: 'CDISC QRS — Expanded DRS-PI Survivor Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — structured DRS postacute interview development and psychometrics', url: 'https://pubmed.ncbi.nlm.nih.gov/22510680/', role: 'evidence' },
    ],
    related: ['disability-rating-scale', 'glasgow-outcome-scale-extended', 'chart-short-form'],
  },
  {
    slug: 'expanded-drs-postacute-interview-caregiver',
    nameAr: 'مقابلة مقياس العجز الموسع بعد المرحلة الحادة — نسخة مقدم الرعاية',
    nameEn: 'Expanded Disability Rating Scale — Postacute Interview Caregiver Version',
    acronym: 'EXPANDED DRS-PI CAREGIVER',
    version: 'Expanded DRS-PI Caregiver Version 1.0',
    summary: 'صيغة مقابلة منظمة لمقدم الرعاية ضمن عائلة Expanded DRS-PI لقياس العجز والوظيفة بعد إصابة الدماغ عندما يكون تقرير الناجي غير كافٍ أو عندما يكون منظور مقدم الرعاية هو المصدر المحدد بالبروتوكول.',
    purpose: 'توحيد الحصول على معلومات العجز والمشاركة بعد المرحلة الحادة من مقدم الرعاية مع الحفاظ على فصل مصدر التقرير عن نسخة الناجي.',
    construct: 'العجز والوظيفة والمشاركة بعد إصابة الدماغ كما يبلغ عنها مقدم الرعاية',
    populations: ['مقدمو رعاية لأشخاص بعد إصابة دماغية رضحية ضمن متابعات ما بعد الحادة', 'حالات يكون فيها التقرير الذاتي للناجي محدودًا أو البروتوكول يحدد proxy report'],
    settings: ['التأهيل العصبي', 'المتابعة المجتمعية', 'البحوث الطولية', 'الطب الفيزيائي وإعادة التأهيل'],
    categories: ['brain-injury', 'rehabilitation-outcomes', 'participation'],
    administrationMode: 'مقابلة منظمة مع مقدم الرعاية باستخدام نسخة caregiver المحددة وخوارزمية التسجيل التابعة لها.',
    administrationTime: 'قصيرة نسبيًا؛ يتغير الزمن حسب تعقيد الحالة ووضوح معلومات مقدم الرعاية.',
    equipment: ['نسخة Caregiver المحددة من Expanded DRS-PI', 'تعليمات المقابلة وخوارزمية التسجيل'],
    scoring: 'تسجل الإجابات وتحوّل إلى الدرجات وفق خوارزمية النسخة. يجب إبقاء مصدر التقرير ظاهرًا وعدم دمج caregiver وsurvivor كما لو أنهما استجابة واحدة.',
    interpretation: 'توفر منظور proxy منظمًا لكنه قد يختلف عن تقرير الناجي أو التقييم المباشر؛ الاختلاف نفسه قد يكون ذا دلالة ويجب ألا يُخفى.',
    limitations: ['قد يتأثر التقرير بعبء مقدم الرعاية أو مدة الملاحظة أو توقعاته.', 'ليس بديلًا مطلقًا عن تقرير الناجي عندما يكون قادرًا على الإجابة.', 'مقارنة الدرجات بين مصادر مختلفة تحتاج حذرًا.', 'لا يقيس كل أبعاد جودة الحياة أو المشاركة بصورة مستقلة.'],
    administrationSteps: ['حدد أن مصدر التقرير هو مقدم الرعاية ووثق علاقته ومدة معرفته بالحالة.', 'طبق نسخة caregiver كما هي دون خلطها بنسخة survivor.', 'اشتق الدرجات بالخوارزمية الأصلية.', 'وثق أي عدم يقين أو محدودية في معرفة المجيب.', 'قارن مع مصادر أخرى عند توفرها بدل اعتبار proxy حقيقة مطلقة.'],
    safetyNotes: ['لا تستخدم تقرير مقدم الرعاية وحده لحجب صوت الناجي أو لتحديد الأهلية القانونية أو التأهيلية.', 'التعارض بين تقرير الناجي ومقدم الرعاية يحتاج استكشافًا سريريًا لا اختيار الأعلى أو الأدنى آليًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Expanded DRS-PI Caregiver Version بحالة Public Domain. حقوق أي ترجمة أو مادة تدريبية منفصلة تُراجع بصورة مستقلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'تحتاج نسخة مقدم الرعاية العربية إلى ترجمة معيارية وتحقيق',
    arabicNote: 'لا تفترض روافد أن ترجمة نسخة الناجي تصلح لنسخة مقدم الرعاية؛ يجب الحفاظ على صياغة المصدر والمنظور والخوارزمية الخاصة بهذه النسخة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يعرض الدليل والمنهج فقط حتى تثبت نسخة عربية معيارية وحقوق نصها.',
    sources: [
      { label: 'CDISC QRS — Expanded DRS-PI Caregiver Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — structured DRS postacute interview development including caregiver sample', url: 'https://pubmed.ncbi.nlm.nih.gov/22510680/', role: 'evidence' },
    ],
    related: ['expanded-drs-postacute-interview-survivor', 'disability-rating-scale', 'chart-short-form'],
  },
  {
    slug: 'international-physical-activity-questionnaire-short-form-self-administered',
    nameAr: 'الاستبيان الدولي للنشاط البدني — النسخة القصيرة ذاتية التطبيق لآخر 7 أيام',
    nameEn: 'International Physical Activity Questionnaire — Short Last 7 Days Self-Administered Format',
    acronym: 'IPAQ-SF',
    version: 'August 2002 Short Last 7 Days Self-Administered / CDISC Version 1.0',
    summary: 'نسخة قصيرة ذاتية التطبيق من IPAQ لتقدير النشاط البدني والجلوس خلال الأيام السبعة السابقة، مفيدة للمسوحات والبحوث عندما يلزم عبء تطبيق أقل من النسخة الطويلة.',
    purpose: 'تقدير النشاط البدني المبلغ عنه ذاتيًا خلال أسبوع بصورة مختصرة مع إمكانية اشتقاق مؤشرات النشاط وفق بروتوكول IPAQ المحدد.',
    construct: 'النشاط البدني المبلغ عنه ذاتيًا والجلوس خلال آخر سبعة أيام',
    populations: ['البالغون ضمن نطاقات الاستخدام المحددة لبروتوكول IPAQ', 'المسوحات والبحوث السكانية والعيادات الوقائية عندما تناسب النسخة القصيرة'],
    settings: ['الصحة العامة', 'البحوث السكانية', 'الوقاية', 'التأهيل'],
    categories: ['participation', 'mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'استبيان قصير ذاتي التطبيق يلتقط أيام ومدة النشاط الشديد والمتوسط والمشي والجلوس خلال آخر سبعة أيام وفق صيغة August 2002 المحددة.',
    administrationTime: 'عادة بضع دقائق، وهو أقصر من IPAQ-LF.',
    equipment: ['نسخة IPAQ-SF Self-Administered المحددة', 'بروتوكول IPAQ للتنظيف والحساب والتصنيف'],
    scoring: 'تستخدم الأيام والدقائق لاشتقاق مؤشرات النشاط وMET-min/week عند تطبيق بروتوكول IPAQ. يجب الالتزام بقواعد القص والتنظيف وعدم خلط صيغة الهاتف أو النسخة الطويلة مع هذه الصيغة.',
    interpretation: 'مناسب للتقدير السكاني وتتبع النشاط المبلغ عنه، لكنه ليس قياسًا موضوعيًا للحركة. الأدلة العربية الحديثة تظهر تباينًا في الصدق المعياري مقابل مقاييس التسارع، خصوصًا للجلوس والنشاط على المستوى الفردي.',
    limitations: ['تحيز التذكر والمبالغة أو التقليل في التقرير الذاتي.', 'الصدق مقابل مقاييس التسارع قد يكون محدودًا في بعض العينات العربية.', 'النسخة القصيرة لا توفر تفصيل المجالات الموجود في النسخة الطويلة.', 'الاختلافات في الترجمة وطريقة التطبيق تؤثر على المقارنة.'],
    administrationSteps: ['ثبت صيغة Short Last 7 Days Self-Administered August 2002.', 'استخدم ترجمة موثقة ولا تستبدلها بنسخة الهاتف.', 'اجمع الأيام والدقائق والجلوس وفق التعليمات.', 'طبق قواعد تنظيف وحساب IPAQ نفسها المخصصة لهذه الصيغة.', 'وثق اللغة والصيغة وطريقة التطبيق عند المقارنة.'],
    safetyNotes: ['IPAQ-SF لا يحدد أمان ممارسة التمارين ولا يمثل اختبار لياقة أو تصريحًا طبيًا للنشاط.', 'الأعراض القلبية أو التنفسية أو العصبية المقلقة تستلزم تقييمًا مهنيًا مستقلًا عن نتيجة الاستبيان.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — الصيغة القصيرة ذاتية التطبيق موثقة في CDISC',
    rightsNote: 'CDISC يدرج International Physical Activity Questionnaire (August 2002) Short Last 7 Days Self-Administered Format بحالة Public Domain. يجب عدم تعميم هذا الحكم على ترجمة بعينها دون مراجعتها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'IPAQ-SF دُرس في عدة مجتمعات عربية مع تباين الخصائص القياسية',
    arabicNote: 'مراجعة منهجية COSMIN منشورة في 2026 حددت دراسات IPAQ-SF في الأردن والإمارات والسعودية والكويت وغيرها. الثبات والصدق يختلفان بين العينات، والصدق المعياري مقابل accelerometer كان ضعيفًا في عدة دراسات؛ لذلك تعرض روافد حالة الدليل ولا تدعي نسخة عربية واحدة صالحة عالميًا.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد نص ترجمة عربية بعينها كاملًا حتى مطابقة النسخة المستخدمة وحقوق نص الترجمة، رغم أن الأداة الأصلية Public Domain.',
    sources: [
      { label: 'CDISC QRS — IPAQ-SF Self-Administered Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/international-physical-activity-questionnaire-august-2002-short-last-7', role: 'rights' },
      { label: 'CDISC Nutrition User Guide — IPAQ formats and permission status', url: 'https://www.cdisc.org/standards/therapeutic-areas/nutrition/nutrition-therapeutic-area-user-guide-v1-0/html', role: 'original' },
      { label: 'PubMed — 2026 COSMIN systematic review of Arabic physical-activity measures', url: 'https://pubmed.ncbi.nlm.nih.gov/42040138/', role: 'translation' },
    ],
    related: ['international-physical-activity-questionnaire-long-form', '6-minute-walk-test'],
  },
  {
    slug: 'vignos-lower-extremity-rating-scale',
    nameAr: 'مقياس فيغنوس لوظيفة الأطراف السفلية',
    nameEn: 'Vignos Lower Extremity Rating Scale',
    acronym: 'VLERS',
    version: 'Vignos Lower Extremity Rating Scale / CDISC Version 1.0',
    summary: 'تصنيف سريري رتبي لوظيفة الطرفين السفليين في الأمراض العصبية العضلية، وخاصة الحثل العضلي، يركز على المشي وصعود الدرج والنهوض والانتقال إلى الكرسي المتحرك أو السرير.',
    purpose: 'وصف مستوى الوظيفة الحركية للأطراف السفلية ومتابعة فقدان الوظيفة في الأمراض العصبية العضلية ضمن سياق سريري وبحثي.',
    construct: 'الوظيفة الحركية للأطراف السفلية في الأمراض العصبية العضلية',
    populations: ['أشخاص مصابون بحثل دوشين وأنواع أخرى من الأمراض العصبية العضلية عندما يكون المقياس مناسبًا', 'دراسات المتابعة الوظيفية والتأهيل'],
    settings: ['الأعصاب العضلية', 'العلاج الطبيعي', 'التأهيل', 'البحوث السريرية'],
    categories: ['mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'تصنيف سريري واحد يعتمد على أعلى مستوى وظيفي موصوف وفق مراسي Vignos الأصلية، مع توثيق استخدام الأجهزة والمساعدة.',
    administrationTime: 'دقائق قليلة بعد الملاحظة/الفحص الوظيفي.',
    equipment: ['مرجع مراسي Vignos', 'معلومات عن المشي والدرج والنهوض والأجهزة المساعدة'],
    scoring: 'تصنيف رتبي من مستويات متزايدة تعكس فقدًا أكبر لوظيفة الطرفين السفليين؛ لا يعامل الفرق بين كل درجتين كمسافة كمية متساوية.',
    interpretation: 'ارتفاع الدرجة يدل على محدودية أكبر في وظيفة الطرفين السفليين. يفضل دمجه مع اختبارات أداء ومقاييس أحدث متعددة الأبعاد لأن Vignos لا يلتقط القوة أو وظيفة الطرف العلوي أو التنفس بصورة مباشرة.',
    limitations: ['مقياس رتبي خشن وقد لا يلتقط تغيرات صغيرة.', 'يركز على الطرف السفلي ولا يمثل الوظيفة الكلية.', 'قد تتأثر الدرجة باستخدام أجهزة مساعدة أو استراتيجيات تعويضية.', 'قد تكون مقاييس حديثة أكثر حساسية للتغير في بعض الأمراض.'],
    administrationSteps: ['حدد النسخة والمراسي المرجعية.', 'راقب أو تحقق من المشي وصعود الدرج والنهوض والحاجة للمساعدة.', 'اختر الوصف المطابق دون استنتاج درجات وسطية غير موجودة.', 'وثق الأجهزة المساعدة والسياق.', 'استخدم المقياس مع مؤشرات أداء أخرى للمتابعة.'],
    safetyNotes: ['لا تطلب تجربة درج أو نهوض غير آمن فقط من أجل الحصول على الدرجة.', 'خطر السقوط والإجهاد التنفسي أو القلبي مقدم على استكمال المقياس.', 'لا تستخدم Vignos وحده لتحديد فقدان أهلية العلاج أو التأهيل.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Vignos Lower Extremity Rating Scale بحالة Public Domain. أي صور أو جداول معاد تصميمها أو ترجمات تابعة لناشرين آخرين مستقلة حقوقيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف وظيفي قابل للتوطين مع تثبيت المراسي',
    arabicNote: 'يمكن شرح المراسي بالعربية، لكن أي نسخة تشغيلية يجب أن تحافظ على ترتيب الدرجات وتعريفاتها وعلى طريقة التعامل مع المساعدة والأجهزة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يعرض كمرجع سريري وتاريخي دون تحويله إلى اختبار أداء ذاتي غير مراقب.',
    sources: [
      { label: 'CDISC QRS — Vignos Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/vignos-lower-extremity-rating-scale', role: 'rights' },
      { label: 'PubMed — relationship of Vignos/Brooke functional loss in neuromuscular disease', url: 'https://pubmed.ncbi.nlm.nih.gov/3800628/', role: 'evidence' },
      { label: 'PubMed — muscular dystrophy functional scale validation with Vignos correlation', url: 'https://pubmed.ncbi.nlm.nih.gov/17005504/', role: 'evidence' },
    ],
    related: ['6-minute-walk-test', 'four-stair-ascend', 'four-stair-descend'],
  },
  {
    slug: 'west-haven-hepatic-encephalopathy-grade',
    nameAr: 'درجة ويست هيفن للاعتلال الدماغي الكبدي',
    nameEn: 'West Haven Hepatic Encephalopathy Grade',
    acronym: 'WEST HAVEN',
    version: 'West Haven Criteria / CDISC QRS',
    summary: 'تصنيف سريري لشدة الاعتلال الدماغي الكبدي الظاهر اعتمادًا على التغيرات الذهنية والسلوكية والعصبية، ويستخدم ضمن تقييم تشخيصي يستبعد الأسباب الأخرى لاضطراب الوعي.',
    purpose: 'وصف شدة مظاهر الاعتلال الدماغي الكبدي والتواصل حولها ومتابعتها ضمن سياق مرض الكبد.',
    construct: 'شدة الاعتلال الدماغي الكبدي السريري الظاهر',
    populations: ['مرضى تشمع/مرض كبد مع اشتباه اعتلال دماغي كبدي ظاهر', 'سياقات البحث والرعاية التي تستخدم West Haven مع تشخيص تفريقي مناسب'],
    settings: ['أمراض الكبد', 'الجهاز الهضمي', 'العناية الحثيثة', 'الطوارئ', 'الباطني'],
    categories: ['hepatology-liver-disease', 'gastroenterology', 'critical-care'],
    administrationMode: 'تقييم سريري للحالة العقلية والسلوك واليقظة والعلامات العصبية ثم تعيين الدرجة وفق مراسي West Haven، مع استخدام GCS عند الغيبوبة/الاضطراب الشديد حسب الإرشادات.',
    administrationTime: 'دقائق ضمن الفحص السريري، مع إعادة التقييم بعد علاج العوامل المحرضة أو تغير الحالة.',
    equipment: ['فحص عصبي وعقلي سريري', 'مرجع West Haven', 'بيانات سريرية لاستبعاد أسباب أخرى لاضطراب الوعي'],
    scoring: 'تصنف الشدة عادة من دون اضطراب ظاهر إلى درجات متزايدة حتى الغيبوبة. يجب الحفاظ على تعريفات المراسي وعدم استخدام الأمونيا وحدها لتعيين الدرجة.',
    interpretation: 'الدرجة الأعلى تعكس اضطرابًا سريريًا أشد، لكنها لا تثبت أن سبب الاضطراب هو الكبد وحده. AASLD/EASL تؤكد ضرورة استبعاد الأسباب الأخرى، وتعتبر West Haven أداة لتصنيف overt HE لا لاكتشاف كل covert HE.',
    limitations: ['المراسي السريرية تحمل عنصرًا ذاتيًا واختلافًا بين المقيمين.', 'الأدوية والإنتان والنزف واضطرابات الاستقلاب والسكتة وغيرها قد تحاكي HE.', 'لا يعتمد تشخيص أو تصنيف HE على الأمونيا وحدها.', 'الدرجات الخفيفة قد تكون أقل موثوقية وتتطلب أدوات إضافية في covert/minimal HE.'],
    administrationSteps: ['أكد وجود مرض كبدي وسياق يجعل HE احتمالًا معقولًا.', 'ابحث عن أسباب أخرى أو عوامل محرضة لاضطراب الدماغ بالتوازي.', 'قيّم اليقظة والسلوك والإدراك والعلامات العصبية.', 'عين درجة West Haven بالمراسي المحددة واستخدم GCS عندما يلزم في الاضطراب الشديد.', 'أعد التقييم بعد التدخلات ووثق العوامل المحرضة والاستجابة.'],
    safetyNotes: ['تغير الوعي في مريض كبد حالة تستوجب تقييمًا عاجلًا ولا يجوز افتراض أنه HE قبل استبعاد أسباب خطرة أخرى.', 'لا تستخدم مستوى الأمونيا وحده لتشخيص أو نفي أو تحديد درجة HE.', 'لا تستخدم West Haven وحده لتقرير الزراعة أو سحب العلاج أو مستوى الرعاية.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج West Haven Hepatic Encephalopathy Grade بحالة Public Domain. نصوص الإرشادات والجداول المنشورة من الجمعيات العلمية تبقى مستقلة حقوقيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف سريري قابل للتوطين مع تدريب على المراسي والتشخيص التفريقي',
    arabicNote: 'المصطلحات قابلة للشرح بالعربية، لكن الاستخدام السريري يحتاج تعريفات ثابتة وتدريبًا لأن الاختلاف بين المقيمين خاصة في الدرجات الخفيفة ممكن.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يعرض الدليل والمراسي المنهجية دون اختزال تشخيص HE إلى جدول آلي.',
    sources: [
      { label: 'CDISC QRS — West Haven Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/west-haven-hepatic-encephalopathy-grade', role: 'rights' },
      { label: 'AASLD/EASL — Hepatic Encephalopathy in Chronic Liver Disease guideline', url: 'https://www.aasld.org/practice-guidelines/hepatic-encephalopathy', role: 'original' },
      { label: 'PubMed — HESA comparison with West Haven Criteria', url: 'https://pubmed.ncbi.nlm.nih.gov/17710551/', role: 'evidence' },
    ],
    related: ['child-pugh-classification', 'model-for-end-stage-liver-disease', 'glasgow-coma-scale-ninds'],
  },
];
