import type { AssessmentMeasure } from '@/lib/assessment-measures';

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';

export const assessmentMeasuresWave11: AssessmentMeasure[] = [
  {
    slug: 'ascvd-pooled-cohort-equations-10-year-risk',
    nameAr: 'مقدّر خطر ASCVD لعشر سنوات — معادلات المجموعات المجمعة',
    nameEn: 'Atherosclerotic Cardiovascular Disease 10-Year Risk Estimator — Pooled Cohort Equations',
    acronym: 'ASCVD PCE',
    version: '2013 ACC/AHA Pooled Cohort Equations / CDISC QRS Version 1.0 — legacy clinical model in 2026',
    summary: 'نموذج تاريخي واسع الاستخدام لتقدير خطر احتشاء القلب أو الوفاة القلبية التاجية أو السكتة خلال عشر سنوات في الوقاية الأولية. أصبح مرجعًا legacy في 2026 بعد أن أوصت إرشادات ACC/AHA الحديثة باستخدام PREVENT-ASCVD بدل PCE لتوجيه خفض الدهون لدى البالغين المناسبين.',
    purpose: 'تفسير الدراسات والسجلات والقرارات التاريخية المبنية على PCE، وإتاحة مقارنة منهجية مع نماذج خطر أحدث دون تقديمه كحاسبة علاجية معاصرة عامة.',
    construct: 'خطر ASCVD لمدة عشر سنوات وفق Pooled Cohort Equations التاريخية',
    populations: ['بالغون في الوقاية الأولية ضمن شروط ونطاقات نموذج PCE الأصلي', 'الدراسات والسجلات التي تستخدم أو تبلغ ASCVD PCE'],
    settings: ['أمراض القلب', 'الرعاية الأولية', 'الوقاية', 'البحوث السكانية'],
    categories: ['cardiovascular-risk'],
    administrationMode: 'حساب متعدد المتغيرات وفق معادلات PCE المحددة باستخدام العمر والجنس والعرق كما صيغ تاريخيًا والكوليسترول وضغط الدم وعلاج الضغط والسكري والتدخين.',
    administrationTime: 'دقائق بعد توفر المتغيرات الصحيحة، لكن اختيار النموذج المناسب يسبق الحساب نفسه.',
    equipment: ['بيانات عوامل الخطر المحددة في PCE', 'قياسات ضغط ودهون موثوقة', 'مرجع الصيغة/الإصدار', 'إرشادات حديثة لتحديد ما إذا كان PCE مناسبًا أصلًا'],
    scoring: 'تطبق معاملات Pooled Cohort Equations للإصدار الأصلي لإنتاج احتمال 10 سنوات. لا يجوز مزج معاملات PCE مع PREVENT أو Framingham أو ASSIGN أو نقل عتبات قرار من نموذج لآخر.',
    interpretation: 'النتيجة احتمال إحصائي تاريخي مشروط بالسكان والمعايرة. في إرشاد ACC/AHA 2026 لإدارة اضطراب الدهون، تُستخدم PREVENT-ASCVD بدل PCE لتوجيه العلاج في الوقاية الأولية للبالغين 30–79 سنة ضمن النطاق المحدد.',
    limitations: ['PCE نموذج أقدم وقد يسيء المعايرة في مجتمعات أو أزمنة مختلفة عن عينات الاشتقاق.', 'تقسيمات العرق في النموذج التاريخي لا تمثل كل السكان ولا ينبغي إسقاطها آليًا على مجتمعات الشرق الأوسط وشمال أفريقيا.', 'إرشادات ACC/AHA 2026 استبدلته بـPREVENT-ASCVD في قرارات خفض الدهون الأولية.', 'النموذج لا يشمل بعض محددات الخطر الحديثة التي تستخدم في التخصيص أو إعادة التصنيف.'],
    administrationSteps: ['أكد أن الغرض هو تفسير/مقارنة PCE لا تطبيق توصية 2026 تلقائيًا.', 'ثبت الإصدار والمتغيرات والوحدات ونطاق العمر.', 'احسب النتيجة فقط بأداة أو معادلة موثقة للصيغة الأصلية.', 'وثق أن الناتج PCE legacy وليس PREVENT-ASCVD.', 'عند اتخاذ قرار سريري حالي ارجع إلى الإرشاد المعاصر والسكان والسياق الفردي.'],
    safetyNotes: ['لا تنشر روافد حاسبة ASCVD/PCE عامة لتوجيه علاج خفض الدهون في 2026؛ إرشادات ACC/AHA الحديثة توصي PREVENT-ASCVD بدل PCE لهذا الغرض.', 'لا تستخدم النتيجة لنفي أعراض قلبية حادة أو لتأخير تقييمها.', 'لا تفترض صلاحية المعايرة في السكان العرب دون تحقق محلي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Atherosclerotic Cardiovascular Disease 10-Year Risk Estimator بحالة Public Domain. التطبيقات التجارية والواجهات والمواد الإرشادية التابعة لجهات أخرى لها شروطها الخاصة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'المتغيرات قابلة للتوطين؛ المعايرة السكانية ليست ترجمة لغوية',
    arabicNote: 'تعريب أسماء المتغيرات لا يجعل PCE صالحًا تلقائيًا لسكان عرب. المشكلة الأساسية في هذا النموذج هي الملاءمة والمعايرة والسياق الزمني، لا اللغة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تعرض روافد الشرح التاريخي والمنهجي ولا تقدم حاسبة علاجية عربية لهذا النموذج legacy.',
    sources: [
      { label: 'CDISC QRS — ASCVD 10-Year Risk Estimator Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: '2013 ACC/AHA guideline — development and use of Pooled Cohort Equations', url: 'https://www.jacc.org/doi/10.1016/j.jacc.2013.11.005', role: 'original' },
      { label: 'AHA 2026 Dyslipidemia Guideline — PREVENT replaces older PCE for current primary-prevention risk assessment', url: 'https://professional.heart.org/en/science-news/2026-guideline-on-the-management-of-dyslipidemia/top-things-to-know', role: 'evidence' },
    ],
    related: ['framingham-cvd-10-year-risk', 'assign-cardiovascular-risk-score'],
  },
  {
    slug: 'barnes-akathisia-rating-scale',
    nameAr: 'مقياس بارنز لتقدير الأكاثيزيا',
    nameEn: 'Barnes Akathisia Rating Scale',
    acronym: 'BARS',
    version: 'Barnes Akathisia Rating Scale / CDISC QRS Version 2.0',
    summary: 'مقياس سريري مختصر يجمع الملاحظة الموضوعية للتململ مع الشعور الذاتي بالحاجة للحركة والضيق المرتبط بها، ويستخدم لتوصيف شدة الأكاثيزيا الدوائية خصوصًا مع مضادات الذهان.',
    purpose: 'اكتشاف وتوصيف شدة الأكاثيزيا ومتابعة تغيرها مع العلاج أو تعديل الدواء ضمن تقييم سريري أوسع للآثار الحركية الجانبية.',
    construct: 'الأكاثيزيا الدوائية: التململ الحركي والخبرة الذاتية والضيق',
    populations: ['الأشخاص المعرضون لأكاثيزيا مرتبطة بالأدوية، خاصة مضادات الذهان', 'الدراسات النفسدوائية ومراقبة الآثار الجانبية الحركية'],
    settings: ['الطب النفسي', 'الصيدلة السريرية', 'العيادات النفسية', 'البحوث النفسدوائية'],
    categories: ['movement-disorders', 'mental-health'],
    administrationMode: 'ملاحظة سريرية منظمة يتبعها سؤال مباشر عن الشعور الداخلي بالتململ والضيق، ثم تقدير عالمي للشدة وفق مراسي BARS.',
    administrationTime: 'نحو 5 دقائق عادةً عند معرفة طريقة التطبيق.',
    equipment: ['مراسي BARS المحددة', 'مكان يسمح بملاحظة الجلوس والوقوف والحركة', 'فاحص قادر على التفريق بين الأكاثيزيا والقلق والهياج واضطرابات الحركة الأخرى'],
    scoring: 'تسجل المكونات الموضوعية والذاتية والضيق والتقدير العالمي وفق المراسي الأصلية. لا ينبغي إنشاء مجموع جديد غير معياري أو استبدال التقدير العالمي بجمع آلي للبنود.',
    interpretation: 'ارتفاع التقديرات يعكس تململًا/أكاثيزيا أشد، لكن تشخيص السبب يحتاج مراجعة توقيت الأدوية والجرعات والأعراض التفريقية مثل القلق والهياج ومتلازمة تململ الساقين.',
    limitations: ['قد يصعب التقييم عند ضعف القدرة على التواصل أو الاضطراب المعرفي.', 'التململ الحركي غير نوعي وقد ينتج عن أسباب أخرى.', 'يتطلب معرفة بالمراسي وبالتفريق السريري للآثار خارج الهرمية.', 'لا يقيس كل اضطرابات الحركة الدوائية؛ AIMS مثلًا يستهدف خلل الحركة المتأخر بدرجة أكبر.'],
    administrationSteps: ['راجع الأدوية وتوقيت بدء/تغير الأعراض.', 'راقب المريض في الجلوس والوقوف والحركة وفق بروتوكول BARS.', 'اسأل عن الشعور الداخلي بالحاجة للحركة والضيق.', 'سجل كل عنصر والتقدير العالمي دون اختراع مجموع غير معياري.', 'فسر النتيجة مع الفحص الدوائي والعصبي والنفسي.'],
    safetyNotes: ['الأكاثيزيا الشديدة قد ترتبط بضيق شديد واندفاع أو أفكار إيذاء النفس؛ وجود خطر نفسي حاد يتطلب تقييم سلامة مباشرًا ولا ينتظر استكمال المقياس.', 'لا تستخدم BARS وحده لتغيير أو إيقاف مضاد الذهان دون تقييم سريري لمخاطر وفوائد العلاج.', 'فرّق بين الأكاثيزيا والهياج أو القلق قبل نسبة الأعراض إلى الدواء.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Barnes Akathisia Rating Scale بحالة Public Domain. المقالة الأصلية وشروح الناشرين أو المواد التدريبية التابعة لطرف ثالث تبقى مستقلة حقوقيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لا توجد لدى روافد نسخة عربية معيارية محققة محددة',
    arabicNote: 'المعنى السريري قابل للشرح بالعربية، لكن مراسي الخبرة الذاتية والضيق تحتاج ترجمة معيارية واختبار اتفاق المقيمين قبل اعتماد نموذج عربي كامل.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يعرض الدليل المنهجي ولا ينشر ترجمة عربية كاملة غير محققة للمراسي.',
    sources: [
      { label: 'CDISC QRS — BARS Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/barnes-akathisia-rating-scale', role: 'rights' },
      { label: 'PubMed — original Barnes rating scale for drug-induced akathisia', url: 'https://pubmed.ncbi.nlm.nih.gov/2574607/', role: 'original' },
      { label: 'PubMed — BARS review and established reliability/validity', url: 'https://pubmed.ncbi.nlm.nih.gov/14870947/', role: 'evidence' },
    ],
    related: ['abnormal-involuntary-movement-scale', 'clinical-global-impression'],
  },
  {
    slug: 'brooke-upper-extremity-rating-scale',
    nameAr: 'مقياس بروك لوظيفة الأطراف العلوية',
    nameEn: 'Brooke Upper Extremity Rating Scale',
    acronym: 'BUERS',
    version: 'Brooke Upper Extremity Rating Scale / CDISC QRS',
    summary: 'تصنيف رتبي بسيط لوظيفة الطرفين العلويين طُور في الأمراض العصبية العضلية، ويستخدم خصوصًا في الحثل العضلي لتوصيف القدرة الوظيفية من رفع الذراعين واليدين إلى فقدان الوظيفة المتقدمة.',
    purpose: 'توصيف وظيفة الطرفين العلويين ومتابعة التدهور أو الاستقرار في الأمراض العصبية العضلية ضمن تقييم متعدد الأبعاد.',
    construct: 'الوظيفة الحركية للطرفين العلويين في الأمراض العصبية العضلية',
    populations: ['أشخاص مصابون بحثل دوشين وأمراض عصبية عضلية أخرى عندما يكون المقياس مناسبًا', 'برامج التأهيل والدراسات الطبيعية/العلاجية العصبية العضلية'],
    settings: ['الأعصاب العضلية', 'العلاج الطبيعي والوظيفي', 'التأهيل', 'البحوث السريرية'],
    categories: ['movement-disorders', 'rehabilitation-outcomes'],
    administrationMode: 'تصنيف سريري لأعلى مستوى وظيفي للطرف العلوي يطابق وصف المقياس، مع ملاحظة الأداء وتوثيق التعويضات أو المساعدة.',
    administrationTime: 'دقائق قليلة عادةً.',
    equipment: ['مراسي Brooke الأصلية', 'مساحة آمنة لملاحظة حركات الطرفين العلويين'],
    scoring: 'تختار الفئة الرتبية المطابقة للقدرة الوظيفية. الفئات ليست فواصل كمية متساوية ولا ينبغي اشتقاق درجات وسطية غير موجودة.',
    interpretation: 'ارتفاع الدرجة يعكس فقدًا أكبر لوظيفة الطرفين العلويين. يفيد في وصف المسار لكنه أقل حساسية من بعض المقاييس الحديثة متعددة المهام للتغيرات الصغيرة.',
    limitations: ['مقياس رتبي خشن وقد يظهر تأثيرات سقف/أرضية.', 'لا يقيس القوة العضلية مباشرة ولا كل مهارات اليد الدقيقة.', 'الحركات التعويضية قد تؤثر في التصنيف.', 'ينبغي دمجه مع مقاييس حديثة ووظيفة الطرف السفلي والتنفس حسب المرض.'],
    administrationSteps: ['ثبت نسخة Brooke ومراسيها.', 'لاحظ الأداء الوظيفي الفعلي دون دفع الشخص إلى حركة غير آمنة.', 'اختر الفئة الأقرب حرفيًا إلى الأداء.', 'وثق التعويضات والمساعدة والأجهزة إن وجدت.', 'قارن الاتجاه زمنيًا مع مؤشرات عصبية عضلية أخرى.'],
    safetyNotes: ['لا تطلب حركة تسبب ألمًا أو خطر سقوط أو إجهادًا غير مناسب فقط لإكمال التصنيف.', 'لا تستخدم BUERS وحده لتقرير أهلية علاج أو جهاز مساعد أو خدمات تأهيل.', 'التغير المفاجئ في القوة أو الوظيفة يحتاج تقييمًا سريريًا لسببه ولا يفسر من الدرجة وحدها.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Brooke Upper Extremity Rating Scale بحالة Public Domain. أي صور أو مخططات أو ترجمات منشورة من جهات أخرى منفصلة حقوقيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف وظيفي قابل للتوطين مع تثبيت المراسي',
    arabicNote: 'يمكن توطين وصف الوظائف بالعربية، لكن يجب الحفاظ على ترتيب الفئات ودلالتها وعدم إعادة تعريف المراسي بما يغير مستوى الوظيفة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يعرض كمرجع منهجي إلى أن تراجع صياغة عربية تشغيلية مع مختصي الأعصاب العضلية والتأهيل.',
    sources: [
      { label: 'CDISC QRS — Brooke Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/brooke-upper-extremity-rating-scale', role: 'rights' },
      { label: 'PubMed — upper-extremity functional rating in Duchenne muscular dystrophy', url: 'https://pubmed.ncbi.nlm.nih.gov/3827555/', role: 'evidence' },
    ],
    related: ['vignos-lower-extremity-rating-scale', '6-minute-walk-test'],
  },
  {
    slug: 'hamilton-depression-rating-scale-17',
    nameAr: 'مقياس هاملتون لتقدير الاكتئاب — 17 بندًا',
    nameEn: 'Hamilton Depression Rating Scale — 17 Item',
    acronym: 'HAMD-17',
    version: 'HAMD 17 / CDISC RS Version 2.1 (2026)',
    summary: 'النسخة ذات 17 بندًا من مقياس هاملتون السريري لتقدير شدة أعراض الاكتئاب، وهي صيغة شائعة جدًا في التجارب والبحوث وتختلف عن HAMD-24 الموجود في المكتبة من حيث مجموعة البنود وتفسير المجموع.',
    purpose: 'تقدير شدة أعراض الاكتئاب ومتابعة التغير في سياقات سريرية وبحثية تستخدم HAMD-17 صراحة.',
    construct: 'شدة أعراض الاكتئاب كما يقدرها فاحص سريري',
    populations: ['بالغون في سياقات تقييم ومتابعة الاكتئاب عندما تكون HAMD-17 هي النسخة المحددة', 'التجارب السريرية والبحوث النفسية'],
    settings: ['الطب النفسي', 'الصحة النفسية', 'التجارب السريرية', 'المتابعة العلاجية'],
    categories: ['mental-health'],
    administrationMode: 'مقابلة يطبقها فاحص مدرب ويقدر البنود السبعة عشر وفق مراسي HAMD-17 وتعليمات النسخة المستخدمة.',
    administrationTime: 'عادة نحو 15–30 دقيقة بحسب الخبرة وتعقيد الحالة.',
    equipment: ['مراسي HAMD-17 المحددة', 'فاحص مدرب', 'معلومات سريرية كافية عن الفترة المرجعية'],
    scoring: 'تسجل البنود وفق نطاقاتها المحددة وتجمع وفق HAMD-17. لا يجوز استخدام قواعد HAMD-24 أو HAMD-21 أو HAMD-6/7 على أنها النسخة نفسها.',
    interpretation: 'الدرجة الأعلى تعكس شدة أكبر لأعراض يلتقطها HAMD-17، لكن العتبات ومعايير الاستجابة/الهدأة تعتمد على البروتوكول والسياق ولا تقوم مقام التشخيص السريري.',
    limitations: ['ترجيح المقياس لأعراض النوم والجسد قد يؤثر في المقارنة بين أنماط الاكتئاب.', 'الثبات يعتمد على تدريب المقيمين والمقابلة المعيارية.', 'النسخ المختلفة من HAMD ليست قابلة للاستبدال الحسابي المباشر.', 'درجة الاكتئاب لا تمثل تقييمًا مستقلًا لخطر الانتحار رغم وجود بند متعلق به.'],
    administrationSteps: ['ثبت HAMD-17 تحديدًا لا نسخة أخرى من عائلة هاملتون.', 'طبق مقابلة ومراسي موحدة للفترة المرجعية.', 'سجل كل بند كما هو دون إعادة وزن محلية.', 'احسب مجموع HAMD-17 واحتفظ بدرجات البنود عند المتابعة.', 'فسر النتيجة مع التشخيص والوظيفة والسلامة والآثار العلاجية.'],
    safetyNotes: ['HAMD-17 ليس أداة مستقلة لتقييم خطر الانتحار؛ أي أفكار إيذاء النفس تستدعي تقييم سلامة مباشرًا وخطة مناسبة.', 'لا تستخدم المجموع وحده لبدء أو إيقاف علاج دوائي أو لتحديد تشخيص.', 'لا تنقل عتبات HAMD-17 إلى HAMD-24 أو HAMD-7 والعكس.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Hamilton Depression Rating Scale 17-Item بحالة Public Domain، مع RS Version 2.1 وADaM منشورين في 21 أبريل 2026. حقوق الترجمات أو أدلة التدريب التابعة لطرف ثالث منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'الدليل العربي المنشور الذي عثرنا عليه يخص HAMD-6/7 وليس HAMD-17 نفسه',
    arabicNote: 'توجد دراسات عربية لنسخ مختصرة مثل HAMD-6 وHAMD-7، ومنها تحقق HAMD-7 لدى 153 متحدثًا بالعربية في السعودية، لكن لا يجوز نقل صلاحية تلك الترجمات إلى بنود HAMD-17 السبعة عشر. يلزم تثبيت نسخة عربية خاصة بـHAMD-17 وخصائصها قبل نشرها.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد ترجمة HAMD-17 كاملة اعتمادًا على تحقق نسخة مختلفة من عائلة هاملتون.',
    sources: [
      { label: 'CDISC QRS — HAMD-17 Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/hamilton-depression-rating-scale-17-item', role: 'rights' },
      { label: 'CDISC all QRS — HAMD-17 RS v2.1 and ADaM released April 2026', url: 'https://www.cdisc.org/qrs/all', role: 'evidence' },
      { label: 'PubMed — Arabic HAMD-7 validation in Saudi Arabia; evidence cannot be transferred to HAMD-17', url: 'https://pubmed.ncbi.nlm.nih.gov/30210846/', role: 'translation' },
    ],
    related: ['hamilton-depression-rating-scale-24', 'clinical-global-impression'],
  },
  {
    slug: 'cdc-hiv-surveillance-stage-2014',
    nameAr: 'تصنيف مرحلة عدوى HIV للمراقبة الوبائية — CDC 2014',
    nameEn: 'CDC Revised Surveillance Case Definition for HIV Infection — 2014 Stage',
    acronym: 'CDC HIV STAGE 2014',
    version: 'CDC 2014 surveillance stages 0, 1, 2, 3, unknown — current CDC surveillance reference context',
    summary: 'تصنيف مراقبة وبائية أمريكي رسمي يضع حالات HIV المؤكدة في مرحلة 0 أو 1 أو 2 أو 3 أو غير معروفة استنادًا إلى توقيت العدوى المبكرة وCD4 والحالات المعرفة للمرحلة 3. صُمم للمراقبة السكانية وليس لاتخاذ قرارات علاج فردية.',
    purpose: 'توحيد تصنيف مرحلة HIV لأغراض المراقبة وتحليل مرحلة المرض عند التشخيص ومتابعة عبء HIV على مستوى السكان.',
    construct: 'مرحلة عدوى HIV لأغراض المراقبة الوبائية',
    populations: ['حالات HIV المؤكدة ضمن نظم المراقبة التي تتبع تعريف CDC 2014', 'تحليلات الصحة العامة والوبائيات لاستخدامات التصنيف السكاني'],
    settings: ['الصحة العامة', 'مراقبة الأمراض المعدية', 'وبائيات HIV', 'البحوث السكانية'],
    categories: ['infectious-disease-severity'],
    administrationMode: 'تصنيف يعتمد على تعريف حالة HIV المؤكدة، دليل عدوى مبكرة للمرحلة 0، وقيم CD4/النسبة أو مرض معرف للمرحلة 3 وفق قواعد CDC.',
    administrationTime: 'يعتمد على توفر سجلات الفحوص وCD4 والتشخيصات؛ التعيين الحسابي نفسه قصير بعد اكتمال البيانات.',
    equipment: ['نتائج اختبارات HIV المؤكدة وتواريخها', 'CD4 count أو percentage عند الحاجة', 'توثيق الحالات المعرفة للمرحلة 3', 'مرجع CDC 2014'],
    scoring: 'تصنف الحالة إلى stage 0 أو 1 أو 2 أو 3 أو unknown وفق تعريف CDC 2014. المرحلة 0 لها أولوية زمنية محددة، والمرحلة 3 يمكن أن تحددها حالة انتهازية معرفة حتى مع معلومات CD4 مختلفة ضمن قواعد التعريف.',
    interpretation: 'التصنيف يصف حالة المراقبة عند نقطة زمنية ويستخدم لتحليل عبء المرض ومرحلة التشخيص. CDC ينص صراحة على أنه ليس أساسًا لإدارة المريض سريريًا، وأن العلاج المضاد للفيروسات القهقرية لا يقرر من هذه المرحلة وحدها.',
    limitations: ['نظام مراقبة أمريكي وليس نظامًا عالميًا موحدًا للرعاية السريرية.', 'اكتمال التصنيف يعتمد على اكتمال الإبلاغ عن CD4 والتشخيصات.', 'المرحلة في بيانات المراقبة لا تعكس بالضرورة الحالة السريرية الحالية للشخص.', 'لا يستبدل إرشادات علاج HIV الحالية أو تقييم الحمل الفيروسي والمقاومة والأمراض المصاحبة.'],
    administrationSteps: ['أكد أن الغرض مراقبة وبائية لا قرار علاجي.', 'ثبت تشخيص HIV وفق تعريف الحالة المعتمد.', 'تحقق أولًا من شروط stage 0 والتوقيت.', 'استخدم CD4 count/percentage والحالات المعرفة للمرحلة 3 وفق ترتيب قواعد CDC.', 'وثق تاريخ المرحلة ومصدر البيانات ودرجة اكتمال التقارير.'],
    safetyNotes: ['لا تستخدم CDC HIV surveillance stage لتحديد بدء العلاج أو وقفه أو تأخيره؛ التعريف مخصص للمراقبة السكانية.', 'لا تعرض المرحلة كوصمة أو حكم على الشخص؛ استخدم لغة سريرية محترمة وبيانات ضرورية فقط.', 'بيانات HIV حساسة وتتطلب ضوابط خصوصية وصلاحيات وصول مناسبة في أي نظام تطبيقي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — مادة CDC اتحادية مع شروط النسبة وعدم الإيحاء بالتأييد',
    rightsNote: 'تنص سياسة CDC على أن معظم مواد الوكالة في المجال العام ويمكن استخدامها مع النسبة المناسبة، وعدم الإيحاء بتأييد CDC، وعدم تغيير المحتوى الجوهري. تستخدم روافد تعريف 2014 الرسمي كرابط مرجعي وتشرح التصنيف دون شعارات أو مواد طرف ثالث.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف مراقبة يمكن شرحه بالعربية مع الحفاظ على تعريفات CDC',
    arabicNote: 'التوطين هنا لغوي/منهجي؛ لا ينبغي تغيير الشروط الجوهرية أو الحدود الرقمية أو تعريفات الحالات عند عرض النسخة العربية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تعرض روافد شرحًا عربيًا منهجيًا مع الإحالة إلى CDC، لا نسخة تدعي أنها تعريف رسمي عربي صادر عن CDC.',
    sources: [
      { label: 'CDC — Use of Agency Materials / public-domain reuse conditions', url: 'https://www.cdc.gov/other/agencymaterials.html', role: 'rights' },
      { label: 'CDC MMWR — Revised Surveillance Case Definition for HIV Infection, United States, 2014', url: 'https://www.cdc.gov/mmwr/preview/mmwrhtml/rr6303a1.htm', role: 'original' },
      { label: 'CDC NHSS — stage at diagnosis continues to use the 2014 surveillance case definition', url: 'https://www.cdc.gov/hiv-data/nhss/index.html', role: 'evidence' },
    ],
    related: [],
  },
];
