import type { AssessmentMeasure } from '@/lib/assessment-measures';

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';

export const assessmentMeasuresWave2: AssessmentMeasure[] = [
  {
    slug: 'expanded-disability-status-scale',
    nameAr: 'مقياس كورتزكي الموسّع لحالة الإعاقة',
    nameEn: 'Kurtzke Expanded Disability Status Scale',
    acronym: 'EDSS',
    version: 'Kurtzke EDSS',
    summary: 'مقياس سريري رتبي واسع الاستخدام في التصلب المتعدد لتوصيف الإعاقة العصبية، ويُفسَّر مع درجات الأنظمة الوظيفية والفحص العصبي.',
    purpose: 'تقدير مستوى الإعاقة العصبية في التصلب المتعدد ومتابعة التغير بمرور الوقت ضمن تقييم سريري متخصص.',
    construct: 'الإعاقة العصبية في التصلب المتعدد',
    populations: ['الأشخاص المصابون بالتصلب المتعدد'],
    settings: ['طب الأعصاب', 'عيادات التصلب المتعدد', 'التجارب السريرية', 'بحوث النتائج'],
    categories: ['neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'تقييم سريري يعتمد على الفحص العصبي ودرجات الأنظمة الوظيفية والقدرة على المشي.',
    administrationTime: 'نحو 15–30 دقيقة وفق RMD والسياق السريري.',
    equipment: ['نموذج EDSS/FSS', 'أدوات الفحص العصبي المعتادة بحسب السياق'],
    scoring: 'درجة رتبية من 0 إلى 10، ترتفع مع زيادة الإعاقة؛ تتداخل درجات الأنظمة الوظيفية والقدرة على المشي في تحديد الدرجة. الفروق بين الدرجات ليست مسافات خطية متساوية.',
    interpretation: 'يُستخدم مع الفحص العصبي والسياق السريري؛ لا ينبغي تفسير تغير رقمي صغير بمعزل عن موثوقية القياس والمرحلة المرضية والمكوّن الوظيفي الذي تغيّر.',
    limitations: ['يميل الجزء المتوسط/المرتفع من السلم إلى إعطاء وزن كبير للمشي.', 'الاتفاق بين المقيمين يتفاوت، خصوصًا في بعض الأنظمة الوظيفية.', 'مقياس رتبي وليس قياسًا خطيًا مستمرًا.', 'لا يغطي كل ما يهم المريض من تعب وإدراك ومشاركة وجودة حياة.'],
    administrationSteps: ['إجراء تقييم عصبي منظم.', 'تحديد درجات الأنظمة الوظيفية أولًا.', 'تطبيق قواعد EDSS الرسمية وربطها بالقدرة على المشي والوظيفة.', 'توثيق التاريخ والمقيّم والسياق وأي تغير سريري مؤثر.'],
    safetyNotes: ['يتطلب معرفة عصبية سريرية؛ لا يُستخدم كأداة تشخيص ذاتي للتصلب المتعدد.', 'التدهور العصبي الحاد أو أعراض الانتكاس الجديدة تحتاج تقييمًا طبيًا ولا تنتظر إعادة القياس وحدها.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Kurtzke Expanded Disability Status Scale بحالة Public Domain، ويعرّف هذه الحالة بأن الأداة في المجال العام ولا يلزم إذن لاستخدامها. يجب عدم الخلط بين الأداة الأصلية وأي مواد تدريبية أو نسخ مترجمة لطرف ثالث.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج توثيقًا مستقلًا',
    arabicNote: 'لا تُنسب أي ترجمة عربية إلى EDSS كنسخة معتمدة قبل تحديد النص والدراسة وحقوق الترجمة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الشرح السريري والهيكل منشوران؛ النموذج العربي الكامل ينتظر مطابقة نسخة موثقة.',
    sources: [
      { label: 'RMD — Expanded Disability Status Scale & Kurtzke Functional Systems Score', url: 'https://www.sralab.org/rehabilitation-measures/expanded-disability-status-scale-kurtzke-functional-systems-score', role: 'evidence' },
      { label: 'CDISC QRS — EDSS Public Domain status', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['kurtzke-functional-systems-score', 'patient-determined-disease-steps', '10-meter-walk-test'],
  },
  {
    slug: 'kurtzke-functional-systems-score',
    nameAr: 'درجات كورتزكي للأنظمة الوظيفية',
    nameEn: 'Kurtzke Functional Systems Scores',
    acronym: 'KFSS',
    version: 'Kurtzke Functional Systems Scores',
    summary: 'تصنيف سريري للأنظمة العصبية الوظيفية يُستخدم مع EDSS في التصلب المتعدد لتوصيف مواضع وشدة الاختلال العصبي.',
    purpose: 'تقدير شدة الاختلال في أنظمة عصبية وظيفية متعددة وتوفير الأساس السريري لتحديد EDSS.',
    construct: 'الاختلال العصبي بحسب الأنظمة الوظيفية',
    populations: ['الأشخاص المصابون بالتصلب المتعدد'],
    settings: ['طب الأعصاب', 'عيادات التصلب المتعدد', 'بحوث النتائج'],
    categories: ['neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'فحص عصبي سريري وتصنيف أنظمة وظيفية متعددة.',
    administrationTime: 'يُجرى عادةً ضمن تقييم EDSS/FSS ويختلف حسب تعقيد الفحص.',
    equipment: ['نموذج KFSS/EDSS', 'معدات الفحص العصبي اللازمة'],
    scoring: 'تُقيَّم الأنظمة الوظيفية على سلالم رتبية خاصة بكل نظام؛ تُستخدم النتائج مع قواعد EDSS ولا ينبغي جمعها في مجموع محلي غير معتمد.',
    interpretation: 'يوضح نمط الاختلال العصبي أكثر من كونه درجة عالمية منفردة، ويحتاج إلى حكم عصبي سريري.',
    limitations: ['الاتفاق بين المقيمين ليس كاملًا.', 'الدرجات رتبية.', 'لا تمثل جودة الحياة أو المشاركة أو التعب بصورة مباشرة.'],
    administrationSteps: ['إجراء الفحص العصبي لكل نظام وظيفي.', 'اختيار الدرجة وفق التعريف القياسي لكل نظام.', 'توثيق أي عدم يقين أو عامل مؤثر في الفحص.', 'استخدام الدرجات مع EDSS عند الحاجة بدل اختراع مجموع جديد.'],
    safetyNotes: ['أداة فحص سريري متخصص وليست استبيانًا ذاتيًا.', 'أي عجز عصبي جديد أو متفاقم يحتاج تقييمًا طبيًا مناسبًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Kurtzke Functional Systems Scores بحالة Public Domain. حقوق أي ترجمة أو دليل تدريبي منفصل تُراجع بصورة مستقلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج توثيقًا مستقلًا',
    arabicNote: 'يجب تثبيت مصطلحات الأنظمة العصبية وتعريفات الدرجات في نسخة عربية واحدة قابلة للتتبع قبل نشر نموذج كامل.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا يُنشر نموذج عربي كامل قبل توثيق النسخة اللغوية.',
    sources: [
      { label: 'RMD — Expanded Disability Status Scale & Kurtzke Functional Systems Score', url: 'https://www.sralab.org/rehabilitation-measures/expanded-disability-status-scale-kurtzke-functional-systems-score', role: 'evidence' },
      { label: 'CDISC QRS — KFSS Public Domain status', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['expanded-disability-status-scale', 'patient-determined-disease-steps'],
  },
  {
    slug: 'mayo-portland-adaptability-inventory-4',
    nameAr: 'مخزون مايو–بورتلاند للتكيف — الإصدار الرابع',
    nameEn: 'Mayo-Portland Adaptability Inventory-4',
    acronym: 'MPAI-4',
    version: 'MPAI-4',
    summary: 'أداة من 35 بندًا لتوصيف الإعاقة والتكيف والقدرة والمشاركة بعد إصابة دماغية مكتسبة، ويمكن أن يجيب عنها المختص أو الشخص أو شخص مقرّب وفق السياق.',
    purpose: 'توصيف نتائج ما بعد المرحلة الحادة وفهم القدرة والتكيف والمشاركة وتقييم برامج التأهيل لإصابات الدماغ المكتسبة.',
    construct: 'القدرة والتكيف والمشاركة بعد إصابة الدماغ المكتسبة',
    populations: ['الأشخاص ذوو إصابة دماغية مكتسبة بعد عمر سنة'],
    settings: ['التأهيل ما بعد الحاد', 'العيادات الخارجية', 'برامج إعادة الاندماج المجتمعي', 'بحوث النتائج'],
    categories: ['brain-injury', 'participation', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير/تقدير من المختص أو الشخص أو شخص مقرّب؛ يفضّل توافق فريق التأهيل عند استخدام تقدير الفريق.',
    administrationTime: 'يختلف بحسب مصدر التقدير وتوافر المعلومات؛ RMD لا يحدد زمنًا واحدًا ثابتًا.',
    equipment: ['نموذج MPAI-4', 'تعليمات التسجيل المطابقة للإصدار'],
    scoring: 'تضم النسخة 35 بندًا؛ أول 29 بندًا تدخل في ثلاثة مؤشرات رئيسية، مع ستة بنود إضافية غير محسوبة في الدرجة الكلية. يلزم اتباع قواعد الإصدار نفسه وعدم خلط نسخ أو مصادر تقدير بلا توثيق.',
    interpretation: 'تُقرأ مؤشرات القدرة والتكيف والمشاركة والدرجة العامة مع مصدر التقدير والسياق؛ الاختلاف بين تقييم الشخص والأسرة والفريق قد يحمل معنى سريريًا ولا يُمحى تلقائيًا بالمتوسط.',
    limitations: ['نتائج مصادر التقدير المختلفة قد تختلف.', 'تحتاج معرفة جيدة بحالة الشخص حتى تكون الإجابات دقيقة.', 'لا تستبدل الاختبارات المعرفية أو الحركية المتخصصة.'],
    administrationSteps: ['تحديد من سيقوم بالتقدير ولماذا.', 'استخدام نفس الإصدار لجميع المقارنات.', 'تطبيق تعريفات الاستجابة وقواعد البنود كما في الدليل.', 'تسجيل مصدر التقدير والتاريخ والسياق.', 'فحص مؤشرات القدرة والتكيف والمشاركة بدل الاعتماد على رقم واحد فقط.'],
    safetyNotes: ['قد تكشف البنود عن مشكلات سلوكية أو نفسية أو دعم مجتمعي تحتاج متابعة منفصلة.', 'أي خطر مباشر على النفس أو الآخرين يتطلب مسار سلامة مستقلًا عن الدرجة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج MPAI-4 بحالة Public Domain. RMD يصف الأداة بأنها مجانية ويعرض بنيتها واستخداماتها، لكن حقوق أي ترجمة منشورة تبقى منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لم نثبت بعد نسخة عربية كاملة قابلة لإعادة النشر',
    arabicNote: 'تُراجع الترجمة والتكييف الثقافي وحقوق النص قبل عرض نموذج عربي كامل.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تتاح صفحة عربية موسعة عن الاستخدام والتسجيل، بينما تبقى البنود العربية الكاملة محجوبة حتى توثيق النسخة.',
    sources: [
      { label: 'RMD — Mayo-Portland Adaptability Inventory', url: 'https://www.sralab.org/rehabilitation-measures/mayo-portland-adaptability-inventory', role: 'evidence' },
      { label: 'CDISC QRS — MPAI-4 Public Domain status', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['disability-rating-scale', 'glasgow-outcome-scale-extended', 'chart-short-form'],
  },
  {
    slug: 'generalized-anxiety-disorder-7',
    nameAr: 'مقياس اضطراب القلق العام — 7 بنود',
    nameEn: 'Generalized Anxiety Disorder-7',
    acronym: 'GAD-7',
    version: 'original 7-item version',
    summary: 'أداة تقرير ذاتي من سبعة بنود لفحص شدة أعراض القلق العام خلال الأسبوعين السابقين ومتابعتها؛ لا تعمل كتشخيص مستقل.',
    purpose: 'فحص عبء أعراض القلق ومتابعتها ضمن تقييم سريري أوسع.',
    construct: 'أعراض القلق العام',
    populations: ['البالغون في الرعاية الأولية والصحة النفسية ومجتمعات سريرية متعددة'],
    settings: ['الرعاية الأولية', 'الصحة النفسية', 'البحوث', 'متابعة النتائج'],
    categories: ['mental-health', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير ذاتي أو مقابلة عند الحاجة؛ سبعة بنود عن الأسبوعين السابقين.',
    administrationTime: 'دقائق قليلة عادةً.',
    equipment: ['نسخة GAD-7 المطابقة للغة والإصدار المستخدم'],
    scoring: 'تُسجل البنود عادةً من 0 إلى 3 ويكون المجموع 0–21. درجات الشدة الشائعة أدوات تفسيرية للفحص وليست تشخيصًا بذاتها.',
    interpretation: 'ارتفاع الدرجة يشير إلى عبء أعراض أكبر ويبرر استكشافًا سريريًا بحسب السياق. لا تكفي الدرجة لإثبات اضطراب القلق العام أو استبعاد أسباب أخرى.',
    limitations: ['فحص أعراض لا تشخيص مستقل.', 'قد تتداخل أعراض القلق مع حالات نفسية وجسدية أخرى.', 'الترجمة والسياق والثقافة قد تؤثر في الخصائص القياسية.'],
    administrationSteps: ['تثبيت فترة الأسبوعين السابقين.', 'استخدام نسخة لغوية موثقة دون تعديل البنود أثناء التطبيق.', 'حساب المجموع وفق القاعدة الأصلية.', 'ربط النتيجة بالضيق والوظيفة والتقييم التفريقي عند الحاجة.'],
    safetyNotes: ['الأعراض الشديدة أو التدهور الوظيفي أو الخطر المصاحب تحتاج تقييمًا مهنيًا؛ الدرجة لا تحدد وحدها مستوى الطوارئ.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — النسخة الأصلية موثقة في CDISC QRS',
    rightsNote: 'CDISC يدرج Generalized Anxiety Disorder - 7 Item الأصلي بحالة Public Domain. يجب عدم الخلط مع GAD-7 Version 2 الذي يدرجه CDISC كـ Exempt from Copyright وتخضع استخداماته لشروط صاحب الحقوق.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد نسخ عربية ودراسات تحقق منشورة',
    arabicNote: 'وجود نسخة عربية متداولة لا يكفي؛ قبل نشر البنود كاملة نثبت نص النسخة ودراسة التحقق وحقوقها.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'يُنشر دليل عربي كامل للغرض والتطبيق والتفسير، بينما ينتظر نص البنود مطابقة نسخة عربية موثقة.',
    sources: [
      { label: 'CDISC QRS — GAD-7 original Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'RMD — PHQ-4 page referencing GAD-7 lineage and clinical use', url: 'https://www.sralab.org/rehabilitation-measures/four-item-patient-health-questionnaire-anxiety-and-depression', role: 'evidence' },
    ],
    related: ['patient-health-questionnaire-9', 'geriatric-depression-scale', 'satisfaction-with-life-scale'],
  },
  {
    slug: 'satisfaction-with-life-scale',
    nameAr: 'مقياس الرضا عن الحياة',
    nameEn: 'Satisfaction With Life Scale',
    acronym: 'SWLS',
    version: '5-item original scale',
    summary: 'مقياس قصير من خمسة بنود للتقييم المعرفي الذاتي للرضا العام عن الحياة، لا لقياس المزاج اللحظي أو تشخيص اضطراب نفسي.',
    purpose: 'قياس الرضا العام عن الحياة كجانب معرفي ذاتي من الرفاه وجودة الحياة.',
    construct: 'الرضا العام عن الحياة',
    populations: ['البالغون', 'كبار السن', 'مجتمعات عصبية وتأهيلية وصحية متعددة'],
    settings: ['البحوث', 'التأهيل', 'الصحة النفسية', 'متابعة جودة الحياة'],
    categories: ['participation', 'mental-health', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير ذاتي قصير من خمسة بنود.',
    administrationTime: 'دقائق قليلة عادةً.',
    equipment: ['نموذج SWLS بالنسخة اللغوية المحددة'],
    scoring: 'خمسة بنود تُجمع وفق سلم الاستجابة الأصلي؛ الدرجة الأعلى تدل على رضا أكبر عن الحياة. لا ينبغي تحويلها إلى تشخيص أو حكم شامل على الصحة النفسية.',
    interpretation: 'تُفهم الدرجة كحكم معرفي ذاتي على الرضا بالحياة، مع مراعاة الثقافة والظروف والسياق الزمني.',
    limitations: ['لا يقيس كل أبعاد جودة الحياة.', 'لا يحدد أسباب انخفاض الرضا.', 'قد تختلف الدلالات الثقافية والمعايير بين المجتمعات.'],
    administrationSteps: ['اختيار نسخة لغوية موثقة.', 'تقديم التعليمات الأصلية دون توجيه الإجابات.', 'حساب المجموع وفق النسخة المستخدمة.', 'تفسير النتيجة مع السياق بدل استعمالها كتسمية نفسية.'],
    safetyNotes: ['انخفاض الرضا لا يساوي اكتئابًا، ووجود خطر نفسي يُقيَّم بأدوات ومسارات مخصصة لا بدرجة SWLS وحدها.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Satisfaction With Life Scale بحالة Public Domain، كما يورد RMD أنها مجانية الاستخدام. النسخ المترجمة تراجع منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد دراسات عربية منشورة',
    arabicNote: 'يجب تثبيت النص العربي المحدد ومصدر الترجمة قبل إعادة نشر البنود.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'شرح الاستخدام والتفسير متاح؛ نص النسخة العربية الكاملة ينتظر التحقق الحقوقي واللغوي.',
    sources: [
      { label: 'RMD — Satisfaction With Life Scale', url: 'https://www.sralab.org/rehabilitation-measures/satisfaction-life-scale', role: 'evidence' },
      { label: 'CDISC QRS — SWLS Public Domain status', url: CDISC_QRS, role: 'rights' },
    ],
    related: ['generalized-anxiety-disorder-7', 'patient-health-questionnaire-9', 'chart-short-form'],
  },
  {
    slug: 'karnofsky-performance-scale',
    nameAr: 'مقياس كارنوفـسكي للأداء الوظيفي',
    nameEn: 'Karnofsky Performance Scale',
    acronym: 'KPS',
    version: '0–100 performance status scale',
    summary: 'مقياس سريري للحالة الوظيفية العامة والقدرة على النشاط والرعاية الذاتية، شائع خصوصًا في الأورام والرعاية التلطيفية والبحوث السريرية.',
    purpose: 'تلخيص مستوى الأداء الوظيفي والاعتماد العام ومتابعة تغيره في سياقات مرضية وعلاجية متعددة.',
    construct: 'الحالة الوظيفية العامة',
    populations: ['مرضى السرطان', 'مرضى الأمراض المزمنة والمتقدمة في بعض السياقات'],
    settings: ['الأورام', 'الرعاية التلطيفية', 'التجارب السريرية', 'المتابعة الوظيفية'],
    categories: ['rehabilitation-outcomes', 'participation'],
    administrationMode: 'تصنيف سريري مبني على الأداء والنشاط والحاجة إلى المساعدة.',
    administrationTime: 'دقائق قليلة عند توافر معلومات وظيفية كافية.',
    equipment: ['تعريفات الدرجات القياسية'],
    scoring: 'سلم من 0 إلى 100 على فواصل 10 نقاط؛ الدرجات الأعلى تشير إلى أداء واستقلال أكبر. يجب الحفاظ على تعريفات الدرجات وعدم تحويلها إلى نسبة احتمال أو تشخيص.',
    interpretation: 'مقياس عالمي للحالة الوظيفية، مفيد للتواصل والمتابعة، لكنه لا يحدد السبب ولا يغطي جودة الحياة أو الأعراض النوعية.',
    limitations: ['تصنيف واسع نسبيًا وقد يتأثر بحكم المقيّم.', 'لا يلتقط تفاصيل وظيفية دقيقة.', 'لا ينبغي اعتباره بديلًا عن تقييمات المجال المحددة.'],
    administrationSteps: ['جمع وصف حديث للنشاط والرعاية الذاتية والحاجة للمساعدة.', 'مطابقة الوصف مع تعريف الدرجة الأقرب.', 'توثيق تاريخ القياس والسياق والمقيّم.', 'استخدام مقاييس إضافية عند الحاجة لتفاصيل مجال محدد.'],
    safetyNotes: ['التدهور الوظيفي السريع يحتاج تقييمًا سريريًا لسببه ولا يُفسر كمجرد تغير رقمي في KPS.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Karnofsky Performance Scale بحالة Public Domain. أي نسخة مترجمة أو مادة تدريبية منشورة من جهة أخرى تراجع منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'translation-reported',
    arabicLabel: 'توجد استخدامات عربية؛ التحقق من نسخة موحدة مطلوب',
    arabicNote: 'لأن السلم يعتمد على تعريفات وصفية دقيقة، يجب تثبيت الصياغة العربية ومصدرها قبل نشر نموذج رسمي.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الصفحة تشرح السلم واستخدامه، أما الصياغة العربية الكاملة لدرجاته فتنتظر مراجعة النسخة.',
    sources: [
      { label: 'CDISC QRS — KPS Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'RMD — current rehabilitation measure directory', url: 'https://www.sralab.org/rehabilitation-measures', role: 'evidence' },
    ],
    related: ['eastern-cooperative-oncology-group-performance-status', '6-minute-walk-test'],
  },
  {
    slug: 'eastern-cooperative-oncology-group-performance-status',
    nameAr: 'مقياس الحالة الوظيفية لمجموعة الأورام التعاونية الشرقية',
    nameEn: 'Eastern Cooperative Oncology Group Performance Status',
    acronym: 'ECOG PS',
    version: 'ECOG performance status 0–5',
    summary: 'تصنيف سريري موجز للحالة الوظيفية في الأورام، يصف القدرة على النشاط والعمل والرعاية الذاتية والبقاء في السرير أو الكرسي.',
    purpose: 'توصيف الحالة الوظيفية العامة في رعاية الأورام والبحوث والتجارب السريرية.',
    construct: 'الحالة الوظيفية في الأورام',
    populations: ['مرضى السرطان'],
    settings: ['الأورام', 'التجارب السريرية', 'الرعاية التلطيفية', 'المتابعة'],
    categories: ['rehabilitation-outcomes', 'participation'],
    administrationMode: 'تصنيف سريري سريع يعتمد على مستوى النشاط والاعتماد.',
    administrationTime: 'دقائق قليلة.',
    equipment: ['تعريفات ECOG القياسية'],
    scoring: 'سلم رتبي من 0 إلى 5؛ 0 يمثل أداءً كاملًا و5 الوفاة. الدرجات ليست فواصل عددية متساوية ولا تُحوّل إلى نسبة مئوية.',
    interpretation: 'يُستخدم لوصف الأداء العام ودعم التواصل والبحث، لكن يجب ربطه بالحالة السريرية والأعراض وخطة الرعاية.',
    limitations: ['قد يختلف التقدير بين المقيمين.', 'سلم عالمي لا يشرح سبب العجز.', 'لا يغطي الأعراض أو جودة الحياة تفصيليًا.'],
    administrationSteps: ['تحديد النشاط الفعلي خلال الفترة السريرية ذات الصلة.', 'مطابقة الأداء مع تعريفات ECOG القياسية.', 'تسجيل الدرجة والتاريخ والسياق.', 'عدم استخدام الدرجة وحدها لاتخاذ قرار علاجي خارج الإرشادات والبروتوكول السريري.'],
    safetyNotes: ['أي تدهور سريع في الأداء عند مريض سرطان يستدعي تقييم السبب الطبي ولا يُختزل في الدرجة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Eastern Cooperative Oncology Group Performance Status بحالة Public Domain. يجب الحفاظ على تعريفات السلم وعدم نسب أي ترجمة عربية لطرف رسمي دون مصدر.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'translation-reported',
    arabicLabel: 'توجد استخدامات عربية؛ يلزم توحيد النسخة',
    arabicNote: 'يجب ربط الصياغة العربية المستخدمة بمصدر موثوق قبل نشرها كنسخة مرجعية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'شرح الدرجات والغرض منشور؛ الصياغة العربية الرسمية الكاملة تنتظر توثيق النسخة.',
    sources: [
      { label: 'CDISC QRS — ECOG Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'RMD — rehabilitation measure directory', url: 'https://www.sralab.org/rehabilitation-measures', role: 'evidence' },
    ],
    related: ['karnofsky-performance-scale', '6-minute-walk-test'],
  },
  {
    slug: 'patient-determined-disease-steps',
    nameAr: 'خطوات المرض التي يحددها المريض',
    nameEn: 'Patient Determined Disease Steps',
    acronym: 'PDDS',
    version: 'patient-reported disability steps',
    summary: 'مقياس تقرير ذاتي موجز للإعاقة في التصلب المتعدد يركز بدرجة كبيرة على القدرة على المشي واستخدام وسائل المساعدة.',
    purpose: 'توفير تقدير ذاتي سريع لمستوى الإعاقة/الحركة في التصلب المتعدد ومتابعته في الدراسات والرعاية.',
    construct: 'الإعاقة الحركية المبلغ عنها ذاتيًا في التصلب المتعدد',
    populations: ['الأشخاص المصابون بالتصلب المتعدد'],
    settings: ['عيادات التصلب المتعدد', 'البحوث', 'المتابعة المجتمعية', 'التأهيل'],
    categories: ['neurological-outcomes', 'mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير ذاتي باختيار الوصف الأقرب إلى الحالة الوظيفية.',
    administrationTime: 'دقائق قليلة.',
    equipment: ['نسخة PDDS المطابقة للإصدار/اللغة'],
    scoring: 'سلم رتبي من مستويات متدرجة للإعاقة الحركية؛ يجب استخدام تعريفات الفئات الأصلية وعدم تحويل السلم إلى قياس خطي أو نسبة.',
    interpretation: 'يُقرأ كتصنيف ذاتي للإعاقة، ويمكن مقارنته طوليًا عند ثبات النسخة والسياق. لا يستبدل EDSS أو الفحص العصبي عندما يكون التقييم السريري مطلوبًا.',
    limitations: ['يركز بدرجة كبيرة على المشي والتنقل.', 'تقرير ذاتي وقد يختلف عن تقدير الطبيب.', 'لا يغطي الأعراض غير الحركية بالكامل.'],
    administrationSteps: ['عرض أو قراءة الفئات وفق النسخة الموثقة.', 'اختيار الوصف الأقرب للحالة الحالية.', 'تسجيل الدرجة والوسيلة المساعدة إن كانت ذات صلة.', 'ربط النتيجة بالتقييم الأوسع عند وجود تغير مهم.'],
    safetyNotes: ['تدهور المشي الجديد أو السريع أو أعراض عصبية جديدة يحتاج تقييمًا طبيًا للتفريق بين الانتكاس وأسباب أخرى.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Patient Determined Disease Steps بحالة Public Domain. النسخة العربية نفسها تحتاج توثيق الترجمة قبل إعادة نشر نص الفئات.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج توثيقًا مستقلًا',
    arabicNote: 'لا نولد وصف الفئات بالعربية ثم نقدمه كنسخة رسمية دون تكييف وترجمة موثقة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'دليل الاستخدام متاح؛ نص الفئات العربي الكامل ينتظر توثيق النسخة.',
    sources: [
      { label: 'CDISC QRS — PDDS Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'RMD — Satisfaction With Life Scale evidence page citing PDDS in MS studies', url: 'https://www.sralab.org/rehabilitation-measures/satisfaction-life-scale', role: 'evidence' },
    ],
    related: ['expanded-disability-status-scale', 'kurtzke-functional-systems-score', '10-meter-walk-test'],
  },
];
