import type { AssessmentMeasure } from '@/lib/assessment-measures';

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';

export const assessmentMeasuresWave7: AssessmentMeasure[] = [
  {
    slug: 'sofa-27mar2024',
    nameAr: 'تقييم فشل الأعضاء المرتبط بالإنتان — SOFA 27MAR2024',
    nameEn: 'Sepsis-related Organ Failure Assessment 27MAR2024 Score',
    acronym: 'SOFA 27MAR2024',
    version: 'CDISC QRS RS v1.0 — 27MAR2024 construct',
    summary: 'نظام لتوصيف درجة اختلال ستة أجهزة عضوية في المرضى شديدي الاعتلال. يفيد في متابعة شدة اختلال الأعضاء على مستوى السياق السريري والبحثي، ولا يمثل حكمًا حتميًا على مآل فرد بعينه.',
    purpose: 'توحيد وصف اختلال الأعضاء في العناية الحثيثة والبحوث ومراقبة تغيره مع الزمن ضمن سياق سريري متكامل.',
    construct: 'شدة اختلال الأعضاء متعدد الأجهزة',
    populations: ['البالغون شديدو الاعتلال في العناية الحثيثة', 'دراسات الإنتان والاختلال العضوي وفق تعريفات النسخة المستخدمة'],
    settings: ['العناية الحثيثة', 'الطوارئ المتقدمة', 'بحوث الإنتان', 'بحوث شدة المرض'],
    categories: ['critical-care'],
    administrationMode: 'تجميع متغيرات سريرية ومخبرية محددة ثم تسجيل كل جهاز وفق قواعد النسخة المرجعية.',
    administrationTime: 'يعتمد على توفر القياسات المطلوبة؛ الحساب نفسه قصير بعد اكتمال البيانات.',
    equipment: ['بيانات التنفس والأكسجة', 'الصفائح', 'البيليروبين', 'ضغط الدم/الدعم الوعائي', 'تقييم عصبي', 'الكرياتينين أو معطيات الكلية حسب النسخة'],
    scoring: 'تسجل مكونات الأجهزة وفق جداول النسخة المحددة ثم تجمع. يجب تثبيت إصدار SOFA المستخدم وعدم خلط الجداول التاريخية أو التعديلات المحلية مع SOFA 27MAR2024.',
    interpretation: 'ارتفاع الدرجة أو ازديادها يعكس اختلالًا عضويًا أكبر في سياق المجموعة/المسار السريري، لكنه لا يحدد وحده التشخيص أو الإنذار الفردي أو قرار العلاج.',
    limitations: ['يتأثر بالتوقيت وبطريقة التقاط أسوأ/أقرب القيم.', 'بعض المكونات تتأثر بالعلاج نفسه مثل الدعم الوعائي والتهوية.', 'المعايرة والارتباط بالمآلات تختلف حسب السكان والسياق.', 'لا يجوز خلط النسخ دون توثيق.'],
    administrationSteps: ['ثبت نسخة SOFA المراد استخدامها والفترة الزمنية للقياسات.', 'اجمع القيم المطلوبة من مصدرها السريري الأصلي.', 'طبق قواعد التسجيل الخاصة بكل جهاز دون استنتاج قيم مفقودة.', 'وثق التوقيت والدعم العلاجي المصاحب.', 'فسر الدرجة ضمن السياق السريري وبالاشتراك مع بقية المعطيات.'],
    safetyNotes: ['لا تستخدم SOFA وحده لتشخيص الإنتان أو لاستبعاد العلاج أو لتقرير سحب الدعم الحيوي.', 'أي تدهور سريري حاد يحتاج استجابة فورية مستقلة عن الدرجة.', 'لا تحول روافد SOFA إلى حاسبة وفاة فردية أو أداة قرار علاجي حتمي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Sepsis-related Organ Failure Assessment 27MAR2024 Score بحالة Public Domain. يجب مع ذلك تثبيت النسخة والجداول المرجعية وعدم نسخ شروح طرف ثالث المحمية.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'التطبيق العربي يحتاج تثبيت نسخة ومصطلحات سريرية موحدة',
    arabicNote: 'يمكن شرح المفاهيم بالعربية، لكن أي نموذج عربي تشغيلي يجب أن يطابق حرفيًا تعريفات الإصدار المرجعي للمتغيرات والتسجيل.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننشر جدول تسجيل عربي كامل قبل مراجعة مطابقة النسخة 27MAR2024 بندًا ببند.',
    sources: [
      { label: 'CDISC QRS — SOFA 27MAR2024 Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — original SOFA description (1996)', url: 'https://pubmed.ncbi.nlm.nih.gov/8844239/', role: 'original' },
    ],
    related: ['apache-ii'],
  },
  {
    slug: 'model-for-end-stage-liver-disease',
    nameAr: 'نموذج مرض الكبد في المرحلة النهائية',
    nameEn: 'Model for End Stage Liver Disease',
    acronym: 'MELD',
    version: 'CDISC QRS MELD construct — distinguish from current MELD 3.0 allocation policy',
    summary: 'نظام تقدير شدة مرض الكبد ومخاطر الوفاة طُوّر تاريخيًا ثم أصبح أساسًا مهمًا لترتيب الأولوية في زراعة الكبد. المعادلات والسياسات تطورت، لذلك يجب تحديد الإصدار والجهة التنظيمية قبل أي استخدام تطبيقي.',
    purpose: 'وصف شدة مرض الكبد والتقسيم الطبقي للمخاطر ودعم أنظمة تخصيص الزراعة عندما يطبق ضمن السياسة الرسمية المعمول بها.',
    construct: 'شدة مرض الكبد ومخاطر الوفاة المرتبطة به',
    populations: ['مرضى الكبد المتقدمون', 'مرشحو زراعة الكبد وفق سياسة برنامج/نظام زراعة معتمد'],
    settings: ['أمراض الكبد', 'زراعة الكبد', 'البحوث السريرية'],
    categories: ['hepatology-liver-disease', 'gastroenterology'],
    administrationMode: 'حساب يعتمد على متغيرات مخبرية وقواعد إصدار محدد؛ سياسات تخصيص الأعضاء قد تضيف متغيرات وحدودًا واستثناءات.',
    administrationTime: 'قصير بعد توفر القيم المختبرية الصحيحة.',
    equipment: ['نتائج مختبرية حديثة وموثقة', 'مرجع الإصدار أو سياسة الزراعة الحالية'],
    scoring: 'لا توجد في روافد معادلة عامة واحدة باسم MELD. يجب التمييز بين MELD التاريخي وMELD-Na وMELD 3.0 وسياسات الجهات المختلفة، واستخدام الحاسبة الرسمية المعتمدة للسياق التنظيمي.',
    interpretation: 'الدرجة الأعلى تعكس عادة خطورة أكبر، لكن معناها العملي يعتمد على الإصدار والسياسة والسكان. ترتيب الزراعة قرار تنظيمي وسريري وليس نتيجة صفحة تعليمية.',
    limitations: ['تغيرت معادلات MELD وسياسات التخصيص عبر الزمن.', 'القيم المختبرية والتدخلات مثل الغسيل الكلوي تؤثر في القواعد حسب الإصدار.', 'لا تعكس الدرجة كل مضاعفات الكبد أو الاستثناءات السريرية.', 'المقارنة بين درجات محسوبة بإصدارات مختلفة غير صالحة مباشرة.'],
    administrationSteps: ['حدد الإصدار والغرض قبل الحساب.', 'تحقق من تاريخ القيم المختبرية ووحداتها.', 'استخدم الأداة الرسمية للجهة التنظيمية عند تخصيص عضو.', 'وثق الإصدار والسياسة المستخدمة مع الدرجة.', 'فسر النتيجة ضمن تقييم اختصاصي الكبد والزراعة.'],
    safetyNotes: ['لا تستخدم صفحة روافد لتحديد أهلية الزراعة أو ترتيب القائمة أو رفض الرعاية.', 'في الولايات المتحدة مثلًا تستخدم سياسات OPTN الحالية MELD 3.0، وليس الصيغة التاريخية وحدها.', 'أي قرار زراعة يجب أن يعتمد على نظام الزراعة الرسمي والاختصاصيين.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — MELD موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Model for End Stage Liver Disease بحالة Public Domain. هذا لا يعني أن جميع الحاسبات التجارية أو شروح الجهات أو السياسات التنظيمية قابلة للنسخ.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'المصطلحات قابلة للشرح عربيًا لكن التطبيق مرتبط بإصدار رسمي',
    arabicNote: 'لا توجد قيمة في ترجمة معادلة تاريخية بلا تحديد إصدارها. الأولوية هي توجيه المستخدم إلى السياسة والحاسبة الرسمية الحالية لسياقه.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد حاسبة MELD عامة بسبب اختلاف الإصدارات والسياسات التنظيمية.',
    sources: [
      { label: 'CDISC QRS — MELD Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — MELD/PELD application to liver allocation (2001)', url: 'https://pubmed.ncbi.nlm.nih.gov/11460223/', role: 'original' },
      { label: 'HRSA/OPTN — current liver policy and MELD 3.0 resources', url: 'https://www.hrsa.gov/optn/professionals/resources/liver-intestine', role: 'evidence' },
    ],
    related: ['apache-ii', 'sofa-27mar2024'],
  },
  {
    slug: 'assign-cardiovascular-risk-score',
    nameAr: 'درجة ASSIGN لمخاطر القلب والأوعية',
    nameEn: 'ASSIGN Risk Score',
    acronym: 'ASSIGN CVD 10-YEAR RISK',
    version: 'ASSIGN v2.0 context — Scottish cardiovascular risk model',
    summary: 'نموذج اسكتلندي لتقدير خطر أمراض القلب والأوعية خلال عشر سنوات، يتميز بإدخال الحرمان الاجتماعي والتاريخ العائلي ضمن عوامل الخطر. لا ينبغي نقله إلى سكان آخرين دون معايرة وتحقق.',
    purpose: 'تقدير مخاطر القلب والأوعية على مدى عشر سنوات في السكان الذين تتوافق خصائصهم مع النموذج وإصداره ومعايرته.',
    construct: 'خطر الإصابة بأمراض القلب والأوعية خلال عشر سنوات',
    populations: ['السكان الاسكتلنديون أو مجتمعات جرى التحقق من النموذج فيها', 'البالغون دون مرض قلبي وعائي سابق وفق شروط النسخة المستخدمة'],
    settings: ['الرعاية الأولية', 'الوقاية القلبية الوعائية', 'الصحة العامة', 'البحوث السكانية'],
    categories: ['cardiovascular-risk'],
    administrationMode: 'نموذج متعدد المتغيرات يعتمد على عوامل خطر سريرية واجتماعية محددة بحسب الإصدار.',
    administrationTime: 'دقائق عند توفر البيانات الصحيحة.',
    equipment: ['بيانات عوامل الخطر المطلوبة', 'تعريف الحرمان الاجتماعي المعتمد في النموذج', 'مرجع الإصدار والمعايرة'],
    scoring: 'يجب استخدام معادلة الإصدار المحدد ومعاملاته الرسمية. لا تنقل معاملات ASSIGN أو مؤشر الحرمان الاسكتلندي إلى بلد آخر على أنها صالحة تلقائيًا.',
    interpretation: 'الناتج تقدير احتمالي وليس يقينًا. قيمة الخطر تعتمد على المعايرة الزمنية والسكانية، وقد أظهرت أعمال تحديث حديثة أن النسخة الأصلية قد تبالغ في الخطر في بيانات أحدث.',
    limitations: ['مطور أساسًا من بيانات اسكتلندية.', 'مؤشر الحرمان الاجتماعي خاص بالسياق ويصعب نقله حرفيًا.', 'تتغير معدلات المرض مع الزمن فتحتاج النماذج إلى إعادة معايرة.', 'القرار الوقائي يعتمد على إرشادات وعوامل إضافية لا على الرقم وحده.'],
    administrationSteps: ['ثبت إصدار ASSIGN والسكان المقصودين.', 'اجمع المتغيرات بالتعريفات الصحيحة.', 'استخدم النموذج/الحاسبة الرسمية المعتمدة للسياق.', 'وثق الإصدار والمعايرة.', 'ناقش النتيجة ضمن الإرشاد الوقائي المناسب محليًا.'],
    safetyNotes: ['لا تستخدم ASSIGN لتقرير دواء أو حرمان شخص من علاج دون تقييم سريري وإرشادات محلية.', 'لا تحوّل روافد النموذج إلى حاسبة عربية عامة قبل وجود معايرة سكانية مناسبة.', 'التقدير لا يستبدل تقييم أعراض قلبية حادة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — ASSIGN موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج ASSIGN Risk Score بحالة Public Domain، بما في ذلك إصدار QRS v2.0. تبقى المواد التفسيرية والحاسبات التابعة لجهات أخرى خاضعة لشروطها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لا توجد معايرة عربية عامة معتمدة لدى روافد',
    arabicNote: 'ترجمة أسماء المتغيرات لا تجعل النموذج صالحًا لسكان عرب؛ يلزم تحقق ومعايرة محلية ومؤشر اجتماعي مناسب للسياق.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد حاسبة ASSIGN عربية عامة بلا تحقق ومعايرة محلية.',
    sources: [
      { label: 'CDISC QRS — ASSIGN Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — original ASSIGN model', url: 'https://pubmed.ncbi.nlm.nih.gov/17090561/', role: 'original' },
      { label: 'PubMed — ASSIGN version 2.0 recalibration/update', url: 'https://pubmed.ncbi.nlm.nih.gov/39819614/', role: 'evidence' },
    ],
    related: [],
  },
  {
    slug: 'four-stair-ascend',
    nameAr: 'اختبار صعود أربع درجات',
    nameEn: '4-Stair Ascend',
    acronym: '4-STAIR ASCEND',
    version: 'CDISC QRS FT v1.0',
    summary: 'اختبار أداء وظيفي موقّت يقيس القدرة على صعود أربع درجات وفق بروتوكول موحد، ويستخدم خصوصًا في تقييم الأمراض العصبية العضلية مثل الحثل العضلي الدوشيني.',
    purpose: 'قياس أداء صعود الدرج ومتابعة التغير الوظيفي الحركي بصورة قابلة للتكرار ضمن بروتوكول ثابت.',
    construct: 'أداء صعود الدرج ووظيفة الطرفين السفليين',
    populations: ['الأطفال واليافعون ذوو الاضطرابات العصبية العضلية وفق البروتوكول', 'أبحاث الأداء الحركي عندما يكون الاختبار مناسبًا وآمنًا'],
    settings: ['التأهيل', 'الأعصاب العضلية', 'التجارب السريرية'],
    categories: ['mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'اختبار أداء موقّت على أربع درجات بمواصفات وبداية ونهاية وتعليمات محددة.',
    administrationTime: 'ثوانٍ إلى دقائق شاملًا التحضير.',
    equipment: ['سلم من أربع درجات بالمواصفات المعتمدة', 'ساعة توقيت', 'إجراءات أمان ومراقب مؤهل'],
    scoring: 'يسجل زمن الأداء و/أو حالة عدم القدرة وفق البروتوكول المستخدم. لا تخلط أزمنة بروتوكولات تختلف في ارتفاع الدرج أو استخدام الدرابزين أو نقطة بدء/إيقاف التوقيت.',
    interpretation: 'الزمن الأقصر عادة يعكس أداء أسرع، لكن التغير يجب تفسيره ضمن العمر والمرض والبروتوكول والقدرة على إتمام المهمة.',
    limitations: ['حساسية كبيرة لاختلاف مواصفات الدرج والتوقيت.', 'قد يصبح الاختبار غير قابل للأداء مع تقدم الضعف.', 'لا يقيس كل جوانب الحركة أو التحمل.', 'المساعدة والدرابزين يغيران المقارنة.'],
    administrationSteps: ['تحقق من ثبات أبعاد الدرج والبروتوكول.', 'اشرح المهمة وقيّم الأمان قبل البدء.', 'طبق نقطة البداية والنهاية القياسيتين.', 'سجل الزمن وأي مساعدة أو عدم قدرة.', 'استخدم نفس الإعداد في المتابعة.'],
    safetyNotes: ['خطر السقوط يستلزم حراسة قريبة وإيقاف الاختبار عند عدم الأمان.', 'لا يُجرى الاختبار لمن لا يستطيع صعود الدرج بأمان وفق تقييم المختص.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج 4-Stair Ascend FT وADaM بحالة Public Domain. يجب توثيق البروتوكول التشغيلي وعدم افتراض أن كل مواد تدريب طرف ثالث قابلة لإعادة النشر.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'بروتوكول أداء قابل للتوطين مع تثبيت التعليمات',
    arabicNote: 'الاختبار أدائي؛ يمكن تقديم التعليمات بالعربية بعد تثبيت معنى الأوامر ونقطة التوقيت وعدم تغيير المهمة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا حاجة إلى ترجمة استبيان؛ المطلوب بروتوكول تشغيل عربي مضبوط قبل نشره كاملًا.',
    sources: [
      { label: 'CDISC QRS — 4-Stair Ascend Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — clinical relevance of timed stair performance in DMD', url: 'https://pubmed.ncbi.nlm.nih.gov/25539097/', role: 'evidence' },
      { label: 'PubMed — Delphi consensus on lower-extremity DMD outcome protocols', url: 'https://pubmed.ncbi.nlm.nih.gov/30562905/', role: 'evidence' },
    ],
    related: ['four-stair-descend', 'rising-from-floor', '6-minute-walk-test', '10-meter-walk-test'],
  },
  {
    slug: 'four-stair-descend',
    nameAr: 'اختبار نزول أربع درجات',
    nameEn: '4-Stair Descend',
    acronym: '4-STAIR DESCEND',
    version: 'CDISC QRS FT v1.0',
    summary: 'اختبار أداء وظيفي موقّت لنزول أربع درجات وفق بروتوكول ثابت، يفيد في متابعة وظيفة الطرفين السفليين والقدرة الحركية في الأمراض العصبية العضلية.',
    purpose: 'قياس أداء نزول الدرج ومتابعة تغيره بمرور الوقت ضمن نفس الإعداد والبروتوكول.',
    construct: 'أداء نزول الدرج والتحكم الحركي للطرفين السفليين',
    populations: ['الأطفال واليافعون ذوو الاضطرابات العصبية العضلية وفق البروتوكول', 'سياقات تأهيلية مختارة بعد تقييم الأمان'],
    settings: ['التأهيل', 'الأعصاب العضلية', 'التجارب السريرية'],
    categories: ['mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'مهمة نزول أربع درجات موقّتة مع تعليمات ومواصفات درج ثابتة.',
    administrationTime: 'ثوانٍ إلى دقائق شاملًا التحضير.',
    equipment: ['سلم من أربع درجات بالمواصفات المعتمدة', 'ساعة توقيت', 'حراسة أمان'],
    scoring: 'يسجل زمن إكمال المهمة وحالة عدم القدرة أو المساعدة وفق البروتوكول. يجب فصل النزول عن الصعود وعدم جمعهما في زمن واحد إلا إذا نص بروتوكول محدد على ذلك.',
    interpretation: 'الزمن ومقدار المساعدة يعكسان جانبًا من الأداء الوظيفي؛ تتطلب المقارنة ثبات الإعداد والبروتوكول.',
    limitations: ['نزول الدرج قد يكون أكثر حساسية للخوف من السقوط والتحكم اللامركزي.', 'اختلاف الدرابزين وارتفاع الدرج يغير النتيجة.', 'قد يصبح الاختبار غير آمن قبل فقدان القدرة على المشي بالكامل.'],
    administrationSteps: ['ثبّت الدرج ونقطة البداية والنهاية.', 'قيّم الأمان والحاجة للحراسة.', 'أعط التعليمات نفسها في كل زيارة.', 'سجل الزمن والمساعدة وأي توقف.', 'أوقف الاختبار إذا أصبح النزول غير آمن.'],
    safetyNotes: ['نزول الدرج يحمل خطر سقوط أعلى من كثير من الاختبارات الأرضية؛ السلامة تتقدم على استكمال القياس.', 'لا تفسر عدم القدرة كتشخيص منفرد أو كدليل على قرار علاجي محدد.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج 4-Stair Descend FT وADaM بحالة Public Domain. مواد التدريب أو الفيديوهات التابعة لجهات أخرى ليست ضمن هذا الحكم تلقائيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'بروتوكول أداء قابل للتوطين مع تثبيت التعليمات',
    arabicNote: 'التوطين يقتصر على تعليمات المهمة مع المحافظة على التعريف التشغيلي والتوقيت ومواصفات الدرج.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا يوجد استبيان نصي؛ يُنشر بروتوكول عربي كامل فقط بعد توثيق المواصفات التشغيلية.',
    sources: [
      { label: 'CDISC QRS — 4-Stair Descend Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — timed stair performance near gait loss in DMD', url: 'https://pubmed.ncbi.nlm.nih.gov/25539097/', role: 'evidence' },
      { label: 'PubMed — Delphi consensus on lower-extremity DMD outcomes', url: 'https://pubmed.ncbi.nlm.nih.gov/30562905/', role: 'evidence' },
    ],
    related: ['four-stair-ascend', 'rising-from-floor', '6-minute-walk-test'],
  },
  {
    slug: 'rising-from-floor',
    nameAr: 'اختبار النهوض من الأرض',
    nameEn: 'Rising From Floor',
    acronym: 'RISING FROM FLOOR',
    version: 'CDISC QRS FT v1.0',
    summary: 'اختبار أداء موقّت يقيس القدرة على الانتقال من الأرض إلى الوقوف، ويستخدم كعلامة وظيفية مهمة في المتابعة العصبية العضلية، خصوصًا في الحثل العضلي الدوشيني.',
    purpose: 'قياس سرعة وقدرة الانتقال من الأرض إلى الوقوف ومتابعة التغير الوظيفي بمرور الوقت.',
    construct: 'الانتقال الحركي الأرضي والقوة الوظيفية للطرفين السفليين والجذع',
    populations: ['الأطفال واليافعون المصابون بالحثل العضلي الدوشيني', 'اضطرابات عصبية عضلية أخرى عندما يكون البروتوكول مناسبًا'],
    settings: ['الأعصاب العضلية', 'التأهيل', 'التجارب السريرية'],
    categories: ['mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'مهمة موقّتة من وضع محدد على الأرض إلى الوقوف وفق تعريف تشغيلي ثابت.',
    administrationTime: 'ثوانٍ إلى دقائق.',
    equipment: ['سطح آمن وثابت', 'ساعة توقيت', 'مساحة كافية', 'حراسة عند الحاجة'],
    scoring: 'يسجل زمن النهوض وحالة عدم القدرة، ويمكن توثيق الاستراتيجية الحركية عندما ينص البروتوكول. يجب عدم خلط بروتوكولات تبدأ من أوضاع أرضية مختلفة.',
    interpretation: 'إطالة الزمن أو فقدان القدرة قد يعكس تدهورًا وظيفيًا في سياق المرض، لكن يجب دمجه مع 6MWT والاختبارات الأخرى والعمر والمسار السريري.',
    limitations: ['يتأثر بوضع البداية والتعليمات وسطح الأرض.', 'استراتيجيات التعويض قد تغير الزمن دون أن تعكس عاملًا فسيولوجيًا واحدًا.', 'عدم القدرة يخلق سقفًا للقياس.', 'البيانات الأقوى متاحة في DMD أكثر من كثير من المجتمعات الأخرى.'],
    administrationSteps: ['حدد وضع البداية والبروتوكول قبل القياس.', 'تأكد من أمان البيئة.', 'ابدأ وأنهِ التوقيت حسب التعريف المعتمد.', 'سجل الزمن أو عدم القدرة والاستراتيجية إذا كانت جزءًا من البروتوكول.', 'حافظ على نفس الإجراءات في المتابعة.'],
    safetyNotes: ['أوقف المهمة عند خطر السقوط أو الإجهاد غير الآمن.', 'لا تجبر المريض على المحاولة إذا فقد القدرة الوظيفية الآمنة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Rising From Floor FT وADaM بحالة Public Domain. حقوق أي مواد تدريب أو فيديوهات منفصلة تبقى مستقلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'اختبار أدائي قابل للتوطين مع توحيد البروتوكول',
    arabicNote: 'لا توجد بنود لغوية معقدة؛ التحدي هو توحيد الأمر ووضع البداية ونهاية التوقيت لا مجرد الترجمة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'سيُنشر بروتوكول عربي تفصيلي فقط بعد مراجعة التعريفات التشغيلية الرسمية.',
    sources: [
      { label: 'CDISC QRS — Rising From Floor Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — timed rise from floor predicts DMD progression', url: 'https://pubmed.ncbi.nlm.nih.gov/26982196/', role: 'evidence' },
      { label: 'PubMed — 2025 natural history of timed rise from floor in DMD', url: 'https://pubmed.ncbi.nlm.nih.gov/40680325/', role: 'evidence' },
    ],
    related: ['four-stair-ascend', 'four-stair-descend', '6-minute-walk-test', '10-meter-walk-test'],
  },
  {
    slug: 'harvey-bradshaw-index',
    nameAr: 'مؤشر هارفي–برادشو',
    nameEn: 'Harvey-Bradshaw Index',
    acronym: 'HBI',
    version: 'CDISC QRS RS v1.0',
    summary: 'مؤشر سريري مبسط لنشاط داء كرون يجمع الرفاه العام والألم البطني وعدد مرات البراز السائل والكتلة البطنية والمضاعفات، ويستخدم للمتابعة أكثر من كونه بديلًا عن التقييم الالتهابي الموضوعي.',
    purpose: 'تقدير النشاط السريري لداء كرون بصورة مبسطة ومتابعة التغير عبر الزيارات أو الدراسات.',
    construct: 'نشاط داء كرون السريري',
    populations: ['البالغون المصابون بداء كرون', 'سياقات سريرية وبحثية تستخدم تعريف HBI المحدد'],
    settings: ['أمراض الجهاز الهضمي', 'عيادات أمراض الأمعاء الالتهابية', 'البحوث السريرية'],
    categories: ['gastroenterology'],
    administrationMode: 'تقييم سريري مركب من عناصر أعراض وفحص/مضاعفات وفق نسخة HBI المحددة.',
    administrationTime: 'عدة دقائق ضمن الزيارة السريرية.',
    equipment: ['نموذج HBI المحدد', 'تاريخ سريري وفحص مناسب'],
    scoring: 'تجمع مكونات HBI وفق القواعد المرجعية. تختلف عتبات النشاط/الهدأة المستخدمة بين الدراسات، لذلك يجب توثيق العتبة والسياق بدل تقديم رقم واحد كقاعدة عالمية.',
    interpretation: 'الدرجة الأعلى تعكس نشاطًا سريريًا أكبر، لكنها لا تساوي وحدها التهابًا مخاطيًا أو نشاطًا بيولوجيًا ولا تستبدل المؤشرات المخبرية أو التنظير.',
    limitations: ['يعتمد جزئيًا على أعراض ذاتية.', 'قد تكون الأعراض ناجمة عن أسباب غير التهابية.', 'لا يقيس الشفاء المخاطي.', 'العتبات المستخدمة في الدراسات ليست متطابقة دائمًا.'],
    administrationSteps: ['أكد تشخيص وسياق داء كرون.', 'اجمع مكونات HBI وفق تعريفاتها.', 'سجل المضاعفات والفحص دون اختصار غير موثق.', 'احسب المجموع ودوّن العتبة التفسيرية المستخدمة.', 'قارنه بالمؤشرات الموضوعية والمسار السريري.'],
    safetyNotes: ['نزف أو انسداد محتمل أو ألم شديد أو حمى أو تدهور حاد يستلزم تقييمًا عاجلًا بغض النظر عن HBI.', 'لا تستخدم HBI وحده لبدء أو إيقاف علاج مناعي أو بيولوجي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Harvey-Bradshaw Index بحالة Public Domain. ePROVIDE يوضح أن عرض HBI كما ظهر في النشر الأصلي قد تكون له حقوق عرض لدى الناشر، بينما النسخ الأخرى ليست محمية بالطريقة نفسها؛ لذلك لا تنسخ تصميم الناشر.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية التشغيلية تحتاج مراجعة',
    arabicNote: 'يمكن ترجمة المفاهيم، لكن يجب تثبيت صياغة عناصر الأعراض والمضاعفات وطريقة التسجيل قبل استخدام نسخة عربية معيارية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا نعيد نشر تخطيط الناشر الأصلي ولا صياغة ترجمة عربية غير موثقة.',
    sources: [
      { label: 'CDISC QRS — HBI Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'ePROVIDE — HBI description and copyright nuance', url: 'https://eprovide.mapi-trust.org/instruments/harvey-bradshaw-index', role: 'original' },
      { label: 'PubMed — original Harvey-Bradshaw reference search', url: 'https://pubmed.ncbi.nlm.nih.gov/?term=Harvey+Bradshaw+simple+index+Crohn%27s+disease+1980', role: 'evidence' },
    ],
    related: ['crohns-disease-activity-index-v1'],
  },
  {
    slug: 'pain-relief-cdisc',
    nameAr: 'تقدير تخفيف الألم',
    nameEn: 'Pain Relief',
    acronym: 'PR',
    version: 'CDISC QRS QS v2.0',
    summary: 'مقياس تصنيفي بسيط يطلب من المريض تقدير مقدار تخفيف الألم بعد تدخل أو خلال فترة محددة، ويستخدم خصوصًا كمخرج في دراسات الألم الحاد والمسكنات.',
    purpose: 'قياس مقدار التخفيف المدرك للألم بطريقة قصيرة ومتكررة وربط الاستجابة بالتغير السريري أو العلاج.',
    construct: 'التخفيف الذاتي المدرك للألم',
    populations: ['البالغون القادرون على التقرير الذاتي', 'دراسات الألم الحاد والمزمن عند ملاءمة السؤال والفترة الزمنية'],
    settings: ['عيادات الألم', 'التجارب السريرية', 'الأورام والرعاية التلطيفية', 'الطوارئ وفق البروتوكول'],
    categories: ['pain-function', 'symptom-burden'],
    administrationMode: 'سؤال تقرير ذاتي قصير بدرجات تصنيفية من لا تخفيف إلى تخفيف كامل وفق النسخة المحددة.',
    administrationTime: 'أقل من دقيقة.',
    equipment: ['نسخة Pain Relief المحددة', 'فترة زمنية مرجعية واضحة'],
    scoring: 'في تطبيقات شائعة يسجل التخفيف على سلم رتبي من 0 إلى 4؛ يجب استخدام تسميات النسخة المرجعية وعدم افتراض تكافؤه مع شدة الألم أو نسبة التحسن الحسابية.',
    interpretation: 'الدرجة الأعلى تعكس تخفيفًا مدركًا أكبر. المقياس يقيس relief لا pain intensity، ولذلك قد لا يطابق الفرق العددي في شدة الألم عند كل مريض.',
    limitations: ['يتأثر بالتوقعات والذاكرة والسياق.', 'الرتب ليست بالضرورة فواصل متساوية.', 'لا يحدد سبب الألم أو سلامة العلاج.', 'قد تختلف الصياغة والفترة الزمنية بين البروتوكولات.'],
    administrationSteps: ['حدد الفترة المرجعية بوضوح.', 'استخدم نفس صياغة السؤال وخيارات الإجابة في كل مرة.', 'سجل الإجابة دون تحويل غير موثق إلى نسبة مئوية.', 'حللها مع شدة الألم والحاجة للإنقاذ والوظيفة عند الحاجة.'],
    safetyNotes: ['تحسن الألم لا يثبت سلامة السبب أو العلاج.', 'ألم جديد شديد أو أعراض إنذار تحتاج تقييمًا طبيًا مستقلًا عن درجة التخفيف.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Pain Relief بحالة Public Domain. أي واجهة أو ترجمة أو تعليمات مملوكة لطرف ثالث تبقى منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'صياغة عربية معيارية تحتاج تحققًا لغويًا',
    arabicNote: 'بساطة السلم لا تلغي ضرورة اختبار فهم الفروق بين قليل/متوسط/كثير/كامل في المجتمع المستهدف.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننشر صياغة عربية معيارية قبل التحقق من نسخة محددة وفهم درجاتها.',
    sources: [
      { label: 'CDISC QRS — Pain Relief Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — clinically important differences in pain outcome measures', url: 'https://pubmed.ncbi.nlm.nih.gov/11068116/', role: 'evidence' },
      { label: 'PubMed — validation of clinically important changes in acute pain measures', url: 'https://pubmed.ncbi.nlm.nih.gov/12727037/', role: 'evidence' },
    ],
    related: ['pain-intensity-cdisc'],
  },
  {
    slug: 'bode-index',
    nameAr: 'مؤشر BODE لمرض الانسداد الرئوي المزمن',
    nameEn: 'BODE Index',
    acronym: 'BODE INDEX',
    version: 'CDISC QRS RS v1.0 / original BODE construct',
    summary: 'مؤشر متعدد الأبعاد لمرض الانسداد الرئوي المزمن يجمع مؤشر كتلة الجسم وانسداد مجرى الهواء وضيق النفس والقدرة على التمرين، ويكمل النظرة الأحادية القائمة على FEV1 وحده.',
    purpose: 'توصيف شدة COPD بصورة متعددة الأبعاد والتقسيم الطبقي للمخاطر في السياق السريري والبحثي.',
    construct: 'شدة COPD متعددة الأبعاد والقدرة الوظيفية',
    populations: ['البالغون المصابون بمرض الانسداد الرئوي المزمن ضمن سياقات مشابهة للتحقق', 'البحوث والتأهيل الرئوي'],
    settings: ['طب الرئة', 'التأهيل الرئوي', 'العيادات المزمنة', 'البحوث السريرية'],
    categories: ['respiratory-function', 'rehabilitation-outcomes'],
    administrationMode: 'تجميع أربعة أبعاد: BMI، انسداد مجرى الهواء المقاس بـFEV1، ضيق النفس بـmMRC، ومسافة المشي في 6MWT، ثم تطبيق نقاط BODE.',
    administrationTime: 'يعتمد أساسًا على توفر spirometry و6MWT؛ الحساب بعد توفرها قصير.',
    equipment: ['طول ووزن لحساب BMI', 'قياس وظائف الرئة', 'mMRC', '6MWT موحد'],
    scoring: 'تحول المكونات الأربعة إلى نقاط وفق جدول BODE الأصلي ثم تجمع. يجب تثبيت نسخة الجدول وعدم استبدال 6MWT أو mMRC بنسخ معدلة دون تسمية المؤشر المعدل.',
    interpretation: 'الدرجة الأعلى ارتبطت بمخاطر أعلى ومرض أشد في دراسات التحقق، لكنها ليست توقعًا فرديًا حتميًا ولا بديلًا عن تقييم التفاقم والأكسجة والأمراض المصاحبة.',
    limitations: ['يتطلب عدة قياسات مختلفة وقد تتأثر بجودتها.', 'النسخ المعدلة من BODE ليست مكافئة للأصل.', 'العلاقة بالمآلات تعتمد على المجتمع والزمن والعلاج.', 'لا يستخدم لتشخيص COPD من الأساس.'],
    administrationSteps: ['أكد تشخيص COPD وملاءمة الاختبار.', 'احسب BMI بطريقة موحدة.', 'استخدم spirometry موثوقة وmMRC محددة.', 'نفذ 6MWT وفق بروتوكول ثابت.', 'طبق جدول BODE نفسه ووثق النسخة.', 'فسر النتيجة مع الصورة السريرية الكاملة.'],
    safetyNotes: ['لا تستخدم BODE وحده لتحديد أهلية علاج أو رعاية تلطيفية أو زراعة أو لإنهاء علاج.', '6MWT يجب أن يتبع احتياطات السلامة الخاصة به.', 'تفاقم COPD الحاد يحتاج تقييمًا وعلاجًا مستقلين عن الدرجة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج BODE Index بحالة Public Domain. المقالة الأصلية وشروحها المنشورة تبقى محمية بحقوق ناشرها، لذلك تعتمد روافد على وصف منهجي لا نسخ النص.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'المؤشر يعتمد على مكونات يجب تثبيت نسخها العربية',
    arabicNote: 'BMI وFEV1 و6MWT غير لغوية أساسًا، لكن mMRC يحتاج نسخة عربية موثقة وتعريفات موحدة قبل تقديم مسار عربي تشغيلي كامل.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننشر جدول BODE عربي كامل قبل تثبيت جميع المكونات والنسخ المرجعية، خصوصًا mMRC.',
    sources: [
      { label: 'CDISC QRS — BODE Index Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — original BODE index study', url: 'https://pubmed.ncbi.nlm.nih.gov/14999112/', role: 'original' },
      { label: 'PubMed — modified BODE validation illustrates version non-equivalence', url: 'https://pubmed.ncbi.nlm.nih.gov/18579541/', role: 'evidence' },
    ],
    related: ['modified-medical-research-council-dyspnea-scale', '6-minute-walk-test'],
  },
];
