import type { AssessmentMeasure } from '@/lib/assessment-measures';

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';

export const assessmentMeasuresWave8: AssessmentMeasure[] = [
  {
    slug: 'framingham-cvd-10-year-risk',
    nameAr: 'تقدير فرامنغهام لخطر أمراض القلب والأوعية خلال 10 سنوات',
    nameEn: 'Framingham Heart Study Cardiovascular Disease 10-Year Risk Score',
    acronym: 'FHS CVD 10-YEAR RISK',
    version: 'General CVD risk profile — D’Agostino et al. 2008 / CDISC QRS',
    summary: 'نموذج خطر متعدد المتغيرات مشتق من دراسة فرامنغهام لتقدير احتمال حدوث أول حدث قلبي وعائي خلال عشر سنوات لدى بالغين دون مرض قلبي وعائي سابق ضمن شروط النموذج.',
    purpose: 'دعم التقسيم الطبقي لخطر أمراض القلب والأوعية في الوقاية الأولية عندما يكون النموذج مناسبًا للسكان والسياق.',
    construct: 'خطر أمراض القلب والأوعية خلال عشر سنوات',
    populations: ['بالغون في الوقاية الأولية ضمن نطاق العمر وشروط النموذج', 'سكان جرى التحقق من صلاحية النموذج أو إعادة معايرته لديهم'],
    settings: ['الرعاية الأولية', 'الوقاية القلبية الوعائية', 'الصحة العامة', 'البحوث السكانية'],
    categories: ['cardiovascular-risk'],
    administrationMode: 'حساب متعدد المتغيرات يعتمد على عوامل خطر محددة مثل العمر والجنس وضغط الدم والتدخين والسكري ودهون الدم بحسب نسخة النموذج.',
    administrationTime: 'دقائق بعد توفر بيانات عوامل الخطر الصحيحة.',
    equipment: ['قياس ضغط دم موثوق', 'بيانات مخبرية عند استخدام النسخة المعتمدة على الدهون', 'تاريخ التدخين والسكري والعلاج', 'مرجع الإصدار والمعايرة'],
    scoring: 'تستخدم معاملات ومعادلة النسخة المحددة. لا توفر روافد حاسبة عامة لأن الصيغ والبدائل والمعايرات تختلف، ولأن نماذج أحدث قد تكون أنسب حسب البلد والإرشادات.',
    interpretation: 'الناتج احتمال إحصائي لمجموعة من الأحداث القلبية الوعائية خلال عشر سنوات، وليس يقينًا فرديًا. يجب تفسيره مع الإرشادات المحلية ومحددات الخطر التي قد لا يتضمنها النموذج.',
    limitations: ['مشتق تاريخيًا من مجتمع فرامنغهام وقد يحتاج إعادة معايرة في مجتمعات أخرى.', 'معدلات المرض والعلاج تتغير عبر الزمن.', 'لا يشمل كل عوامل الخطر أو الحالات السريرية.', 'لا يجوز مقارنة نتيجة نسخة عامة بنتيجة نموذج مختلف على أنها النسبة نفسها.'],
    administrationSteps: ['حدد نسخة Framingham والغرض المقصود.', 'تحقق من شروط الأهلية ونطاق العمر.', 'اجمع المتغيرات بتعريفاتها ووحداتها الصحيحة.', 'استخدم معادلة/أداة موثقة للإصدار المقصود.', 'فسر النتيجة ضمن الإرشادات الوقائية المحلية ومع عوامل الخطر الأخرى.'],
    safetyNotes: ['لا تستخدم النتيجة وحدها لبدء أو إيقاف علاج دوائي أو لإهمال أعراض قلبية حادة.', 'لا تعمم المعايرة الأمريكية التاريخية على مجتمع عربي دون تحقق محلي.', 'روافد لا تقدم حاسبة Framingham فردية عامة بلا تحديد إصدار ومعايرة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Framingham Heart Study Cardiovascular Disease 10-Year Risk Score بحالة Public Domain. الواجهات البرمجية أو الحاسبات التابعة لجهات أخرى قد تكون لها شروط منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لا توجد معايرة عربية عامة معتمدة لدى روافد',
    arabicNote: 'ترجمة أسماء المتغيرات لا تعني صلاحية النموذج للسكان العرب. يلزم تقييم التمييز والمعايرة محليًا قبل الاستخدام كأداة خطر سريرية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد حاسبة عربية عامة أو عتبات علاجية من Framingham دون تحقق سكاني وإرشادي.',
    sources: [
      { label: 'CDISC QRS — Framingham CVD Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/framingham-heart-study-cardiovascular-disease-10-year-risk-score', role: 'rights' },
      { label: 'PubMed — general Framingham CVD risk profile (2008)', url: 'https://pubmed.ncbi.nlm.nih.gov/18212285/', role: 'original' },
    ],
    related: ['assign-cardiovascular-risk-score'],
  },
  {
    slug: 'atlas-cdi-score',
    nameAr: 'مقياس ATLAS لعدوى المطثية العسيرة',
    nameEn: 'ATLAS Score for Clostridioides difficile Infection',
    acronym: 'ATLAS',
    version: '5-component bedside ATLAS score / CDISC QRS RS v1.0',
    summary: 'مقياس سريري-مخبري طوّر لتقسيم مرضى عدوى C. difficile بحسب عوامل مرتبطة بالاستجابة للعلاج، ويجمع العمر واستعمال مضادات جهازية وعدد الكريات البيضاء والألبومين والكرياتينين.',
    purpose: 'توصيف شدة/خطر عدم الاستجابة في عدوى C. difficile ودعم البحث والمقارنة السريرية، لا استبدال إرشادات التشخيص والعلاج.',
    construct: 'شدة عدوى C. difficile واحتمال الاستجابة للعلاج',
    populations: ['بالغون مصابون بعدوى C. difficile وفق تعريفات الدراسة والسياق السريري', 'دراسات CDI وسياقات سريرية تستخدم ATLAS موثقًا'],
    settings: ['الأمراض المعدية', 'المستشفى', 'الطب الباطني', 'البحوث السريرية'],
    categories: ['infectious-disease-severity'],
    administrationMode: 'تجميع خمسة مكونات سريرية/مخبرية ثم تحويلها إلى نقاط وفق جدول ATLAS الأصلي.',
    administrationTime: 'دقائق بعد توفر البيانات السريرية والمخبرية.',
    equipment: ['العمر', 'حالة استخدام مضادات حيوية جهازية أثناء علاج CDI', 'عدد الكريات البيضاء', 'ألبومين المصل', 'كرياتينين المصل'],
    scoring: 'تسجل المكونات الخمسة وفق فئات ATLAS وتجمع إلى مجموع نهائي. يجب استخدام الجدول المرجعي نفسه وعدم استبدال تعريفات المختبر أو تحويل الوحدات دون توثيق.',
    interpretation: 'ارتبطت الدرجات الأعلى في دراسة الاشتقاق/التحقق بانخفاض احتمالات الشفاء السريري. لا يمثل المجموع تشخيصًا للعدوى ولا يحدد وحده اختيار المضاد أو الحاجة للجراحة.',
    limitations: ['مشتق ومحقق من قواعد بيانات تجارب علاجية محددة.', 'العلاج والمقاومة الوبائية وإرشادات CDI تغيرت منذ الدراسة الأصلية.', 'المتغيرات المخبرية تتأثر بأمراض مرافقة.', 'لا يغطي كل مؤشرات الشدة الحالية أو المضاعفات.'],
    administrationSteps: ['أكد تشخيص CDI والسياق الزمني للقياسات.', 'اجمع المكونات الخمسة ووحداتها من المصدر الأصلي.', 'طبق جدول ATLAS الموثق.', 'وثق توقيت المضادات والقياسات.', 'فسر الدرجة مع الإرشادات الحالية والحالة السريرية الكاملة.'],
    safetyNotes: ['لا تستخدم ATLAS لتأخير علاج CDI شديد أو مهدد للحياة.', 'لا تستعمل الدرجة منفردة لاختيار المضاد أو الجراحة أو العزل.', 'التدهور الحاد أو علامات الصدمة/توسع القولون السمي تستلزم تقييمًا عاجلًا مستقلًا عن الدرجة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج ATLAS بحالة Public Domain. المقالات وشروح الناشرين تبقى محمية ولا تعاد صياغتها حرفيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'مؤشر سريري-مخبري قابل للتوطين مع تثبيت التعريفات',
    arabicNote: 'المكونات رقمية/سريرية في معظمها؛ المطلوب توحيد أسماء المتغيرات والوحدات والتعريفات لا ترجمة استبيان.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا تنشر روافد حاسبة آلية قبل مراجعة الوحدات وقواعد الإصدار ضمن إرشادات CDI الحالية.',
    sources: [
      { label: 'CDISC QRS — ATLAS Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/age-treatment-systemic-antibiotics-leukocyte-count-serum-albumin-and', role: 'rights' },
      { label: 'PubMed — ATLAS derivation and validation', url: 'https://pubmed.ncbi.nlm.nih.gov/23530807/', role: 'original' },
    ],
    related: ['sofa-27mar2024', 'apache-ii'],
  },
  {
    slug: 'simple-endoscopic-score-crohns-disease-v1',
    nameAr: 'المؤشر التنظيري المبسط لداء كرون — الإصدار 1',
    nameEn: 'Simple Endoscopic Score for Crohn’s Disease Version 1',
    acronym: 'SES-CD V1',
    version: 'SES-CD Version 1 / CDISC QRS RS',
    summary: 'مؤشر تنظيري مبسط لنشاط داء كرون يقيّم حجم القرح ونسبة السطح المتقرح والسطح المتأثر والتضيقات عبر المقاطع المعوية المحددة.',
    purpose: 'توحيد قياس النشاط التنظيري لداء كرون ومتابعة الاستجابة في الرعاية والبحوث.',
    construct: 'النشاط التنظيري المخاطي لداء كرون',
    populations: ['مرضى داء كرون الخاضعون لتنظير قولوني/لفائفي مناسب', 'التجارب السريرية ودراسات الالتهاب المعوي'],
    settings: ['أمراض الجهاز الهضمي', 'التنظير', 'عيادات أمراض الأمعاء الالتهابية', 'البحوث السريرية'],
    categories: ['gastroenterology'],
    administrationMode: 'تقدير مناظر مدرب لأربعة متغيرات تنظيرية في المقاطع المحددة ثم جمع النقاط وفق SES-CD.',
    administrationTime: 'يحسب خلال/بعد مراجعة التنظير؛ الوقت يعتمد على الإجراء والتوثيق.',
    equipment: ['تنظير عالي الجودة', 'نموذج SES-CD المحدد', 'توثيق المقاطع المعوية'],
    scoring: 'تسجل أربعة عناصر لكل مقطع معوي قابل للتقييم ثم تجمع. يجب توثيق المقاطع غير القابلة للمرور أو غير المقيمة وعدم اختراع قيم مفقودة.',
    interpretation: 'الدرجة الأعلى تعكس نشاطًا تنظيريًا أكبر. عتبات الهدأة والاستجابة تختلف حسب الدراسة والبروتوكول ولا تقدم هنا كقاعدة علاجية عالمية.',
    limitations: ['يتطلب تنظيرًا ومقيّمًا مدربًا.', 'يوجد تباين بين المقيمين.', 'قد لا يلتقط المرض العابر للجدار أو الناسور الشرجي كما تفعل وسائل تصوير أخرى.', 'العتبات التفسيرية تعتمد على سياق الدراسة.'],
    administrationSteps: ['ثبت نسخة SES-CD والبروتوكول.', 'قيّم كل مقطع معوي بالمكونات الأربعة نفسها.', 'وثق أي مقطع غير قابل للتقييم أو تضيق يمنع المرور.', 'اجمع الدرجات وفق القواعد المرجعية.', 'قارن النتيجة مع المؤشرات السريرية والمخبرية والتصوير عند الحاجة.'],
    safetyNotes: ['SES-CD لا يحدد وحده قرار العلاج البيولوجي أو الجراحة.', 'سلامة إجراء التنظير وملاءمته للمريض تسبق الحاجة إلى الحصول على الدرجة.', 'غياب أعراض شديدة لا يضمن غياب نشاط تنظيري والعكس صحيح.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Simple Endoscopic Score for Crohn’s Disease Version 1 بحالة Public Domain. صور التنظير أو الرسوم من منشورات أخرى ليست ضمن هذا الحكم.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف تنظيري قابل للتوطين بعد توحيد المصطلحات',
    arabicNote: 'المشكلة الأساسية ليست اللغة بل توحيد تعريف حجم القرحة والسطح والتضيق وتدريب المقيمين.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننشر نموذجًا عربيًا تشغيليًا كاملًا قبل مراجعة المصطلحات والتدريب بين المقيمين.',
    sources: [
      { label: 'CDISC QRS — SES-CD V1 Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/simple-endoscopic-score-crohns-disease-version-1', role: 'rights' },
      { label: 'PubMed — development and validation of SES-CD', url: 'https://pubmed.ncbi.nlm.nih.gov/15472670/', role: 'original' },
    ],
    related: ['harvey-bradshaw-index', 'crohns-disease-activity-index-v1', 'modified-van-assche-index'],
  },
  {
    slug: 'modified-van-assche-index',
    nameAr: 'مؤشر فان آشه المعدل للنواسير حول الشرج في داء كرون',
    nameEn: 'Modified Van Assche Index',
    acronym: 'MVAI',
    version: 'Modified MRI fistula activity index / CDISC QRS RS v1.0',
    summary: 'مؤشر تصوير بالرنين المغناطيسي لتقييم شدة النواسير حول الشرج في داء كرون، طُوّر لتحسين موثوقية مؤشر Van Assche الأصلي ويضم سبعة مكونات تصويرية.',
    purpose: 'توحيد وصف نشاط النواسير حول الشرج على MRI ومتابعة التغير في الدراسات والعلاج.',
    construct: 'شدة/نشاط النواسير حول الشرج بالتصوير بالرنين المغناطيسي',
    populations: ['مرضى داء كرون ذوو نواسير حول الشرج', 'دراسات التصوير والاستجابة العلاجية في perianal fistulizing Crohn’s disease'],
    settings: ['الأشعة', 'أمراض الجهاز الهضمي', 'جراحة القولون والمستقيم', 'البحوث السريرية'],
    categories: ['gastroenterology'],
    administrationMode: 'تقييم منظم لـMRI بواسطة مقيّم مدرب باستخدام مكونات MVAI وتعريفاتها.',
    administrationTime: 'يعتمد على قراءة فحص MRI وتعقيد الناسور؛ الحساب بعد التقييم قصير.',
    equipment: ['MRI حوض ببروتوكول مناسب للنواسير', 'معايير MVAI', 'قارئ أشعة مدرب'],
    scoring: 'المؤشر المعدل يتكون من سبعة مكونات وينتج مجموعًا ضمن نطاق موثق في الدراسة الأصلية. يجب استخدام تعريفات MVAI لا خلطها بمؤشر Van Assche الأصلي.',
    interpretation: 'انخفاض الدرجة قد يترافق مع تحسن تصويري، لكن التغير لا يطابق دائمًا الاستجابة السريرية؛ يجب دمجه مع الفحص والأعراض والتقييم الجراحي/الهضمي.',
    limitations: ['يتطلب MRI جيدًا وخبرة في تصوير النواسير.', 'ظل التباين بين المقيمين ملحوظًا حتى بعد التعديل.', 'الاستجابة السريرية والتصويرية قد لا تتطابق.', 'لا يصف النشاط اللمعي العام لداء كرون.'],
    administrationSteps: ['أكد استخدام بروتوكول MRI مناسب.', 'طبق تعريفات المكونات السبعة كما في MVAI.', 'وثق مواقع ومسارات وخصائص الناسور وفق القواعد.', 'احسب المجموع دون دمج عناصر من النسخة الأصلية.', 'قارن التغير مع التقييم السريري وSES-CD/HBI/CDAI حسب السياق.'],
    safetyNotes: ['MVAI لا يقرر وحده الحاجة للجراحة أو العلاج البيولوجي.', 'الخراج أو الإنتان المشتبه به يحتاج تقييمًا وعلاجًا عاجلًا بغض النظر عن المجموع.', 'لا تستخدم نماذج رؤية آلية غير محققة لإسناد الدرجة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Modified Van Assche Index بحالة Public Domain. المقالة الأصلية ومواد الصور المنشورة تبقى خاضعة لحقوق ناشريها.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'مؤشر تصويري قابل للتوطين مع تدريب المصطلحات',
    arabicNote: 'التوطين يركز على مصطلحات الأشعة وتعريفات المكونات، بينما صلاحية التسجيل تعتمد على تدريب القارئ أكثر من اللغة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننشر صورًا أو أمثلة محمية من المقالات؛ يمكن لاحقًا نشر بروتوكول عربي أصلي بعد مراجعة اختصاصية.',
    sources: [
      { label: 'CDISC QRS — MVAI Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — development of modified Van Assche index', url: 'https://pubmed.ncbi.nlm.nih.gov/28653753/', role: 'original' },
      { label: 'PubMed — MVAI response evaluation study', url: 'https://pubmed.ncbi.nlm.nih.gov/31821976/', role: 'evidence' },
    ],
    related: ['harvey-bradshaw-index', 'crohns-disease-activity-index-v1', 'simple-endoscopic-score-crohns-disease-v1'],
  },
  {
    slug: 'valg-small-cell-lung-cancer-staging',
    nameAr: 'تصنيف VALG لسرطان الرئة صغير الخلايا',
    nameEn: 'Veterans Administration Lung Study Group Classification',
    acronym: 'VALG',
    version: 'Limited-stage / extensive-stage SCLC classification',
    summary: 'نظام تاريخي وعملي يصنف سرطان الرئة صغير الخلايا إلى مرض محدود ومرض واسع الانتشار، وما زال مستخدمًا سريريًا بجانب تصنيف TNM الأكثر تفصيلًا.',
    purpose: 'توحيد وصف مدى انتشار سرطان الرئة صغير الخلايا وتسهيل التخطيط والمقارنة بين الدراسات، مع استخدام TNM عند الحاجة للتفصيل التشريحي.',
    construct: 'مرحلة انتشار سرطان الرئة صغير الخلايا',
    populations: ['مرضى سرطان الرئة صغير الخلايا المؤكد تشخيصه', 'دراسات SCLC والسياقات الأورامية التي تستخدم limited/extensive stage'],
    settings: ['طب الأورام', 'أورام الصدر', 'العلاج الإشعاعي', 'البحوث السريرية'],
    categories: ['oncology-staging'],
    administrationMode: 'تصنيف سريري يعتمد على مدى الورم والعقد والنقائل ومدى إمكانية احتواء المرض ضمن مجال علاجي إشعاعي مقبول وفق التعريف المستخدم.',
    administrationTime: 'يحدد بعد استكمال معلومات staging المناسبة؛ لا يقاس بزمن استبيان.',
    equipment: ['تصوير staging مناسب', 'تقييم أورام صدري متعدد التخصصات', 'مرجع VALG/TNM الحالي'],
    scoring: 'النتيجة فئوية: limited-stage أو extensive-stage وفق تعريف النظام المستخدم. ينبغي توثيق الاستثناءات والتوافق مع TNM بدل اختزال تفاصيل staging إلى فئة ثنائية فقط.',
    interpretation: 'الفئة تساعد في التخطيط والتواصل لكنها لا تستبدل TNM ولا التقييم الكامل لمواضع النقائل والحالة الوظيفية والعوامل الجزيئية/السريرية.',
    limitations: ['تعريف limited stage ليس موحدًا تمامًا بين جميع المجموعات التاريخية.', 'التصنيف ثنائي وأقل تفصيلًا من TNM.', 'تغيرت تقنيات التصوير والعلاج الإشعاعي منذ تطويره.', 'يجب توثيق أي اختلاف بين VALG وTNM.'],
    administrationSteps: ['أكد تشخيص SCLC.', 'استكمل staging بالتصوير والفحوص المطلوبة حسب الإرشادات.', 'حدد limited أو extensive وفق التعريف المعتمد محليًا.', 'وثق TNM أيضًا عندما يكون متاحًا/مطلوبًا.', 'ناقش المرحلة ضمن فريق الأورام قبل القرار العلاجي.'],
    safetyNotes: ['لا تستخدم VALG وحده لاختيار العلاج دون staging كامل وتقييم اختصاصي.', 'NCI ما زال يصف limited/extensive stages لكنه يوضح أيضًا دور TNM وتباين تعريف limited stage.', 'أي اشتباه بنقائل أو أعراض عصبية يحتاج استقصاء مناسبًا مستقلًا عن التصنيف الثنائي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Veterans Administration Lung Study Group classification بحالة Public Domain. نصوص NCI أو المقالات المرجعية لا تعاد نشرها حرفيًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'تصنيف سريري قابل للتوطين مع تثبيت التعريف',
    arabicNote: 'المصطلحان محدود/واسع بسيطان لغويًا، لكن القيمة تعتمد على تعريف نطاق المرض والتصوير وسياسة الفريق العلاجي.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا يوجد استبيان؛ ستعرض روافد شرحًا منهجيًا لا بديلًا عن staging السريري.',
    sources: [
      { label: 'CDISC QRS — VALG Public Domain status', url: CDISC_QRS, role: 'rights' },
      { label: 'NCI PDQ — current SCLC staging overview', url: 'https://www.cancer.gov/types/lung/hp/small-cell-lung-treatment-pdq', role: 'evidence' },
      { label: 'PubMed — VALG versus IASLC staging comparison', url: 'https://pubmed.ncbi.nlm.nih.gov/12234695/', role: 'evidence' },
    ],
    related: ['eastern-cooperative-oncology-group-performance-status', 'karnofsky-performance-scale'],
  },
  {
    slug: 'clinical-global-impression',
    nameAr: 'مقياس الانطباع السريري العالمي',
    nameEn: 'Clinical Global Impression',
    acronym: 'CGI',
    version: 'CGI severity/improvement framework — CDISC QRS',
    summary: 'أداة تقدير سريري عالمية مختصرة يستخدمها المختص لتقدير شدة الحالة والتحسن العام مقارنة بخط الأساس، وتستعمل كثيرًا كمرساة تفسيرية إلى جانب مقاييس أعراض أكثر تفصيلًا.',
    purpose: 'تكميم الحكم السريري العام حول شدة المرض والتغير عبر الزمن بطريقة بسيطة وقابلة للتتبع.',
    construct: 'الانطباع السريري العالمي عن الشدة والتغير',
    populations: ['سياقات نفسية وسريرية متعددة عندما يعرف المقيم الحالة جيدًا', 'البحوث الدوائية والنفسية التي تحدد نسخة CGI بوضوح'],
    settings: ['الصحة النفسية', 'الطب النفسي', 'التجارب السريرية', 'المتابعة العلاجية'],
    categories: ['mental-health'],
    administrationMode: 'تقدير من مختص باستخدام مراسي CGI المحددة للشدة و/أو التحسن وفق بروتوكول الدراسة أو الرعاية.',
    administrationTime: 'دقيقة إلى بضع دقائق بعد تقييم سريري كافٍ.',
    equipment: ['مراسي CGI للنسخة المستخدمة', 'معلومات خط الأساس والمتابعة المناسبة'],
    scoring: 'تستخدم CGI عادة مراسي رتبية محددة للشدة والتحسن. يجب تسمية البعد المستخدم (مثل CGI-S أو CGI-I) وعدم دمج الدرجات في مجموع غير معياري.',
    interpretation: 'الدرجة تلخص حكمًا سريريًا عالميًا ولا تحدد تشخيصًا أو عرضًا بعينه. فائدتها الأكبر كمؤشر مكمل ومثبت للتغير وليس كبديل عن المقاييس المتخصصة.',
    limitations: ['تعتمد على حكم المقيم وخبرته ومعرفته بخط الأساس.', 'قد تختلف المراسي والتطبيق بين الدراسات.', 'حساسيتها أقل لتغيرات نوعية دقيقة مقارنة بمقاييس الأعراض.', 'التدريب والتعريف الواضح لمرجع المقارنة يحسنان الثبات.'],
    administrationSteps: ['حدد بعد CGI المطلوب ومراسيه قبل التقييم.', 'راجع خط الأساس والمعلومات السريرية الكافية.', 'أصدر التقدير باستخدام المراسي لا وصفًا حرًا فقط.', 'وثق الدرجة والبعد والزمن.', 'فسرها مع مقياس أعراض أو وظيفة أكثر تخصصًا.'],
    safetyNotes: ['CGI لا يثبت التشخيص ولا يبرر وحده تغيير علاج مرتفع المخاطر.', 'في الحالات الحادة أو خطر إيذاء النفس/الآخرين يجب إجراء تقييم سلامة مباشر مستقلًا عن CGI.', 'لا تستخدم الدرجة كبديل عن تقييم الأعراض والوظيفة والآثار الجانبية.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Clinical Global Impression بحالة Public Domain. النسخة القياسية تختلف عن General Clinical Global Impression المسجل لدينا كأداة مستقلة، لذا يبقى الاسمان منفصلين.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'المراسي العربية تحتاج توحيدًا وتحققًا',
    arabicNote: 'سهولة السؤال لا تمنع اختلاف تفسير أوصاف الشدة والتحسن بين المقيمين؛ يلزم تثبيت المصطلحات والتدريب قبل اعتماد صياغة عربية معيارية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننشر مراسي عربية معيارية كاملة قبل مراجعة نسخة محددة والتأكد من الاتساق بين المقيمين.',
    sources: [
      { label: 'CDISC QRS — CGI Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs/clinical-global-impression', role: 'rights' },
      { label: 'PubMed — CGI clinical use review', url: 'https://pubmed.ncbi.nlm.nih.gov/20526405/', role: 'evidence' },
    ],
    related: ['general-clinical-global-impression', 'hamilton-anxiety-rating-scale', 'hamilton-depression-rating-scale-24', 'brief-psychiatric-rating-scale-anchored'],
  },
];
