import type { AssessmentMeasure } from '@/lib/assessment-measures';

export const assessmentMeasuresWave3: AssessmentMeasure[] = [
  {
    slug: 'glasgow-coma-scale-ninds',
    nameAr: 'مقياس غلاسكو للغيبوبة — نسخة NINDS',
    nameEn: 'Glasgow Coma Scale — NINDS Version 1.0',
    acronym: 'GCS',
    version: 'NINDS Version 1.0',
    summary: 'تصنيف سريري لمستوى الوعي يعتمد على الاستجابة العينية واللفظية والحركية، ويستخدم في التقييم الأولي ومراقبة التغير العصبي.',
    purpose: 'توصيف مستوى الوعي بطريقة منظمة ومتابعة التغير بمرور الوقت في سياقات عصبية وإصابات حادة.',
    construct: 'مستوى الوعي والاستجابة العصبية',
    populations: ['المراهقون والبالغون وكبار السن في السياقات العصبية وإصابات الدماغ وفق النسخة والسياق'],
    settings: ['الطوارئ', 'العناية الحادة', 'إصابات الدماغ', 'المتابعة العصبية'],
    categories: ['brain-injury', 'neurological-outcomes', 'rehabilitation-outcomes'],
    administrationMode: 'ملاحظة سريرية منظمة لفتح العين والاستجابة اللفظية والاستجابة الحركية.',
    administrationTime: 'RMD يورد نحو 10–15 دقيقة؛ الزمن العملي يتأثر بالسياق السريري والحاجة إلى تكرار الفحص.',
    equipment: ['تعريفات مكونات GCS المطابقة للنسخة المستخدمة', 'بيئة تسمح بالتقييم السريري الآمن'],
    scoring: 'تُسجل المكونات الثلاثة منفصلة ثم يمكن جمعها إلى مجموع من 3 إلى 15. تسجيل E/V/M منفصلًا أكثر إفادة من المجموع وحده، خصوصًا عندما تكون إحدى الاستجابات غير قابلة للاختبار.',
    interpretation: 'المجموع الأقل يعكس اضطراب وعي أشد عمومًا، لكن تفسيره يعتمد على سبب الحالة، التهدئة، التنبيب، اللغة، السمع والعوامل العصبية الأخرى. لا ينبغي اختزال القرار السريري في رقم واحد.',
    limitations: ['الاستجابة اللفظية قد تكون غير قابلة للتقييم مع التنبيب أو حاجز لغوي شديد.', 'الأدوية المهدئة أو الشلل الدوائي قد تغير الاستجابة.', 'المجموع نفسه قد ينتج من أنماط مختلفة جدًا من E/V/M.', 'التصنيفات التقليدية لشدة إصابة الدماغ تحتاج سياقًا وتوقيتًا ولا تعمل كتشخيص منفرد.'],
    administrationSteps: ['تأكد أولًا من السلامة والاستقرار والسياق الذي قد يمنع التقييم.', 'قيّم فتح العين والاستجابة اللفظية والحركية باستخدام تعريفات النسخة المحددة.', 'سجل كل مكوّن منفصلًا، وأشر بوضوح إلى أي مكوّن غير قابل للاختبار.', 'احسب المجموع عند ملاءمة ذلك وسجّل وقت القياس والعوامل المؤثرة.', 'قارن التغير الزمني بالمكونات نفسها، لا بالمجموع فقط.'],
    safetyNotes: ['انخفاض الوعي أو تدهوره حالة طبية محتملة الطوارئ؛ لا يُستخدم GCS كبديل عن التقييم والعلاج العاجلين.', 'تجنب تطبيق منبه مؤلم أو مناورة غير آمنة خارج بروتوكول ومهارة سريرية مناسبة.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — نسخة NINDS V1.0 موثقة في CDISC',
    rightsNote: 'CDISC يحدد صراحة Glasgow Coma Scale NINDS Version 1.0 بحالة Public Domain، ويعرّف Public Domain بأنه لا يحتاج إذنًا. هذا السجل يستهدف تلك النسخة المحددة ولا يعمم الحالة الحقوقية على أي مواد تدريبية أو ترجمة أو تنسيق من طرف ثالث.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج تثبيت النص والمصدر',
    arabicNote: 'توجد استخدامات عربية واسعة، لكن روافد لا يعتبر أي صياغة متداولة نسخة مرجعية قبل توثيق مصدرها ومطابقتها للنسخة المستهدفة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تُنشر طريقة الاستخدام والهيكل والحدود، بينما ينتظر نص الدرجات العربي الكامل توثيق نسخة لغوية محددة.',
    sources: [
      { label: 'RMD — Glasgow Coma Scale', url: 'https://www.sralab.org/rehabilitation-measures/glasgow-coma-scale', role: 'evidence' },
      { label: 'CDISC QRS — GCS NINDS V1.0 Public Domain', url: 'https://www.cdisc.org/standards/foundational/qrs/glasgow-coma-scale-gcs-national-institute-neurological-disorders-and', role: 'rights' },
    ],
    related: ['disability-rating-scale', 'glasgow-outcome-scale-extended', 'rivermead-post-concussion-questionnaire'],
  },
  {
    slug: 'disease-steps',
    nameAr: 'مقياس خطوات المرض في التصلب المتعدد',
    nameEn: 'Disease Steps',
    acronym: 'Disease Steps',
    version: 'Hohol Disease Steps',
    summary: 'تصنيف سريري موجز للإعاقة الوظيفية في التصلب المتعدد يعتمد بدرجة كبيرة على المشي واستخدام وسائل المساعدة مع التاريخ والفحص العصبي.',
    purpose: 'متابعة تطور الإعاقة الوظيفية لدى الأشخاص المصابين بالتصلب المتعدد وتوفير تصنيف سريري بسيط للحركة والاعتماد.',
    construct: 'الإعاقة الوظيفية المرتبطة بالتصلب المتعدد',
    populations: ['الأشخاص المصابون بالتصلب المتعدد'],
    settings: ['طب الأعصاب', 'عيادات التصلب المتعدد', 'التأهيل', 'المتابعة السريرية'],
    categories: ['neurological-outcomes', 'mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'تصنيف سريري يستند إلى حالة المشي واستخدام المساعدة وتاريخ/فحص عصبي.',
    administrationTime: 'RMD يورد نحو 15–35 دقيقة بحسب اكتمال الفحص والسياق.',
    equipment: ['مسار غير معاق بطول 25 قدمًا', 'تعريفات Disease Steps القياسية'],
    scoring: 'يتدرج التصنيف من 0 إلى 6 مع فئة U للحالات غير القابلة للتصنيف ضمن الهيكل المعتاد. ارتفاع الدرجة يعكس اعتمادًا حركيًا أكبر، مع تركيز واضح على المشي.',
    interpretation: 'يرتبط Disease Steps بقوة مع EDSS في دراسات التصلب المتعدد، لكنه يزن القدرة على المشي بدرجة كبيرة ولا يغطي كل أبعاد المرض أو المشاركة.',
    limitations: ['ثقيل الوزن للمشي وقد لا يمثل التعب أو الإدراك أو الرؤية أو الأعراض غير الحركية جيدًا.', 'قد تصبح بعض الحالات U عندما تكون الإعاقة المهمة خارج النمط الحركي الذي يلتقطه السلم.', 'ليس مقياسًا لنشاط المرض أو معدل الانتكاسات.', 'RMD يورد قيودًا على استخدامه البحثي مقارنة باختبارات أداء أكثر موضوعية.'],
    administrationSteps: ['اجمع تاريخًا وظيفيًا وعصبيًا حديثًا.', 'حدد قدرة المشي واستخدام العصا أو الدعم الثنائي أو الكرسي المتحرك وفق تعريفات السلم.', 'أجر الفحص العصبي اللازم لتمييز الدرجات المبكرة.', 'اختر الفئة الأقرب دون إجبار حالة غير منطبقة على درجة غير مناسبة.', 'وثق الدرجة والوسيلة المساعدة وأي سبب يجعل الحالة غير قابلة للتصنيف.'],
    safetyNotes: ['اختبار المشي أو محاولة المسافة يجب ألا تُجرى إذا كانت غير آمنة.', 'أي تدهور عصبي حاد أو احتمال انتكاس يحتاج تقييمًا طبيًا منفصلًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Disease Steps بحالة Public Domain، وRMD يورده كأداة مجانية مع وصف التطبيق والأدلة. حقوق أي ترجمة عربية بعينها تراجع منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'النسخة العربية تحتاج توثيقًا مستقلًا',
    arabicNote: 'لا يُعاد إنشاء تعريفات الفئات بالعربية ثم تقديمها كنسخة رسمية قبل تكييف لغوي موثق ومراجعة حقوق النسخة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'الشرح السريري متاح، بينما نص الفئات العربي الكامل ينتظر تثبيت النسخة.',
    sources: [
      { label: 'RMD — Disease Steps', url: 'https://www.sralab.org/rehabilitation-measures/disease-steps', role: 'evidence' },
      { label: 'CDISC QRS — Disease Steps Public Domain status', url: 'https://www.cdisc.org/standards/foundational/qrs', role: 'rights' },
    ],
    related: ['expanded-disability-status-scale', 'kurtzke-functional-systems-score', 'patient-determined-disease-steps'],
  },
  {
    slug: 'international-physical-activity-questionnaire-long-form',
    nameAr: 'الاستبيان الدولي للنشاط البدني — النسخة الطويلة',
    nameEn: 'International Physical Activity Questionnaire — Long Form',
    acronym: 'IPAQ-LF',
    version: 'Long Form — last 7 days',
    summary: 'استبيان تقرير ذاتي من 27 بندًا يقدّر النشاط البدني خلال الأيام السبعة السابقة عبر العمل والتنقل والمنزل والترفيه والجلوس.',
    purpose: 'تقدير مستوى وأنماط النشاط البدني لدى البالغين للاستخدام السريري والسكاني والبحثي مع إمكان المقارنة عبر مجتمعات مختلفة عند توحيد النسخة والبروتوكول.',
    construct: 'النشاط البدني المبلغ عنه ذاتيًا والجلوس',
    populations: ['البالغون بعمر 15–69 عامًا وفق وصف RMD للأداة الأصلية'],
    settings: ['الصحة العامة', 'البحوث السكانية', 'التأهيل', 'العيادات الوقائية'],
    categories: ['participation', 'mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'تقرير ذاتي أو صيغة مقابلة حسب الإصدار؛ يغطي آخر سبعة أيام عبر مجالات النشاط المختلفة.',
    administrationTime: 'RMD يورد نحو 15–30 دقيقة للنسخة الطويلة.',
    equipment: ['نسخة IPAQ-LF المحددة وطريقة تطبيقها', 'بروتوكول التسجيل والحساب المطابق للإصدار'],
    scoring: 'تُشتق مدد وتكرارات النشاط ثم يمكن حساب MET-min/week ومجاميع حسب الشدة والمجال وفق بروتوكول IPAQ. يجب تطبيق قواعد تنظيف البيانات والتعامل مع القيم المتطرفة كما في بروتوكول التسجيل المستخدم.',
    interpretation: 'يمكن تصنيف النشاط إلى مستويات وفق قواعد IPAQ، لكن المقياس يعتمد على التذكر والإبلاغ الذاتي وقد يبالغ في النشاط مقارنة بالقياسات الموضوعية في بعض المجتمعات.',
    limitations: ['تأثير التذكر والتحيز الاجتماعي في التقرير الذاتي.', 'RMD يحذر من المبالغة في النشاط المتوسط والعالي في بعض الدراسات.', 'قد تكون الملاءمة أقل في البيئات منخفضة القراءة أو شديدة الاختلاف ثقافيًا دون تكييف مناسب.', 'المراجعة المنهجية العربية المنشورة في 2026 تشير إلى أن الخصائص القياسية لأدوات النشاط العربية ما تزال غير مكتملة بصورة متجانسة وفق COSMIN.'],
    administrationSteps: ['حدد النسخة الطويلة وطريقة التطبيق والفترة المرجعية بدقة.', 'استخدم النسخة اللغوية الموثقة دون خلطها بالنسخة القصيرة.', 'اجمع الأيام والدقائق في مجالات العمل والتنقل والمنزل والترفيه والجلوس.', 'طبق بروتوكول IPAQ المعتمد لحساب MET-min/week والتنظيف والتصنيف.', 'وثق طريقة التطبيق والنسخة واللغة عند المقارنة عبر الزمن أو المجتمعات.'],
    safetyNotes: ['IPAQ يقيس النشاط المبلغ عنه ولا يقرر سلامة ممارسة الرياضة لشخص بعينه.', 'وجود أعراض قلبية أو تنفسية أو عصبية مقلقة يحتاج تقييمًا مهنيًا قبل استخدام نتيجة النشاط لتوجيه برنامج تمرين.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — صيغ IPAQ الطويلة موثقة لدى CDISC',
    rightsNote: 'دليل CDISC الخاص بالتغذية يدرج صيغة IPAQ Long Form للهاتف وصيغة self-administered ضمن Public Domain. يجب تحديد الصيغة الفعلية وعدم الخلط بين long/short أو telephone/self-administered.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'توجد نسخة عربية طويلة محققة منشورة',
    arabicNote: 'دراسة منشورة عام 2017 قامت بتكييف وترجمة النسخة الطويلة إلى العربية في لبنان ووجدت صلاحية وثباتًا مقبولين لدى عينة من البالغين. كما تؤكد مراجعة منهجية 2026 أن IPAQ من أكثر أدوات النشاط تحققًا بالعربية، مع بقاء فجوات في بعض خصائص COSMIN. حقوق نص الترجمة المحددة تُراجع قبل إعادة نشر البنود كاملة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'تُنشر طريقة الاستخدام والدليل العربي، بينما ينتظر النص الكامل مطابقة النسخة العربية المنشورة وشروط إعادة استخدامها.',
    sources: [
      { label: 'RMD — International Physical Activity Questionnaire Long Form', url: 'https://www.sralab.org/rehabilitation-measures/international-physical-activity-questionnaire-long-form', role: 'evidence' },
      { label: 'CDISC Nutrition User Guide — IPAQ Long Form Public Domain status', url: 'https://www.cdisc.org/standards/therapeutic-areas/nutrition/nutrition-therapeutic-area-user-guide-v1-0/html', role: 'rights' },
      { label: 'PubMed — adapted Arabic IPAQ-LF validation (2017)', url: 'https://pubmed.ncbi.nlm.nih.gov/28738790/', role: 'translation' },
      { label: 'PubMed — 2026 COSMIN systematic review of Arabic physical-activity scales', url: 'https://pubmed.ncbi.nlm.nih.gov/42040138/', role: 'evidence' },
    ],
    related: ['6-minute-walk-test', '10-meter-walk-test', 'satisfaction-with-life-scale'],
  },
];
