import type { AssessmentOperationalMaterial, OperationalOption } from '@/lib/assessment-measure-operational';

const bother02: OperationalOption[] = [
  { labelAr: '0 — لم يزعجني إطلاقًا', labelEn: 'Not bothered at all', value: '0', score: 0 },
  { labelAr: '1 — أزعجني قليلًا', labelEn: 'Bothered a little', value: '1', score: 1 },
  { labelAr: '2 — أزعجني كثيرًا', labelEn: 'Bothered a lot', value: '2', score: 2 },
];

const phqFrequency02: OperationalOption[] = [
  { labelAr: '0 — أبدًا', value: '0', score: 0 },
  { labelAr: '1 — عدة أيام', value: '1', score: 1 },
  { labelAr: '2 — أكثر من نصف الأيام أو كل يوم تقريبًا', value: '2', score: 2 },
];

const covi15: OperationalOption[] = [
  { labelAr: '1 — لا يوجد/ليس إطلاقًا', value: '1', score: 1 },
  { labelAr: '2 — إلى حد ما', value: '2', score: 2 },
  { labelAr: '3 — متوسط', value: '3', score: 3 },
  { labelAr: '4 — ملحوظ/إلى حد كبير', value: '4', score: 4 },
  { labelAr: '5 — شديد جدًا/إلى حد كبير جدًا', value: '5', score: 5 },
];

const yesNo: OperationalOption[] = [
  { labelAr: 'نعم', value: 'yes' },
  { labelAr: 'لا', value: 'no' },
];

const yesNoNA: OperationalOption[] = [
  { labelAr: 'نعم', value: 'yes' },
  { labelAr: 'لا', value: 'no' },
  { labelAr: 'غير منطبق', value: 'na' },
];

export const assessmentOperationalFullFormsWave3: Record<string, AssessmentOperationalMaterial> = {
  'patient-health-questionnaire-15': {
    slug: 'patient-health-questionnaire-15',
    kind: 'full-instrument',
    completeness: 'exact-public-domain-form',
    titleAr: 'استبيان صحة المريض — 15 عرضًا جسديًا (PHQ-15)',
    titleEn: 'Patient Health Questionnaire-15',
    version: 'PHQ-15 — conventional 4-week version',
    provenance: 'CDISC يصنف PHQ-15 ضمن Public Domain، وLOINC ينص على أن Pfizer لا تطلب إذنًا لإعادة إنتاج PHQ أو ترجمته أو عرضه أو توزيعه. توجد أدلة تحقق عربية منشورة، لكن الصياغة العربية هنا تُوسم كترجمة تشغيلية من روافد ما لم تُطابق نسخة عربية محققة بعينها.',
    rightsNotice: 'يمكن إعادة إنتاج الأداة الأصلية وترجمتها وعرضها دون إذن وفق شروط PHQ/LOINC وCDISC. لا تنسب صياغة روافد العربية إلى Pfizer أو دراسة تحقق عربية محددة إلا بعد مطابقة النص.',
    intendedUseAr: 'تقدير عبء الأعراض الجسدية خلال الأسابيع الأربعة الماضية ومتابعة التغير. ارتفاع الدرجة لا يثبت أن الأعراض غير عضوية ولا يغني عن التقييم الطبي.',
    respondentFields: ['الاسم/الرمز', 'التاريخ', 'العمر', 'الجنس/مدى انطباق بند الدورة الشهرية', 'السياق السريري', 'الأعراض الطبية الجديدة أو الحادة'],
    preflightChecks: ['الفترة المرجعية الأساسية: الأسابيع الأربعة الماضية.', 'اسأل عن الأعراض كما هي ولا تفترض سببًا نفسيًا أو عضويًا من الدرجة.', 'بند مشاكل الدورة الشهرية يطبق فقط عندما يكون ذا صلة؛ وثق بوضوح إن كان غير منطبق.', 'أعراض مثل ألم الصدر أو الإغماء أو ضيق النفس الحاد تُفرز طبيًا قبل متابعة استبيان روتيني.'],
    sections: [
      {
        titleAr: 'الأعراض الجسدية الأساسية — إلى أي مدى أزعجتك خلال الأسابيع الأربعة الماضية؟',
        items: [
          { code: 'PHQ15-1', labelAr: 'ألم المعدة/البطن.', type: 'choice', options: bother02 },
          { code: 'PHQ15-2', labelAr: 'ألم الظهر.', type: 'choice', options: bother02 },
          { code: 'PHQ15-3', labelAr: 'ألم الذراعين أو الساقين أو المفاصل مثل الركبتين أو الوركين.', type: 'choice', options: bother02 },
          { code: 'PHQ15-4', labelAr: 'تقلصات الدورة الشهرية أو مشكلات أخرى مرتبطة بها — عندما ينطبق.', type: 'choice', options: bother02, noteAr: 'غير منطبق لدى من لا ينطبق عليه بند الدورة؛ لا تعوّضه بدرجة مخترعة.' },
          { code: 'PHQ15-5', labelAr: 'الصداع.', type: 'choice', options: bother02 },
          { code: 'PHQ15-6', labelAr: 'ألم الصدر.', type: 'choice', options: bother02, noteAr: 'ألم الصدر الجديد أو الشديد أو المصحوب بعلامات خطر يحتاج تقييمًا طبيًا مستقلًا.' },
          { code: 'PHQ15-7', labelAr: 'الدوخة.', type: 'choice', options: bother02 },
          { code: 'PHQ15-8', labelAr: 'نوبات الإغماء.', type: 'choice', options: bother02, noteAr: 'الإغماء غير المفسر أو المتكرر يحتاج تقييمًا طبيًا؛ لا يفسر بالدرجة النفسية.' },
          { code: 'PHQ15-9', labelAr: 'الشعور بخفقان القلب أو تسارع نبضه.', type: 'choice', options: bother02 },
          { code: 'PHQ15-10', labelAr: 'ضيق النفس.', type: 'choice', options: bother02 },
          { code: 'PHQ15-11', labelAr: 'ألم أو مشكلات أثناء العلاقة الجنسية.', type: 'choice', options: bother02 },
          { code: 'PHQ15-12', labelAr: 'الإمساك أو ليونة البراز أو الإسهال.', type: 'choice', options: bother02 },
          { code: 'PHQ15-13', labelAr: 'الغثيان أو الغازات أو عسر الهضم.', type: 'choice', options: bother02 },
        ],
      },
      {
        titleAr: 'بندا PHQ-9 اللذان يدخلان في PHQ-15',
        instructionsAr: 'يُحافظ على طريقة الترميز القياسية: 0 أبدًا، 1 عدة أيام، 2 أكثر من نصف الأيام أو كل يوم تقريبًا.',
        items: [
          { code: 'PHQ15-14', labelAr: 'الشعور بالتعب أو قلة الطاقة.', type: 'choice', options: phqFrequency02 },
          { code: 'PHQ15-15', labelAr: 'صعوبة النوم أو اضطرابه.', type: 'choice', options: phqFrequency02 },
        ],
      },
      {
        titleAr: 'التسجيل',
        items: [
          { code: 'PHQ15-TOTAL', labelAr: 'المجموع المحسوب', type: 'number', min: 0, max: 30, unit: 'نقطة' },
          { code: 'PHQ15-APPLICABLE', labelAr: 'عدد البنود القابلة للتطبيق والمجاب عنها', type: 'number', min: 0, max: 15, unit: 'بند' },
        ],
      },
    ],
    scoringSteps: ['اجمع البنود القابلة للتطبيق بعد ترميز كل بند 0–2.', 'عند تطبيق البنود الخمسة عشر يكون النطاق 0–30. لدى من لا ينطبق عليه بند الدورة الشهرية قد يكون المجموع الخام من 14 بندًا ونطاقه 0–28؛ وثق طريقة المعالجة بدل افتراض درجة.', 'في الأدبيات التقليدية استُخدمت نقاط 5 و10 و15 لوصف عبء منخفض/متوسط/مرتفع بصورة تقريبية؛ لا تحولها إلى تشخيص.', 'إذا كانت هناك بيانات مفقودة فلا تعوّضها أو تُعدّل المجموع إلا وفق بروتوكول معلن ومثبت مسبقًا.'],
    interpretationGuardrails: ['PHQ-15 يقيس عبء الأعراض ولا يحدد سببها.', 'ارتفاع الدرجة لا يعني أن الأعراض «نفسية فقط» أو غير مفسرة طبيًا.', 'عند المتابعة استخدم الفترة المرجعية والنسخة وطريقة التعامل مع البنود غير المنطبقة نفسها.', 'الخصائص القياسية لترجمة عربية في مجتمع محدد لا تعمم تلقائيًا على جميع البلدان العربية.'],
    stopRules: ['ألم صدري حاد، إغماء، ضيق نفس شديد، أعراض عصبية جديدة، نزف أو تدهور طبي سريع يحتاج تقييمًا مباشرًا قبل الاستمرار في التقييم الروتيني.'],
    officialDownloads: [
      { label: 'CDISC QRS — PHQ-15 Public Domain', url: 'https://www.cdisc.org/standards/foundational/qrs/patient-health-questionnaire-15', language: 'en', publisher: 'CDISC' },
      { label: 'LOINC PHQ-15 panel — terms, items and scores', url: 'https://loinc.org/69728-4/panel', language: 'en', publisher: 'Regenstrief Institute / LOINC' },
    ],
    sourceUrls: ['https://www.cdisc.org/standards/foundational/qrs/patient-health-questionnaire-15', 'https://loinc.org/69728-4/panel', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3606198/', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5585978/'],
    lastVerifiedOn: '2026-09-06',
  },

  'covi-anxiety-scale': {
    slug: 'covi-anxiety-scale',
    kind: 'scoring-form',
    completeness: 'recording-and-scoring-sheet',
    titleAr: 'مقياس كوفي للقلق — COVI',
    titleEn: 'Covi Anxiety Scale',
    version: '3-item clinician-rated COVI — 1–5 scoring convention',
    provenance: 'CDISC يصنف COVI ضمن Public Domain. توجد في الأدبيات طريقتان تاريخيتان للترميز (1–5 ومجموع 3–15، وأحيانًا 0–4 ومجموع 0–12)، لذلك تثبت هذه الورقة صراحة اتفاقية 1–5 ولا تخلط النتائج بين النسختين.',
    rightsNotice: 'الأداة الأصلية Public Domain وفق CDISC. الصياغة العربية هنا ترجمة تشغيلية من روافد؛ يجب تثبيت نسخة الترميز في البروتوكول قبل المقارنة أو البحث.',
    intendedUseAr: 'تقدير سريع لشدة القلق بواسطة فاحص مدرب عبر التقرير اللفظي والسلوك المرصود والشكاوى الجسدية.',
    respondentFields: ['الاسم/الرمز', 'التاريخ', 'الفاحص', 'سياق المقابلة', 'نسخة الترميز: 1–5'],
    preflightChecks: ['حدد قبل التطبيق أن هذه الورقة تستخدم 1–5 لكل عنصر.', 'اجمع معلومات من المقابلة والملاحظة معًا؛ لا تجعل التقرير الذاتي وحده بديلًا عن الملاحظة.', 'استبعد/راجع الأسباب الطبية أو الدوائية الملائمة للشكاوى الجسدية.'],
    sections: [{
      titleAr: 'الأبعاد الثلاثة',
      instructionsAr: 'قدّر كل بعد من 1 إلى 5: 1 لا يوجد إطلاقًا، 2 إلى حد ما، 3 متوسط، 4 ملحوظ، 5 شديد جدًا.',
      items: [
        { code: 'COVI1', labelAr: 'التقرير اللفظي عن القلق: العصبية، الارتجاف/التوتر الداخلي، الخوف غير المبرر، التجنب المرتبط بالخوف، وصعوبة التركيز ذات الصلة.', type: 'task-score', options: covi15 },
        { code: 'COVI2', labelAr: 'السلوك المرصود أثناء المقابلة: مظهر خائف أو متوتر، تململ، ارتجاف أو عدم ارتياح واضح.', type: 'task-score', options: covi15 },
        { code: 'COVI3', labelAr: 'الشكاوى الجسدية للقلق: مثل التعرق أو الرجفان أو الخفقان أو ضيق النفس أو اضطراب النوم أو الانزعاج المعدي عند ارتباطها بالسياق.', type: 'task-score', options: covi15 },
      ],
    }],
    scoringSteps: ['اجمع البنود الثلاثة في اتفاقية 1–5: المجموع 3–15.', 'الدرجة الأعلى تعكس شدة أكبر للأعراض ضمن هذه الاتفاقية.', 'لا تقارن مجموع 3–15 مباشرة بنتيجة منشورة باستخدام ترميز 0–4/مجموع 0–12 دون تحويل منهجي موثق.', 'لا تستخدم المجموع كتشخيص مستقل أو لتحديد سبب الشكاوى الجسدية.'],
    interpretationGuardrails: ['COVI مقياس شدة قصير وليس أداة تشخيص مستقلة.', 'يجب تسجيل اتفاقية الترميز المستخدمة مع النتيجة.', 'المقارنة الطولية تحتاج فاحصًا/تدريبًا وطريقة مقابلة ثابتة قدر الإمكان.'],
    stopRules: ['ألم الصدر أو الإغماء أو ضيق النفس المقلق أو خطر إيذاء النفس/الآخرين يحتاج تقييمًا مباشرًا مستقلًا عن COVI.'],
    officialDownloads: [{ label: 'CDISC QRS — COVI Public Domain', url: 'https://www.cdisc.org/standards/foundational/qrs/covi-anxiety-scale', language: 'en', publisher: 'CDISC' }],
    sourceUrls: ['https://www.cdisc.org/standards/foundational/qrs/covi-anxiety-scale', 'https://clinicaltrials.gov/study/NCT00384033', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11005863/'],
    lastVerifiedOn: '2026-09-06',
  },

  'brooke-upper-extremity-rating-scale': {
    slug: 'brooke-upper-extremity-rating-scale',
    kind: 'clinical-classification',
    completeness: 'exact-public-domain-form',
    titleAr: 'مقياس بروك لوظيفة الأطراف العلوية — BUERS',
    titleEn: 'Brooke Upper Extremity Rating Scale',
    version: '6-level Brooke upper extremity functional classification',
    provenance: 'CDISC يصنف Brooke Upper Extremity Rating Scale ضمن Public Domain. المستويات الستة موثقة في الأدبيات العصبية العضلية وDMD.',
    rightsNotice: 'المقياس Public Domain وفق CDISC. هذه ترجمة عربية تشغيلية للمستويات الوظيفية الأصلية؛ عند البحث الرسمي وثق النسخة ومصدر الترجمة.',
    intendedUseAr: 'تصنيف مستوى وظيفة الطرف العلوي بصورة رتبية سريعة، خصوصًا في الأمراض العصبية العضلية مثل الحثل العضلي الدوشيني.',
    respondentFields: ['الاسم/الرمز', 'التاريخ', 'الفاحص', 'التشخيص/السياق', 'الأجهزة أو الدعم المستخدم', 'ألم أو تقييد مفصلي مؤثر'],
    preflightChecks: ['نفذ فقط الحركات الآمنة والممكنة طبيًا.', 'جهز كوبًا/كأسًا يحتوي نحو 8 أونصات (نحو 237 مل) عند اختبار المستوى 3 مقابل 4.', 'سجل التعويضات والأجهزة أو الدعم الخارجي إذا أثرت في الأداء.', 'لا تطلب حركة تسبب ألمًا أو خطر سقوط أو إجهادًا غير آمن.'],
    sections: [{
      titleAr: 'اختر أعلى مستوى وظيفي مطابق للأداء',
      items: [{
        code: 'BUERS',
        labelAr: 'درجة Brooke',
        type: 'choice',
        options: [
          { labelAr: '1 — يبدأ والذراعان بجانب الجسم ويستطيع تبعيدهما في دائرة كاملة حتى تلتقي اليدان فوق الرأس.', value: '1', score: 1 },
          { labelAr: '2 — يستطيع رفع الذراعين فوق الرأس فقط بثني المرفق/تقليل قوس الحركة أو باستخدام عضلات إضافية.', value: '2', score: 2 },
          { labelAr: '3 — لا يستطيع رفع اليدين فوق الرأس، لكنه يستطيع رفع كأس ماء 8 أونصات إلى الفم، باستخدام اليدين معًا عند الحاجة.', value: '3', score: 3 },
          { labelAr: '4 — يستطيع رفع اليدين إلى الفم، لكنه لا يستطيع رفع كأس ماء 8 أونصات إلى الفم.', value: '4', score: 4 },
          { labelAr: '5 — لا يستطيع رفع اليد إلى الفم، لكنه يستطيع استخدام اليدين لإمساك قلم أو التقاط قطع نقدية صغيرة من الطاولة.', value: '5', score: 5 },
          { labelAr: '6 — لا يستطيع رفع اليدين إلى الفم ولا توجد وظيفة يدوية مفيدة وفق تعريف المقياس.', value: '6', score: 6 },
        ],
      }],
    }],
    scoringSteps: ['اختر وصفًا واحدًا يطابق أفضل/أعلى وظيفة موثقة وفق تسلسل المقياس.', 'الدرجة 1 تمثل وظيفة أفضل، والدرجة 6 تمثل تقييدًا أشد.', 'هذا مقياس رتبي؛ الفرق بين 1 و2 ليس بالضرورة مساويًا سريريًا للفرق بين 5 و6.', 'وثق أي جهاز مساعد أو تعويض أو ألم غيّر الأداء.'],
    interpretationGuardrails: ['المقياس خشن نسبيًا وقد لا يلتقط تغيرات اليد الدقيقة.', 'لا تختبر حركة غير آمنة لمجرد تثبيت الدرجة.', 'استخدمه مع مقاييس أكثر تفصيلًا عند الحاجة لتقييم الطرف العلوي.'],
    stopRules: ['أوقف أي محاولة تسبب ألمًا واضحًا أو عدم استقرار أو إجهادًا غير آمن.'],
    officialDownloads: [{ label: 'CDISC QRS — Brooke Upper Extremity Rating Scale', url: 'https://www.cdisc.org/standards/foundational/qrs/brooke-upper-extremity-rating-scale', language: 'en', publisher: 'CDISC' }],
    sourceUrls: ['https://www.cdisc.org/standards/foundational/qrs/brooke-upper-extremity-rating-scale', 'https://onlinelibrary.wiley.com/doi/full/10.1111/j.1469-8749.2012.04345.x', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4770889/'],
    lastVerifiedOn: '2026-09-06',
  },

  'vignos-lower-extremity-rating-scale': {
    slug: 'vignos-lower-extremity-rating-scale',
    kind: 'clinical-classification',
    completeness: 'exact-public-domain-form',
    titleAr: 'مقياس Vignos لوظيفة الطرفين السفليين — VLERS',
    titleEn: 'Vignos Lower Extremity Rating Scale',
    version: '10-level Vignos lower extremity functional classification',
    provenance: 'CDISC يصنف Vignos Lower Extremity Rating Scale ضمن Public Domain. المستويات العشرة موثقة في الأدبيات العصبية العضلية، مع اختلاف تاريخي في تعبير زمن المستوى 3 (مثل >12 ثانية لأربع درجات أو >25 ثانية لثماني درجات).',
    rightsNotice: 'المقياس Public Domain وفق CDISC. ثبت تعريف الدرج والزمن المستخدم في البروتوكول عند استعمال المستوى 3، ولا تخلط صيغًا تاريخية مختلفة.',
    intendedUseAr: 'تصنيف القدرة الوظيفية للطرفين السفليين والتنقل وصعود الدرج في الأمراض العصبية العضلية.',
    respondentFields: ['الاسم/الرمز', 'التاريخ', 'الفاحص', 'الأجهزة/الجبائر', 'الحاجة لمساعدة بشرية', 'تعريف الدرج المستخدم إذا طُبق المستوى 3'],
    preflightChecks: ['لا تطلب صعود الدرج أو الوقوف إذا كان غير آمن.', 'وثق استخدام الدرابزين أو الجبائر الطويلة أو المساعدة البشرية.', 'عند التمييز بين الدرجة 2 و3، ثبت معيار الزمن/عدد الدرجات في البروتوكول نفسه عبر المتابعة.'],
    sections: [{
      titleAr: 'اختر الوصف المطابق للوظيفة',
      items: [{
        code: 'VLERS',
        labelAr: 'درجة Vignos',
        type: 'choice',
        options: [
          { labelAr: '1 — يمشي ويصعد الدرج دون مساعدة.', value: '1', score: 1 },
          { labelAr: '2 — يمشي ويصعد الدرج باستخدام الدرابزين.', value: '2', score: 2 },
          { labelAr: '3 — يمشي ويصعد الدرج ببطء مع الدرابزين؛ استخدم معيار الزمن المحدد مسبقًا في النسخة/البروتوكول.', value: '3', score: 3 },
          { labelAr: '4 — يمشي دون مساعدة ويستطيع النهوض من الكرسي، لكنه لا يستطيع صعود الدرج.', value: '4', score: 4 },
          { labelAr: '5 — يمشي دون مساعدة، لكنه لا يستطيع النهوض من الكرسي ولا صعود الدرج.', value: '5', score: 5 },
          { labelAr: '6 — يمشي فقط مع المساعدة، أو يمشي بصورة مستقلة باستخدام جبائر طويلة للساقين.', value: '6', score: 6 },
          { labelAr: '7 — يمشي بجبائر طويلة للساقين لكنه يحتاج مساعدة للموازنة.', value: '7', score: 7 },
          { labelAr: '8 — يستطيع الوقوف بجبائر طويلة للساقين لكنه لا يستطيع المشي حتى مع المساعدة.', value: '8', score: 8 },
          { labelAr: '9 — يستخدم الكرسي المتحرك.', value: '9', score: 9 },
          { labelAr: '10 — ملازم للسرير وفق تعريف المقياس.', value: '10', score: 10 },
        ],
      }, {
        code: 'VLERS-G3-PROTOCOL', labelAr: 'إذا كانت الدرجة 3 محتملة: معيار الزمن/عدد الدرجات المستخدم', type: 'text', noteAr: 'توجد صيغ منشورة مثل >12 ثانية لأربع درجات أو >25 ثانية لثماني درجات؛ لا تخلط بينهما في المتابعة.'
      }],
    }],
    scoringSteps: ['سجل درجة واحدة من 1 إلى 10 بحسب الوصف المطابق.', 'الدرجة الأعلى تعكس تقييدًا وظيفيًا أشد.', 'ثبت نسخة/تعريف المستوى 3 في جميع الزيارات.', 'وثق الأجهزة والمساعدة البشرية لأنها جزء جوهري من معنى المستوى.'],
    interpretationGuardrails: ['المقياس رتبي وخشن نسبيًا ولا يمثل كل أبعاد الوظيفة.', 'تغير جهاز مساعد أو بيئة الدرج قد يغير الدرجة دون تغير فسيولوجي مكافئ.', 'لا تستخدمه وحده لقرارات أهلية علاج أو تأهيل.'],
    stopRules: ['لا تطلب تجربة درج أو نهوض غير آمنة؛ خطر السقوط أو الإجهاد القلبي/التنفسي مقدم على استكمال التصنيف.'],
    officialDownloads: [{ label: 'CDISC QRS — Vignos Lower Extremity Rating Scale', url: 'https://www.cdisc.org/standards/foundational/qrs/vignos-lower-extremity-rating-scale', language: 'en', publisher: 'CDISC' }],
    sourceUrls: ['https://www.cdisc.org/standards/foundational/qrs/vignos-lower-extremity-rating-scale', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3482408/', 'https://link.springer.com/article/10.1007/s40120-020-00206-3'],
    lastVerifiedOn: '2026-09-06',
  },

  'four-stair-ascend': {
    slug: 'four-stair-ascend',
    kind: 'protocol-sheet',
    completeness: 'standardized-protocol-sheet',
    titleAr: 'اختبار صعود أربع درجات — ورقة التطبيق',
    titleEn: '4-Stair Ascend',
    version: 'CDISC QRS FT v1.0 construct',
    provenance: 'CDISC يصنف 4-Stair Ascend ضمن Public Domain. Controlled Terminology يتضمن على الأقل: هل نُفذ الاختبار، زمن الصعود، استخدام orthoses، وTest Grade.',
    rightsNotice: 'الاختبار Public Domain. تفاصيل ارتفاع الدرج، نقطة بدء/إيقاف التوقيت، عدد المحاولات وTest Grade يجب أن تثبت من بروتوكول الدراسة/النسخة المرجعية ولا تُخترع محليًا.',
    intendedUseAr: 'تسجيل أداء صعود أربع درجات بصورة موقوتة وقابلة للمقارنة، خصوصًا في المتابعة العصبية العضلية.',
    respondentFields: ['الاسم/الرمز', 'التاريخ', 'الفاحص', 'ارتفاع/مواصفات الدرج', 'نسخة البروتوكول', 'الأجهزة/الجبائر'],
    preflightChecks: ['استخدم أربع درجات ثابتة وآمنة ومواصفات موثقة.', 'حدد قبل القياس نقطة بدء وإيقاف المؤقت.', 'وفر حارس أمان مناسبًا دون تقديم مساعدة تغير الأداء إلا إذا كان البروتوكول يسمح بذلك.', 'ثبت تعليمات استخدام الدرابزين/الجبائر وعدد المحاولات بين الزيارات.'],
    sections: [{
      titleAr: 'التطبيق والتسجيل',
      items: [
        { code: 'A4STR-PERFORMED', labelAr: 'هل تم تنفيذ صعود الأربع درجات؟', type: 'choice', options: yesNo },
        { code: 'A4STR-T1', labelAr: 'زمن المحاولة 1', type: 'time', unit: 'ثانية' },
        { code: 'A4STR-T2', labelAr: 'زمن المحاولة 2 — إذا كان البروتوكول يتطلبها', type: 'time', unit: 'ثانية' },
        { code: 'A4STR-ORTHOSES', labelAr: 'هل استُخدمت جبائر/Orthoses؟', type: 'choice', options: yesNoNA },
        { code: 'A4STR-HANDRAIL', labelAr: 'استخدام الدرابزين/دعم اليد', type: 'text' },
        { code: 'A4STR-GRADE', labelAr: 'Test Grade وفق النسخة المرجعية — إن كان مطلوبًا', type: 'text' },
        { code: 'A4STR-STRATEGY', labelAr: 'الاستراتيجية/التعويضات أو المساعدة المسموح بها', type: 'text' },
        { code: 'A4STR-STOP', labelAr: 'سبب عدم التنفيذ/الإيقاف إن وجد', type: 'text' },
      ],
    }],
    scoringSteps: ['سجل الزمن بالثواني وفق نقطة البدء/النهاية المحددة في بروتوكولك.', 'إذا كانت هناك محاولات متعددة، استخدم قاعدة الاختيار المحددة مسبقًا في البروتوكول (مثل أفضل/أول/متوسط) ولا تخترعها بعد رؤية النتيجة.', 'سجل عدم القدرة على الأداء كحالة منفصلة؛ لا تستبدلها بزمن اعتباطي.', 'وثق orthoses والدرابزين والمساعدة والتعويضات لأنها تؤثر في المقارنة.'],
    interpretationGuardrails: ['الزمن يتأثر بمواصفات الدرج والتعليمات والأجهزة.', 'البيانات الأقوى تاريخيًا في الأمراض العصبية العضلية مثل DMD؛ لا تعمم العتبات على كل السكان.', 'التغير في الزمن ليس تشخيصًا ولا سببًا كافيًا منفردًا لقرار علاجي.'],
    stopRules: ['أوقف الاختبار عند خطر سقوط، ألم حاد، دوخة، ضيق نفس غير آمن أو عجز وظيفي يجعل الصعود غير آمن.'],
    officialDownloads: [{ label: 'CDISC QRS — 4-Stair Ascend Public Domain listing', url: 'https://www.cdisc.org/standards/foundational/qrs', language: 'en', publisher: 'CDISC' }],
    sourceUrls: ['https://www.cdisc.org/standards/foundational/qrs', 'https://pubmed.ncbi.nlm.nih.gov/25539097/', 'https://pubmed.ncbi.nlm.nih.gov/30562905/'],
    lastVerifiedOn: '2026-09-06',
  },

  'four-stair-descend': {
    slug: 'four-stair-descend',
    kind: 'protocol-sheet',
    completeness: 'standardized-protocol-sheet',
    titleAr: 'اختبار نزول أربع درجات — ورقة التطبيق',
    titleEn: '4-Stair Descend',
    version: 'CDISC QRS FT/ADaM v1.0 construct',
    provenance: 'CDISC يصنف 4-Stair Descend ضمن Public Domain. هذه الورقة تحفظ التوقيت والعوامل التي يجب توثيقها دون اختراع Test Grade أو إعداد درج غير موثق.',
    rightsNotice: 'الاختبار Public Domain. مواصفات الدرج والتوقيت والمساعدة والـTest Grade يجب أن تتبع النسخة/البروتوكول المحدد.',
    intendedUseAr: 'تسجيل أداء نزول أربع درجات بصورة موقوتة وقابلة للمقارنة، مع توثيق الدعم والاستراتيجية والسلامة.',
    respondentFields: ['الاسم/الرمز', 'التاريخ', 'الفاحص', 'ارتفاع/مواصفات الدرج', 'نسخة البروتوكول', 'الأجهزة/الجبائر'],
    preflightChecks: ['قيّم خطر السقوط قبل بدء النزول.', 'ثبت نقطة بدء وإيقاف المؤقت.', 'حدد تعليمات الدرابزين/الجبائر والمساعدة وعدد المحاولات قبل القياس.', 'ضع حارس أمان بطريقة لا تغير الأداء إلا حسب البروتوكول.'],
    sections: [{
      titleAr: 'التطبيق والتسجيل',
      items: [
        { code: 'D4STR-PERFORMED', labelAr: 'هل تم تنفيذ نزول الأربع درجات؟', type: 'choice', options: yesNo },
        { code: 'D4STR-T1', labelAr: 'زمن المحاولة 1', type: 'time', unit: 'ثانية' },
        { code: 'D4STR-T2', labelAr: 'زمن المحاولة 2 — إذا كان البروتوكول يتطلبها', type: 'time', unit: 'ثانية' },
        { code: 'D4STR-ORTHOSES', labelAr: 'هل استُخدمت جبائر/Orthoses؟', type: 'choice', options: yesNoNA },
        { code: 'D4STR-HANDRAIL', labelAr: 'استخدام الدرابزين/دعم اليد', type: 'text' },
        { code: 'D4STR-GRADE', labelAr: 'Test Grade وفق النسخة المرجعية — إن كان مطلوبًا', type: 'text' },
        { code: 'D4STR-STRATEGY', labelAr: 'الاستراتيجية/التعويضات أو المساعدة المسموح بها', type: 'text' },
        { code: 'D4STR-STOP', labelAr: 'سبب عدم التنفيذ/الإيقاف إن وجد', type: 'text' },
      ],
    }],
    scoringSteps: ['سجل الزمن بالثواني وفق التعريف المسبق.', 'استخدم قاعدة المحاولات المحددة في البروتوكول نفسه.', 'عدم القدرة/عدم الأمان نتيجة وصفية مستقلة، وليس زمنًا اصطناعيًا.', 'وثق الأجهزة والدرابزين والمساعدة والتعويضات.'],
    interpretationGuardrails: ['نزول الدرج قد يكون أكثر حساسية للتحكم اللامركزي والخوف من السقوط.', 'اختلاف ارتفاع الدرج أو الدرابزين يغير قابلية المقارنة.', 'فسر التغير مع بقية المقاييس الوظيفية ولا تستخدمه منفردًا لاتخاذ قرار عالي المخاطر.'],
    stopRules: ['أوقف عند خطر سقوط أو ألم أو دوخة أو عدم اتزان أو إجهاد غير آمن.'],
    officialDownloads: [{ label: 'CDISC QRS — 4-Stair Descend', url: 'https://www.cdisc.org/standards/foundational/qrs/4-stair-descend-0', language: 'en', publisher: 'CDISC' }],
    sourceUrls: ['https://www.cdisc.org/standards/foundational/qrs/4-stair-descend-0', 'https://pubmed.ncbi.nlm.nih.gov/25539097/', 'https://pubmed.ncbi.nlm.nih.gov/30562905/'],
    lastVerifiedOn: '2026-09-06',
  },

  'rising-from-floor': {
    slug: 'rising-from-floor',
    kind: 'protocol-sheet',
    completeness: 'standardized-protocol-sheet',
    titleAr: 'اختبار النهوض من الأرض — ورقة التطبيق',
    titleEn: 'Rising From Floor',
    version: 'CDISC QRS FT construct',
    provenance: 'CDISC يصنف Rising From Floor ضمن Public Domain. الاختبار يستخدم في DMD والمتابعة العصبية العضلية مع أهمية تثبيت وضع البداية والتوقيت والاستراتيجية.',
    rightsNotice: 'الاختبار Public Domain. يجب الالتزام بتعريف وضع البداية والنهاية وعدد المحاولات في البروتوكول المحدد؛ لا تُنشئ عتبة محلية غير موثقة.',
    intendedUseAr: 'تسجيل القدرة والزمن والاستراتيجية اللازمة للانتقال من الأرض إلى الوقوف بصورة قابلة للمتابعة.',
    respondentFields: ['الاسم/الرمز', 'التاريخ', 'الفاحص', 'سطح الأرض', 'وضع البداية المحدد', 'الأجهزة/الدعم'],
    preflightChecks: ['تأكد من أمان الأرض والمساحة المحيطة.', 'حدد وضع البداية ونقطة نهاية التوقيت مسبقًا.', 'وثق ما إذا كان استخدام اليدين على الجسم/الأثاث أو مساعدة خارجية مسموحًا.', 'لا تطلب المهمة إذا كان السقوط أو الإجهاد غير آمن.'],
    sections: [{
      titleAr: 'التطبيق والتسجيل',
      items: [
        { code: 'RFF-PERFORMED', labelAr: 'هل استطاع المشارك تنفيذ النهوض وفق البروتوكول؟', type: 'choice', options: yesNo },
        { code: 'RFF-T1', labelAr: 'زمن المحاولة 1', type: 'time', unit: 'ثانية' },
        { code: 'RFF-T2', labelAr: 'زمن المحاولة 2 — إذا كان البروتوكول يتطلبها', type: 'time', unit: 'ثانية' },
        { code: 'RFF-STRATEGY', labelAr: 'استراتيجية النهوض/علامة Gowers أو استخدام اليدين والدعم', type: 'text' },
        { code: 'RFF-ASSIST', labelAr: 'مساعدة بشرية أو جهاز/سطح مساعد', type: 'text' },
        { code: 'RFF-GRADE', labelAr: 'Test Grade/تصنيف الأداء وفق النسخة المرجعية — إن وُجد', type: 'text' },
        { code: 'RFF-STOP', labelAr: 'سبب عدم التنفيذ أو الإيقاف', type: 'text' },
      ],
    }],
    scoringSteps: ['سجل القدرة على إكمال المهمة والزمن وفق نقاط التوقيت المحددة مسبقًا.', 'إذا كانت هناك محاولات متعددة فطبّق قاعدة البروتوكول نفسها في كل زيارة.', 'سجل الاستراتيجية والتعويضات لأنها قد تتغير حتى قبل تغير الزمن بوضوح.', 'عدم القدرة نتيجة ذات معنى ولا ينبغي تحويلها إلى زمن رقمي اعتباطي.'],
    interpretationGuardrails: ['الوضع الأولي وسطح الأرض والتعليمات والتعويضات تؤثر في الزمن.', 'أفضل الأدلة متاحة في DMD؛ لا تنقل معايير التفسير مباشرة إلى أمراض أخرى.', 'الاختبار يقيس وظيفة مركبة ولا يعزل قوة عضلة واحدة.'],
    stopRules: ['أوقف عند خطر سقوط، ألم حاد، دوخة، ضيق نفس غير آمن أو عدم قدرة على استكمال الانتقال بأمان.'],
    officialDownloads: [{ label: 'CDISC QRS — Rising From Floor', url: 'https://www.cdisc.org/standards/foundational/qrs/rising-floor', language: 'en', publisher: 'CDISC' }],
    sourceUrls: ['https://www.cdisc.org/standards/foundational/qrs/rising-floor', 'https://pubmed.ncbi.nlm.nih.gov/26982196/', 'https://pubmed.ncbi.nlm.nih.gov/40680325/'],
    lastVerifiedOn: '2026-09-06',
  },
};
