import type { AssessmentMeasure } from '@/lib/assessment-measures';

const CDISC_QRS = 'https://www.cdisc.org/standards/foundational/qrs';

export const assessmentMeasuresWave6: AssessmentMeasure[] = [
  {
    slug: 'alcohol-use-disorders-identification-test-consumption',
    nameAr: 'اختبار تحديد اضطرابات استخدام الكحول — أسئلة الاستهلاك',
    nameEn: 'Alcohol Use Disorders Identification Test - Consumption Questions',
    acronym: 'AUDIT-C',
    version: '3-item consumption screen',
    summary: 'أداة فحص مختصرة من ثلاثة أسئلة مشتقة من AUDIT لتقدير أنماط استهلاك الكحول التي قد تستدعي تقييمًا أوسع.',
    purpose: 'الفحص الأولي للاستخدام الخطر أو الضار للكحول وتحديد من قد يستفيد من تقييم كامل مثل AUDIT أو مقابلة سريرية.',
    construct: 'نمط وكمية وتواتر استهلاك الكحول',
    populations: ['البالغون في الرعاية الأولية والبحوث السكانية', 'مجتمعات سريرية مختلفة بعد تحقق مناسب'],
    settings: ['الرعاية الأولية', 'الصحة السلوكية', 'الإدمان والتعافي', 'البحوث السكانية'],
    categories: ['substance-use-addiction', 'mental-health'],
    administrationMode: 'تقرير ذاتي أو مقابلة قصيرة من ثلاثة أسئلة عن الاستهلاك.',
    administrationTime: 'عادةً أقل من دقيقتين.',
    equipment: ['نسخة AUDIT-C المحددة', 'تعريف واضح للمشروب القياسي والفترة المرجعية'],
    scoring: 'تسجل البنود الثلاثة عادةً من 0 إلى 4 ويجمع المجموع من 0 إلى 12. العتبات المثلى تختلف حسب الجنس والمجتمع والغرض السريري، لذلك لا تعتمد روافد قطعًا واحدًا عالميًا.',
    interpretation: 'الدرجة الأعلى تشير إلى احتمال أكبر للاستخدام الخطر أو اضطراب استخدام الكحول، لكنها فحص وليست تشخيصًا. يجب تفسيرها وفق المجتمع المستهدف ثم استكمال التقييم عند الحاجة.',
    limitations: ['العتبات تختلف بين الدراسات والمجتمعات.', 'يعتمد على الإفصاح الذاتي وقد يتأثر بالوصمة أو الخوف من العواقب.', 'لا يغطي وحده الضرر والاعتماد والسياق الاجتماعي كما يفعل AUDIT الكامل.'],
    administrationSteps: ['وضح معنى المشروب القياسي بما يناسب البلد والسياق.', 'اطرح البنود الثلاثة بالصياغة المعتمدة للنسخة المستخدمة.', 'اجمع الدرجة دون تحويلها إلى تشخيص.', 'إذا تجاوزت النتيجة العتبة المعتمدة محليًا أو ظهرت مخاطر أخرى، انتقل إلى تقييم أوسع.'],
    safetyNotes: ['الاشتباه بانسحاب كحولي شديد أو تسمم حاد أو خطر طبي يحتاج تقييمًا عاجلًا مستقلًا عن الدرجة.', 'لا تستخدم النتيجة وحدها لتقرير علاج دوائي أو تشخيص اضطراب استخدام الكحول.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج AUDIT-C بحالة Public Domain. أي ترجمة عربية بعينها أو تعريف محلي للمشروب القياسي يحتاج توثيقًا منفصلًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'الدليل العربي المباشر للنسخة المختصرة يحتاج تثبيتًا',
    arabicNote: 'توجد بيانات عربية للـAUDIT الكامل، لكننا لا نعاملها تلقائيًا كتحقق مستقل للـAUDIT-C في جميع المجتمعات العربية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا ننشر صياغة عربية كاملة قبل مطابقة ترجمة محددة للثلاثة بنود وحقوقها وسياق المشروب القياسي.',
    sources: [
      { label: 'CDISC QRS — AUDIT-C Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — AUDIT-C as a brief screen in primary care', url: 'https://pubmed.ncbi.nlm.nih.gov/17451397/', role: 'evidence' },
      { label: 'PubMed — AUDIT and AUDIT-C validation in a general population', url: 'https://pubmed.ncbi.nlm.nih.gov/25623414/', role: 'evidence' },
    ],
    related: ['alcohol-use-disorders-identification-test-self-report', 'minnesota-tobacco-withdrawal-scale-revised'],
  },
  {
    slug: 'alcohol-use-disorders-identification-test-self-report',
    nameAr: 'اختبار تحديد اضطرابات استخدام الكحول — نسخة التقرير الذاتي',
    nameEn: 'Alcohol Use Disorders Identification Test - Self-Report Version',
    acronym: 'AUDIT-SR',
    version: '10-item self-report version',
    summary: 'نسخة تقرير ذاتي من AUDIT لتقدير الاستهلاك والمشكلات المرتبطة بالكحول ومؤشرات الاعتماد المحتمل ضمن فحص منظم.',
    purpose: 'الفحص المنظم للاستخدام الخطر والضار للكحول ومؤشرات اضطراب استخدامه، ودعم قرار الانتقال إلى تقييم أو تدخل مناسب.',
    construct: 'استهلاك الكحول والعواقب ومؤشرات الاعتماد',
    populations: ['البالغون في الرعاية الصحية والمجتمع', 'مجتمعات خاصة بعد تحقق مستقل'],
    settings: ['الرعاية الأولية', 'الإدمان والتعافي', 'الصحة النفسية', 'البحوث'],
    categories: ['substance-use-addiction', 'mental-health'],
    administrationMode: 'تقرير ذاتي من عشرة بنود وفق النسخة والفترة المرجعية المحددتين.',
    administrationTime: 'نحو 2–5 دقائق غالبًا.',
    equipment: ['نسخة AUDIT-SR الموثقة', 'تعريف المشروب القياسي المناسب للسياق'],
    scoring: 'تجمع الدرجات وفق قواعد AUDIT القياسية. العتبات توجه الفحص ولا تستبدل المقابلة التشخيصية، كما أن الحساسية والنوعية تتغيران باختلاف المجتمع والغرض.',
    interpretation: 'المجموع الأعلى يعكس نمطًا أكثر خطورة أو ضررًا. يجب قراءة مجالات الاستهلاك والعواقب والاعتماد مع التاريخ السريري والسياق الاجتماعي والقانوني.',
    limitations: ['يعتمد على الإفصاح الذاتي.', 'العتبات والخصائص التشخيصية تختلف باختلاف المجتمع.', 'التعريفات المحلية للمشروب القياسي قد تغير الإجابات.', 'لا يحدد شدة الانسحاب أو المخاطر الطبية الحادة.'],
    administrationSteps: ['حدد صيغة التقرير الذاتي والفترة المرجعية.', 'قدم تعريفًا واضحًا للمشروب القياسي.', 'اسمح بالإجابة الخاصة دون ضغط يزيد نقص الإفصاح.', 'احسب الدرجة وفق القواعد الأصلية.', 'استخدم النتيجة لتوجيه تقييم أوسع أو تدخل مختصر عند الحاجة.'],
    safetyNotes: ['الانسحاب الشديد أو تاريخ الاختلاجات الانسحابية أو الهذيان يحتاج مسارًا طبيًا متخصصًا.', 'النتيجة لا تكفي وحدها للتشخيص أو تحديد خطة إزالة السموم.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج AUDIT-SR بحالة Public Domain. حقوق الترجمة العربية المنشورة تبقى مرتبطة بالنسخة والمصدر المحددين.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'validated-version-reported',
    arabicLabel: 'يوجد تحقق عربي منشور محدود بالسياق',
    arabicNote: 'دراسة في الإمارات اختبرت ترجمة عربية لـAUDIT لدى 107 سجناء مسلمين ذكور ووجدت اتساقًا داخليًا وصدقًا تنبؤيًا جيدين؛ لا نعمم تلك النتائج على النساء أو المجتمع العام أو جميع البلدان العربية.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'وجود دراسة عربية لا يثبت تلقائيًا حق إعادة نشر نص الترجمة بعينه؛ نحتاج تثبيت مصدر الصياغة وشروطها قبل عرض البنود كاملة.',
    sources: [
      { label: 'CDISC QRS — AUDIT-SR Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'WHO — AUDIT guidelines for use in primary care', url: 'https://www.who.int/publications/i/item/WHO-MSD-MSB-01.6a', role: 'original' },
      { label: 'PubMed — Arabic AUDIT validation in a UAE prison sample', url: 'https://pubmed.ncbi.nlm.nih.gov/20001691/', role: 'translation' },
      { label: 'PubMed — general-population validation of AUDIT and AUDIT-C', url: 'https://pubmed.ncbi.nlm.nih.gov/25623414/', role: 'evidence' },
    ],
    related: ['alcohol-use-disorders-identification-test-consumption', 'minnesota-tobacco-withdrawal-scale-revised'],
  },
  {
    slug: 'rey-auditory-verbal-learning-test',
    nameAr: 'اختبار ري للتعلم اللفظي السمعي',
    nameEn: 'Rey Auditory Verbal Learning Test',
    acronym: 'RAVLT',
    version: 'Rey Auditory Verbal Learning Test',
    summary: 'اختبار أداء عصبي نفسي للقائمة اللفظية يقيس التعلم عبر المحاولات والتذكر والتداخل والاحتفاظ، ويحتاج معايير لغوية وسكانية مناسبة.',
    purpose: 'توصيف التعلم اللفظي والذاكرة السمعية اللفظية ضمن بطارية عصبية نفسية أوسع.',
    construct: 'التعلم اللفظي والذاكرة الفورية والمؤجلة والتداخل',
    populations: ['البالغون في التقييم العصبي النفسي', 'الشيخوخة وإصابات الدماغ والاضطرابات العصبية وفق معايير مناسبة'],
    settings: ['علم النفس العصبي', 'طب الأعصاب', 'التأهيل العصبي', 'البحوث المعرفية'],
    categories: ['cognition-neuropsychology', 'neurological-outcomes', 'brain-injury'],
    administrationMode: 'اختبار أداء يتضمن تعلم قائمة كلمات عبر محاولات متكررة، قائمة تداخل، واستدعاء فوري أو مؤجل وفق البروتوكول.',
    administrationTime: 'نحو 10–20 دقيقة للتطبيق المباشر إضافة إلى فترة التأخير عند قياس الاستدعاء المؤجل.',
    equipment: ['قوائم الكلمات الخاصة بالنسخة اللغوية', 'مؤقت', 'نموذج تسجيل الاستجابات والأخطاء'],
    scoring: 'يمكن اشتقاق درجات متعددة مثل تعلم المحاولات، الاستدعاء بعد التداخل، الاستدعاء المؤجل، الأخطاء والتعرف. لا تختزل النتائج في مجموع واحد دون تحديد المتغير المقصود.',
    interpretation: 'التفسير يعتمد بشدة على العمر والجنس والتعليم واللغة وطريقة العرض ومعايير النسخة. الدراسات المعيارية الكبيرة تظهر تأثيرات ديموغرافية مهمة، لذلك لا تنقل المعايير بين اللغات أو البلدان.',
    limitations: ['قوائم الكلمات ليست متكافئة تلقائيًا بين اللغات.', 'العمر والجنس والتعليم يؤثرون في الأداء.', 'طريقة العرض وإجراءات التأخير قد تغير النتائج.', 'لا يشخص اضطراب ذاكرة أو خرفًا بمفرده.'],
    administrationSteps: ['اختر نسخة لغوية ومعايير سكانية مناسبة.', 'ثبت ترتيب المحاولات وتعليمات التذكر والتداخل.', 'سجل الاستجابات حرفيًا والأخطاء والتكرارات.', 'احترم زمن التأخير إذا كان جزءًا من البروتوكول.', 'فسر كل مؤشر مقابل معايير النسخة نفسها.'],
    safetyNotes: ['لا تستخدم قائمة مترجمة محليًا مع معايير إنجليزية.', 'تفسير الأداء يحتاج خبرة في القياس العصبي النفسي والعوامل اللغوية والتعليمية.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Rey Auditory Verbal Learning Test بحالة Public Domain. القوائم المترجمة أو المعايير المنشورة من جهات أخرى قد تحمل حقوقًا منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لا توجد قائمة عربية مرجعية موحدة مثبتة في سجلنا بعد',
    arabicNote: 'بسبب أثر اللغة وتواتر الكلمات والثقافة لا نترجم القائمة حرفيًا؛ نحتاج نسخة عربية منشورة ومعاييرها قبل توفير بروتوكول عربي كامل.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'نشرح المنهج والحدود فقط إلى أن نثبت قائمة عربية معيارية ومصدرها وحقوقها.',
    sources: [
      { label: 'CDISC QRS — Rey AVLT Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — normative data and effects of age, sex, education and presentation', url: 'https://pubmed.ncbi.nlm.nih.gov/15892905/', role: 'evidence' },
      { label: 'PubMed — updated Mayo normative data and sex adjustment', url: 'https://pubmed.ncbi.nlm.nih.gov/32815494/', role: 'evidence' },
    ],
    related: ['controlled-oral-word-association-test', 'mayo-portland-adaptability-inventory-4'],
  },
  {
    slug: 'rockport-one-mile-walk-test',
    nameAr: 'اختبار روكبورت للمشي لمسافة ميل واحد',
    nameEn: 'Rockport One Mile Walk Test',
    acronym: 'Rockport 1MWT',
    version: 'Rockport One Mile Walk Test V1.0',
    summary: 'اختبار ميداني للمشي لمسافة ميل واحد يستخدم الزمن ومعدل القلب وخصائص الشخص لتقدير القدرة الهوائية؛ صلاحية معادلاته تعتمد على المجتمع وطريقة التنفيذ.',
    purpose: 'تقدير القدرة الهوائية بصورة ميدانية منخفضة الكلفة لدى أشخاص قادرين على إكمال مشي سريع لمسافة ميل بأمان.',
    construct: 'القدرة الهوائية المقدرة من أداء المشي',
    populations: ['البالغون القادرون على المشي لمسافة ميل', 'مجتمعات اللياقة والتأهيل بعد فحص الملاءمة والسلامة'],
    settings: ['التأهيل', 'اللياقة الصحية', 'بحوث القدرة الهوائية'],
    categories: ['mobility-walking', 'rehabilitation-outcomes'],
    administrationMode: 'مشي مسافة ميل واحدة بأسرع سرعة مشي آمنة مع قياس الزمن ومعدل القلب النهائي وتطبيق المعادلة المعتمدة.',
    administrationTime: 'يعتمد على سرعة المشي؛ التطبيق العملي غالبًا في حدود 10–25 دقيقة مع الإعداد والتعافي.',
    equipment: ['مسار مقاس بدقة لمسافة ميل', 'مؤقت', 'وسيلة موثوقة لقياس معدل القلب', 'ميزان وبيانات العمر والجنس إذا تطلبت المعادلة'],
    scoring: 'تستخدم معادلات Rockport زمن إكمال الميل ومعدل القلب وعوامل ديموغرافية لتقدير VO2max. لا تنشر روافد حاسبة تلقائية لأن اختيار المعادلة والتحقق السكاني يجب أن يسبقا الحساب.',
    interpretation: 'الناتج تقدير للقدرة الهوائية وليس قياسًا مباشرًا بتبادل الغازات. صلاحية المعادلة تختلف بحسب العمر واللياقة وطريقة المشي والمسار أو جهاز المشي.',
    limitations: ['المعادلات مشتقة من مجتمعات محددة.', 'التغير في السطح أو جهاز المشي قد يغير الصلاحية.', 'الأدوية المؤثرة في معدل القلب والحالات القلبية قد تربك التقدير.', 'ليس بديلًا عن اختبار جهد قلبي رئوي عند الحاجة السريرية.'],
    administrationSteps: ['افحص موانع الاختبار ومخاطر الجهد أولًا.', 'استخدم مسارًا مقاسًا بدقة وتعليمات ثابتة.', 'سجل زمن الميل ومعدل القلب النهائي بدقة.', 'اختر المعادلة المناسبة للمجتمع والبروتوكول.', 'فسر التقدير مع حالة الشخص ولا تعامله كقياس VO2max مباشر.'],
    safetyNotes: ['ألم الصدر أو ضيق النفس غير المعتاد أو دوخة شديدة أثناء الاختبار يستدعي إيقافه وتقييمًا مناسبًا.', 'الأشخاص عالي الخطورة قد يحتاجون اختبارًا مراقبًا أو بديلًا أكثر أمانًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في صفحة CDISC الخاصة',
    rightsNote: 'صفحة CDISC الخاصة بـRockport One Mile Walk Test V1.0 تحدد Permission: Public Domain. حقوق أي معادلة مشتقة أو برنامج حساب مستقل تراجع منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'البروتوكول قابل للتوطين مع الحفاظ على القياس',
    arabicNote: 'تعليمات المشي قابلة للتوطين لغويًا، لكن المسافة والوحدات وطريقة قياس القلب والمعادلة يجب أن تبقى مطابقة للبروتوكول المستخدم.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'نقدم شرحًا تشغيليًا دون حاسبة تقدير تلقائية إلى أن تعتمد معادلة وسياق سكاني واضحان.',
    sources: [
      { label: 'CDISC QRS — Rockport One Mile Walk Test Public Domain', url: 'https://www.cdisc.org/standards/foundational/qrs/rockport-one-mile-walk-test', role: 'rights' },
      { label: 'PubMed — validation of a one-mile treadmill walk approach', url: 'https://pubmed.ncbi.nlm.nih.gov/12500996/', role: 'evidence' },
      { label: 'PubMed — Rockport VO2max estimation on a curved treadmill', url: 'https://pubmed.ncbi.nlm.nih.gov/23478472/', role: 'evidence' },
    ],
    related: ['6-minute-walk-test', '10-meter-walk-test'],
  },
  {
    slug: 'patient-global-impression',
    nameAr: 'الانطباع العالمي للمريض',
    nameEn: 'Patient Global Impression',
    acronym: 'PGI',
    version: 'Patient Global Impression family',
    summary: 'تقدير عالمي قصير يعبّر عن رؤية المريض لشدة حالته أو مقدار التحسن؛ قيمته الأساسية كمرساة ذاتية بسيطة مرتبطة بسياق مرضي محدد.',
    purpose: 'التقاط الانطباع العام للمريض عن الشدة أو التغير ودعمه كمؤشر مكمل للمقاييس التفصيلية أو كمرساة لتفسير التغير.',
    construct: 'الإدراك الذاتي العالمي لشدة الحالة أو التحسن',
    populations: ['مرضى في مجتمعات مرضية مختلفة بعد تحديد صيغة PGI وسياقها'],
    settings: ['البحوث السريرية', 'متابعة النتائج', 'الرعاية المتمحورة حول الشخص'],
    categories: ['rehabilitation-outcomes', 'symptom-burden'],
    administrationMode: 'سؤال عالمي واحد أو صيغة قصيرة جدًا يجيب عنها المريض حول الشدة أو التحسن حسب النسخة.',
    administrationTime: 'أقل من دقيقة عادةً.',
    equipment: ['صيغة PGI المحددة ومراسي الاستجابة المطابقة للسياق'],
    scoring: 'تختلف PGI-S عن PGI-I في السؤال والمراسي؛ لا تدمج الصيغتين في درجة واحدة. التسجيل رتبي ويجب ذكر النسخة والسياق المرضي.',
    interpretation: 'النتيجة تعكس منظور المريض العالمي ولا تحدد أي عرض تغيّر أو سبب التغير. دراسات تحقق في حالات محددة تدعم PGI-S/PGI-I كأدوات بسيطة، لكن الصدق لا يعمم تلقائيًا بين الأمراض.',
    limitations: ['مقياس عالمي أحادي البند نسبيًا.', 'يتأثر بتوقعات المريض وحالته الحالية وذاكرة خط الأساس.', 'التحقق سياقي ومرضي وليس عالميًا.', 'لا يستبدل المقاييس متعددة المجالات.'],
    administrationSteps: ['حدد هل المطلوب شدة أم تحسنًا.', 'استخدم صيغة ومراسي ثابتة طوال المتابعة.', 'سجل الاستجابة كما اختارها المريض.', 'فسرها كمرساة ذاتية مع نتائج أكثر تفصيلًا.'],
    safetyNotes: ['الانطباع الإيجابي أو السلبي لا يستبدل تقييم الأعراض الخطرة أو التدهور الطبي.', 'لا تستخدم PGI منفردًا لاتخاذ قرار علاجي عالي المخاطر.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Patient Global Impression بحالة Public Domain. يجب مع ذلك تحديد الصيغة الفعلية PGI-S أو PGI-I وسياقها وعدم نسخ نسخة معدلة مملوكة لطرف ثالث.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'قابل للتوطين لكن المراسي والسياق يجب تثبيتهما',
    arabicNote: 'الصياغة قصيرة لكن التكافؤ يعتمد على ترجمة مفاهيم الشدة والتحسن ومراسيها بصورة ثابتة داخل المرض أو الدراسة.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'نحتفظ بالصفحة كمرجع للصيغ والسياقات بدل إنشاء سؤال عربي واحد ندعي أنه صالح لكل الأمراض.',
    sources: [
      { label: 'CDISC QRS — Patient Global Impression Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — PGI-S and PGI-I construct validation in BPH-LUTS', url: 'https://pubmed.ncbi.nlm.nih.gov/23134716/', role: 'evidence' },
      { label: 'PubMed — PGI-I validation in another condition-specific setting', url: 'https://pubmed.ncbi.nlm.nih.gov/27999508/', role: 'evidence' },
    ],
    related: ['general-clinical-global-impression', 'patient-health-questionnaire-15'],
  },
  {
    slug: 'deployment-risk-resilience-inventory-2',
    nameAr: 'مخزون مخاطر ومرونة الانتشار العسكري — الإصدار الثاني',
    nameEn: 'Deployment Risk and Resilience Inventory-2',
    acronym: 'DRRI-2',
    version: 'DRRI-2 suite',
    summary: 'منظومة من 17 مقياسًا لتقييم عوامل الخطر والمرونة النفسية والاجتماعية المرتبطة بدورة الانتشار العسكري لدى العسكريين والمحاربين القدامى.',
    purpose: 'توصيف ضغوط وعوامل حماية مرتبطة بما قبل الانتشار وأثناءه وبعده ودراسة علاقتها بالصحة والتكيف.',
    construct: 'عوامل الخطر والمرونة المرتبطة بتجارب الانتشار العسكري',
    populations: ['العسكريون وأفراد الخدمة والمحاربون القدامى ذوو خبرات انتشار عسكري'],
    settings: ['الصحة النفسية العسكرية', 'بحوث المحاربين القدامى', 'برامج الوقاية والمرونة'],
    categories: ['trauma-stress', 'mental-health'],
    administrationMode: 'مجموعة مقاييس تقرير ذاتي مستقلة؛ تختار المقاييس الفرعية المناسبة لسؤال البحث أو التقييم.',
    administrationTime: 'يتغير حسب عدد المقاييس الفرعية المستخدمة؛ لا يلزم تطبيق المجموعة كاملة في كل سياق.',
    equipment: ['مقاييس DRRI-2 الفرعية المناسبة', 'دليل البنود والتسجيل المطابق للإصدار'],
    scoring: 'DRRI-2 ليس مجموعًا واحدًا؛ يتكون من 17 مقياسًا متميزًا. تسجل كل بنية بحسب قواعد المقياس الفرعي ولا تجمع المقاييس في درجة مرونة أو خطر محلية غير موثقة.',
    interpretation: 'المقاييس تصف عوامل انتشار عسكري وسياقًا نفسيًا اجتماعيًا، ولا تشخص PTSD أو الاكتئاب. التطوير الأصلي تضمن عينات وطنية من قدامى OEF/OIF وأظهر اتساقًا داخليًا وصدقًا معياريًا جيدين.',
    limitations: ['مصمم لسياق الانتشار العسكري الأمريكي أساسًا.', 'خبرات الحروب والقوات والثقافات الأخرى قد تختلف.', 'لا يمثل اختبار تشخيص اضطراب نفسي.', 'الترجمة تتطلب حساسية عالية للسياق العسكري المحلي.'],
    administrationSteps: ['حدد عوامل الخطر أو المرونة التي تحتاجها بدل تطبيق كل المقاييس تلقائيًا.', 'استخدم المقياس الفرعي وتعليماته كما نشر.', 'احسب كل مقياس منفصلًا.', 'اربط النتائج بتاريخ الخدمة والسياق الثقافي ولا تفسرها كتشخيص.'],
    safetyNotes: ['الأسئلة عن القتال والتحرش والفقد قد تثير ضيقًا؛ يجب توفير خيار التوقف ودعم مناسب.', 'الإفصاح عن خطر حالي أو عنف أو أعراض شديدة يحتاج تقييم سلامة مستقلًا.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج DRRI-2 بحالة Public Domain. أي ترجمة أو تكييف عسكري عربي يحتاج توثيقًا لغويًا وسياقيًا مستقلًا.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'لا توجد نسخة عربية معيارية مثبتة في سجلنا بعد',
    arabicNote: 'مصطلحات الانتشار والخدمة والقتال والعائلة شديدة الحساسية للسياق؛ لا نبني ترجمة محلية قبل برنامج تكييف واختبار مناسب.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'ننشر وصف المنظومة والمصادر فقط إلى أن تتوفر نسخة عربية موثقة ومراجعة حقوقيًا.',
    sources: [
      { label: 'CDISC QRS — DRRI-2 Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — DRRI-2 development and psychometric validation', url: 'https://pubmed.ncbi.nlm.nih.gov/24490250/', role: 'evidence' },
    ],
    related: ['combat-exposure-scale', 'ptsd-checklist-for-dsm5', 'life-events-checklist-dsm5-standard'],
  },
  {
    slug: 'psoriasis-area-severity-index-fredriksson',
    nameAr: 'مؤشر مساحة وشدة الصدفية — نسخة فريدريكسون',
    nameEn: 'Psoriasis Area and Severity Index Version Fredriksson',
    acronym: 'PASI-F',
    version: 'Fredriksson PASI',
    summary: 'مؤشر سريري يجمع مساحة إصابة الصدفية وشدة الاحمرار والتثخن والقشور عبر مناطق الجسم، وهو واسع الاستخدام في التجارب والمتابعة لكنه يتأثر باختلاف المقيمين.',
    purpose: 'تقدير شدة الصدفية الجلدية بصورة كمية ومتابعة الاستجابة للعلاج في الأبحاث والممارسة المنظمة.',
    construct: 'مساحة وشدة إصابة الصدفية',
    populations: ['الأشخاص المصابون بالصدفية اللويحية وغيرها من السياقات التي تحقق فيها PASI'],
    settings: ['الأمراض الجلدية', 'التجارب السريرية', 'متابعة علاج الصدفية'],
    categories: ['dermatology', 'symptom-burden'],
    administrationMode: 'تقييم سريري لأربع مناطق جسم مع تقدير المساحة وشدة ثلاث علامات جلدية ثم تطبيق الأوزان المحددة.',
    administrationTime: 'عادةً 5–10 دقائق للفاحص المدرب، وقد تزيد مع الحالات المعقدة.',
    equipment: ['تعريفات PASI Fredriksson', 'نموذج تسجيل المناطق والأوزان'],
    scoring: 'تنتج الدرجة الكلية تقليديًا من 0 إلى 72 عبر أوزان المناطق ومساحة الإصابة وشدة الحمامى والتثخن والقشور. يجب استخدام نسخة Fredriksson نفسها عند المقارنة وعدم خلطها بصيغ PASI أخرى.',
    interpretation: 'الدرجة الأعلى تعكس صدفية جلدية أشد، لكنها لا تقيس الحكة أو الألم أو نوعية الحياة بالكامل. الاتفاق بين المقيمين قد يتراجع خصوصًا في بعض نطاقات الشدة، لذلك التدريب مهم.',
    limitations: ['يتضمن تقديرات بصرية ذاتية نسبيًا.', 'اختلاف المقيمين قد يؤثر في القرار القائم على عتبات PASI.', 'لا يغطي العبء النفسي أو المفاصل أو فروة الرأس والأظافر بصورة كافية دائمًا.', 'توجد صيغ PASI متعددة في المراجع ويجب تحديد النسخة.'],
    administrationSteps: ['ثبت نسخة Fredriksson وتعريفات المناطق.', 'قدّر مساحة الإصابة في كل منطقة.', 'قيّم الاحمرار والتثخن والقشور بالمراسي القياسية.', 'طبق أوزان المناطق والصيغة المحددة.', 'وثق المقيّم والنسخة عند المتابعة.'],
    safetyNotes: ['PASI ليس أداة تشخيص للصدفية ولا يستبدل الفحص الجلدي.', 'قرارات علاجية عالية المخاطر يجب ألا تعتمد على فرق صغير في PASI دون مراعاة التباين بين المقيمين والسياق السريري.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — نسخة Fredriksson موثقة في CDISC QRS',
    rightsNote: 'CDISC يدرج PASI Fredriksson وبقية عدة صيغ PASI بحالة Public Domain. روافد يحدد النسخة صراحة حتى لا يخلط التعريفات أو الأوزان بين الصيغ.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'المصطلحات السريرية قابلة للتوطين مع تدريب موحد',
    arabicNote: 'المشكلة الأساسية ليست اللغة فقط بل اتفاق الفاحصين؛ يجب تثبيت ترجمة العلامات والمراسي وتدريب المقيمين قبل الاستخدام المؤسسي.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'ننشر شرح المنهج ولا نوفر حاسبة قرار علاجي أو عتبات محلية غير معايرة.',
    sources: [
      { label: 'CDISC QRS — PASI Fredriksson Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — PASI inter-rater concordance', url: 'https://pubmed.ncbi.nlm.nih.gov/21152786/', role: 'evidence' },
      { label: 'PubMed — limitations of PASI agreement for therapeutic decisions', url: 'https://pubmed.ncbi.nlm.nih.gov/22592157/', role: 'evidence' },
      { label: 'PubMed — comparison of PASI reliability with other psoriasis measures', url: 'https://pubmed.ncbi.nlm.nih.gov/29068583/', role: 'evidence' },
    ],
    related: [],
  },
  {
    slug: 'crohns-disease-activity-index-v1',
    nameAr: 'مؤشر نشاط داء كرون — الإصدار الأول',
    nameEn: "Crohn's Disease Activity Index Version 1",
    acronym: 'CDAI V1',
    version: 'Version 1',
    summary: 'مؤشر مركب من ثمانية متغيرات تاريخيًا لقياس نشاط داء كرون في التجارب السريرية، ويضم أعراضًا ومؤشرات سريرية ومخبرية ويحتاج تفسيرًا حذرًا بسبب مكوناته الذاتية.',
    purpose: 'تقدير نشاط داء كرون بصورة مركبة، خصوصًا في البحوث والتجارب السريرية ومقارنة الاستجابة.',
    construct: 'نشاط داء كرون السريري المركب',
    populations: ['البالغون المصابون بداء كرون ضمن سياقات التقييم التي تستخدم CDAI'],
    settings: ['أمراض الجهاز الهضمي', 'التجارب السريرية', 'بحوث أمراض الأمعاء الالتهابية'],
    categories: ['gastroenterology', 'symptom-burden'],
    administrationMode: 'تجميع بيانات يومية وسريرية ومخبرية لثمانية متغيرات ثم تطبيق أوزان وصيغة CDAI.',
    administrationTime: 'لا يمثل زيارة واحدة قصيرة؛ يتطلب بيانات أعراض عبر عدة أيام إضافة إلى الفحص والمختبر حسب البروتوكول.',
    equipment: ['سجل أعراض مطابق للبروتوكول', 'بيانات الفحص والوزن', 'الهيماتوكريت وبقية المدخلات المطلوبة', 'صيغة CDAI V1'],
    scoring: 'المؤشر الأصلي يوزن ثمانية متغيرات. تاريخيًا ارتبط ≤150 بخمول المرض و>150 بالنشاط و>450 بالشدة العالية، لكن هذه الحدود نشأت في سياق تطوير المؤشر ولا تستبدل التقييم المعاصر للالتهاب أو التنظير أو المؤشرات الحيوية.',
    interpretation: 'CDAI مفيد تاريخيًا كنقطة نهاية بحثية، لكنه يتضمن أعراضًا ذاتية وقد لا يتطابق مع الالتهاب الموضوعي. يجب ذكر البروتوكول وطريقة جمع البيانات عند المقارنة.',
    limitations: ['بعض المكونات ذاتية وتتأثر باضطرابات وظيفية أو أعراض غير التهابية.', 'الت reproducibility قد تتأثر بطريقة جمع البيانات والمقيم.', 'لا يساوي شدة الالتهاب التنظيري أو البيوكيميائي.', 'هناك اختلافات في التطبيق بين الدراسات.'],
    administrationSteps: ['حدد CDAI V1 وبروتوكول جمع البيانات قبل البدء.', 'اجمع الأعراض للفترة المطلوبة بدل الاعتماد على تذكر لحظي.', 'أدخل المتغيرات السريرية والمخبرية بدقة.', 'طبق الأوزان الأصلية دون تعديل محلي.', 'فسر الدرجة مع مؤشرات الالتهاب والتقييم المتخصص.'],
    safetyNotes: ['ألم بطني شديد أو انسداد محتمل أو نزف أو حمى أو تدهور حاد يحتاج تقييمًا طبيًا عاجلًا مستقلًا عن CDAI.', 'لا تستخدم الدرجة وحدها لبدء أو إيقاف علاج مناعي أو بيولوجي.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — CDAI V1 موثق في CDISC QRS',
    rightsNote: 'CDISC يدرج Crohn’s Disease Activity Index Version 1 بحالة Public Domain. أدوات مشتقة أو مختصرة أو منصات حساب مستقلة قد تحمل شروطًا مختلفة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'version-review-required',
    arabicLabel: 'التطبيق العربي يحتاج تثبيت نموذج جمع البيانات والمصطلحات',
    arabicNote: 'لا ننشئ ترجمة عربية تشغيلية كاملة قبل مراجعة كل عنصر وصياغة سجل الأعراض ومطابقته للإصدار المرجعي.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لا نوفر حاسبة آلية أو توصية علاجية؛ الصفحة تشرح المؤشر وتربطه بمصادره وحدوده.',
    sources: [
      { label: 'CDISC QRS — CDAI V1 Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — original development of CDAI', url: 'https://pubmed.ncbi.nlm.nih.gov/1248701/', role: 'original' },
      { label: 'PubMed — review of CDAI reliability and validity', url: 'https://pubmed.ncbi.nlm.nih.gov/10099817/', role: 'evidence' },
      { label: 'PubMed — concerns about CDAI reliability and subjective endpoints', url: 'https://pubmed.ncbi.nlm.nih.gov/18636655/', role: 'evidence' },
    ],
    related: ['patient-global-impression'],
  },
  {
    slug: 'apache-ii',
    nameAr: 'نظام APACHE II لشدة المرض',
    nameEn: 'Acute Physiology and Chronic Health Evaluation II',
    acronym: 'APACHE II',
    version: 'CDISC QRS RS v2.1 / classic APACHE II construct',
    summary: 'نظام تقسيم طبقي لشدة المرض في العناية الحثيثة يعتمد على 12 قياسًا فسيولوجيًا والعمر والحالة الصحية المزمنة؛ صمم لتوصيف مجموعات المرضى ومخاطرهم وليس للحكم الحتمي على مريض فردي.',
    purpose: 'تقدير شدة المرض ودعم التقسيم الطبقي للمخاطر ومقارنة مجموعات العناية الحثيثة والنتائج في البحث والجودة.',
    construct: 'شدة المرض الحاد والمخاطر المرتبطة بها في العناية الحثيثة',
    populations: ['مرضى العناية الحثيثة البالغون ضمن المجتمعات التي تحقق فيها النظام أو أعيدت معايرته'],
    settings: ['العناية الحثيثة', 'بحوث النتائج', 'مقارنة وحدات العناية', 'تحسين الجودة'],
    categories: ['critical-care', 'symptom-burden'],
    administrationMode: 'تجميع أسوأ القيم الفسيولوجية ضمن النافذة الزمنية المحددة مع العمر والحالة الصحية المزمنة ثم تطبيق نظام النقاط.',
    administrationTime: 'يعتمد على توفر بيانات الساعات الأولى؛ الحساب نفسه قصير لكن يحتاج بيانات كاملة ونافذة زمنية صحيحة.',
    equipment: ['بيانات العلامات الحيوية والغازات والمختبرات المطلوبة', 'معلومات العمر والحالة المزمنة', 'تعريفات APACHE II ونظام النقاط'],
    scoring: 'الدرجة الكلية الكلاسيكية من 0 إلى 71 تجمع نقاط 12 متغيرًا فسيولوجيًا والعمر والصحة المزمنة. الدرجة الأعلى ترتبط بخطر أعلى على مستوى المجموعات، لكن روافد لا يحولها إلى احتمال وفاة فردي آلي.',
    interpretation: 'الدراسة الأصلية على 5815 إدخالًا للعناية الحثيثة وجدت ارتباطًا بين ارتفاع الدرجة وخطر الوفاة بالمستشفى. استخدام النظام الصحيح يتطلب معايرة للسكان والفترة والممارسة؛ لا يجوز تفسير احتمال مجموعة إحصائية كحكم حتمي على فرد.',
    limitations: ['النماذج التنبؤية تتأثر بتغير الممارسات والزمن والجغرافيا ومزيج الحالات.', 'المعايرة قد تتدهور خارج مجتمع التطوير.', 'التسجيل يعتمد على جودة ونافذة البيانات.', 'غير مناسب لتحديد عدم جدوى العلاج أو سحب الرعاية عن مريض فردي.'],
    administrationSteps: ['حدد نافذة التسجيل وتعريفات APACHE II قبل استخراج البيانات.', 'اجمع القيم الفسيولوجية المطلوبة بدقة وفق القواعد.', 'أضف نقاط العمر والحالة الصحية المزمنة كما يحدد النظام.', 'احسب درجة الشدة دون تحويلها تلقائيًا إلى قرار فردي.', 'استخدم نموذجًا معايرًا محليًا إذا كان الهدف تقدير مخاطر على مستوى خدمة أو بحث.'],
    safetyNotes: ['لا تستخدم APACHE II لتقرير سحب العلاج أو رفض العناية أو التنبؤ الحتمي بوفاة فرد.', 'أي قرار علاجي يبقى قائمًا على التقييم السريري الكامل وأهداف المريض والأدلة ذات الصلة.', 'النظام ليس أداة فرز ذاتي أو استخدام عام للمريض.'],
    rightsStatus: 'public-domain',
    rightsLabel: 'Public Domain — موثق في CDISC QRS، أحدث RS v2.1 في 2025',
    rightsNote: 'CDISC يدرج APACHE II بحالة Public Domain ويعرض إصدار RS v2.1 بتاريخ 20 مايو 2025. البرمجيات التجارية أو نماذج المعايرة الخاصة قد تحمل حقوقًا منفصلة.',
    rightsVerifiedOn: '2026-09-05',
    arabicStatus: 'protocol-localizable',
    arabicLabel: 'قابل للتوطين كمصطلحات وبروتوكول لا كحاسبة قرار فردي',
    arabicNote: 'المتغيرات أرقام طبية أساسًا، لكن تعريفات النوافذ والحالة المزمنة والتعليمات يجب ترجمتها بدقة ومراجعتها سريريًا قبل التشغيل المؤسسي.',
    fullArabicFormPublished: false,
    fullArabicFormNote: 'لن تنشر روافد حاسبة وفيات فردية. الصفحة تبقى دليلًا منهجيًا للدرجة والحدود ومصادر المعايرة.',
    sources: [
      { label: 'CDISC QRS — APACHE II Public Domain', url: CDISC_QRS, role: 'rights' },
      { label: 'PubMed — original APACHE II development and validation', url: 'https://pubmed.ncbi.nlm.nih.gov/3928249/', role: 'original' },
    ],
    related: ['glasgow-coma-scale-ninds'],
  },
];
