export type LegacyGuide = {
  slug: string;
  title: string;
  englishLabel: string;
  definition: string;
  primaryHref: string;
  primaryLabel: string;
  referenceTitle: string;
  referenceUrl: string;
  observations: string[];
};

export const legacyGuides: LegacyGuide[] = [
  { slug:'adhd-guide', title:'دليل اضطراب نقص الانتباه وفرط الحركة', englishLabel:'ADHD', definition:'نمط نمائي مستمر من تشتت الانتباه و/أو فرط النشاط والاندفاع يؤثر في الأداء.', primaryHref:'/capabilities/adhd/', primaryLabel:'الدليل الموسع لاضطراب نقص الانتباه وفرط الحركة', referenceTitle:'NIMH — Attention-Deficit/Hyperactivity Disorder (ADHD)', referenceUrl:'https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd', observations:['متى ظهرت الصعوبات أول مرة، وهل يمكن تتبعها إلى الطفولة بدل ظهورها حديثًا فقط؟','هل يظهر النمط في أكثر من سياق مثل المنزل والدراسة أو العمل، أم يرتبط ببيئة واحدة؟','ما الأثر الفعلي في بدء المهام، إكمالها، التنظيم، الانتظار، إدارة الوقت أو العلاقات؟','هل توجد عوامل قد تغير الانتباه أو النشاط مثل النوم، القلق، المزاج، الأدوية أو الضغوط؟'] },
  { slug:'agoraphobia-guide', title:'دليل رهاب الساحات', englishLabel:'Agoraphobia', definition:'خوف شديد من مواقف قد يبدو الهروب منها صعبًا أو قد لا تتوفر فيها المساعدة عند ظهور أعراض قوية.', primaryHref:'/evidence-guides/clinical-anxiety/', primaryLabel:'الدليل السريري للقلق', referenceTitle:'NIMH — Anxiety Disorders', referenceUrl:'https://www.nimh.nih.gov/health/topics/anxiety-disorders', observations:['ما المواقف التي أصبحت صعبة: النقل العام، الأماكن المفتوحة أو المغلقة، الطوابير، الزحام أو الابتعاد عن المنزل؟','هل يرتبط الخوف بفكرة صعوبة الخروج أو عدم توفر المساعدة إذا ظهرت أعراض قوية؟','ما حجم التجنب أو الحاجة إلى مرافق، وكيف تغيّر ذلك مع الوقت؟','هل توجد نوبات هلع أو أعراض طبية تستحق تقييمًا منفصلًا بدل افتراض سبب واحد؟'] },
  { slug:'anxiety-guide', title:'دليل القلق', englishLabel:'Anxiety', definition:'حالة تتضمن الترقب والخوف والتوتر، وقد تكون طبيعية مؤقتًا أو تصبح مشكلة عندما تشتد وتستمر وتعيق الحياة.', primaryHref:'/evidence-guides/clinical-anxiety/', primaryLabel:'الدليل السريري للقلق', referenceTitle:'NIMH — Anxiety Disorders', referenceUrl:'https://www.nimh.nih.gov/health/topics/anxiety-disorders', observations:['ما موضوع القلق الأساسي، وهل هو محدد أم ينتقل بين مجالات كثيرة؟','كيف يظهر جسديًا وفكريًا وسلوكيًا، وما الذي يحدث قبل اشتداده؟','هل يدفع إلى التجنب أو طلب الطمأنة أو تعطيل الدراسة والعمل والعلاقات؟','ما علاقة النمط بالنوم والكافيين والأدوية والحالة الصحية والضغوط الحالية؟'] },
  { slug:'autism-spectrum-guide', title:'دليل طيف التوحد', englishLabel:'Autism Spectrum', definition:'مجموعة متنوعة من السمات النمائية المتعلقة بالتواصل الاجتماعي والأنماط المقيدة أو المتكررة.', primaryHref:'/content/autism', primaryLabel:'الدليل الموسع لطيف التوحد عبر مراحل الحياة', referenceTitle:'NIMH — Autism Spectrum Disorder', referenceUrl:'https://www.nimh.nih.gov/health/topics/autism-spectrum-disorders-asd', observations:['ما السمات النمائية المبكرة المتعلقة بالتواصل والتفاعل والاهتمامات والروتين؟','كيف تختلف الاحتياجات بين المنزل والمدرسة والعمل والبيئات الحسية المختلفة؟','ما نقاط القوة وطرق التواصل المفضلة وما التكييفات التي تحسن المشاركة والاستقلال؟','هل توجد احتياجات مرافقة في النوم أو اللغة أو التعلم أو الانتباه أو الصحة تحتاج تقييمًا مستقلًا؟'] },
  { slug:'bipolar-disorder-guide', title:'دليل الاضطراب ثنائي القطب', englishLabel:'Bipolar Disorder', definition:'اضطراب مزاجي يتضمن نوبات من الاكتئاب وفترات من الهوس أو الهوس الخفيف وفق نمط سريري محدد.', primaryHref:'/evidence-guides/bipolar-disorder-safe-guide/', primaryLabel:'الدليل الآمن للاضطراب ثنائي القطب', referenceTitle:'NIMH — Bipolar Disorder', referenceUrl:'https://www.nimh.nih.gov/health/topics/bipolar-disorder', observations:['هل توجد فترات متميزة بوضوح من تغير المزاج والطاقة والنشاط والحاجة إلى النوم مقارنة بالمعتاد؟','كم استمرت الفترات وما أثرها في العمل أو الدراسة أو العلاقات أو القرارات؟','هل توجد أدوية أو مواد أو حالات صحية يمكن أن تؤثر في النوم أو المزاج والطاقة؟','هل ظهرت أفكار إيذاء للنفس أو سلوك شديد الخطورة أو فقدان للاتصال بالواقع بما يستدعي مساعدة عاجلة؟'] },
  { slug:'burnout-guide', title:'دليل الاحتراق النفسي', englishLabel:'Burnout', definition:'ظاهرة مرتبطة بالعمل تتضمن استنزافًا وتباعدًا ذهنيًا وانخفاض الفاعلية المهنية.', primaryHref:'/evidence-guides/stress-burnout-depression-differences-guide/', primaryLabel:'الفروق بين الضغط والاحتراق والاكتئاب', referenceTitle:'WHO — Burn-out an occupational phenomenon', referenceUrl:'https://www.who.int/standards/classifications/frequently-asked-questions/burn-out-an-occupational-phenomenon', observations:['هل يرتبط الاستنزاف أساسًا بسياق العمل أو الدراسة المهنية، أم يمتد بصورة عامة إلى كل مجالات الحياة؟','ما مصادر الضغط المزمن: عبء العمل، غياب السيطرة، ساعات طويلة، غموض الدور أو نقص الدعم؟','هل يوجد تباعد ذهني أو سلبية تجاه العمل وانخفاض واضح في الشعور بالفاعلية؟','هل تستمر الأعراض بعيدًا عن العمل أو تترافق مع فقد المتعة واليأس بما يستحق تقييمًا أوسع للاكتئاب أو حالات أخرى؟'] },
  { slug:'emotion-regulation-guide', title:'دليل تنظيم الانفعال', englishLabel:'Emotion Regulation', definition:'العمليات التي تساعد على فهم الانفعال وتعديله والتعبير عنه بطريقة ملائمة للموقف.', primaryHref:'/comparisons/emotional-intelligence-vs-emotion-regulation/', primaryLabel:'الفرق بين الذكاء العاطفي وتنظيم الانفعال', referenceTitle:'WHO — Mental health', referenceUrl:'https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response', observations:['ما المواقف التي ترفع شدة الانفعال بسرعة، وما العلامات المبكرة قبل التصاعد؟','هل الصعوبة في تسمية الشعور، تحمله، التعبير عنه، تهدئة الاستثارة أو اختيار السلوك؟','ما الاستراتيجيات المستخدمة الآن، وأيها يساعد مؤقتًا لكنه يسبب مشكلة لاحقًا؟','كيف تؤثر البيئة والعلاقات والنوم والضغط في القدرة على التنظيم؟'] },
  { slug:'emotional-intelligence-guide', title:'دليل الذكاء العاطفي', englishLabel:'Emotional Intelligence', definition:'مجموعة قدرات مرتبطة بإدراك الانفعالات وفهمها وتنظيمها واستخدامها في التفاعل.', primaryHref:'/comparisons/emotional-intelligence-vs-emotion-regulation/', primaryLabel:'الفرق بين الذكاء العاطفي وتنظيم الانفعال', referenceTitle:'WHO — Mental health', referenceUrl:'https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response', observations:['هل المقصود التعرف إلى الانفعال، فهم أسبابه، تنظيمه أم التعامل مع انفعالات الآخرين؟','في أي سياقات تظهر القوة أو الصعوبة: الأسرة، العمل، المدرسة أو المواقف عالية الضغط؟','هل التقدير مبني على سلوك قابل للملاحظة أم على اختبار تجاري أو درجة عامة غير موثقة؟','ما المهارة المحددة التي يمكن تدريبها بدل التعامل مع الذكاء العاطفي كصفة ثابتة أو حكم على قيمة الشخص؟'] },
  { slug:'generalized-anxiety-disorder-guide', title:'دليل اضطراب القلق العام', englishLabel:'Generalized Anxiety Disorder', definition:'نمط من القلق المفرط والمتكرر حول مجالات متعددة مع صعوبة في التحكم به وتأثير واضح في الأداء.', primaryHref:'/care-guides/generalized-anxiety-daily-support/', primaryLabel:'دليل الدعم اليومي للقلق العام', referenceTitle:'NIMH — Generalized Anxiety Disorder', referenceUrl:'https://www.nimh.nih.gov/health/publications/generalized-anxiety-disorder-gad', observations:['هل يمتد القلق إلى مجالات متعددة بدل موضوع واحد محدد؟','ما مدى صعوبة إيقاف سلسلة القلق أو تأجيلها، وكيف تتغير عبر الأيام؟','هل توجد أعراض مرافقة مثل التوتر، الإرهاق، صعوبة التركيز أو اضطراب النوم؟','ما مقدار التعطيل في الأداء، وهل توجد حالات صحية أو أدوية أو مواد قد تؤثر في الصورة؟'] },
  { slug:'insomnia-guide', title:'دليل الأرق', englishLabel:'Insomnia', definition:'صعوبة مستمرة في بدء النوم أو استمراره أو جودته مع تأثير نهاري ملحوظ.', primaryHref:'/evidence-guides/insomnia-and-sleep/', primaryLabel:'دليل الأرق والنوم المبني على الدليل', referenceTitle:'NHLBI/NIH — Insomnia', referenceUrl:'https://www.nhlbi.nih.gov/health/insomnia', observations:['هل المشكلة في بدء النوم أم الاستمرار فيه أم الاستيقاظ المبكر أم جودة النوم؟','ما مواعيد النوم والاستيقاظ والقيلولة خلال أيام العمل والعطلة؟','ما الأثر النهاري في النعاس والتركيز والمزاج والأداء؟','هل توجد عوامل مثل الشخير، الألم، الأدوية، الكافيين، المناوبات أو تغير الجدول تستحق مناقشتها مع مقدم الرعاية؟'] },
  { slug:'mental-health-guide', title:'دليل الصحة النفسية', englishLabel:'Mental Health', definition:'حالة من العافية النفسية تساعد الإنسان على التعامل مع ضغوط الحياة، والتعلّم والعمل والمشاركة في المجتمع.', primaryHref:'/evidence-guides/mental-health-foundations/', primaryLabel:'أسس الصحة النفسية', referenceTitle:'WHO — Mental health', referenceUrl:'https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response', observations:['ما الذي تغير عن خطك المعتاد في النوم والطاقة والمزاج والتركيز والعلاقات والأداء؟','ما العوامل الفردية والأسرية والاجتماعية والبيئية التي تزيد الضغط أو توفر حماية ودعمًا؟','هل المشكلة ضيق عابر مرتبط بحدث، أم نمط مستمر يسبب تعطيلًا أو خطرًا؟','ما نوع المساندة الأنسب الآن: معلومات، دعم اجتماعي، تكييف عملي، رعاية صحية أو تقييم متخصص؟'] },
  { slug:'obsessive-compulsive-disorder-guide', title:'دليل الوسواس القهري', englishLabel:'Obsessive-Compulsive Disorder', definition:'وساوس متكررة أو أفعال قهرية تستهلك الوقت وتسبب ضيقًا أو تعطلًا في الحياة.', primaryHref:'/care-guides/ocd-first-assessment-preparation/', primaryLabel:'الاستعداد لأول تقييم للوسواس القهري', referenceTitle:'NIMH — Obsessive-Compulsive Disorder (OCD)', referenceUrl:'https://www.nimh.nih.gov/health/topics/obsessive-compulsive-disorder-ocd', observations:['ما الأفكار أو الصور أو الدوافع المتكررة غير المرغوبة، وما مقدار الضيق المرتبط بها؟','ما الأفعال أو الطقوس أو الفحوص أو طلب الطمأنة التي تستخدم لتقليل القلق؟','كم من الوقت يستهلك النمط، وما أثره في الدراسة والعمل والعلاقات والروتين؟','هل يوجد تجنب واسع أو تأثير على السلامة أو القدرة على أداء الاحتياجات الأساسية؟'] },
  { slug:'panic-disorder-guide', title:'دليل اضطراب الهلع', englishLabel:'Panic Disorder', definition:'حالة تتكرر فيها نوبات هلع مفاجئة مع قلق مستمر من تكرارها أو تغييرات سلوكية مرتبطة بها.', primaryHref:'/evidence-guides/panic-disorder-safe-guide/', primaryLabel:'الدليل الآمن لاضطراب الهلع', referenceTitle:'NIMH — Panic Disorder: What You Need to Know', referenceUrl:'https://www.nimh.nih.gov/health/publications/panic-disorder-when-fear-overwhelms', observations:['كيف تبدأ النوبة وكم تبلغ ذروتها وما الأعراض الجسدية والفكرية خلالها؟','هل أصبحت هناك مراقبة مستمرة للجسم أو خوف من نوبة جديدة بين النوبات؟','ما الأماكن أو الأنشطة التي بدأ الشخص يتجنبها بسبب الخوف من تكرار النوبة؟','هل توجد أعراض جديدة أو شديدة قد تحتاج تقييمًا طبيًا بدل افتراض أنها هلع تلقائيًا؟'] },
  { slug:'post-traumatic-stress-disorder-guide', title:'دليل اضطراب ما بعد الصدمة', englishLabel:'Post-Traumatic Stress Disorder', definition:'مجموعة أعراض قد تظهر بعد حدث شديد التهديد، مثل الاسترجاع والتجنب والشعور المستمر بالخطر.', primaryHref:'/evidence-guides/ptsd-safe-guide/', primaryLabel:'الدليل الآمن لاضطراب ما بعد الصدمة', referenceTitle:'NIMH — Traumatic Events and PTSD', referenceUrl:'https://www.nimh.nih.gov/health/topics/post-traumatic-stress-disorder-ptsd', observations:['هل حدث تعرض لحدث صادم، وما الأعراض التي ظهرت بعده من دون الحاجة إلى سرد تفاصيل مؤذية في صفحة عامة؟','هل توجد ذكريات اقتحامية أو كوابيس أو تجنب أو تغير في الاستثارة والشعور بالأمان؟','ما أثر الأعراض في النوم والعمل والعلاقات والتنقل والعناية بالنفس؟','هل يوجد خطر حالي أو عنف مستمر أو حاجة إلى بيئة أكثر أمانًا قبل التركيز على المعالجة النفسية؟'] },
  { slug:'resilience-guide', title:'دليل المرونة النفسية', englishLabel:'Resilience', definition:'القدرة على التكيّف والتعافي النسبي بعد الشدائد مع الاستفادة من الدعم والمهارات والموارد.', primaryHref:'/content/family-resilience', primaryLabel:'دليل المرونة الأسرية والتكيف', referenceTitle:'WHO — Mental health', referenceUrl:'https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response', observations:['ما الضغوط أو الشدائد الحالية، وما الذي تغير في القدرة على الأداء مقارنة بما قبلها؟','ما الموارد المتاحة: علاقات داعمة، سكن آمن، تعليم، عمل، خدمات أو مهارات عملية؟','ما الذي يساعد على الاستعادة دون تحويل المرونة إلى مطالبة بتحمل ظروف غير آمنة أو غير عادلة؟','ما الدعم البنيوي أو الأسري المطلوب إلى جانب مهارات الفرد؟'] },
  { slug:'self-esteem-guide', title:'دليل تقدير الذات', englishLabel:'Self-esteem', definition:'التقييم العام الذي يحمله الشخص لقيمته وكفاءته، ويتأثر بالخبرات والعلاقات والتوقعات.', primaryHref:'/comparisons/self-esteem-vs-self-confidence/', primaryLabel:'الفرق بين تقدير الذات والثقة بالنفس', referenceTitle:'WHO — Mental health', referenceUrl:'https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response', observations:['هل التقييم السلبي عام وثابت أم يظهر في مجال أو علاقة محددة؟','ما العبارات التي يستخدمها الشخص للحكم على نفسه، وهل تخلط بين الخطأ والقيمة الإنسانية؟','كيف تؤثر المقارنة الاجتماعية والنقد والعلاقات والنجاحات والإخفاقات في الصورة الذاتية؟','هل توجد أعراض اكتئاب أو قلق أو إساءة أو تنمر تحتاج فهمًا أوسع من مصطلح تقدير الذات وحده؟'] },
  { slug:'social-anxiety-guide', title:'دليل القلق الاجتماعي', englishLabel:'Social Anxiety', definition:'خوف ملحوظ من التقييم السلبي أو الإحراج في المواقف الاجتماعية أو الأدائية.', primaryHref:'/comparisons/introversion-vs-social-anxiety/', primaryLabel:'الفرق بين الانطواء والقلق الاجتماعي', referenceTitle:'NIMH — Social Anxiety Disorder', referenceUrl:'https://www.nimh.nih.gov/health/publications/social-anxiety-disorder-more-than-just-shyness', observations:['ما المواقف الاجتماعية أو الأدائية التي تثير الخوف تحديدًا، وما التوقع السلبي فيها؟','هل يوجد تجنب أو احتمال للموقف مع ضيق شديد، وما أثر ذلك في الدراسة والعمل والعلاقات؟','هل القلق مرتبط بالخوف من التقييم أكثر من مجرد تفضيل الهدوء أو قلة الاختلاط؟','ما سلوكيات الأمان مثل تجنب النظر أو التحضير المفرط أو الانسحاب، وهل تزيد الاعتماد عليها مع الوقت؟'] },
  { slug:'stress-guide', title:'دليل الضغط النفسي', englishLabel:'Stress', definition:'استجابة نفسية وجسدية لمطالب أو تغيّرات يشعر الشخص أنها تتطلب منه التكيّف.', primaryHref:'/evidence-guides/stress-burnout-depression-differences-guide/', primaryLabel:'الفروق بين الضغط والاحتراق والاكتئاب', referenceTitle:'WHO — Mental health', referenceUrl:'https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response', observations:['ما المطالب الحالية، وأيها قابل للتعديل وأيها خارج السيطرة المباشرة؟','كيف يظهر الضغط في الجسم والنوم والانتباه والانفعال والسلوك؟','هل توجد فترات استعادة كافية، وما الذي يمنعها عمليًا؟','هل تحول النمط إلى تعطيل مستمر أو أعراض واسعة لا تتحسن بزوال الموقف وتحتاج تقييمًا أوسع؟'] },
];

export const legacyGuideSlugs = legacyGuides.map((guide) => guide.slug);
export function getLegacyGuide(slug: string) { return legacyGuides.find((guide) => guide.slug === slug) ?? null; }
