const IAHPC_DEFINITION = 'https://iahpc.org/what-we-do/research/consensus-based-definition-of-palliative-care/';
const IAHPC_PACKAGES = 'https://iahpc.org/what-we-do/research/essential-and-expanded-palliative-care-packages-for-adults-and-children/';
const IAHPC_MEDICINES = 'https://iahpc.org/resources/publications/manual-on-the-use-of-essential-palliative-care-medicines-for-adults/';
const IAHPC_GETTING_STARTED = 'https://iahpc.org/resources/publications/getting-started/';

const sources = {
  definition: { title: 'IAHPC — Consensus-Based Definition of Palliative Care', url: IAHPC_DEFINITION },
  packages: { title: 'IAHPC — Essential and Expanded Palliative Care Packages for Adults and Children', url: IAHPC_PACKAGES },
  medicines: { title: 'IAHPC — Manual on the Use of Essential Palliative Care Medicines for Adults', url: IAHPC_MEDICINES },
  service: { title: 'IAHPC — Guidelines and Suggestions for Those Starting a Hospice/Palliative Care Service', url: IAHPC_GETTING_STARTED },
} as const;

type SourceKey = keyof typeof sources;

const style = `<style>:root{--bg:#f4f8f7;--ink:#13251f;--muted:#526660;--line:#cfddd8;--brand:#075d4d;--soft:#e4f2ed;--blue:#edf5fb;--warn:#fff6e6;--danger:#fff0ee}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Tahoma,Arial,sans-serif;line-height:1.95}a{color:var(--brand)}header,main,footer{max-width:1120px;margin:auto;padding:1rem clamp(1rem,3vw,2rem)}header{display:flex;gap:.55rem;flex-wrap:wrap;align-items:center}.hero,.panel,.sources,.note,.tool,.safety{background:#fff;border:1px solid var(--line);border-radius:18px;padding:1.2rem;margin:1rem 0}.hero{background:linear-gradient(135deg,var(--soft),#fff)}.note{border-inline-start:6px solid #8a4f0b;background:var(--warn)}.safety{border-inline-start:6px solid #9f2f25;background:var(--danger)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:.8rem}.card{display:block;background:#fff;border:1px solid var(--line);border-radius:14px;padding:1rem;text-decoration:none;color:var(--ink)}.card strong{display:block;color:var(--brand);margin-bottom:.25rem}.tag{display:inline-block;background:var(--soft);border-radius:999px;padding:.15rem .6rem;font-size:.88rem;margin-inline-end:.35rem}.meta{color:var(--muted);font-size:.94rem}table{width:100%;border-collapse:collapse;background:#fff}th,td{border:1px solid var(--line);padding:.7rem;vertical-align:top}th{background:#edf7f3}li{margin:.45rem 0}.question{background:var(--blue);border-radius:12px;padding:.8rem;margin:.65rem 0}footer{color:var(--muted);font-size:.92rem}@media(max-width:620px){table{display:block;overflow-x:auto;white-space:normal}.hero,.panel,.sources,.note,.tool,.safety{border-radius:14px}}</style>`;

function sourceList(keys: SourceKey[]) {
  const unique = [...new Set(keys)];
  return unique.map((key) => `<li><a href="${sources[key].url}" target="_blank" rel="noopener noreferrer"><strong>${sources[key].title}</strong></a></li>`).join('');
}

function shell(slug: string, title: string, description: string, body: string, sourceKeys: SourceKey[]) {
  const base = 'https://healthrenewal.org/evidence-guides/palliative-care/';
  const canonical = slug ? `${base}${slug}/` : base;
  const schema = {
    '@context': 'https://schema.org',
    '@type': slug ? 'MedicalWebPage' : 'CollectionPage',
    name: title,
    description,
    url: canonical,
    inLanguage: 'ar',
    isPartOf: { '@type': 'WebSite', name: 'Health Renewal | روافد', url: 'https://healthrenewal.org/' },
    about: { '@type': 'MedicalSpecialty', name: 'Palliative care' },
  };
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | روافد</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:locale" content="ar_AR"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script>${style}</head><body><header><a href="/"><strong>روافد | Health Renewal</strong></a><span>·</span><a href="/evidence-guides/">الأدلة المبنية على المصادر</a><span>·</span><a href="/evidence-guides/palliative-care/">الرعاية التلطيفية</a></header><main>${body}<section class="sources"><h2>المصادر الأصلية المستخدمة</h2><ul>${sourceList(sourceKeys)}</ul><p class="meta">المحتوى العربي هنا إعداد مستقل من روافد اعتمادًا على المصادر الأصلية أعلاه، وليس ترجمة رسمية لها ولا يعني مراجعة IAHPC أو اعتمادها أو مصادقتها للمحتوى. نربط إلى المصدر القانوني/الأصلي بدل إعادة نشر المواد المحمية.</p></section><section class="safety"><h2>حدود الاستخدام</h2><p>هذا المحتوى للتثقيف العام وتحسين الحوار مع فريق الرعاية، ولا يقدم تشخيصًا أو وصفة أو جرعات أو خطة علاج فردية. عند وجود أعراض شديدة أو متفاقمة أو أسئلة دوائية يجب الرجوع إلى الطبيب أو الصيدلي أو فريق الرعاية المختص.</p></section></main><footer>روافد | Health Renewal — مسار عربي مبني على مصادر IAHPC الأصلية، مع الحفاظ على الإسناد والروابط وحدود الاستخدام.</footer></body></html>`;
}

const hub = shell('', 'الرعاية التلطيفية: دليل عربي مبني على مصادر IAHPC', 'مسار عربي عملي لفهم الرعاية التلطيفية، الاحتياجات الجسدية والنفسية والاجتماعية والروحية، دعم الأسرة، حزم الرعاية، الأمان الدوائي وتطوير الخدمات.', `<section class="hero"><span class="tag">IAHPC</span><span class="tag">للأسر والمهنيين</span><h1>الرعاية التلطيفية: من المفهوم إلى التطبيق الآمن</h1><p>هذا المسار يفصل بين أربعة أسئلة كثيرًا ما تختلط: ما الرعاية التلطيفية؟ متى تكون الحاجة إليها موجودة؟ ما الذي ينبغي أن تغطيه الخدمة؟ وما الذي يجب أن يبقى قرارًا سريريًا فرديًا؟</p></section><section class="note"><h2>الفكرة الأساسية</h2><p>الرعاية التلطيفية ليست مرادفًا لإيقاف العلاج وليست محصورة بالساعات أو الأيام الأخيرة. إطار IAHPC يضع تخفيف المعاناة المرتبطة بالمرض الشديد وجودة حياة المريض والأسرة في المركز، ويمكن تقديم الرعاية بالتوازي مع العلاجات المعدلة لمسار المرض بحسب الحاجة.</p></section><section class="panel"><h2>خريطة المسار</h2><div class="grid"><a class="card" href="./what-is-palliative-care/"><strong>ما الرعاية التلطيفية؟</strong>تعريف واضح وما الذي لا يعنيه المصطلح.</a><a class="card" href="./serious-health-related-suffering/"><strong>المعاناة الصحية الجسيمة</strong>عدسة عملية لفهم الاحتياجات بدل اختزالها في الألم فقط.</a><a class="card" href="./essential-care-packages/"><strong>حزم الرعاية للبالغين والأطفال</strong>كيف نقرأ الحد الأدنى من التدخلات والخدمات المبنية على الدليل.</a><a class="card" href="./family-caregiver-support/"><strong>الأسرة ومقدمو الرعاية</strong>الأهداف، التواصل، العبء، القيم الثقافية والدعم بعد الوفاة.</a><a class="card" href="./medicines-safety/"><strong>الأمان الدوائي</strong>كيف تستخدم مرجع الأدوية دون تحويله إلى وصفة ذاتية.</a><a class="card" href="./service-development/"><strong>تطوير خدمة تلطيفية</strong>مسار للفرق والمؤسسات يبدأ من التصميم ولا ينتهي عند السرير.</a><a class="card" href="./questions-for-care-team/"><strong>أسئلة للفريق العلاجي</strong>قائمة عملية ترفع جودة الحوار دون إعطاء قرار علاجي جاهز.</a></div></section><section class="tool"><h2>ابدأ من الحاجة لا من الاسم</h2><ol><li>ما الأعراض أو الضغوط التي تعطل الحياة اليومية؟</li><li>ما الذي يهم المريض والأسرة الآن؟</li><li>هل توجد احتياجات نفسية أو اجتماعية أو روحية غير معالجة؟</li><li>هل التواصل حول أهداف العلاج واضح؟</li><li>هل يحتاج الوضع إلى خبرة تلطيفية متخصصة بسبب التعقيد؟</li></ol></section>`, ['definition', 'packages', 'medicines', 'service']);

const whatIs = shell('what-is-palliative-care', 'ما الرعاية التلطيفية؟ فهم صحيح بعيدًا عن الخرافات', 'شرح عربي مبني على تعريف IAHPC للرعاية التلطيفية: الهدف، التوقيت، علاقتها بالعلاج، دور الأسرة ومتى تلزم الإحالة المتخصصة.', `<section class="hero"><h1>ما الرعاية التلطيفية؟</h1><p>هي رعاية نشطة وشمولية للأشخاص من مختلف الأعمار عندما يسبب المرض الشديد معاناة صحية جسيمة، وهدفها تحسين جودة الحياة للمريض والأسرة ومقدمي الرعاية.</p></section><section class="panel"><h2>أربع خرافات تحتاج تصحيحًا</h2><table><tr><th>الخرافة</th><th>ما يوضحه إطار IAHPC</th></tr><tr><td>«تعني أن العلاج انتهى»</td><td>يمكن أن تُقدم بالتزامن مع علاجات تعدل مسار المرض عندما تكون مطلوبة.</td></tr><tr><td>«هي فقط لنهاية الحياة»</td><td>يمكن تطبيقها عبر مسار المرض بحسب الاحتياجات، مع أهمية خاصة قرب نهاية الحياة.</td></tr><tr><td>«تعالج الألم فقط»</td><td>تشمل المشكلات الجسدية والنفسية والاجتماعية والروحية، إضافة إلى التواصل والأهداف.</td></tr><tr><td>«لا يبدأها إلا اختصاصي تلطيفي»</td><td>يمكن لمهنيين لديهم تدريب أساسي تقديم جوانب منها، بينما الحالات المعقدة تحتاج فريقًا متخصصًا متعدد المهن.</td></tr></table></section><section class="panel"><h2>ماذا يعني هذا للأسرة؟</h2><p>السؤال المفيد ليس «هل وصلنا إلى مرحلة الرعاية التلطيفية؟» بقدر ما هو: هل توجد معاناة أو أعراض أو ضغوط أو قرارات صعبة يمكن تخفيفها الآن؟ هذا التحول يقلل تأخير الدعم بسبب سوء فهم المصطلح.</p></section><section class="note"><h2>نسخة عربية رسمية موجودة</h2><p>صفحة تعريف IAHPC نفسها توفر رابطًا للنسخة العربية من التعريف. لذلك نوجه القارئ إلى الصفحة الأصلية بدل إنشاء نسخة تبدو رسمية من طرفنا.</p></section>`, ['definition']);

const suffering = shell('serious-health-related-suffering', 'المعاناة الصحية الجسيمة: كيف نفهم الحاجة للرعاية التلطيفية؟', 'إطار عربي لفهم المعاناة الصحية الجسيمة عبر الوظيفة الجسدية والنفسية والاجتماعية والروحية وتأثير المرض والعلاج وعبء الرعاية.', `<section class="hero"><h1>المعاناة الصحية الجسيمة ليست «درجة ألم» فقط</h1><p>في إطار IAHPC تصبح المعاناة صحية عندما ترتبط بمرض أو إصابة، وتصبح جسيمة عندما لا يمكن تخفيفها دون تدخل مهني وعندما تمس الأداء الجسدي أو الاجتماعي أو الروحي أو العاطفي.</p></section><section class="panel"><h2>خريطة احتياجات من أربعة محاور</h2><div class="grid"><div class="card"><strong>جسدي</strong>ألم، ضيق نفس، غثيان، ضعف، نوم، أعراض مرهقة أو آثار العلاج.</div><div class="card"><strong>نفسي وعاطفي</strong>خوف، قلق، حزن، ارتباك، ضغط قرار أو فقدان الإحساس بالسيطرة.</div><div class="card"><strong>اجتماعي</strong>عبء الرعاية، العمل والدخل، أدوار الأسرة، الوصول للخدمة، العزلة.</div><div class="card"><strong>روحي وقيمي</strong>المعنى، الأمل، المعتقدات، الأولويات، ما يعد جودة حياة مقبولة للشخص.</div></div></section><section class="tool"><h2>فحص سريع قبل الزيارة</h2><p>اكتب أكثر ثلاثة أمور تعطل يومك، وما الذي تحاول حاليًا لتخفيفها، وما الذي تخشاه من الخطة الحالية. هذه المعلومات أكثر فائدة من الاكتفاء بقول «أنا متعب» أو «الأمور سيئة».</p></section><section class="note"><h2>لا تنتظر تشخيصًا بعينه</h2><p>هدف تعريف IAHPC هو تخفيف المعاناة في الوقت المناسب وبغض النظر عن التشخيص أو الإنذار أو المكان أو مستوى الدخل. الأهلية القانونية أو توفر الخدمة محليًا يختلفان، لكن منطق تقييم الحاجة أوسع من اسم المرض.</p></section>`, ['definition']);

const packages = shell('essential-care-packages', 'حزم الرعاية التلطيفية الأساسية والموسعة للبالغين والأطفال', 'شرح عربي لكيفية قراءة حزم IAHPC الأساسية والموسعة للبالغين والأطفال كحد أدنى من التدخلات والخدمات المبنية على الدليل.', `<section class="hero"><h1>حزم الرعاية: من «مفهوم جيد» إلى مكونات خدمة قابلة للفحص</h1><p>تنشر IAHPC حزمًا أساسية وموسعة للبالغين، وحزمًا أساسية وموسعة للأطفال. الهدف هو تحديد حد أدنى من التدخلات والخدمات المبنية على الدليل لتخفيف معظم المعاناة الصحية الجسيمة.</p></section><section class="panel"><h2>كيف نستخدم الحزم بشكل مسؤول؟</h2><ol><li><strong>كمخطط فجوات:</strong> هل الخدمة تغطي المجالات الأساسية أم تركز على عرض واحد فقط؟</li><li><strong>للفصل بين البالغين والأطفال:</strong> وجود حزمة أطفال مستقلة يذكّر بأن الرعاية ليست نسخة مصغرة من خدمة البالغين.</li><li><strong>لتحديد ما يحتاج بروتوكولًا محليًا:</strong> الموارد البشرية والأدوية والتنظيم والإحالة يجب أن تتوافق مع القانون والنظام الصحي المحلي.</li><li><strong>للتدرج:</strong> «الأساسي» ليس نهاية التطوير؛ الحزمة الموسعة تساعد على تصور النضج القادم.</li></ol></section><section class="panel"><h2>أسئلة تدقيق للخدمة</h2><table><tr><th>المجال</th><th>سؤال الفحص</th></tr><tr><td>الوصول</td><td>هل يستطيع المريض الحصول على دعم مبكر أم لا يصل إلا في المرحلة الأخيرة؟</td></tr><tr><td>الأطفال</td><td>هل توجد ترتيبات ملائمة للعمر والأسرة بدل افتراض نموذج بالغين؟</td></tr><tr><td>التكامل</td><td>هل تعمل الرعاية التلطيفية مع التخصص المعالج أم كمسار منفصل متأخر؟</td></tr><tr><td>الإحالة</td><td>متى يصبح التعقيد سببًا لإحالة إلى فريق متخصص متعدد المهن؟</td></tr></table></section><section class="note"><h2>ما لا نفعله هنا</h2><p>لا نعيد نشر تفاصيل الحزم أو جداولها كأنها معيار محلي ملزم. نستخدمها كإطار توجيهي ونربط إلى النسخة الأصلية لدى IAHPC حتى تبقى التفاصيل والسياق والتحديثات عند المصدر.</p></section>`, ['packages', 'definition']);

const family = shell('family-caregiver-support', 'دعم الأسرة ومقدمي الرعاية في الرعاية التلطيفية', 'دليل عربي عملي لدور الأسرة ومقدمي الرعاية: أهداف الرعاية، التواصل، العبء، القيم الثقافية والدعم أثناء المرض وفي الحداد.', `<section class="hero"><h1>الأسرة ليست هامشًا في الرعاية التلطيفية</h1><p>تعريف IAHPC يضع الأسرة ومقدمي الرعاية ضمن هدف تحسين جودة الحياة، وينص على دعمهم أثناء مرض المريض وفي الحداد، مع احترام القيم والمعتقدات الثقافية للمريض والأسرة.</p></section><section class="panel"><h2>خمسة مجالات للحوار</h2><div class="question"><strong>1. ما الذي يهم المريض؟</strong><br>ما الأولويات التي يجب أن تقود القرارات عندما تتعارض الراحة والوظيفة والوقت والآثار الجانبية؟</div><div class="question"><strong>2. ما الذي تتحمله الأسرة؟</strong><br>من يقدم الرعاية اليومية؟ ما العبء الجسدي أو النفسي أو المالي؟ ومن يمكن أن يساند؟</div><div class="question"><strong>3. هل المعلومات مفهومة؟</strong><br>من يحتاج الشرح؟ وبأي لغة؟ وهل توجد اختلافات داخل الأسرة حول الأهداف أو التوقعات؟</div><div class="question"><strong>4. ما القيم والمعتقدات المؤثرة؟</strong><br>اسأل بدل الافتراض؛ الثقافة والدين والعادات مهمة لكنها لا تجعل كل أفراد المجتمع متشابهين.</div><div class="question"><strong>5. ماذا بعد التغير أو الوفاة؟</strong><br>الدعم لا ينتهي عند حدث سريري واحد؛ التخطيط للعبء والحداد جزء من الرعاية الشاملة.</div></section><section class="tool"><h2>ورقة تحضير عائلية</h2><ul><li>أكثر عرض أو ضغط يصعب التعامل معه في المنزل.</li><li>الشخص الذي يتحمل العبء الأكبر حاليًا.</li><li>قرار واحد غير مفهوم أو مؤجل.</li><li>معلومة يحتاج أفراد الأسرة سماعها معًا من الفريق.</li><li>قيمة أو تفضيل يجب ألا يضيع أثناء اتخاذ القرار.</li></ul></section>`, ['definition']);

const medicines = shell('medicines-safety', 'أمان أدوية الرعاية التلطيفية: كيف تستخدم المراجع دون علاج ذاتي؟', 'صفحة أمان دوائي تربط إلى دليل IAHPC للأدوية الأساسية دون نسخ الجرعات أو تحويل المرجع المهني إلى وصفة عامة.', `<section class="hero"><h1>مرجع دوائي مهني لا وصفة عامة</h1><p>دليل IAHPC للأدوية الأساسية صُمم لتقديم توصيات عملية للمهنيين حول الاستخدام الآمن والفعال لأدوية الرعاية التلطيفية، ويتضمن تفاصيل جرعات واحتياطات. لهذا السبب لا نعيد نشر تلك التفاصيل هنا.</p></section><section class="safety"><h2>قاعدة واضحة</h2><p><strong>لا جرعات، لا تبديل دواء، لا إيقاف دواء، ولا مقارنة علاجية فردية من هذه الصفحة.</strong> الدواء المناسب والجرعة والتحذيرات وموانع الاستعمال تعتمد على الشخص والسياق السريري والأدوية الأخرى ووظائف الأعضاء والقواعد المحلية.</p></section><section class="panel"><h2>ماذا نستفيد من الدليل إذن؟</h2><ol><li>معرفة أن تدبير الأعراض الدوائي يجب أن يكون منظمًا ومبنيًا على السلامة لا التجربة العشوائية.</li><li>التمييز بين تثقيف المريض حول الدواء وبين قرار الوصف السريري.</li><li>تجهيز أسئلة للطبيب أو الصيدلي حول الهدف، وطريقة المراقبة، والتداخلات، ومتى يجب طلب المساعدة.</li><li>إحالة المهني إلى المرجع الأصلي المحدث بدل نقل جدول قد يفقد سياقه أو يصبح قديمًا.</li></ol></section><section class="tool"><h2>أسئلة آمنة للطبيب أو الصيدلي</h2><ul><li>ما العرض الذي يستهدفه هذا الدواء تحديدًا؟</li><li>ما العلامات التي تعني أن الفائدة غير كافية أو أن هناك أثرًا جانبيًا مهمًا؟</li><li>هل توجد تداخلات مع الأدوية أو المكملات الحالية؟</li><li>هل تؤثر وظائف الكلى أو الكبد أو العمر أو القدرة على البلع في الخطة؟</li><li>متى نتواصل مع الفريق، ومتى تكون الحالة طارئة؟</li></ul></section><section class="note"><h2>حقوق المصدر</h2><p>دليل IAHPC Press لعام 2025 محفوظ الحقوق ومخصص للأغراض التعليمية والمناصرة وفق صفحة المصدر. لذلك نلخص مبادئ الأمان ونربط إليه، ولا ننسخ جداول الجرعات أو محتواه التفصيلي.</p></section>`, ['medicines', 'packages']);

const service = shell('service-development', 'تطوير خدمة رعاية تلطيفية: أسئلة تأسيس وتشغيل للفرق والمؤسسات', 'دليل عربي لتطوير خدمة رعاية تلطيفية مستند إلى Getting Started وحزم IAHPC: النطاق، الفريق، الإحالة، التعليم، التوثيق والتحسين.', `<section class="hero"><h1>تطوير الخدمة يبدأ قبل افتتاح العيادة</h1><p>كتاب IAHPC «Getting Started» يتعامل مع التأسيس كمنظومة: معنى الرعاية ومبادئها، بدء الخدمة، الإدارة، نماذج المستشفى والمجتمع، الموارد البشرية، المتطوعون، التدريب، التواصل والتوثيق.</p></section><section class="panel"><h2>خريطة تأسيس من سبعة أسئلة</h2><ol><li><strong>الحاجة:</strong> من السكان الذين لا يحصلون على تخفيف مناسب للمعاناة؟</li><li><strong>النطاق:</strong> هل البداية استشارة داخل مستشفى، فريقًا متنقلًا، رعاية منزلية، عيادة أم مزيجًا؟</li><li><strong>الفريق:</strong> ما المهارات الأساسية وما الحالات التي تتطلب خبرة متخصصة متعددة المهن؟</li><li><strong>الإحالة:</strong> من يستطيع الإحالة ومتى، وكيف نتجنب وصول المرضى متأخرين؟</li><li><strong>الأدوية والتقنيات:</strong> ما المتاح قانونيًا وعمليًا، ومن يتحمل مسؤولية السلامة والحوكمة؟</li><li><strong>التواصل والتوثيق:</strong> كيف تُسجل الأهداف والتفضيلات والخطة والتغيرات والمسؤوليات؟</li><li><strong>الجودة:</strong> ما النتائج التي سنراجعها: الأعراض، تجربة الأسرة، الوصول، الاستجابة، الاستمرارية، الإحالات المتأخرة؟</li></ol></section><section class="panel"><h2>استخدم مصدرين معًا</h2><p>«Getting Started» مفيد لتصميم وتشغيل الخدمة، بينما حزم IAHPC الأساسية والموسعة تساعد على فحص الحد الأدنى من التدخلات والخدمات. الجمع بينهما أفضل من استخدام أي منهما كقائمة تحقق منفصلة عن السياق المحلي.</p></section><section class="note"><h2>التوطين إلزامي</h2><p>نماذج العمل والتنظيم والأدوية وصلاحيات المهن والتمويل تختلف بين البلدان. هذا الدليل ليس بروتوكول تشغيل قانونيًا للأردن أو لأي دولة أخرى؛ يجب مواءمة أي خدمة مع التشريع والترخيص والسياسات المحلية.</p></section>`, ['service', 'packages', 'definition']);

const questions = shell('questions-for-care-team', 'أسئلة تساعدك في الحوار مع فريق الرعاية التلطيفية', 'قائمة أسئلة عربية عملية للمريض والأسرة لتحسين الحوار حول الأعراض، الأهداف، الخيارات، دعم مقدم الرعاية والقيم دون تقديم قرار علاجي جاهز.', `<section class="hero"><h1>أسئلة أفضل = حوار سريري أوضح</h1><p>هذه القائمة لا تخبرك ماذا تختار. وظيفتها أن تمنع ضياع الاحتياجات الجسدية والنفسية والاجتماعية والروحية، وأن تجعل أهداف الرعاية والدعم الأسري أكثر وضوحًا.</p></section><section class="panel"><h2>عن الأعراض والمعاناة</h2><ul><li>ما أكثر عرض أو مشكلة تؤثر في يومي الآن؟ وكيف سنقيس تحسنها؟</li><li>هل هناك سبب قابل للعلاج يجب البحث عنه بالإضافة إلى تخفيف العرض؟</li><li>ماذا نفعل إذا تغير العرض في المنزل أو خارج ساعات الدوام؟</li></ul><h2>عن الأهداف والخيارات</h2><ul><li>ما هدف الخطة الحالية: إطالة الحياة، تقليل الأعراض، تحسين الوظيفة، أم أكثر من هدف؟</li><li>ما الفوائد والأعباء المحتملة لكل خيار بالنسبة لأولوياتي الشخصية؟</li><li>هل يمكن تقديم الرعاية التلطيفية بالتوازي مع العلاج الحالي؟</li></ul><h2>عن الأسرة ومقدم الرعاية</h2><ul><li>ما الذي يحتاج مقدم الرعاية إلى تعلمه قبل العودة للمنزل؟</li><li>من نتصل به عندما لا نستطيع إدارة الوضع؟</li><li>هل توجد خدمات دعم نفسي أو اجتماعي أو للحداد للأسرة؟</li></ul><h2>عن القيم والتواصل</h2><ul><li>ما المعلومات التي يحتاج الفريق معرفتها عن معتقداتي أو تفضيلاتي أو حدودي؟</li><li>من أريد أن يشارك في المحادثات والقرارات؟</li><li>هل نحتاج مترجمًا أو وسيلة تواصل أو وقتًا إضافيًا لفهم الخيارات؟</li></ul></section><section class="tool"><h2>خذ معك ملخصًا من صفحة واحدة</h2><p>اكتب الأعراض الحالية، قائمة الأدوية كما وُصفت لك، الحساسية، أهم تغير منذ الزيارة السابقة، وأول ثلاثة أسئلة تريد جوابًا عنها. لا تعدل الأدوية اعتمادًا على القائمة؛ استخدمها لتحسين دقة الحوار.</p></section>`, ['definition', 'medicines']);

export const PALLIATIVE_CARE_IAHPC_PAGES: Record<string, string> = {
  '': hub,
  'what-is-palliative-care': whatIs,
  'serious-health-related-suffering': suffering,
  'essential-care-packages': packages,
  'family-caregiver-support': family,
  'medicines-safety': medicines,
  'service-development': service,
  'questions-for-care-team': questions,
};

export const PALLIATIVE_CARE_IAHPC_SLUGS = Object.keys(PALLIATIVE_CARE_IAHPC_PAGES);
