const GG_HUB = 'https://globalgenes.org/learn/';
const GG_PATIENT_SERVICES = 'https://globalgenes.org/rare-disease-patient-services/';
const GG_UNDIAGNOSED = 'https://globalgenes.org/blog/becoming-an-empowered-patient-a-toolkit-for-the-undiagnosed/';
const GG_FAMILY_HISTORY = 'https://globalgenes.org/know-your-family-history/';
const GG_CAREGIVERS = 'https://globalgenes.org/toolkit/rare-caregivers-guidebook/';
const GG_CURRICULUM = 'https://globalgenes.org/curriculum/';
const GG_RESOURCES = 'https://globalgenes.org/blog/rare-disease-resources-for-individuals-caregivers-and-advocates/';

const sources = {
  hub: { title: 'Global Genes — Resource Hub', url: GG_HUB },
  services: { title: 'Global Genes — RARE Concierge Patient Services', url: GG_PATIENT_SERVICES },
  undiagnosed: { title: 'Global Genes — Toolkit for the Undiagnosed', url: GG_UNDIAGNOSED },
  history: { title: 'Global Genes — Know Your Family History', url: GG_FAMILY_HISTORY },
  caregivers: { title: 'Global Genes — Rare Caregivers Guidebook', url: GG_CAREGIVERS },
  curriculum: { title: 'Global Genes — Rare Disease Curriculum', url: GG_CURRICULUM },
  resources: { title: 'Global Genes — Rare Disease Resources for Individuals, Caregivers, and Advocates', url: GG_RESOURCES },
} as const;

type SourceKey = keyof typeof sources;

const style = `<style>:root{--bg:#f7f8fb;--ink:#1b2230;--muted:#596476;--line:#dbe0ea;--brand:#244ca3;--soft:#edf2ff;--warn:#fff7e8;--danger:#fff0ef}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Tahoma,Arial,sans-serif;line-height:1.9}a{color:var(--brand)}header,main,footer{max-width:1120px;margin:auto;padding:1rem clamp(1rem,3vw,2rem)}header{display:flex;gap:.55rem;flex-wrap:wrap}.hero,.panel,.sources,.note,.safety,.tool{background:#fff;border:1px solid var(--line);border-radius:18px;padding:1.2rem;margin:1rem 0}.hero{background:linear-gradient(135deg,var(--soft),#fff)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:.8rem}.card{display:block;background:#fff;border:1px solid var(--line);border-radius:14px;padding:1rem;text-decoration:none;color:var(--ink)}.card strong{display:block;color:var(--brand)}.tag{display:inline-block;background:var(--soft);border-radius:999px;padding:.15rem .6rem;font-size:.88rem;margin-inline-end:.35rem}.note{background:var(--warn);border-inline-start:6px solid #925c12}.safety{background:var(--danger);border-inline-start:6px solid #a23b34}.meta{color:var(--muted);font-size:.94rem}table{width:100%;border-collapse:collapse;background:#fff}th,td{border:1px solid var(--line);padding:.7rem;vertical-align:top}th{background:#f0f4ff}li{margin:.42rem 0}footer{color:var(--muted);font-size:.92rem}@media(max-width:620px){table{display:block;overflow-x:auto}.hero,.panel,.sources,.note,.safety,.tool{border-radius:14px}}</style>`;

function sourceList(keys: SourceKey[]) {
  return [...new Set(keys)].map((key) => `<li><a href="${sources[key].url}" target="_blank" rel="noopener noreferrer"><strong>${sources[key].title}</strong></a></li>`).join('');
}

function shell(slug: string, title: string, description: string, body: string, keys: SourceKey[]) {
  const base = 'https://healthrenewal.org/evidence-guides/rare-disease/';
  const canonical = slug ? `${base}${slug}/` : base;
  const schema = {'@context':'https://schema.org','@type':slug?'MedicalWebPage':'CollectionPage',name:title,description,url:canonical,inLanguage:'ar',isPartOf:{'@type':'WebSite',name:'Health Renewal | روافد',url:'https://healthrenewal.org/'}};
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | روافد</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:locale" content="ar_AR"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>${style}</head><body><header><a href="/"><strong>روافد | Health Renewal</strong></a><span>·</span><a href="/evidence-guides/">الأدلة المبنية على المصادر</a><span>·</span><a href="/evidence-guides/rare-disease/">رحلة المرض النادر</a></header><main>${body}<section class="sources"><h2>المصادر الأصلية المستخدمة</h2><ul>${sourceList(keys)}</ul><p class="meta">أعدّت روافد هذا المحتوى العربي بصورة مستقلة اعتمادًا على الموارد العامة المرتبطة أعلاه. الروابط تحيل إلى Global Genes كمصدر أصلي ولا تعني أن Global Genes راجعت أو اعتمدت أو صادقت على هذه الصفحات.</p></section><section class="safety"><h2>حدود السلامة</h2><p>هذا المسار للتثقيف والتنظيم والاستعداد للحوار، ولا يشخّص مرضًا نادرًا ولا يفسر نتيجة جينية فردية ولا يوصي بعلاج أو تجربة سريرية لشخص بعينه. استخدم المختص المناسب للتقييم الطبي أو الجيني، واتبع خدمات الطوارئ المحلية عند وجود خطر حاد.</p></section></main><footer>روافد | Health Renewal — مسار عربي مستقل لرحلة المرض النادر مع إحالات مباشرة للمصادر الأصلية.</footer></body></html>`;
}

const hub = shell('', 'رحلة المرض النادر: دليل عربي للأسرة من البحث عن التشخيص إلى الدعم', 'مسار عربي عملي ينظم رحلة المرض النادر: قبل التشخيص وبعده، التاريخ العائلي، الاستعداد للفحوص الجينية، دعم مقدم الرعاية، الصحة النفسية، البحث والتجارب السريرية.', `<section class="hero"><span class="tag">Global Genes</span><span class="tag">للأسرة ومقدم الرعاية</span><h1>رحلة المرض النادر: ماذا نفعل عندما تكون المعلومات مشتتة؟</h1><p>وجود صفحة عن اسم المتلازمة لا يحل وحده مشكلة الأسرة. الصعوبة عادةً تمتد عبر التشخيص، جمع السجلات، فهم الاختبارات، الوصول إلى مختصين، البحث، العبء النفسي والرعائي، ثم تقييم الفرص الجديدة دون الوقوع في الوعود غير المثبتة.</p></section><section class="panel"><h2>اختر المرحلة التي أنت فيها</h2><div class="grid"><a class="card" href="./undiagnosed-journey/"><strong>ما زلنا بلا تشخيص</strong>حوّل رحلة البحث إلى ملف منظم وأسئلة قابلة للإجابة.</a><a class="card" href="./new-diagnosis/"><strong>وصل تشخيص جديد</strong>ما الذي يجب تثبيته أولًا قبل الغرق في البحث؟</a><a class="card" href="./genetic-testing-family-history/"><strong>الفحوص الجينية والتاريخ العائلي</strong>تحضير المعلومات والأسئلة دون تفسير ذاتي للنتائج.</a><a class="card" href="./caregiver-support/"><strong>دعم مقدم الرعاية</strong>العبء، الأدوار، الرعاية الذاتية والتنسيق.</a><a class="card" href="./mental-health-grief/"><strong>الصحة النفسية والحزن الغامض</strong>مساحة للضغط والحزن والقلق دون افتراض اضطراب.</a><a class="card" href="./research-clinical-trials/"><strong>البحث والتجارب السريرية</strong>كيف تنتقل من «وجدت دراسة» إلى سؤال منظم للطبيب؟</a><a class="card" href="./trusted-resource-navigation/"><strong>العثور على الموارد الموثوقة</strong>بوابة عملية للتمييز بين المصدر، المجتمع والخدمة.</a></div></section><section class="note"><h2>حد جغرافي مهم</h2><p>Global Genes تقدم موارد كثيرة ذات فائدة عامة عالميًا، لكن بعض الخدمات والحقوق والتمويل والإحالات قد تكون مرتبطة بالولايات المتحدة أو تعتمد على البلد. نضع هذه الموارد كمرجع تعليمي ولا نحولها إلى تعليمات قانونية أو مالية للأردن أو المنطقة العربية.</p></section>`, ['hub','services','resources','curriculum']);

const undiagnosed = shell('undiagnosed-journey', 'رحلة بلا تشخيص: كيف تنظّم البحث عن إجابة دون تشخيص ذاتي؟', 'دليل عربي للأسرة التي ما زالت تبحث عن تشخيص: تنظيم الخط الزمني والسجلات والفحوص والأسئلة والإحالات وتجنب إعادة الاختبارات أو الاستنتاجات غير الموثقة.', `<section class="hero"><h1>عندما لا يوجد تشخيص بعد: اجعل الرحلة قابلة للتتبع</h1><p>مورد Global Genes للمريض غير المشخّص يركز على الانتقال من الخوف والتشتت إلى الاستعداد والتنظيم. نترجم هذه الفكرة إلى ملف عمل لا إلى قائمة أمراض محتملة.</p></section><section class="panel"><h2>ملف التشخيص من خمس طبقات</h2><ol><li><strong>خط زمني:</strong> متى بدأت العلامات وما الذي تغير فعلًا؟</li><li><strong>الأدلة السابقة:</strong> تقارير وفحوص وصور ونتائج جينية كاملة، لا لقطات شاشة مبتورة.</li><li><strong>ما استُبعد ولماذا:</strong> اسم الفحص وتاريخه والنتيجة وتفسير المختص.</li><li><strong>النمط العائلي:</strong> معلومات صحية ذات صلة من الأقارب مع احترام الخصوصية.</li><li><strong>سؤال الإحالة:</strong> ما القرار الذي نحتاجه من التخصص التالي؟</li></ol></section><section class="tool"><h2>قبل الموعد التالي</h2><ul><li>اختر ثلاثة تغيرات عالية القيمة بدل عشرات الأعراض غير المرتبة.</li><li>اسأل هل توجد نتيجة قديمة تحتاج إعادة تفسير لأن المعرفة تغيرت.</li><li>اسأل إن كان اختصاص الوراثة أو الاستشارة الجينية مناسبًا ولماذا.</li><li>اطلب نسخة من البيانات والتقرير الكامل إذا كان النظام المحلي يسمح بذلك.</li><li>سجل ما لا يزال مجهولًا؛ عدم اليقين معلومة وليس فراغًا يجب ملؤه بتخمين.</li></ul></section>`, ['undiagnosed','services','hub']);

const newDiagnosis = shell('new-diagnosis', 'تشخيص مرض نادر جديد: أول خطوات عملية للأسرة', 'ما الذي تفعله الأسرة بعد تشخيص مرض نادر جديد: تثبيت اسم التشخيص ودليله، اختيار مصادر موثوقة، تحضير الأسئلة وبناء شبكة دعم دون استعجال قرارات علاجية.', `<section class="hero"><h1>وصل التشخيص: لا تجعل أول أسبوع سباقًا لجمع كل شيء</h1><p>ابدأ بتثبيت ما تعرفه، مصدر التشخيص وما يعنيه للفرد، ثم افصل بين معلومات المرض العامة وخطة الشخص الفعلية.</p></section><section class="panel"><h2>الأولوية في أول مراجعة</h2><table><tr><th>اسأل</th><th>لماذا؟</th></tr><tr><td>ما الاسم الدقيق والتصنيف أو الجين/المتغير إن كان ذا صلة؟</td><td>لمنع البحث عن حالة مشابهة بالاسم لكنها مختلفة سريريًا أو وراثيًا.</td></tr><tr><td>ما الدليل الذي بُني عليه التشخيص؟</td><td>تمييز التشخيص المؤكد من الاشتباه أو الوصف السريري.</td></tr><tr><td>ما الذي يحتاج متابعة الآن وما الذي يمكن تأجيله؟</td><td>تقليل الحمل وترتيب المخاطر.</td></tr><tr><td>هل توجد إرشادات أو منظمة متخصصة بالحالة؟</td><td>الانتقال من بحث عام إلى مصادر أكثر اختصاصًا.</td></tr></table></section><section class="note"><h2>قاعدة بحث</h2><p>ابدأ بالمصدر الرسمي أو المهني، ثم المراجعات العلمية، ثم منظمات المرضى الموثوقة لفهم الخبرة المعاشة والخدمات. لا تجعل قصة فردية أو إعلان علاج بديل مساويًا لدليل سريري.</p></section>`, ['hub','services','resources']);

const genetics = shell('genetic-testing-family-history', 'الفحوص الجينية والتاريخ العائلي في الأمراض النادرة: كيف تستعد؟', 'تحضير آمن للفحوص الجينية والتاريخ العائلي: ما الذي تجمعه، ماذا تسأل، ولماذا لا تكفي نتيجة خام أو تاريخ عائلي وحده لتشخيص ذاتي.', `<section class="hero"><h1>الفحص الجيني يبدأ بالسؤال وليس بالأنبوب</h1><p>Global Genes توفر موارد لفهم التاريخ الصحي العائلي والفحوص الجينية. القيمة العملية هي تحسين المعلومات التي تصل إلى المختص، لا استخدام النتيجة الخام لتشخيص النفس أو الأقارب.</p></section><section class="panel"><h2>اجمع ما يفيد دون انتهاك الخصوصية</h2><ul><li>صلة القرابة والعمر التقريبي عند ظهور الحالة إن كان معروفًا.</li><li>تشخيصات مؤكدة مقابل روايات عائلية غير موثقة.</li><li>نتائج جينية سابقة متاحة بموافقة أصحابها.</li><li>وفيات أو أعراض مبكرة ذات صلة عندما تكون المعلومة معروفة ومناسبة للسؤال السريري.</li></ul></section><section class="panel"><h2>أسئلة قبل الفحص</h2><ul><li>ما السؤال الذي يحاول الفحص الإجابة عنه؟</li><li>ماذا تعني نتيجة إيجابية أو سلبية أو غير حاسمة؟</li><li>هل قد تظهر نتائج ثانوية؟ وكيف تُدار الموافقة عليها؟</li><li>هل الاستشارة الجينية قبل الفحص أو بعده مناسبة؟</li><li>كيف ستُحفظ البيانات ومن يمكنه الوصول إليها وفق النظام المحلي؟</li></ul></section><section class="safety"><h2>لا تفسر VUS كتشخيص</h2><p>المتغير ذو الدلالة غير المؤكدة لا يتحول إلى سبب مرض بمجرد ظهوره في التقرير. التفسير يعتمد على تصنيف المختبر والسياق السريري والأدلة المتراكمة وقد يتغير مع الزمن.</p></section>`, ['history','undiagnosed','curriculum']);

const caregiver = shell('caregiver-support', 'مقدم رعاية لمرض نادر: خطة لتقليل العبء وتحسين التنسيق', 'دليل عملي لمقدمي رعاية الأشخاص ذوي الأمراض النادرة: توزيع الأدوار، تنظيم المعلومات، منع الاحتراق، الاستعداد للمواعيد وبناء شبكة دعم.', `<section class="hero"><h1>مقدم الرعاية يحتاج نظام دعم أيضًا</h1><p>Global Genes تجمع موارد لمقدمي الرعاية وتبرز أن رحلة التشخيص والرعاية قد تجعل الشخص مدير مواعيد وباحثًا ومناصرًا ومنسقًا في الوقت نفسه. الحل ليس مطالبة مقدم الرعاية بأن «يتحمل أكثر»، بل تقليل الحمل القابل للتقليل.</p></section><section class="panel"><h2>افصل الأدوار</h2><div class="grid"><div class="card"><strong>الرعاية المباشرة</strong>الأدوية كما وُصفت، التغذية، الحركة، الأمان والمتابعة اليومية.</div><div class="card"><strong>الإدارة</strong>المواعيد، الملفات، التأمين/التمويل المحلي، النقل والتواصل.</div><div class="card"><strong>المناصرة</strong>شرح الاحتياجات وطلب التكييفات والوصول للمعلومة.</div><div class="card"><strong>الحياة الشخصية</strong>النوم والعمل والعلاقات والصحة النفسية لمقدم الرعاية نفسه.</div></div></section><section class="tool"><h2>اختبار عبء أسبوعي</h2><p>حدد مهمة واحدة يمكن نقلها لشخص آخر، مهمة واحدة يمكن أتمتتها أو تجميعها، ومعلومة واحدة يمكن تحويلها إلى ملخص ثابت بدل شرحها من الصفر في كل موعد.</p></section>`, ['caregivers','services','resources']);

const mentalHealth = shell('mental-health-grief', 'الصحة النفسية والحزن في رحلة المرض النادر', 'فهم الضغط والحزن الغامض والقلق والعزلة لدى المرضى والأسر ومقدمي الرعاية، مع علامات طلب الدعم وحدود التثقيف العام.', `<section class="hero"><h1>الحزن قد يظهر حتى دون وفاة</h1><p>رحلة مرض نادر قد تتضمن خسارة توقعات أو يقين أو وظيفة أو مستقبل كان متخيّلًا. تسمية الضغط والحزن لا تعني أن كل استجابة طبيعية أصبحت اضطرابًا نفسيًا.</p></section><section class="panel"><h2>متى يكون الدعم مفيدًا؟</h2><ul><li>عندما يصبح الضغط مستمرًا ويعطل النوم أو العمل أو الرعاية أو العلاقات.</li><li>عندما يشعر مقدم الرعاية أنه لا يستطيع الاستمرار بأمان.</li><li>عندما تصبح العزلة أو الشعور بالذنب أو الخوف هي المسيطر على اليوم.</li><li>عندما يحتاج الطفل أو الأخوة إلى مساحة مناسبة للعمر لفهم ما يحدث.</li></ul></section><section class="safety"><h2>مؤشرات عاجلة</h2><p>عند وجود خطر وشيك على النفس أو الآخرين، أو فقدان القدرة على الحفاظ على السلامة، أو ارتباك طبي حاد، استخدم خدمات الطوارئ المحلية ولا تعتمد على موارد الإنترنت أو مجموعات الدعم.</p></section><section class="note"><h2>المجتمع الداعم ليس بديلًا للعلاج</h2><p>مجتمع المرض النادر قد يقلل العزلة ويعطي خبرة عملية، لكنه لا يحدد تشخيصًا نفسيًا ولا يقرر الدواء ولا يستبدل الرعاية المهنية عند الحاجة.</p></section>`, ['services','resources','hub']);

const research = shell('research-clinical-trials', 'البحث والتجارب السريرية في الأمراض النادرة: أسئلة قبل المشاركة', 'طريقة آمنة لتنظيم البحث عن الدراسات والتجارب السريرية في الأمراض النادرة: الأهلية، المرحلة، المخاطر، السفر، التكلفة والفرق بين البحث والعلاج.', `<section class="hero"><h1>وجود تجربة سريرية لا يعني أنها علاج مناسب لك</h1><p>Global Genes تساعد الأسر على الوصول إلى معلومات عن البحث والتجارب. دور هذه الصفحة هو تحويل الاكتشاف إلى أسئلة تحقق، لا اختيار تجربة أو التنبؤ بالاستفادة.</p></section><section class="panel"><h2>سبعة أسئلة قبل الحماس أو الرفض</h2><ol><li>ما السؤال العلمي والمرحلة الحالية للدراسة؟</li><li>هل معايير الأهلية تنطبق فعلًا، ومن يقرر ذلك؟</li><li>ما التدخل وما المقارنة وهل يوجد تعمية أو عشوائية؟</li><li>ما المخاطر المعروفة وما المجهول؟</li><li>ما المتطلبات: سفر، زيارات، فحوص، وقت، رعاية طفل أو إجازة عمل؟</li><li>من يدفع التكاليف المرتبطة بالدراسة وما الذي لا تغطيه؟</li><li>كيف سيؤثر الانضمام أو عدم الانضمام في الرعاية المعتادة والخيارات اللاحقة؟</li></ol></section><section class="note"><h2>افصل ثلاث طبقات</h2><p><strong>دراسة منشورة</strong> تعطي معلومة، <strong>تجربة مسجلة</strong> تختبر سؤالًا، و<strong>علاج معتمد</strong> له وضع تنظيمي محدد. الخلط بينها مصدر شائع للأمل غير الواقعي أو الخوف غير الضروري.</p></section>`, ['services','hub','curriculum']);

const trusted = shell('trusted-resource-navigation', 'كيف تجد مصدرًا موثوقًا عن مرض نادر؟', 'خريطة عربية لفرز موارد الأمراض النادرة حسب الغرض: معلومات طبية، منظمة مرضى، دعم ملاحي، بحث وتجارب، تعليم مهني، مع فحص الصلاحية الجغرافية.', `<section class="hero"><h1>لا يوجد «أفضل موقع» لكل سؤال</h1><p>Global Genes Resource Hub نفسه منظّم حسب الموضوع والجمهور ونوع المحتوى. الفكرة الأهم هي مطابقة المصدر بالغرض بدل جمع روابط كثيرة بلا وظيفة.</p></section><section class="panel"><h2>خريطة المصدر حسب السؤال</h2><table><tr><th>السؤال</th><th>نوع المصدر الأنسب كبداية</th></tr><tr><td>ما المرض وكيف يُشخّص؟</td><td>مرجع سريري/وراثي رسمي أو مهني ومصدر المرض المتخصص.</td></tr><tr><td>كيف أعيش مع الحالة وأتصل بغيري؟</td><td>منظمة مرضى موثوقة أو خدمة ملاحة مثل RARE Concierge، مع فحص البلد والنطاق.</td></tr><tr><td>ما الجديد في البحث؟</td><td>قاعدة أبحاث أو سجل تجارب رسمي، ثم مناقشة الانطباق مع المختص.</td></tr><tr><td>كيف أفهم المجال من البداية؟</td><td>منهج تعليمي منظم مثل Rare Disease Curriculum أو دليل تمهيدي موثوق.</td></tr><tr><td>هل هذه الخدمة أو المساعدة المالية متاحة لي؟</td><td>المصدر المحلي الرسمي؛ لا تفترض انتقال الأهلية بين الدول.</td></tr></table></section><section class="tool"><h2>اختبار الرابط قبل حفظه</h2><ul><li>من الناشر وما مهمته؟</li><li>هل يوضح تاريخ التحديث والمراجع؟</li><li>هل يميز المعلومات عن الإعلان أو جمع التبرعات؟</li><li>هل الادعاء الطبي أكبر من الدليل الذي يسنده؟</li><li>هل المحتوى عالمي أم مرتبط بنظام صحي/قانوني محدد؟</li></ul></section>`, ['hub','services','curriculum','resources']);

export const RARE_DISEASE_GLOBAL_GENES_PAGES: Record<string,string> = {
  '': hub,
  'undiagnosed-journey': undiagnosed,
  'new-diagnosis': newDiagnosis,
  'genetic-testing-family-history': genetics,
  'caregiver-support': caregiver,
  'mental-health-grief': mentalHealth,
  'research-clinical-trials': research,
  'trusted-resource-navigation': trusted,
};

export const RARE_DISEASE_GLOBAL_GENES_SLUGS = Object.keys(RARE_DISEASE_GLOBAL_GENES_PAGES);
