const SOURCES = {
  avenirCode: 'https://avenirsocial.ch/wp-content/uploads/2025/04/2025_Berufkodex_Soziale-Arbeit_def.pdf',
  avenirKnowledge: 'https://avenirsocial.ch/fachwissen/#broschure',
  lithuaniaCode: 'https://www.e-tar.lt/portal/en/legalAct/f596df101af111eeb233e8b04dc9bb3d',
  lithuaniaMethods: 'https://pktc.lt/metodine-informacija/metodine-medziaga',
  lsda: 'https://www.lsda.lt/kompetenciju-tobulinimo-centras/',
  talentia: 'https://talentia.lukusali.fi/index.html#/reader/c5aa171b-223d-43b7-9778-05a0d8cede8e',
  ifsw: 'https://www.ifsw.org/global-social-work-statement-of-ethical-principles/',
} as const;

type SourceKey = 'avenir' | 'lithuania' | 'talentia' | 'ifsw';
type PageSpec = {
  slug: string;
  title: string;
  description: string;
  intro: string;
  findings: string[];
  steps: string[];
  example: string;
  boundary: string;
  sources: SourceKey[];
};

const style = `<style>:root{--bg:#f4f8f7;--ink:#14251f;--muted:#536760;--line:#cfddd8;--brand:#075d4d;--soft:#e4f2ed;--warn:#fff8e8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Tahoma,Arial,sans-serif;line-height:1.9}a{color:var(--brand)}header,main,footer{max-width:1120px;margin:auto;padding:1rem clamp(1rem,3vw,2rem)}.hero,.panel,.sources,.note,.tool{background:#fff;border:1px solid var(--line);border-radius:18px;padding:1.2rem;margin:1rem 0}.hero{background:linear-gradient(135deg,var(--soft),#eef6ff)}.note{background:var(--warn);border-inline-start:6px solid #8a4f0b}.meta{color:var(--muted)}li{margin:.45rem 0}.eyebrow{font-weight:700;color:#164e63}</style>`;

function sourceList(keys: SourceKey[]) {
  const rows: string[] = [];
  if (keys.includes('avenir')) {
    rows.push(`<li><a href="${SOURCES.avenirCode}" target="_blank" rel="noopener noreferrer"><strong>AvenirSocial — Berufskodex Soziale Arbeit Schweiz / Code de déontologie</strong></a> — مدونة المهنة السويسرية الجديدة، نافذة من 1 يناير 2026 وفق الوثيقة المنشورة.</li>`);
    rows.push(`<li><a href="${SOURCES.avenirKnowledge}" target="_blank" rel="noopener noreferrer">AvenirSocial — الموارد والمعرفة المهنية</a></li>`);
  }
  if (keys.includes('lithuania')) {
    rows.push(`<li><a href="${SOURCES.lithuaniaCode}" target="_blank" rel="noopener noreferrer"><strong>Lithuania e-TAR — Order A1-448, Code of Ethics for Social Services Sector Workers</strong></a> — سجل رسمي نافذ منذ 6 يوليو 2023.</li>`);
    rows.push(`<li><a href="${SOURCES.lithuaniaMethods}" target="_blank" rel="noopener noreferrer">PKTC — مواد منهجية لممارسة الخدمات الاجتماعية</a></li>`);
    rows.push(`<li><a href="${SOURCES.lsda}" target="_blank" rel="noopener noreferrer">Lithuanian Association of Social Workers — Professional Competence Development Centre</a></li>`);
  }
  if (keys.includes('talentia')) rows.push(`<li><a href="${SOURCES.talentia}" target="_blank" rel="noopener noreferrer">Talentia Finland — Work, Values and Ethics</a></li>`);
  if (keys.includes('ifsw')) rows.push(`<li><a href="${SOURCES.ifsw}" target="_blank" rel="noopener noreferrer">IFSW — Global Social Work Statement of Ethical Principles</a></li>`);
  return rows.join('');
}

function shell(page: PageSpec) {
  const canonical = `https://healthrenewal.org/evidence-guides/social-work/${page.slug}/`;
  const jsonLd = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: page.title,
    description: page.description,
    inLanguage: 'ar',
    url: canonical,
    author: { '@type': 'Organization', name: 'منصة روافد | Health Renewal' },
    isPartOf: {
      '@type': 'CollectionPage',
      name: 'العمل الاجتماعي: الممارسة والأخلاقيات الدولية المقارنة',
      url: 'https://healthrenewal.org/evidence-guides/social-work/international-comparative-practice/',
    },
  });
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title} | روافد</title><meta name="description" content="${page.description}"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:locale" content="ar_AR"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${jsonLd}</script>${style}</head><body><header><a href="/"><strong>منصة روافد | Health Renewal</strong></a> · <a href="/evidence-guides/social-work/">العمل الاجتماعي</a> · <a href="/evidence-guides/social-work/international-comparative-practice/">الممارسة والأخلاقيات المقارنة</a></header><main><section class="hero"><div class="eyebrow">دليل مقارن مبني على مصادر مهنية ورسمية</div><h1>${page.title}</h1><p>${page.intro}</p></section><section class="panel"><h2>الخلاصة المهنية</h2><ul>${page.findings.map((item) => `<li>${item}</li>`).join('')}</ul></section><section class="tool"><h2>أداة تطبيق عملية</h2><ol>${page.steps.map((item) => `<li>${item}</li>`).join('')}</ol></section><section class="panel"><h2>مثال تطبيقي</h2><p>${page.example}</p></section><section class="note"><h2>حدود النقل بين الدول</h2><p>${page.boundary}</p><p>هذه قراءة عربية مستقلة للمقارنة والتثقيف والتطوير المهني. إدراج المصدر لا يعني أن AvenirSocial أو LSDA/PKTC أو الجهة الحكومية الليتوانية أو Talentia أو IFSW راجعت الصفحة أو اعتمدتها أو تشرف عليها.</p></section><section class="sources"><h2>المصادر الأصلية</h2><ul>${sourceList(page.sources)}</ul><p class="meta">منهج روافد يفصل بين المبدأ المهني القابل للمقارنة، والنص القانوني المحلي، وأداة التطبيق التي تصوغها روافد. التطبيق الفعلي يستلزم الرجوع إلى القانون والسياسات والإشراف المهني المحلي.</p></section></main><footer>روافد | Health Renewal — معرفة عربية قابلة للتتبع.</footer></body></html>`;
}

const specs: PageSpec[] = [
  {slug:'international-comparative-practice',title:'أخلاقيات وممارسة العمل الاجتماعي: مقارنة دولية تطبيقية',description:'بوابة عربية تقارن مبادئ وممارسات العمل الاجتماعي في سويسرا وليتوانيا وفنلندا ضمن إطار IFSW مع فصل القانون المحلي عن المبدأ المهني.',intro:'بوابة تجمع أوجه الاتفاق والاختلاف بين مصادر سويسرية وليتوانية وفنلندية وعالمية دون تحويل أي نظام وطني إلى وصفة عامة.',findings:['AvenirSocial يضيف الوعي بعلاقات القوة والرقمنة والاستدامة والوقاية والوصول العادل.','ليتوانيا تقدم مثالًا رسميًا يربط الأخلاق المهنية بالشفافية والمسؤولية والسرية.','Talentia يقوي مسار الكرامة وتقرير المصير وحقوق المستفيد وصنع القرار.','IFSW يوفر المرجع العالمي الأعلى مستوى الذي توضع تحته المقارنات الوطنية.'],steps:['حدد السؤال المهني أولًا.','افصل المبدأ عن القانون والسياسة المؤسسية.','قارن البدائل بحسب الضرر والعدالة والسلطة وصوت المستفيد.','وثق سبب القرار وما يحتاج إلى مرجع محلي.'],example:'في سؤال السرية تبدأ المقارنة بالمبدأ والضرورة والتناسب، ثم ينتقل التطبيق إلى القانون المحلي الذي يحدد متى يكون الإفصاح جائزًا أو واجبًا.',boundary:'مدونة AvenirSocial سويسرية، وA1-448 ليتوانية، ودليل Talentia فنلندي؛ لا تتحول أي قاعدة وطنية منها تلقائيًا إلى قاعدة قانونية عربية.',sources:['avenir','lithuania','talentia','ifsw']},
  {slug:'ethics-code-vs-local-law',title:'مدونة الأخلاقيات أم القانون المحلي؟ كيف نفرق بينهما',description:'دليل يميز بين المبدأ الأخلاقي والمعيار المهني والواجب القانوني والسياسة المؤسسية في قرارات العمل الاجتماعي.',intro:'الخلط بين المدونة والقانون والسياسة الداخلية ينتج قرارات ضعيفة. هذه الصفحة تفصل الطبقات الأربع قبل أي تطبيق.',findings:['المدونة توجه السلوك المهني لكنها لا تنشئ بذاتها قانون الدولة.','القانون يحدد سلطات وواجبات تختلف خصوصًا في الإبلاغ والأهلية وحماية البيانات.','السياسة المؤسسية تحتاج فحصًا عندما تتعارض مع حق أو مبدأ مهني.','AvenirSocial يقر بوجود توترات بين المتطلبات القانونية والمؤسسية واحتياجات المستفيد.'],steps:['سمّ طبقة كل قاعدة.','حدد ما هو ملزم قانونيًا محليًا.','وثق التعارض واطلب إشرافًا أو رأيًا قانونيًا عند الحاجة.','لا تنسب قاعدة أجنبية إلى نظامك المحلي.'],example:'طلب إداري واسع لكشف معلومات لا يبرر تلقائيًا مشاركة الملف كاملًا؛ يحدد الغرض والحد الأدنى اللازم والأساس القانوني أولًا.',boundary:'الصفحة لا تقدم رأيًا قانونيًا لأي دولة عربية.',sources:['avenir','lithuania','talentia','ifsw']},
  {slug:'power-awareness-social-work',title:'الوعي بالقوة والسلطة في العمل الاجتماعي',description:'إطار لفهم عدم توازن القوة بين الأخصائي والمستفيد وتقليل الإكراه وإساءة استخدام السلطة.',intro:'القوة تظهر في من يملك المعلومات والتقييم والوصول إلى الخدمة، وليس فقط في القرارات الإجبارية.',findings:['AvenirSocial يجعل الوعي بعلاقات القوة خطًا صريحًا للممارسة.','الاعتماد على الخدمة أو ضعف اللغة قد يزيد الضغط غير المقصود.','المشاركة الحقيقية تعني أثرًا ملموسًا لصوت المستفيد في القرار.','الشفافية حول السلطة والحدود تسمح بالاعتراض والمراجعة.'],steps:['حدد سلطتك الفعلية وحدودها.','افحص ما إذا كان الرفض سيشعر المستفيد بأنه عقوبة.','اعرض خيارات مفهومة.','راجع القرارات عالية الإكراه مع مشرف أو زميل مناسب.'],example:'قبول خطة خوفًا من فقد الخدمة لا يكفي كموافقة مستنيرة؛ يجب تصحيح الفهم وشرح البدائل.',boundary:'صلاحيات الأخصائي وإجراءات الاعتراض تختلف قانونيًا.',sources:['avenir','talentia','ifsw']},
  {slug:'participation-co-production-social-work',title:'المشاركة والتصميم المشترك في العمل الاجتماعي',description:'دليل لتحويل مشاركة المستفيد من حضور شكلي إلى تأثير قابل للتتبع في التقييم والخطة والخدمة.',intro:'المشاركة تبدأ بتحديد ما يمكن للمستفيد التأثير فيه وما يحتاجه كي يشارك فعلًا.',findings:['AvenirSocial يعامل المشاركة والاندماج الاجتماعي كمبدأ مهني.','المشاركة قد تكون فردية أو جماعية أو مجتمعية.','اللغة والتواصل والعمر والسلامة تؤثر في طريقة المشاركة.','يجب توضيح ما هو قابل للتغيير وما هو ثابت.'],steps:['حدد القرار ومساحة التأثير.','وفر تكييفات الوصول والتواصل.','سجل المقترحات وما تغير بسببها.','أعد النتيجة للمشاركين واشرح ما لم يتغير.'],example:'في تطوير نموذج استقبال لا يكفي سؤال الرضا؛ يُختبر أين يتعطل الفهم وما البيانات الحساسة التي يمكن تأجيلها.',boundary:'المشاركة لا تلغي متطلبات الحماية أو القانون المحلي.',sources:['avenir','ifsw']},
  {slug:'equitable-access-resources-social-work',title:'الوصول العادل إلى الموارد والخدمات الاجتماعية',description:'إطار لفحص حواجز الوصول وتجنب تحويل الفقر أو الإعاقة أو اللغة إلى سبب لاستبعاد المستفيد.',intro:'وجود الخدمة نظريًا لا يعني سهولة الوصول إليها؛ النقل والتكلفة واللغة والإعاقة والتوقيت قد تمنع الانتفاع.',findings:['AvenirSocial يربط الوصول العادل بالعدالة الاجتماعية وتوزيع الموارد.','تكرار الغياب قد يعكس عائقًا لا عدم التزام.','شفافية الأولويات والانتظار تقلل التحيز والقرارات غير المتسقة.','البيانات المجمعة تكشف فجوات لا تظهر في الحالة الفردية.'],steps:['ارسم رحلة الوصول إلى الخدمة.','حدد نقاط الانقطاع.','اختبر تعديلًا أو مسارًا بديلًا قابلًا للتطبيق.','راجع أنماط الرفض والانسحاب دون جمع بيانات غير لازمة.'],example:'خدمة صباحية فقط قد تستبعد العاملين بأجر يومي؛ نافذة بديلة أو إحالة مرنة قد تعالج السبب الحقيقي.',boundary:'أهلية الخدمات والاستحقاقات مسائل قانونية وتمويلية محلية.',sources:['avenir','lithuania','ifsw']},
  {slug:'sustainability-social-work',title:'الاستدامة والعدالة البيئية في العمل الاجتماعي',description:'دليل يربط الاستدامة بالهشاشة الاجتماعية والوصول إلى الموارد واستمرارية الخدمات.',intro:'الاستدامة هنا عدسة مهنية لفهم أثر الحرارة والتلوث والسكن والنقل والكوارث على الفئات الأكثر هشاشة.',findings:['AvenirSocial يدرج الاستدامة موضوعًا مركزيًا في المدونة الجديدة.','الأثر البيئي والاجتماعي غير موزع بالتساوي.','استمرارية الخدمة أثناء الأزمات جزء من التخطيط للفئات المعتمدة عليها.','التحول الرقمي أو البيئي لا ينبغي أن ينقل التكلفة إلى المستفيد.'],steps:['أضف المخاطر البيئية عند صلتها بالحالة.','حدد من قد يتضرر من التغيير التشغيلي.','وفر بدائل إتاحة مناسبة.','اربط خطط الطوارئ بأدوار واتصالات محدثة.'],example:'رقمنة كل المواعيد قد تقلل التنقل لكنها قد تستبعد من لا يملك جهازًا أو اتصالًا؛ لذلك يلزم مسار بديل.',boundary:'السياسات البيئية والطوارئ تختلف بين الدول.',sources:['avenir','ifsw']},
  {slug:'prevention-social-work',title:'الوقاية في العمل الاجتماعي: من رد الفعل إلى تقليل المخاطر مبكرًا',description:'إطار للوقاية المهنية يركز على عوامل الحماية والمخاطر والمشاركة دون وصم أو مراقبة مفرطة.',intro:'الوقاية تعني معالجة الضغوط والعوائق القابلة للتغيير قبل تحولها إلى أزمة، لا التنبؤ بمن سيفشل.',findings:['AvenirSocial يصف الوقاية كعمل منهجي واستباقي.','البيانات الحساسة تتطلب ضرورة وتناسبًا وشفافية.','تحسين النظام قد يكون أقوى من مراقبة الأفراد.','مشاركة المجتمع تقلل الافتراضات المهنية غير المطابقة للواقع.'],steps:['عرّف الخطر ومصدر الدليل.','حدد عامل حماية قابلًا للتعزيز.','اختر نتيجة قابلة للقياس.','راجع الآثار غير المقصودة على الخصوصية والعدالة.'],example:'بدل تصنيف المتغيبين كعاليي المخاطر، قد تكشف البيانات أن النقل هو سبب الانقطاع فتُعالج المشكلة تشغيليًا.',boundary:'معايير الإبلاغ والحماية وبرامج الوقاية الرسمية محلية.',sources:['avenir','ifsw']},
  {slug:'professional-integrity-social-work',title:'النزاهة المهنية والكفاءة وحدود الموارد في العمل الاجتماعي',description:'دليل للنزاهة والكفاءة والشفافية عند نقص المهارات أو الوقت أو الموارد أو وجود تضارب مصالح.',intro:'الاعتراف بحدود الكفاءة والموارد وطلب الإشراف قد يكون أكثر مهنية من أداء مهمة لا يمكن تنفيذها بأمان.',findings:['AvenirSocial يربط المهنية بالسلوك المسؤول والتمييز بين الحقائق والافتراضات.','ليتوانيا تربط المسؤولية بجودة أداء الواجبات والاستخدام السليم للمعلومات والوثائق.','تضارب المصالح قد يتطلب أكثر من مجرد الإفصاح.','ظروف العمل قد تصبح قضية جودة وسلامة عندما تمنع التقييم أو التوثيق الضروري.'],steps:['حدد الكفاءة والموارد الدنيا للمهمة.','اكشف فجوة المهارة أو التضارب مبكرًا.','اطلب إشرافًا أو إحالة عند الحاجة.','وثق القيود التنظيمية المؤثرة في الجودة.'],example:'أداة تقييم متخصصة غير مألوفة تستلزم تدريبًا أو إشرافًا أو إحالة، لا قراءة سريعة ثم إصدار نتيجة.',boundary:'الترخيص ونطاق الممارسة ومسؤولية صاحب العمل محلية.',sources:['avenir','lithuania','ifsw']},
  {slug:'confidentiality-privacy-social-work',title:'السرية والخصوصية والتناسب في العمل الاجتماعي',description:'إطار مقارن للسرية والخصوصية والموافقة والإفصاح الضروري وتقليل البيانات.',intro:'السرية ليست وعدًا مطلقًا ولا إذنًا مفتوحًا للمشاركة داخل الفريق؛ تبدأ بالغرض والحد الأدنى اللازم.',findings:['AvenirSocial يربط السرية بالشفافية والتناسب.','A1-448 الليتواني يجعل السرية مبدأً صريحًا ويضع حالات محلية محددة للإفصاح.','الموافقة على الخدمة لا تعني الموافقة على كل مشاركة لاحقة.','الأدوات الرقمية تزيد مخاطر التخزين والوصول غير المقصود.'],steps:['حدد غرض كل جمع أو مشاركة.','اختر الحد الأدنى من البيانات.','اشرح حدود السرية بلغة مفهومة.','وثق أساس أي إفصاح استثنائي.'],example:'في اجتماع متعدد التخصصات لا يعرض كل الملف؛ تُشارك فقط المعلومات اللازمة للقرار مع مراعاة الأساس القانوني.',boundary:'استثناءات السرية وواجبات الإبلاغ تختلف جذريًا بين الأنظمة.',sources:['avenir','lithuania','talentia','ifsw']},
  {slug:'organizational-loyalty-ethical-conflict',title:'تعارض الولاء بين المستفيد والمؤسسة والمهنة',description:'دليل للتعامل مع تعارض تعليمات المؤسسة وحقوق المستفيد والمعايير المهنية والقيود القانونية.',intro:'الأخصائي يعمل داخل مؤسسة لكنه ليس مجرد منفذ لتعليماتها؛ كما لا يستطيع تجاهل القانون والموارد والمسؤوليات التنظيمية.',findings:['AvenirSocial يصف الممارسة كمساحة تتقاطع فيها مطالب قد تتعارض.','المدونات تساعد في تحليل التعارض لكنها لا تنشئ سلطة قانونية جديدة.','التصعيد يكون أقوى عندما يصف أثرًا وبديلًا عمليًا.','التعارضات عالية الخطورة تحتاج إشرافًا ومسار تصعيد واضحًا.'],steps:['سمّ المتطلبات المتعارضة ومصدر كل منها.','صف الضرر المحتمل لكل خيار.','اقترح بديلًا أقل تقييدًا.','صعّد عبر المسار التنظيمي أو القانوني المناسب.'],example:'مؤشر سرعة يضغط وقت المقابلة يمكن معالجته بفرز أولي ومسار أطول للحالات المعقدة بدل اعتراض عام غير قابل للقياس.',boundary:'التظلم وحماية المبلغين ومسؤوليات الموظف تختلف قانونيًا.',sources:['avenir','lithuania','ifsw']},
  {slug:'documenting-ethical-decisions',title:'كيف نوثّق القرار الأخلاقي في العمل الاجتماعي',description:'قالب لتوثيق المعضلة والحقوق والبدائل والمصادر والاستشارة والقرار وخطة المراجعة.',intro:'التوثيق الجيد يسمح لشخص آخر بفهم السؤال والحقائق والبدائل ولماذا اتخذ القرار ومتى يراجع.',findings:['AvenirSocial يقدم المدونة كمرجع لقرارات مهنية مبررة.','الشفافية والمسؤولية الليتوانية تدعمان تفسير مسوغ القرار.','يجب فصل الحقائق عن الافتراضات.','نسخ نص المدونة لا يعوض تحليل الحالة.'],steps:['اكتب سؤال القرار في جملة.','افصل المؤكد عن غير المعروف.','سجل المبادئ والقانون والسياسة والبدائل.','اختم بالقرار والسبب والاستشارة وشرط المراجعة.'],example:'في قرار مشاركة معلومة: حدد الخطر والمبدأ والقاعدة المحلية والبدائل ثم نطاق الإفصاح وسبب اختياره.',boundary:'متطلبات السجلات الرسمية قد تحتاج نماذج قانونية محلية.',sources:['avenir','lithuania','talentia']},
  {slug:'supervision-consultation-ethical-dilemmas',title:'الإشراف والاستشارة في المعضلات الأخلاقية',description:'متى يحتاج القرار الأخلاقي إلى إشراف أو استشارة قانونية أو مراجعة متعددة التخصصات وكيف نحضر السؤال.',intro:'الاستشارة مهمة عندما تكون المعلومات ناقصة أو الحقوق متعارضة أو القرار غير قابل للتراجع أو الخطر مرتفعًا.',findings:['AvenirSocial يشير إلى موارد وأدوات لصنع القرار الأخلاقي الزملائي.','الإشراف الجيد يناقش المنطق والبدائل.','الاستشارة القانونية تجيب عن القانون ولا تستبدل الحكم المهني.','المراجعة متعددة التخصصات مفيدة مع الحفاظ على الحد الأدنى من البيانات.'],steps:['حدد السؤال الذي لا تستطيع حسمه.','اذكر درجة الاستعجال.','شارك أقل بيانات لازمة.','سجل الرأي وكيف أثر في القرار.'],example:'عند تعارض الخصوصية مع خطر محتمل، يلخص الأخصائي الخطر ومصدره والخيارات والنقطة القانونية المحددة المطلوب حسمها.',boundary:'هيكل الإشراف واللجان والمسؤولية القانونية مؤسسي ومحلي.',sources:['avenir','lithuania','talentia','ifsw']},
  {slug:'social-work-ethics-switzerland',title:'أخلاقيات العمل الاجتماعي في سويسرا: ماذا يضيف إطار AvenirSocial 2026؟',description:'قراءة عربية سياقية لمدونة AvenirSocial الجديدة: القوة والمشاركة والاستدامة والرقمنة والخصوصية والوصول العادل.',intro:'المدونة الجديدة توسع الأخلاقيات إلى قضايا معاصرة تشمل القوة والرقمنة والاستدامة والوقاية والعمل المجتمعي.',findings:['المدونة تستند إلى مرجعيات العمل الاجتماعي الدولية مع سياق سويسري.','الوثيقة المنشورة تشير إلى استبدال نسخة 2010 والنفاذ في 1 يناير 2026.','البنية تربط الكرامة والعدالة بالمشاركة والاستدامة وخطوط ممارسة مثل الخصوصية والرقمنة.','قيمتها لروافد هي إثراء أسئلة الممارسة لا تحويلها إلى قانون عربي.'],steps:['حدد المبدأ أو خط الممارسة.','قارنه بمرجع عالمي أو وطني آخر.','افصل العنصر السويسري المحلي.','صغ تطبيقًا عربيًا مستقلًا دون ادعاء ترجمة رسمية.'],example:'إدراج القوة والرقمنة يسمح بتحليل استبعاد الفئات بسبب التحول الرقمي بدل حصر الأخلاق في السرية التقليدية.',boundary:'هذه قراءة مستقلة ولا تعني مراجعة AvenirSocial للتفسير.',sources:['avenir','ifsw']},
  {slug:'social-services-worker-ethics-lithuania',title:'مدونة أخلاقيات العاملين في الخدمات الاجتماعية في ليتوانيا',description:'قراءة عربية للقرار الليتواني A1-448 ودلالاته في الشفافية والمسؤولية والسرية دون تعميم القانون خارج ليتوانيا.',intro:'e-TAR يسجل A1-448 كأمر رسمي نافذ منذ 6 يوليو 2023، لذلك يعامل كنص وطني محدد لا كمعيار عالمي.',findings:['الكود يحدد متطلبات وقيم السلوك للعاملين في قطاع الخدمات الاجتماعية الليتواني.','يتناول السرية والشفافية والمسؤولية ضمن الإطار المحلي.','تجنب تضارب المصالح والاستخدام السليم للمعلومات والوثائق عناصر مفيدة للمقارنة.','مواد PKTC تضيف طبقة منهجية وتطوير كفاءة إلى جانب النص الرسمي.'],steps:['ابدأ باعتباره نصًا ليتوانيًا.','ميز ما يعتمد على قانون أو مؤسسة محلية.','قارن المبدأ بالمصادر العالمية والوطنية الأخرى.','اذكر ليتوانيا بوضوح عند عرض واجب محلي.'],example:'بدل ترجمة استثناءات السرية حرفيًا، تلخص الفكرة المقارنة وتُحال إلى النص الرسمي ويظل القانون المحلي مرجع التطبيق.',boundary:'A1-448 لا يستخدم كحكم قانوني في الأردن أو أي دولة أخرى.',sources:['lithuania','ifsw']},
  {slug:'compare-finland-switzerland-lithuania',title:'فنلندا وسويسرا وليتوانيا: مقارنة أخلاقيات العمل الاجتماعي',description:'مقارنة بين Talentia وAvenirSocial ومدونة ليتوانيا الرسمية عبر الحقوق والقوة والسرية والمشاركة والمساءلة.',intro:'المقارنة لا ترتب المدونات؛ بل تبين كيف تتكرر المبادئ الأساسية وتختلف طريقة تنظيمها وتفصيلها.',findings:['اتفاق واسع على الكرامة والحقوق والعدالة والسرية والمسؤولية.','سويسرا تبرز القوة والاستدامة والرقمنة والوصول العادل.','فنلندا تقوي حقوق العميل وتقرير المصير وصنع القرار.','ليتوانيا توضح كيف تدخل الأخلاقيات في نص تنظيمي رسمي.'],steps:['ضع السؤال ضمن محور واضح.','حدد المشترك دون طمس الفروق.','علّم أي عنصر قانوني أو وطني.','استخدم النتيجة مع مرجع محلي عند التطبيق.'],example:'في السرية يتكرر مبدأ الحماية والتناسب، لكن شروط الإفصاح الإلزامي تبقى مسألة قانون محلي.',boundary:'الاختلاف في مستوى التفصيل لا يعني تقييم قوة أو ضعف أي دولة.',sources:['avenir','lithuania','talentia','ifsw']},
  {slug:'ethics-implementation-organizations',title:'كيف تحوّل المؤسسة مدونة الأخلاقيات إلى ممارسة يومية؟',description:'خطة تربط مدونة الأخلاقيات بالتدريب والإشراف والسياسات والحوادث والقياس والمراجعة.',intro:'وجود المدونة على الموقع لا يثبت تطبيقها؛ التنفيذ يظهر في النماذج والإشراف والتدريب والوصول وإدارة البيانات والشكاوى.',findings:['AvenirSocial يربط المدونة بموارد وأدوات تنفيذ.','PKTC يقدم مثالًا على تطوير الكفاءة والمساعدة المنهجية.','المبدأ يحتاج سلوكًا أو قرارًا يمكن ملاحظته.','مراجعة الحوادث يجب أن تبحث في النظام والموارد والتدريب أيضًا.'],steps:['اختر مبادئ عالية المخاطر واربطها بإجراءات قائمة.','حدد تدريبًا وإشرافًا ومؤشرًا لكل مبدأ.','راجع عينة قرارات أو شكاوى.','حدّث السياسة والأداة والتدريب معًا وأعد القياس.'],example:'لتطبيق السرية تراجع المؤسسة صلاحيات الوصول ونموذج الموافقة واجتماعات الفرق وآلية الإفصاح، لا أن تكتفي بدورة سنوية.',boundary:'الإطار لتحسين الجودة ولا يستبدل متطلبات الاعتماد أو حماية البيانات المحلية.',sources:['avenir','lithuania','talentia','ifsw']},
];

export const SOCIAL_WORK_COMPARATIVE_PAGES: Record<string, string> = Object.fromEntries(specs.map((page) => [page.slug, shell(page)]));
export const SOCIAL_WORK_COMPARATIVE_SLUGS = Object.keys(SOCIAL_WORK_COMPARATIVE_PAGES).sort();

const hubCard = `<section class="panel" data-rawafid-comparative-layer="20260901"><h2>جديد: الممارسة والأخلاقيات الدولية المقارنة</h2><p>أضفنا مسارًا يقارن AvenirSocial في سويسرا، ومدونة العاملين في الخدمات الاجتماعية في ليتوانيا، وTalentia في فنلندا، ضمن إطار IFSW مع فصل القانون المحلي عن المبدأ المهني.</p><p><a href="/evidence-guides/social-work/international-comparative-practice/"><strong>فتح المسار المقارن</strong></a> · <a href="/evidence-guides/social-work/compare-finland-switzerland-lithuania/">مقارنة فنلندا وسويسرا وليتوانيا</a></p></section>`;
const ethicsCard = `<section class="panel" data-rawafid-comparative-layer="20260901"><h2>طبقة مقارنة دولية</h2><p>اقرأ الموضوع بجانب AvenirSocial السويسرية ومدونة ليتوانيا الرسمية ودليل Talentia الفنلندي مع فصل المبدأ المهني عن القانون المحلي.</p><p><a href="/evidence-guides/social-work/international-comparative-practice/">بوابة المقارنة</a> · <a href="/evidence-guides/social-work/ethics-code-vs-local-law/">المدونة والقانون</a></p></section>`;

export function enrichSocialWorkPageWithComparative(html: string, key: string) {
  if (html.includes('data-rawafid-comparative-layer="20260901"')) return html;
  const ethicsKeys = ['professional-ethics','human-dignity-social-justice','self-determination-client-rights','ethical-decision-making','professional-boundaries-conflicts','advocacy-accountability','digital-ethics-confidentiality'];
  const block = key === '' ? hubCard : ethicsKeys.includes(key) ? ethicsCard : '';
  if (!block) return html;
  if (html.includes('</main>')) return html.replace('</main>', `${block}</main>`);
  return html.replace('</body>', `${block}</body>`);
}
