const TALENTIA_GUIDE = 'https://talentia.lukusali.fi/index.html#/reader/c5aa171b-223d-43b7-9778-05a0d8cede8e';
const TALENTIA_NEWS = 'https://www.talentia.fi/en/news/talentias-ethical-guidelines-are-now-available-in-english/';
const IFSW = 'https://www.ifsw.org/global-social-work-statement-of-ethical-principles/';
const CRPD = 'https://www.ohchr.org/sites/default/files/Ch_IV_15.pdf';

const style = `<style>:root{--bg:#f4f8f7;--ink:#14251f;--muted:#536760;--line:#cfddd8;--brand:#075d4d;--soft:#e4f2ed;--warn:#fff6e6}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Tahoma,Arial,sans-serif;line-height:1.95}a{color:var(--brand)}header,main,footer{max-width:1120px;margin:auto;padding:1rem clamp(1rem,3vw,2rem)}.hero,.panel,.sources,.note,.tool{background:#fff;border:1px solid var(--line);border-radius:18px;padding:1.2rem;margin:1rem 0}.hero{background:linear-gradient(135deg,var(--soft),#fff8e9)}.note{border-inline-start:6px solid #8a4f0b;background:var(--warn)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:.8rem}.card{display:block;background:#fff;border:1px solid var(--line);border-radius:14px;padding:.9rem;text-decoration:none;color:var(--ink)}.card strong{display:block;color:var(--brand)}table{width:100%;border-collapse:collapse;background:#fff}th,td{border:1px solid var(--line);padding:.7rem;vertical-align:top}th{background:#edf7f3}.meta{color:var(--muted)}li{margin:.45rem 0}code{background:#eef4f2;padding:.1rem .3rem;border-radius:5px}</style>`;

function shell(slug:string,title:string,description:string,body:string){
  const canonical=`https://healthrenewal.org/evidence-guides/social-work/${slug}/`;
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | روافد</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:locale" content="ar_AR"><meta property="og:title" content="${title}"><meta property="og:url" content="${canonical}">${style}</head><body><header><a href="/"><strong>منصة روافد | Health Renewal</strong></a> · <a href="/evidence-guides/social-work/">العمل الاجتماعي</a> · <a href="/evidence-guides/social-work/professional-ethics/">أخلاقيات المهنة</a></header><main>${body}<section class="sources"><h2>المصادر المؤسسة</h2><ul><li><a href="${TALENTIA_GUIDE}" target="_blank" rel="noopener noreferrer"><strong>Talentia — Work, Values and Ethics: Ethical Guidelines for Social Welfare Professionals</strong></a></li><li><a href="${TALENTIA_NEWS}" target="_blank" rel="noopener noreferrer">Talentia — الصفحة الرسمية للنسخة الإنجليزية</a></li><li><a href="${IFSW}" target="_blank" rel="noopener noreferrer">IFSW — Global Social Work Statement of Ethical Principles</a></li><li><a href="${CRPD}" target="_blank" rel="noopener noreferrer">United Nations — Convention on the Rights of Persons with Disabilities</a></li></ul><p class="meta">أوصت Talentia مباشرة بهذا الدليل لمنصة Health Renewal وسمحت بالاستشهاد والربط مع النسب الكامل إليها. هذه الصفحات تكييفات عربية مستقلة وليست ترجمة رسمية، ولا تعني اعتمادًا أو شراكة أو مصادقة من Talentia. الأجزاء المرتبطة بالتشريع ونظام الخدمات الفنلندي لا تُنقل تلقائيًا إلى أي دولة عربية.</p></section></main><footer>روافد | Health Renewal — للتثقيف والتطوير المهني، مع وجوب الرجوع إلى القانون والسياسات والإشراف المحلي.</footer></body></html>`;
}

const hub=shell('professional-ethics','أخلاقيات العمل الاجتماعي: مرجع تطبيقي عربي','مرجع تطبيقي يربط مبادئ Talentia وIFSW بقرارات العمل الاجتماعي اليومية: الحقوق، تقرير المصير، العدالة، الحدود المهنية والمساءلة.',`<section class="hero"><p><strong>قسم مرجعي متخصص</strong></p><h1>أخلاقيات العمل الاجتماعي</h1><p>هذا المسار لا يعرض الأخلاقيات كشعارات. كل صفحة تبدأ بسؤال مهني قابل للفحص، ثم تحدد الحقوق المتأثرة، تضارب المصالح أو السلطة، والقرار الأقل تقييدًا، وطريقة التوثيق والمراجعة.</p></section><section class="note"><h2>لماذا Talentia هنا؟</h2><p>دليل Talentia يركز على الكرامة الإنسانية، العدالة الاجتماعية، حقوق العملاء، حق تقرير المصير، المسؤولية المهنية واتخاذ القرار الأخلاقي. كما نبهت Talentia صراحة إلى أن بعض تفاصيل الدليل فنلندية تشريعيًا وخدميًا؛ لذلك نفصل بين <strong>المبدأ الأخلاقي القابل للنقل</strong> و<strong>القاعدة القانونية المحلية</strong>.</p></section><section class="panel"><h2>خريطة المسار</h2><div class="grid"><a class="card" href="../human-dignity-social-justice/"><strong>الكرامة والعدالة الاجتماعية</strong>اختبار الوصم، التمييز، الوصول والعوائق البنيوية.</a><a class="card" href="../self-determination-client-rights/"><strong>تقرير المصير وحقوق المستفيد</strong>الاختيار، الموافقة، المخاطر، الأهلية والدعم.</a><a class="card" href="../ethical-decision-making/"><strong>اتخاذ القرار الأخلاقي</strong>إطار عملي عند تعارض الحقوق والواجبات.</a><a class="card" href="../professional-boundaries-conflicts/"><strong>الحدود المهنية وتعارض المصالح</strong>النفوذ، العلاقات المزدوجة، الهدايا والمصالح.</a><a class="card" href="../advocacy-accountability/"><strong>المناصرة والمساءلة</strong>متى يصبح الصمت المهني مشكلة أخلاقية؟</a><a class="card" href="../digital-ethics-confidentiality/"><strong>الأخلاقيات الرقمية والسرية</strong>المراسلة، المنصات، الذكاء الاصطناعي والحد الأدنى من البيانات.</a></div></section><section class="tool"><h2>قاعدة الست خطوات</h2><ol><li>صف المشكلة دون لغة تشخيصية أو اتهامية غير لازمة.</li><li>حدد الحقوق والمبادئ المتأثرة ومن يملك السلطة في القرار.</li><li>افصل ما يفرضه القانون المحلي عما تقترحه الأخلاقيات المهنية.</li><li>قارن البدائل بحسب الضرر، التقييد، العدالة وإمكانية التراجع.</li><li>اشرك المستفيد بقدر ممكن وقدم معلومات مفهومة وخيارات حقيقية.</li><li>وثق السبب، البدائل المستبعدة، الاستشارة المطلوبة وخطة المراجعة.</li></ol></section>`);

const dignity=shell('human-dignity-social-justice','الكرامة الإنسانية والعدالة الاجتماعية في العمل الاجتماعي','دليل تطبيقي لفحص الوصم والتمييز والعوائق البنيوية والعدالة في الوصول للخدمات داخل ممارسة العمل الاجتماعي.',`<section class="hero"><h1>الكرامة الإنسانية والعدالة الاجتماعية</h1><p>الكرامة تعني أن الشخص ليس «حالة» أو «ملفًا». والعدالة الاجتماعية تعني أن تقييم المشكلة لا يتوقف عند السلوك الفردي إذا كانت البيئة أو المؤسسة تنتج عائقًا يمكن تغييره.</p></section><section class="panel"><h2>اختبار من خمس نقاط</h2><table><tr><th>السؤال</th><th>ما الذي نبحث عنه؟</th></tr><tr><td>هل اللغة تحفظ الكرامة؟</td><td>استبدال الأوصاف الوصمية بوصف سلوكي أو وظيفي دقيق.</td></tr><tr><td>هل الوصول متكافئ؟</td><td>لغة، إعاقة، نقل، تكلفة، توقيت، هوية أو إجراء إداري يمنع الخدمة.</td></tr><tr><td>هل القرار يعاقب الفقر أو الهشاشة؟</td><td>اشتراطات يصعب تحقيقها بسبب ظرف اجتماعي لا بسبب رفض متعمد.</td></tr><tr><td>هل صوت الشخص حاضر؟</td><td>وجود أثر فعلي لرأيه لا مجرد توقيع أو حضور شكلي.</td></tr><tr><td>هل يمكن تعديل النظام؟</td><td>إحالة المشكلة إلى مستوى الفريق أو الإدارة عندما يكون سببها بنيويًا.</td></tr></table></section><section class="panel"><h2>مثال مهني</h2><p>إذا missed أحد المستفيدين مواعيد متعددة، فالتفسير الأخلاقي لا يبدأ تلقائيًا من «عدم الالتزام». يُفحص النقل، ساعات العمل، رعاية الأطفال، الإعاقة، الاتصال الهاتفي، والخوف من المؤسسة. بعد ذلك فقط يُبنى قرار الاستمرار أو تعديل الخطة.</p></section><section class="note"><h2>حدود النقل</h2><p>العدالة مبدأ عام، لكن استحقاقات الخدمات وحقوق الطعن وآليات الشكوى تختلف قانونيًا بين الدول. لا تُستخدم أمثلة فنلندية كقواعد استحقاق عربية.</p></section>`);

const autonomy=shell('self-determination-client-rights','تقرير المصير وحقوق المستفيد','دليل عملي لتقرير المصير والموافقة والاختيار والمخاطر والقرار المدعوم في العمل الاجتماعي.',`<section class="hero"><h1>تقرير المصير وحقوق المستفيد</h1><p>السؤال ليس: «هل وافق؟» فقط، بل: هل فهم؟ هل كانت لديه بدائل واقعية؟ هل تعرض لضغط؟ وهل استُخدم أقل تدخل مقيد؟</p></section><section class="panel"><h2>سلم القرار</h2><ol><li><strong>معلومة مفهومة:</strong> شرح الخيارات والنتائج بلغة مناسبة.</li><li><strong>اختيار حقيقي:</strong> عرض بدائل واقعية لا خيار صوري واحد.</li><li><strong>دعم القرار:</strong> استخدام مترجم، تواصل بديل، شخص موثوق أو وقت إضافي عند الحاجة.</li><li><strong>فحص الخطر:</strong> تحديد خطر ملموس ومحدد بدل استخدام عبارات عامة مثل «مصلحته».</li><li><strong>أقل تقييد:</strong> اختيار التدخل الذي يحقق الحماية بأقل انتقاص ممكن من الحرية.</li><li><strong>مراجعة دورية:</strong> أي تقييد استثنائي يجب أن يكون قابلًا للمراجعة والانتهاء.</li></ol></section><section class="panel"><h2>علامات موافقة غير كافية</h2><ul><li>التوقيع دون فهم جوهر القرار.</li><li>ربط الخدمة الأساسية بالموافقة على إجراء غير ضروري.</li><li>تجاهل وسائل التواصل الداعمة لشخص ذي إعاقة.</li><li>اعتبار اختلاف الشخص مع المختص دليلًا تلقائيًا على ضعف البصيرة.</li></ul></section><section class="note"><h2>الأهلية القانونية ليست استنتاجًا أخلاقيًا</h2><p>تحديد الأهلية أو الوصاية أو الإجراء الإلزامي مسألة قانونية/سريرية بحسب النظام المحلي. هذه الصفحة تقدم إطارًا أخلاقيًا لدعم المشاركة وتقليل التقييد، لا حكمًا قانونيًا.</p></section>`);

const decision=shell('ethical-decision-making','اتخاذ القرار الأخلاقي في العمل الاجتماعي','إطار منظم لاتخاذ القرار الأخلاقي عند تعارض السرية والسلامة والاستقلال والعدالة والمسؤولية المهنية.',`<section class="hero"><h1>اتخاذ القرار الأخلاقي</h1><p>المعضلة الأخلاقية الحقيقية تظهر عندما تكون هناك قيمتان مشروعـتان على الأقل لا يمكن تحقيقهما كاملتين في الوقت نفسه.</p></section><section class="tool"><h2>نموذج 8 أسئلة قبل القرار</h2><ol><li>ما الوقائع المؤكدة وما الافتراضات؟</li><li>من الأطراف المتأثرة وما حقوق كل طرف؟</li><li>ما المبادئ المتعارضة: استقلال، سرية، سلامة، عدالة، ولاء مهني؟</li><li>هل يوجد واجب قانوني محلي يغيّر مساحة الاختيار؟</li><li>ما البدائل الواقعية، بما فيها خيار عدم التدخل؟</li><li>أي بديل أقل تقييدًا وأقل ضررًا ويمكن التراجع عنه؟</li><li>من يجب استشارته: مشرف، زميل، لجنة أخلاقيات، قانوني؟</li><li>متى وكيف ستُراجع النتيجة بعد التنفيذ؟</li></ol></section><section class="panel"><h2>قالب توثيق مختصر</h2><p><code>المشكلة → الوقائع → الحقوق المتأثرة → القانون/السياسة → البدائل → تقييم الضرر والتقييد → رأي المستفيد → الاستشارة → القرار والمبرر → تاريخ المراجعة</code></p></section><section class="panel"><h2>أخطاء شائعة</h2><ul><li>تحويل سياسة المؤسسة إلى «قاعدة أخلاقية» دون فحص.</li><li>استخدام «مصلحة المستفيد» دون تحديد مصلحة قابلة للشرح.</li><li>إخفاء التعارض بدل توثيقه.</li><li>عدم تسجيل البدائل الأقل تقييدًا التي تمت مناقشتها.</li></ul></section>`);

const boundaries=shell('professional-boundaries-conflicts','الحدود المهنية وتعارض المصالح','دليل عملي للحدود المهنية والعلاقات المزدوجة والهدايا وتعارض المصالح والنفوذ في العمل الاجتماعي.',`<section class="hero"><h1>الحدود المهنية وتعارض المصالح</h1><p>ليست كل علاقة خارج الإطار الرسمي إساءة، لكن أي علاقة تزيد اعتماد المستفيد على المختص أو تمنح المختص منفعة شخصية أو تضعف الحكم المهني تحتاج فحصًا واضحًا.</p></section><section class="panel"><h2>مصفوفة الفحص</h2><table><tr><th>الموقف</th><th>سؤال الحسم</th></tr><tr><td>هدية</td><td>هل تؤثر القيمة أو التوقيت أو الثقافة أو توقع المقابل في العلاقة المهنية؟</td></tr><tr><td>تواصل شخصي</td><td>هل له غرض مهني مشروع؟ وهل يمكن توثيقه والدفاع عنه؟</td></tr><tr><td>علاقة مزدوجة</td><td>هل توجد بدائل تقلل تضارب الأدوار، خصوصًا في المجتمعات الصغيرة؟</td></tr><tr><td>منفعة مالية/تجارية</td><td>هل يستفيد المختص أو قريب منه من قرار الإحالة أو الشراء؟</td></tr><tr><td>وسائل التواصل</td><td>هل يكشف الاتصال علاقة مهنية أو معلومات حساسة؟</td></tr></table></section><section class="panel"><h2>قاعدة الإفصاح والمراجعة</h2><p>عند وجود تعارض محتمل، لا يعتمد المختص على تقديره الشخصي وحده. يُفصح عنه ضمن الإشراف أو المسار المؤسسي المناسب، ويُوثق سبب استمرار العلاقة أو تغييرها، مع حماية خصوصية المستفيد.</p></section>`);

const advocacy=shell('advocacy-accountability','المناصرة والمساءلة المهنية','إطار للمناصرة المهنية والمساءلة ورفع العوائق البنيوية وتفسير القرار في العمل الاجتماعي.',`<section class="hero"><h1>المناصرة والمساءلة المهنية</h1><p>المسؤولية المهنية لا تنتهي بتنفيذ الإجراء الصحيح إداريًا. إذا كانت القاعدة أو الممارسة تُنتج ضررًا يمكن توقعه أو تمييزًا أو حرمانًا غير مبرر، تصبح المناصرة جزءًا من العمل المهني.</p></section><section class="panel"><h2>مستويات المناصرة</h2><ol><li><strong>الفرد:</strong> إزالة عائق مباشر أمام خدمة أو حق.</li><li><strong>الفريق:</strong> تعديل خطة أو توزيع أدوار أو تفسير سياسة.</li><li><strong>المؤسسة:</strong> توثيق نمط متكرر ورفع توصية قابلة للقياس.</li><li><strong>النظام:</strong> دعم تغيير سياسة أو إجراء عندما تكون المشكلة بنيوية ومتكررة.</li></ol></section><section class="panel"><h2>المساءلة القابلة للفحص</h2><ul><li>ما القرار الذي اتُّخذ؟</li><li>ما مصدر السلطة أو السياسة؟</li><li>ما أثر القرار المتوقع على المستفيد؟</li><li>ما البدائل التي رُفضت ولماذا؟</li><li>ما مسار الاعتراض أو المراجعة؟</li></ul></section><section class="note"><h2>المناصرة ليست وعدًا بنتيجة</h2><p>المختص يستطيع شرح الحقوق والمسارات ودعم الوصول إليها، لكنه لا يضمن قرار مؤسسة أخرى ولا يقدّم تمثيلًا قانونيًا ما لم يكن مخولًا بذلك.</p></section>`);

const digital=shell('digital-ethics-confidentiality','الأخلاقيات الرقمية والسرية في العمل الاجتماعي','دليل تطبيقي للسرية وتقليل البيانات والمراسلة والمنصات والذكاء الاصطناعي في ممارسة العمل الاجتماعي.',`<section class="hero"><h1>الأخلاقيات الرقمية والسرية</h1><p>الأداة الرقمية لا تغيّر المبدأ الأخلاقي: اجمع أقل قدر لازم، شارك أقل قدر لازم، واعرف أين تذهب البيانات ومن يستطيع الوصول إليها.</p></section><section class="panel"><h2>فحص قبل استخدام أداة رقمية</h2><ol><li>هل الأداة معتمدة مؤسسيًا لهذا النوع من البيانات؟</li><li>ما البيانات الضرورية فعلًا للغرض المحدد؟</li><li>هل يعرف المستفيد قناة التواصل ومخاطرها وحدود الخصوصية؟</li><li>هل تُرسل البيانات إلى مزود خارجي أو تُستخدم لتدريب نموذج؟</li><li>من يملك صلاحية الوصول والسجلات؟</li><li>ما خطة التعامل مع إرسال خاطئ أو اختراق أو جهاز مفقود؟</li></ol></section><section class="panel"><h2>استخدام الذكاء الاصطناعي</h2><ul><li>لا تُدخل معلومات تعريفية أو سرية في خدمة غير مصرح بها.</li><li>لا تجعل المخرجات الآلية بديلًا عن الحكم المهني أو موافقة صاحب الصلاحية.</li><li>تحقق من التحيز والهلوسة والمراجع قبل الاعتماد.</li><li>إذا أثر النظام الآلي في قرار يمس حقًا أو خدمة، يجب أن يكون القرار قابلًا للتفسير والمراجعة البشرية.</li></ul></section><section class="panel"><h2>قاعدة الحد الأدنى</h2><p>إذا كان الغرض يمكن تحقيقه بمعلومة أقل تحديدًا أو قناة أكثر أمانًا، فالأصل اختيار البديل الأقل كشفًا للبيانات.</p></section>`);

export const SOCIAL_WORK_TALENTIA_PAGES: Record<string,string>={
  'professional-ethics':hub,
  'human-dignity-social-justice':dignity,
  'self-determination-client-rights':autonomy,
  'ethical-decision-making':decision,
  'professional-boundaries-conflicts':boundaries,
  'advocacy-accountability':advocacy,
  'digital-ethics-confidentiality':digital,
};

export const SOCIAL_WORK_TALENTIA_SLUGS=Object.keys(SOCIAL_WORK_TALENTIA_PAGES).sort();

const TALENTIA_RELATED = new Set(['','ethics-power-autonomy','privacy-information-sharing','involuntary-participation','participation-and-voice','supported-decision-making','documenting-disagreement','non-stigmatizing-professional-language','institutional-advocacy','working-relationship']);

export function enrichSocialWorkPageWithTalentia(html:string,key:string){
  if(!TALENTIA_RELATED.has(key)||html.includes('RAWAFID_TALENTIA_ETHICS_LAYER')) return html;
  const panel=`<!-- RAWAFID_TALENTIA_ETHICS_LAYER --><section class="panel talentia-ethics-layer"><h2>طبقة أخلاقيات Talentia</h2><p>أوصت <strong>Talentia Union of Professional Social Workers</strong> لمنصة Health Renewal بدليلها <em>Work, Values and Ethics</em> وسمحت بالاستشهاد والربط مع النسب الكامل. يضيف المسار الجديد أدوات عملية للكرامة والعدالة وتقرير المصير والقرار الأخلاقي والحدود المهنية والمساءلة، مع فصل صريح بين المبادئ العامة والتشريع الفنلندي.</p><p><a href="/evidence-guides/social-work/professional-ethics/"><strong>فتح قسم أخلاقيات العمل الاجتماعي</strong></a> · <a href="${TALENTIA_GUIDE}" target="_blank" rel="noopener noreferrer">دليل Talentia الأصلي</a> · <a href="${TALENTIA_NEWS}" target="_blank" rel="noopener noreferrer">صفحة Talentia الرسمية</a></p><p class="meta">ذكر Talentia لا يعني اعتمادًا أو شراكة أو مصادقة على محتوى روافد.</p></section>`;
  return html.replace(/<\/main>/i,`${panel}</main>`);
}
