import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata } from '@/lib/seo';
import { getLanguageReadingActivitiesForSeries, getLanguageReadingSeries, languageReadingSeriesPlans } from '@/lib/capabilities/language-reading-lab';
import styles from '../../kids-lab.module.css';

type Props={params:Promise<{series:string}>};
export function generateStaticParams(){return languageReadingSeriesPlans.map(s=>({series:s.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {series:slug}=await params;const s=getLanguageReadingSeries(slug);if(!s)return{};return buildSeoMetadata({title:`${s.title} للأطفال | 5 مستويات و15 نشاطًا`,description:`${s.purpose} خمسة مستويات متدرجة، تدريبان واختبار إتقان في كل مستوى.`,path:`/capabilities/kids-lab/language-reading/${s.slug}/`,index:true,keywords:[s.title,'الاستعداد للقراءة','الوعي الصوتي','العربية للأطفال']});}
export default async function LanguageReadingSeriesPage({params}:Props){const {series:slug}=await params;const s=getLanguageReadingSeries(slug);if(!s)notFound();const items=getLanguageReadingActivitiesForSeries(slug);return <><SiteHeader/><main className={styles.shell}><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><Link href="/capabilities/kids-lab/language-reading/">اللغة والاستعداد للقراءة</Link><span>/</span><span>{s.title}</span></nav><section className={styles.hero}><span className={styles.kicker}>السلسلة {s.number}</span><h1>{s.title}</h1><p className={styles.lead}>{s.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>{s.ages}</span><span className={styles.metaChip}>{s.duration}</span><span className={styles.metaChip}>5 مستويات</span><span className={styles.metaChip}>15 عنصرًا</span></div></section><section className={styles.section}><div className={styles.flow}>{Array.from({length:5},(_,i)=>i+1).map(level=>{const levelItems=items.filter(a=>a.level===level);return <article className={styles.flowCard} key={level}><span className={styles.flowNumber}>{level}</span><h3>المستوى {level}</h3><p>{s.progression[level-1]}</p><div className={styles.seriesList}>{levelItems.map(a=><Link className={a.kind==='test'?styles.seriesActive:styles.seriesItem} href={`/capabilities/kids-lab/language-reading/${s.slug}/${a.slug}/`} key={a.slug}><span><strong>{a.label}</strong><small>{a.title}</small></span>{a.kind==='test'&&<span className={styles.readyBadge}>اختبار</span>}</Link>)}</div></article>})}</div></section><section className={styles.section}><div className={styles.note}><strong>ما الذي نراقبه؟</strong> {s.observation}</div></section></main><SiteFooter/></>}
