import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata, breadcrumbJsonLd, SITE_URL } from '@/lib/seo';
import { languageReadingActivityCount, languageReadingSeriesPlans, languageReadingTestCount } from '@/lib/capabilities/language-reading-lab';
import styles from '../kids-lab.module.css';

export const metadata=buildSeoMetadata({title:'اللغة والاستعداد للقراءة للأطفال | 90 نشاطًا واختبارًا عربيًا متدرجًا',description:'ست سلاسل عربية للوعي الصوتي والقافية والصوت الأول والمقاطع وتمييز الحروف ومطابقة الحرف بالصورة والتسلسل القصصي.',path:'/capabilities/kids-lab/language-reading/',index:true,keywords:['الوعي الصوتي','القافية','الصوت الأول','المقاطع الصوتية','تمييز الحروف العربية','الاستعداد للقراءة']});
export default function LanguageReadingLabPage(){const bc=breadcrumbJsonLd([{name:'الرئيسية',path:'/'},{name:'مختبر الأطفال',path:'/capabilities/kids-lab/'},{name:'اللغة والاستعداد للقراءة',path:'/capabilities/kids-lab/language-reading/'}]);const collection={'@context':'https://schema.org','@type':'CollectionPage','@id':`${SITE_URL}/capabilities/kids-lab/language-reading/#collection`,url:`${SITE_URL}/capabilities/kids-lab/language-reading/`,name:'اللغة والاستعداد للقراءة للأطفال',inLanguage:'ar',isAccessibleForFree:true,numberOfItems:languageReadingActivityCount};return <><SiteHeader/><main className={styles.shell}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([bc,collection]).replace(/</g,'\\u003c')}}/><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><span>اللغة والاستعداد للقراءة</span></nav><section className={styles.hero}><span className={styles.kicker}>المجال الثامن - العربية أولًا</span><h1>اللغة والاستعداد للقراءة</h1><p className={styles.lead}>مهام عربية الأصل وليست قوالب مترجمة: وعي صوتي، أصوات أولية، مقاطع، حروف متشابهة، مطابقة حرف وصورة، وتسلسل قصصي.</p><div className={styles.stats}><div className={styles.stat}><strong>{languageReadingSeriesPlans.length}</strong><span>سلاسل</span></div><div className={styles.stat}><strong>5</strong><span>مستويات</span></div><div className={styles.stat}><strong>{languageReadingTestCount}</strong><span>اختبار إتقان</span></div><div className={styles.stat}><strong>{languageReadingActivityCount}</strong><span>عنصرًا</span></div></div></section><section className={styles.section}><div className={styles.categoryGrid}>{languageReadingSeriesPlans.map(s=><article className={styles.categoryCard} style={{'--category-color':'#2563EB'} as React.CSSProperties} key={s.slug}><span className={styles.kicker}>السلسلة {s.number}</span><h3>{s.title}</h3><p>{s.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>{s.ages}</span><span className={styles.metaChip}>{s.duration}</span><span className={styles.metaChip}>15 عنصرًا</span></div><div className={styles.actions}><Link className={styles.primaryButton} href={`/capabilities/kids-lab/language-reading/${s.slug}/`}>افتح السلسلة</Link></div></article>)}</div></section><section className={styles.section}><div className={styles.note}><strong>قاعدة لغوية:</strong> في مهام الصوت الأول نقيس الصوت المنطوق لا اسم الحرف. وفي مهام المقاطع نعتمد النطق الفصيح الموضح في الورقة لأن التقسيم قد يختلف باختلاف اللهجة.</div></section></main><SiteFooter/></>}
