export type BilateralLabTask='mirror-drawing'|'opposite-directions'|'midline-crossing'|'bilateral-stop-go';
export type BilateralLabKind='training-a'|'training-b'|'test';
export type BilateralLabSeries={number:number;slug:string;title:string;ages:string;duration:string;taskType:BilateralLabTask;purpose:string;observation:string;progression:string[]};
export type BilateralLabActivity={slug:string;seriesSlug:string;seriesNumber:number;seriesTitle:string;taskType:BilateralLabTask;level:number;kind:BilateralLabKind;label:string;title:string;age:string;duration:string;purpose:string;instruction:string;progression:string;observation:string;mastery:string;seed:number};

export const bilateralLabSeriesPlans:BilateralLabSeries[]=[
{number:44,slug:'mirror-drawing',title:'الرسم المرآتي',ages:'5-10 سنوات',duration:'4-7 دقائق',taskType:'mirror-drawing',purpose:'تدريب حركة اليدين المتزامنة على مسارين متناظرين حول خط منتصف بصري واضح، مع المحافظة على اتجاه وسرعة متقاربين.',observation:'تزامن البدء، انتظام السرعة، مقدار الاختلاف بين الجانبين، الخروج عن المسار، والتوقف غير المخطط.',progression:['قوسان كبيران متناظران مع نقطة بدء واضحة.','منحنيات مزدوجة متناظرة مع تغير واحد في الاتجاه.','شكل مرآتي متعدد الفصوص مع عبور بصري قريب من المنتصف.','مساران متناظران أطول مع تغيرات سرعة واتجاه أكثر.','نمط مرآتي مركب يتطلب الحفاظ على التزامن عبر عدة مقاطع دون تلميحات إضافية.']},
{number:45,slug:'opposite-directions',title:'الحركة في اتجاهين مختلفين',ages:'6-11 سنوات',duration:'4-8 دقائق',taskType:'opposite-directions',purpose:'تدريب استقلال نسبي لحركة كل يد عندما تنفذ اليدان نمطين أو اتجاهين مختلفين في الوقت نفسه.',observation:'استمرار كل يد على مسارها، نسخ حركة يد بالأخرى، التوقفات، فقدان الاتجاه، والقدرة على استعادة النمط دون مساعدة.',progression:['دائرة واسعة بيد وموجة واسعة بالأخرى.','مسار دائري مع خط متعرج بسيط في الجهة الأخرى.','اتجاهان متعاكسان مع تغير واحد في السرعة.','نمط حلقي بيد ومسار زاوي بالأخرى مع استمرار متزامن.','نمطا حركة مختلفان ومتغيران يتطلبان استقلالًا أكبر لكل يد حتى النهاية.']},
{number:46,slug:'midline-crossing',title:'عبور خط المنتصف',ages:'4-10 سنوات',duration:'4-7 دقائق',taskType:'midline-crossing',purpose:'تدريب وصول كل يد إلى المساحة المقابلة عبر خط منتصف الصفحة ضمن مسار موجه وواضح، دون تحويل المهمة إلى اختبار تشخيصي.',observation:'إتمام العبور دون تبديل اليد، سلاسة الحركة عبر المنتصف، دوران الجذع المفرط، التوقفات، والعودة للمسار.',progression:['عبور واحد واسع لكل يد إلى الجهة المقابلة.','عبور والعودة مع مسارين واضحين.','عبوران لكل يد عند ارتفاعين مختلفين.','عدة عبورات مع منحنيات وتغير اتجاه.','مسار مركب يكرر العبور والعودة مع نقاط قرار دون تبديل اليدين.']},
{number:47,slug:'bilateral-stop-go',title:'الإيقاع والتوقف بكلتا اليدين',ages:'5-10 سنوات',duration:'4-8 دقائق',taskType:'bilateral-stop-go',purpose:'تدريب استمرار الحركة الثنائية مع الاستجابة لإشارات توقف وبطء واستئناف وتبديل قاعدة بسيطة أثناء الحركة.',observation:'دقة الاستجابة للرمز، استمرار اليدين، زمن العودة للحركة، أخطاء القاعدة، والتزامن العام.',progression:['توقف واحد مشترك عند نجمة واضحة.','توقف وبطء باستخدام رمزين مختلفين.','إشارات موزعة على المسارين مع استمرار الحركة.','بعض الإشارات تخص يدًا واحدة وبعضها اليدين معًا.','تبديل قاعدة في منتصف الصفحة مع ثلاثة رموز واستمرار الحركة الثنائية.']}
];

const labels:{kind:BilateralLabKind,label:string}[]=[{kind:'training-a',label:'تدريب أ'},{kind:'training-b',label:'تدريب ب'},{kind:'test',label:'اختبار الإتقان'}];
const instruction=(task:BilateralLabTask,kind:BilateralLabKind)=>{
 const base=task==='mirror-drawing'?'ضع قلمًا أو إصبعًا على كل نقطة بداية، وتحرك باليدين معًا على المسارين المتناظرين.':task==='opposite-directions'?'ابدأ باليدين معًا، لكن دع كل يد تتبع نمطها واتجاهها الخاص حتى النهاية.':task==='midline-crossing'?'اتبع المسار باليد المحددة حتى يعبر خط المنتصف ويعود؛ لا تبدل اليد عند العبور.':'تحرك باليدين معًا وطبّق رموز التوقف والبطء والاستئناف كما تظهر على الورقة.';
 return kind==='test'?`${base} نفذ المحاولة باستقلال ودون تصحيح أثناء الأداء.`:kind==='training-a'?`${base} ابدأ ببطء وركز على الدقة قبل السرعة.`:`${base} كرر مع تلميحات أقل وحاول الحفاظ على إيقاع هادئ.`;
};
export const bilateralLabActivities:BilateralLabActivity[]=bilateralLabSeriesPlans.flatMap(series=>Array.from({length:5},(_,i)=>i+1).flatMap(level=>labels.map((x,idx)=>({
 slug:`level-${level}-${x.kind}`,seriesSlug:series.slug,seriesNumber:series.number,seriesTitle:series.title,taskType:series.taskType,level,kind:x.kind,label:x.label,title:`${series.title} - المستوى ${level} - ${x.label}`,age:series.ages,duration:series.duration,purpose:series.purpose,instruction:instruction(series.taskType,x.kind),progression:series.progression[level-1],observation:series.observation,mastery:'أداء مستقر في محاولتين متقاربتين مع تلميحات قليلة، وبقاء كل يد على المهمة دون تعويضات واضحة؛ هذا معيار إتقان تعليمي وليس درجة تشخيصية.',seed:series.number*100+level*10+idx
})))));
export const bilateralLabActivityCount=bilateralLabActivities.length;
export const bilateralLabTestCount=bilateralLabActivities.filter(a=>a.kind==='test').length;
export const getBilateralLabSeries=(slug:string)=>bilateralLabSeriesPlans.find(s=>s.slug===slug);
export const getBilateralLabActivitiesForSeries=(slug:string)=>bilateralLabActivities.filter(a=>a.seriesSlug===slug);
export const getBilateralLabActivity=(series:string,slug:string)=>bilateralLabActivities.find(a=>a.seriesSlug===series&&a.slug===slug);
