export type EmotionalRegulationTask='emotion-recognition'|'body-signals'|'emotion-intensity'|'regulation-strategy-choice';
export type EmotionalRegulationKind='training-a'|'training-b'|'test';
export type EmotionalRegulationSeries={number:number;slug:string;title:string;ages:string;duration:string;taskType:EmotionalRegulationTask;purpose:string;observation:string;progression:string[]};
export type EmotionalRegulationActivity={slug:string;seriesSlug:string;seriesNumber:number;seriesTitle:string;taskType:EmotionalRegulationTask;level:number;kind:EmotionalRegulationKind;label:string;title:string;age:string;duration:string;purpose:string;instruction:string;progression:string;observation:string;mastery:string;seed:number};

export const emotionalRegulationSeriesPlans:EmotionalRegulationSeries[]=[
{number:59,slug:'emotion-recognition',title:'التعرف على المشاعر',ages:'3-9 سنوات',duration:'4-7 دقائق',taskType:'emotion-recognition',purpose:'تدريب قراءة مؤشرات الوجه والجسم والسياق معًا، مع قبول أكثر من تفسير عندما يكون الموقف غامضًا.',observation:'هل يعتمد الطفل على الوجه فقط أم يستخدم الحدث والسياق؟ وهل يستطيع ذكر دليل على تفسيره؟',progression:['مشاعر أساسية في مواقف واضحة جدًا.','التمييز بين مشاعر أساسية متقاربة مع سياق داعم.','دمج الوجه مع وضعية الجسم والحدث.','مواقف تحتمل شعورين مع طلب دليل لكل احتمال.','مواقف أكثر غموضًا تتطلب تفسيرًا مرنًا بدل إجابة واحدة مفروضة.']},
{number:60,slug:'body-signals',title:'إشارات الجسم',ages:'5-12 سنوات',duration:'5-8 دقائق',taskType:'body-signals',purpose:'بناء وعي شخصي بإشارات الجسم المصاحبة للاستثارة مثل شد العضلات أو سرعة التنفس أو حرارة الوجه، دون افتراض أن النمط نفسه ينطبق على الجميع.',observation:'قدرة الطفل على وصف إشارة جسمية حقيقية لديه، التفريق بين ملاحظة وإحساس وتفسير، وعدم إجباره على اختيار إشارة لا يشعر بها.',progression:['اختيار إشارات جسمية شائعة من قائمة مفتوحة.','ربط إشارة بالجسم بموقف يومي بسيط.','تمييز تغيرات مبكرة مقابل تغيرات قوية.','تحديد أكثر من إشارة وتقدير ترتيب ظهورها.','إنشاء خريطة شخصية مرنة لإشارات الجسم مع مساحة «لا أعرف/يختلف عندي».']},
{number:61,slug:'emotion-intensity',title:'شدة الشعور',ages:'4-12 سنوات',duration:'4-7 دقائق',taskType:'emotion-intensity',purpose:'تدريب تقدير شدة الشعور على مقياس بصري مرن وربطها بالحاجة أو الخطوة التالية، مع التأكيد أن الشدة ذاتية وليست إجابة يصححها البالغ.',observation:'ثبات استخدام المقياس، القدرة على شرح الفرق بين درجتين، والتمييز بين اسم الشعور وشدته.',progression:['ثلاث درجات واضحة: خفيف/متوسط/قوي.','مقياس من خمس درجات مع أمثلة شخصية.','تقدير شدة المشاعر نفسها في مواقف مختلفة.','تقدير تغير الشدة قبل وبعد خطوة تنظيمية.','استخدام المقياس مع مشاعر مختلطة أو غير مؤكدة دون فرض رقم واحد صحيح.']},
{number:62,slug:'regulation-strategy-choice',title:'اختيار استراتيجية مناسبة',ages:'5-12 سنوات',duration:'5-9 دقائق',taskType:'regulation-strategy-choice',purpose:'تدريب اختيار خطوة تنظيم تناسب الموقف والهدف وشدة الشعور، مع إدراك أن أكثر من استراتيجية قد تكون مناسبة وأن الاستراتيجية قد تتغير حسب السياق.',observation:'هل يطابق الطفل الاستراتيجية مع الهدف والسياق؟ هل يستطيع ذكر بديل؟ وهل يفرق بين تهدئة الجسم وحل المشكلة وطلب المساعدة؟',progression:['اختيار خطوة آمنة واحدة من خيارين في موقف واضح.','المقارنة بين استراتيجيتين مناسبتين لهدفين مختلفين.','اختيار من عدة بدائل مع ذكر سبب.','مواقف تحتاج ترتيب خطوتين أو تغيير الاستراتيجية إذا لم تنجح الأولى.','مواقف مركبة تقبل أكثر من خطة جيدة مع تبرير ومراجعة النتيجة.']}
];

const labels:{kind:EmotionalRegulationKind,label:string}[]=[{kind:'training-a',label:'تدريب أ'},{kind:'training-b',label:'تدريب ب'},{kind:'test',label:'اختبار الإتقان'}];
const instruction=(task:EmotionalRegulationTask,kind:EmotionalRegulationKind)=>{
 const base=task==='emotion-recognition'?'اقرأ الموقف وانظر إلى الوجه ووضعية الجسم معًا، ثم اختر أو اكتب الشعور المحتمل واذكر دليلك.':task==='body-signals'?'لاحظ إشارات الجسم التي قد تظهر في هذا الموقف، ثم علّم ما ينطبق عليك شخصيًا واترك ما لا ينطبق.':task==='emotion-intensity'?'ضع الشعور على مقياس الشدة بحسب تقديرك أنت، ثم اذكر ما الذي جعل الدرجة أعلى أو أقل.':'اختر خطوة أو أكثر قد تساعد في هذا الموقف، ثم اذكر لماذا تناسب الهدف الآن وما البديل إذا لم تنجح.';
 return kind==='test'?`${base} نفذ مرة واحدة باستقلال، ولا يغيّر البالغ إجابتك إلا إذا كانت هناك مسألة أمان.`:kind==='training-a'?`${base} استخدم التلميحات الموجودة واشرح سبب اختيارك.`:`${base} جرّب مع موقف جديد وتلميحات أقل.`;
};
const mastery=(task:EmotionalRegulationTask)=>task==='emotion-recognition'?'يستخدم الطفل دليلًا من السياق أو الوجه/الجسم لتبرير تفسير معقول، ويقبل احتمالًا آخر عند الغموض.':task==='body-signals'?'يحدد إشارات جسمية شخصية دون إجبار على قالب ثابت، ويميز بين الإشارة الجسدية وتفسيرها.':task==='emotion-intensity'?'يستخدم المقياس بطريقة متسقة نسبيًا ويشرح سبب فرق الشدة، دون الحاجة لمطابقة «رقم صحيح» يحدده البالغ.':'يختار استراتيجية آمنة وملائمة نسبيًا للهدف والسياق ويذكر سببًا أو بديلًا، دون افتراض حل وحيد صحيح.';
export const emotionalRegulationActivities:EmotionalRegulationActivity[]=emotionalRegulationSeriesPlans.flatMap(series=>Array.from({length:5},(_,i)=>i+1).flatMap(level=>labels.map((x,idx)=>({
 slug:`level-${level}-${x.kind}`,seriesSlug:series.slug,seriesNumber:series.number,seriesTitle:series.title,taskType:series.taskType,level,kind:x.kind,label:x.label,title:`${series.title} - المستوى ${level} - ${x.label}`,age:series.ages,duration:series.duration,purpose:series.purpose,instruction:instruction(series.taskType,x.kind),progression:series.progression[level-1],observation:series.observation,mastery:mastery(series.taskType),seed:series.number*100+level*10+idx
})))));
export const emotionalRegulationActivityCount=emotionalRegulationActivities.length;
export const emotionalRegulationTestCount=emotionalRegulationActivities.filter(a=>a.kind==='test').length;
export const getEmotionalRegulationSeries=(slug:string)=>emotionalRegulationSeriesPlans.find(s=>s.slug===slug);
export const getEmotionalRegulationActivitiesForSeries=(slug:string)=>emotionalRegulationActivities.filter(a=>a.seriesSlug===slug);
export const getEmotionalRegulationActivity=(series:string,slug:string)=>emotionalRegulationActivities.find(a=>a.seriesSlug===series&&a.slug===slug);
