import type { ExecutiveActivity } from './executive-functions-lab';

const W=794,H=1123,INK='#17324D',MUTED='#5E7184',BLUE='#2563EB',GREEN='#16A34A',RED='#DC2626',ORANGE='#EA580C',PURPLE='#7C3AED',PINK='#DB2777',YELLOW='#F59E0B',PAPER='#FFFDF8',LINE='#D6E1EA';
const esc=(v:string)=>v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function rng(seed:number){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296;};}
function shuffle<T>(arr:T[],r:()=>number){const out=[...arr];for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function text(x:number,y:number,v:string,size=22,weight=700,fill=INK,anchor='start'){return `<text x="${x}" y="${y}" font-family="Tahoma,Arial,sans-serif" font-size="${size}" font-weight="${weight}" fill="${fill}" text-anchor="${anchor}" direction="rtl" unicode-bidi="plaintext">${esc(v)}</text>`;}
function wrapWords(v:string,max:number){const words=v.split(/\s+/),lines:string[]=[];let line='';for(const word of words){const c=line?`${line} ${word}`:word;if(c.length>max&&line){lines.push(line);line=word;}else line=c;}if(line)lines.push(line);return lines;}
function wrappedText(x:number,y:number,v:string,max=62,size=18,lh=28,fill='#FFF'){return wrapWords(v,max).slice(0,2).map((line,i)=>text(x,y+i*lh,line,size,700,fill,'end')).join('');}
function rect(x:number,y:number,w:number,h:number,fill='#FFF',stroke=LINE,rx=18,sw=2){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}" stroke="${stroke}" stroke-width="${sw}"/>`;}
function circle(cx:number,cy:number,r:number,fill:string,stroke='none',sw=0){return `<circle cx="${cx}" cy="${cy}" r="${r}" fill="${fill}" stroke="${stroke}" stroke-width="${sw}"/>`;}
function star(cx:number,cy:number,r:number,fill:string,stroke=INK){const pts:string[]=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2===0?r:r*.45;pts.push(`${cx+Math.cos(a)*rr},${cy+Math.sin(a)*rr}`);}return `<polygon points="${pts.join(' ')}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`;}
function triangle(cx:number,cy:number,r:number,fill:string,stroke=INK){return `<polygon points="${cx},${cy-r} ${cx-r*.9},${cy+r*.75} ${cx+r*.9},${cy+r*.75}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`;}
function diamond(cx:number,cy:number,r:number,fill:string,stroke=INK){return `<polygon points="${cx},${cy-r} ${cx+r},${cy} ${cx},${cy+r} ${cx-r},${cy}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`;}
function shape(kind:number,cx:number,cy:number,r:number,fill:string){if(kind%4===0)return circle(cx,cy,r,fill,INK,2);if(kind%4===1)return star(cx,cy,r,fill);if(kind%4===2)return triangle(cx,cy,r,fill);return diamond(cx,cy,r,fill);}
function header(a:ExecutiveActivity){const type=a.kind==='test'?'اختبار إتقان':'تدريب';return [`<rect width="${W}" height="${H}" fill="${PAPER}"/>`,`<rect x="30" y="25" width="734" height="120" rx="28" fill="#EFF6FF" stroke="#BFDBFE" stroke-width="2"/>`,text(730,70,a.seriesTitle,30,900,INK,'end'),text(730,108,`${type} · المستوى ${a.level}/5`,18,800,BLUE,'end'),text(62,70,`العمر ${a.age}`,15,700,MUTED,'start'),text(62,102,`المدة ${a.duration}`,15,700,MUTED,'start'),`<rect x="30" y="160" width="734" height="76" rx="20" fill="${a.kind==='test'?PURPLE:BLUE}"/>`,wrappedText(730,192,a.instruction,72,17,25,'#FFF')].join('');}
function footer(a:ExecutiveActivity){return [`<line x1="48" y1="1013" x2="746" y2="1013" stroke="${LINE}" stroke-width="2"/>`,text(730,1045,'سجل سريع للمرافق',16,800,INK,'end'),text(730,1074,'الدقة: ____ / ____     التلميحات: ____     التصحيح الذاتي: ____',15,600,MUTED,'end'),text(730,1100,a.taskType==='task-initiation'?'زمن البدء: ____ ثانية     ملاحظة: ____________________':'ملاحظة قصيرة: __________________________________________',14,600,MUTED,'end')].join('');}
function legendChip(x:number,y:number,label:string,fill:string,symbolKind=0){return `${rect(x,y,170,54,'#FFF',LINE,14,2)}${shape(symbolKind,x+28,y+27,14,fill)}${text(x+154,y+34,label,15,800,INK,'end')}`;}

function responseInhibition(a:ExecutiveActivity){const r=rng(a.seed),colors=[GREEN,RED,BLUE,ORANGE],cols=5+Math.min(3,a.level-1),rows=4+Math.min(3,a.level-1),cw=650/cols,ch=500/rows,x0=72,y0=360;let out=a.level>=4?`${rect(70,265,310,54,'#F0FDF4','#86EFAC',14,2)}${text(360,299,'اذهب: النجمة الخضراء فقط',15,800,GREEN,'end')}${rect(414,265,310,54,'#FEF2F2','#FCA5A5',14,2)}${text(704,299,'توقف: أي شكل آخر',15,800,RED,'end')}`:`${legendChip(420,265,'اذهب: الأخضر',GREEN,0)}${legendChip(220,265,'توقف: الأحمر',RED,0)}`;if(a.level===5)out+=text(730,342,'في النصف السفلي اعكس قاعدة اللون: الأحمر = اذهب، الأخضر = توقف.',14,800,PURPLE,'end');for(let rr=0;rr<rows;rr++)for(let c=0;c<cols;c++){const cx=x0+c*cw+cw/2,cy=y0+rr*ch+ch/2,kind=Math.floor(r()*4);let color=colors[Math.floor(r()*(a.level>=3?4:2))];if(a.level===5&&rr>=Math.floor(rows/2))color=r()>.5?RED:GREEN;out+=rect(cx-cw*.38,cy-ch*.35,cw*.76,ch*.7,'#FFF','#D9E2EA',14,1.5)+shape(kind,cx,cy,Math.min(22,cw*.19),color);}return out;}
function flexibility(a:ExecutiveActivity){const r=rng(a.seed),rules=a.level>=4?[{label:'اللون: الأزرق',color:BLUE,shape:-1},{label:'الشكل: نجمة',color:'',shape:1},{label:'الحجم: الكبير',color:'',shape:9}]:[{label:'اللون: الأزرق',color:BLUE,shape:-1},{label:'الشكل: نجمة',color:'',shape:1}],rows=3+a.level,cols=7;let out='';for(let rr=0;rr<rows;rr++){const rule=rules[rr%rules.length],y=280+rr*(650/rows);out+=rect(50,y,170,60,rr%2?'#F5F3FF':'#EFF6FF',rr%2?'#C4B5FD':'#BFDBFE',15,2)+text(205,y+37,rule.label,14,800,rr%2?PURPLE:BLUE,'end');for(let c=0;c<cols;c++){const cx=270+c*66,kind=Math.floor(r()*4),color=[BLUE,RED,GREEN,ORANGE][Math.floor(r()*4)],rad=rule.shape===9&&r()>.5?20:14;out+=shape(kind,cx,y+30,rad,color);}if(rr<rows-1)out+=`<line x1="50" y1="${y+68}" x2="744" y2="${y+68}" stroke="#E5E7EB" stroke-width="1" stroke-dasharray="4 5"/>`;}return out;}
function planning(a:ExecutiveActivity){const r=rng(a.seed),n=5+Math.min(2,a.level-1),gs=520,x0=136,y0=340,cell=gs/n;let out=text(730,285,a.level>=4?'خطط أولًا: مرّ بنقاط التفتيش بالترتيب وتجنب المناطق الممنوعة.':'خطط أولًا ثم ارسم المسار. لا تبدأ بالمحاولة العشوائية.',16,800,INK,'end');out+=rect(x0,y0,gs,gs,'#FFF','#93C5FD',16,3);for(let i=1;i<n;i++){out+=`<line x1="${x0+i*cell}" y1="${y0}" x2="${x0+i*cell}" y2="${y0+gs}" stroke="#CBD5E1" stroke-width="1.5"/><line x1="${x0}" y1="${y0+i*cell}" x2="${x0+gs}" y2="${y0+i*cell}" stroke="#CBD5E1" stroke-width="1.5"/>`;}const start={r:n-1,c:0};out+=rect(x0+8,y0+(n-1)*cell+8,cell-16,cell-16,'#DCFCE7',GREEN,12,2)+text(x0+cell/2,y0+(n-1)*cell+cell/2+7,'ابدأ',16,900,GREEN,'middle');out+=rect(x0+(n-1)*cell+8,y0+8,cell-16,cell-16,'#FEF3C7',YELLOW,12,2)+star(x0+(n-1)*cell+cell/2,y0+cell/2,18,YELLOW);const moves=shuffle([...Array.from({length:n-1},()=> 'R' as const),...Array.from({length:n-1},()=> 'U' as const)],r),safePath=[{...start}];let pr=start.r,pc=start.c;for(const m of moves){if(m==='R')pc++;else pr--;safePath.push({r:pr,c:pc});}const safe=new Set(safePath.map(p=>`${p.r},${p.c}`)),blocked=new Set<string>(),blockCount=Math.min(2+a.level*2,n*n-safe.size-1);let guard=0;while(blocked.size<blockCount&&guard<500){guard++;const rr=Math.floor(r()*n),c=Math.floor(r()*n),key=`${rr},${c}`;if(!safe.has(key))blocked.add(key);}blocked.forEach(key=>{const [rr,c]=key.split(',').map(Number);out+=rect(x0+c*cell+9,y0+rr*cell+9,cell-18,cell-18,'#FEE2E2','#FCA5A5',10,1.5)+`<line x1="${x0+c*cell+18}" y1="${y0+rr*cell+18}" x2="${x0+(c+1)*cell-18}" y2="${y0+(rr+1)*cell-18}" stroke="${RED}" stroke-width="5"/><line x1="${x0+(c+1)*cell-18}" y1="${y0+rr*cell+18}" x2="${x0+c*cell+18}" y2="${y0+(rr+1)*cell-18}" stroke="${RED}" stroke-width="5"/>`;});if(a.level>=3){const cps=[safePath[Math.floor(safePath.length/3)],safePath[Math.floor(safePath.length*2/3)]].slice(0,a.level>=4?2:1);cps.forEach((p,i)=>{out+=circle(x0+p.c*cell+cell/2,y0+p.r*cell+cell/2,18,'#EDE9FE',PURPLE,3)+text(x0+p.c*cell+cell/2,y0+p.r*cell+cell/2+6,`${i+1}`,16,900,PURPLE,'middle');});}out+=text(730,900,a.level>=5?'القيد: لا تتجاوز 14 خطوة، ومرّ بالنقطتين 1 ثم 2.':'قبل التنفيذ: اكتب عدد الخطوات المتوقع: ____',16,700,MUTED,'end');return out;}
const seqSets=[['اختر الكتاب','افتح الصفحة','اقرأ السؤال','حدد الإجابة','راجع الإجابة','أغلق الكتاب','اذهب للعب'],['أحضر الكوب','افتح الماء','املأ الكوب','أغلق الماء','اشرب','أعد الكوب','شغّل التلفاز'],['ضع المعجون','بلل الفرشاة','فرّش الأسنان','اشطف الفم','نظف الفرشاة','أعدها لمكانها','ارتد الحذاء']];
function stepOrdering(a:ExecutiveActivity){const r=rng(a.seed),base=seqSets[a.seed%seqSets.length],count=3+a.level,distr=a.level>=2?1+(a.level>=5?1:0):0,cards=shuffle([...base.slice(0,Math.min(count,base.length)),...base.slice(-distr)],r);let out=text(730,286,'اكتب رقم الترتيب داخل الدائرة، واشطب البطاقة التي لا تنتمي للمهمة إن وجدت.',16,800,INK,'end');cards.forEach((label,i)=>{const c=i%2,rr=Math.floor(i/2),x=68+c*355,y=330+rr*120;out+=rect(x,y,315,92,'#FFF',i%2?'#F9A8D4':'#93C5FD',20,2.5)+circle(x+35,y+46,22,'#FFF','#94A3B8',2)+text(x+290,y+55,label,20,800,INK,'end');});out+=rect(68,880,670,80,'#F8FAFC',LINE,18,2)+text(715,914,a.level>=4?'ما الخطوة التي لا يمكن تجاوزها؟ ولماذا؟':'بعد الترتيب: راجع البداية والنهاية مرة أخرى.',16,800,MUTED,'end');return out;}
function errorMonitoring(a:ExecutiveActivity){const r=rng(a.seed),rows=4+a.level,cols=7;let out=text(730,286,'في كل سطر قاعدة. ابحث عن الخطأ، ضع دائرة حوله، ثم ارسم التصحيح في المربع الأخير.',16,800,INK,'end');for(let rr=0;rr<rows;rr++){const y=325+rr*(570/rows),rule=rr%3,wrong=1+Math.floor(r()*(cols-2));out+=rect(55,y,684,62,'#FFF','#DDE7EF',14,1.6);for(let c=0;c<cols;c++){const cx=92+c*82;let kind=rule===0?c%2:rule===1?c%3:(c+1)%4,color=rule===0?(c%2?BLUE:ORANGE):rule===1?[GREEN,BLUE,PINK][c%3]:[BLUE,RED,GREEN,ORANGE][(c+1)%4];if(c===wrong){kind=(kind+1)%4;color=RED;}out+=shape(kind,cx,y+31,15,color);}out+=rect(680,y+11,42,40,'#F8FAFC','#94A3B8',9,1.5);}out+=text(730,945,a.level>=4?'مراجعة منهجية: هل فحصت الشكل؟ اللون؟ الترتيب؟ العدد؟':'لا تخمّن عدد الأخطاء؛ افحص كل سطر كاملًا.',15,800,MUTED,'end');return out;}
const initGoals=[['أريد حل واجبي','أفتح أول سؤال','أفكر في كل الواجب دفعة واحدة','أنتظر حتى أشعر بالرغبة'],['أريد ترتيب مكتبي','أجمع الأقلام أولًا','أنقل كل شيء إلى الأرض','أبدأ بلعبة على المكتب'],['أريد قراءة قصة','أفتح الصفحة الأولى','أبحث عن نهاية القصة أولًا','أنتظر شخصًا يقرأ بدلًا مني'],['أريد تجهيز حقيبتي','أفتح قائمة المواد','أضع أي شيء قريب','أغلق الحقيبة أولًا']];
function taskInitiation(a:ExecutiveActivity){const r=rng(a.seed),taskCount=2+Math.min(3,a.level-1);let out=text(730,282,'لكل هدف: اختر أول خطوة صغيرة وقابلة للتنفيذ، ثم ابدأ عند إشارة المرافق.',16,800,INK,'end');for(let i=0;i<taskCount;i++){const set=initGoals[(i+a.seed)%initGoals.length],y=320+i*(590/taskCount);out+=rect(52,y,690,Math.min(130,540/taskCount),i%2?'#FDF2F8':'#EFF6FF',i%2?'#F9A8D4':'#93C5FD',18,2)+text(715,y+32,set[0],17,900,INK,'end');shuffle(set.slice(1),r).forEach((opt,j)=>{const ox=74+j*220;out+=rect(ox,y+48,200,48,'#FFF','#CBD5E1',11,1.5)+circle(ox+18,y+72,9,'#FFF','#94A3B8',1.5);wrapWords(opt,20).slice(0,2).forEach((line,li)=>{out+=text(ox+188,y+66+li*15,line,10.5,700,MUTED,'end');});});}out+=rect(52,900,690,70,'#F0FDF4','#86EFAC',16,2)+text(715,932,'زمن البدء بعد الإشارة: ______ ثانية',17,800,GREEN,'end')+text(715,958,a.level>=4?'ما أول شيء سأفعله خلال 60 ثانية؟ __________________________':'بدأت دون تلميح إضافي؟  نعم / لا',14,700,MUTED,'end');return out;}
function goalPersistence(a:ExecutiveActivity){const stages=3+a.level,mini=['ضع دائرة حول النجمة','أكمل النمط','اكتب عدد المثلثات','صل النقاط المتشابهة','اشطب الدائرة الحمراء','ارسم سهمًا للأعلى','راجع المحطة السابقة','اختر الشكل الأكبر'];let out=text(730,282,'مهمة واحدة، عدة محطات. أكمل كل محطة وضع ✓ ثم واصل حتى الهدف النهائي.',16,800,INK,'end');for(let i=0;i<stages;i++){const y=320+i*(600/stages);out+=circle(92,y+28,22,i===stages-1?'#FEF3C7':'#DBEAFE',i===stages-1?YELLOW:BLUE,2.5)+text(92,y+35,`${i+1}`,16,900,i===stages-1?ORANGE:BLUE,'middle')+`<line x1="115" y1="${y+28}" x2="160" y2="${y+28}" stroke="#94A3B8" stroke-width="3"/>`+rect(160,y,520,56,'#FFF','#CBD5E1',14,2)+text(655,y+35,mini[i%mini.length],16,800,INK,'end')+rect(694,y+10,34,34,'#FFF','#94A3B8',7,2);}if(a.level>=3)out+=rect(50,930,690,54,'#FFF7ED','#FDBA74',14,2)+text(715,963,a.level>=5?'إذا أخطأت: توقف → راجع الهدف → أصلح المحطة → واصل. لا تبدأ من الصفر.':'إذا ظهرت عقبة: توقف، راجع، ثم واصل من آخر محطة صحيحة.',14,800,ORANGE,'end');return out;}
function ruleDiscovery(a:ExecutiveActivity){const r=rng(a.seed),level=a.level;let out=text(730,282,'قارن أمثلة «ينتمي» و«لا ينتمي»، اكتشف القاعدة، ثم اختبرها على الأشكال الجديدة.',16,800,INK,'end');out+=rect(52,320,325,270,'#F0FDF4','#86EFAC',20,2)+text(350,352,'ينتمي',18,900,GREEN,'end')+rect(417,320,325,270,'#FEF2F2','#FCA5A5',20,2)+text(715,352,'لا ينتمي',18,900,RED,'end');const yes:Array<{kind:number;color:string;big:boolean}>=[],no:Array<{kind:number;color:string;big:boolean}>=[];for(let i=0;i<6;i++){if(level===1){yes.push({kind:i%4,color:BLUE,big:true});no.push({kind:i%4,color:RED,big:true});}else if(level===2){yes.push({kind:1,color:[BLUE,RED,GREEN][i%3],big:true});no.push({kind:i%2?0:2,color:[BLUE,RED,GREEN][i%3],big:true});}else if(level===3){yes.push({kind:1,color:BLUE,big:true});no.push(i%2?{kind:1,color:RED,big:true}:{kind:0,color:BLUE,big:true});}else if(level===4){yes.push({kind:i%2?1:0,color:GREEN,big:i%2===0});no.push({kind:i%2?1:0,color:RED,big:i%2===0});}else{yes.push({kind:i%2?1:3,color:i%2?BLUE:GREEN,big:true});no.push({kind:i%2?1:3,color:i%2?GREEN:BLUE,big:false});}}[yes,no].forEach((group,g)=>group.forEach((it,i)=>{const c=i%3,rr=Math.floor(i/3),cx=(g?465:100)+c*85,cy=405+rr*100;out+=shape(it.kind,cx,cy,it.big?19:13,it.color);}));out+=rect(52,620,690,80,'#F8FAFC',LINE,16,2)+text(715,654,'قاعدتي هي: ______________________________________________',16,800,INK,'end')+text(715,684,a.level>=4?'اختبر القاعدة على الأمثلة الجديدة قبل تثبيتها.':'لا تكتفِ بمثال واحد؛ تحقق من أمثلة «لا ينتمي» أيضًا.',14,700,MUTED,'end')+text(730,740,'أمثلة جديدة: ضع ✓ إذا كانت تنتمي، و× إذا كانت لا تنتمي.',15,800,INK,'end');for(let i=0;i<6;i++){const cx=110+i*105,cy=820,kind=Math.floor(r()*4),color=[BLUE,RED,GREEN,ORANGE][Math.floor(r()*4)];out+=rect(cx-38,cy-45,76,95,'#FFF','#CBD5E1',14,1.8)+shape(kind,cx,cy-10,17,color)+circle(cx,cy+30,11,'#FFF','#94A3B8',1.5);}return out;}

export function renderExecutiveWorksheet(a:ExecutiveActivity){let body='';switch(a.taskType){case'response-inhibition':body=responseInhibition(a);break;case'cognitive-flexibility':body=flexibility(a);break;case'planning':body=planning(a);break;case'step-ordering':body=stepOrdering(a);break;case'error-monitoring':body=errorMonitoring(a);break;case'task-initiation':body=taskInitiation(a);break;case'goal-persistence':body=goalPersistence(a);break;case'rule-discovery':body=ruleDiscovery(a);break;}return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(a.seriesTitle)} - ${esc(a.label)}">${header(a)}${body}${footer(a)}</svg>`;}
