export type FineMotorTaskType='basic-lines'|'curves-circles-spirals'|'scissor-control'|'coloring-boundaries'|'pencil-control'|'prewriting-patterns';
export type FineMotorKind='training-a'|'training-b'|'test';
export type FineMotorSeries={number:number;slug:string;title:string;ages:string;duration:string;taskType:FineMotorTaskType;purpose:string;observation:string;progression:string[]};
export type FineMotorActivity={slug:string;seriesSlug:string;seriesNumber:number;seriesTitle:string;taskType:FineMotorTaskType;level:number;kind:FineMotorKind;label:string;title:string;age:string;duration:string;purpose:string;instruction:string;progression:string;observation:string;mastery:string;seed:number};

export const fineMotorSeriesPlans:FineMotorSeries[]=[
{number:37,slug:'basic-lines',title:'الخطوط الأساسية',ages:'3-6 سنوات',duration:'4-7 دقائق',taskType:'basic-lines',purpose:'بناء التحكم الاتجاهي بالقلم عبر خطوط رأسية وأفقية ومائلة ومتقاطعة مع تدرج في الطول والدقة.',observation:'استمرارية الحركة، اتجاه الخط، الخروج عن المسار، التوقفات غير الضرورية وضغط القلم.',progression:['خطوط قصيرة عريضة وواضحة.','خطوط أطول مع تبديل الاتجاه.','خطوط مائلة ومتقاطعة.','تسلسلات متعددة الاتجاهات.','مسارات دقيقة تجمع أكثر من اتجاه دون فقد الاستمرارية.']},
{number:38,slug:'curves-circles-spirals',title:'الأقواس والدوائر واللولبيات',ages:'3-7 سنوات',duration:'4-7 دقائق',taskType:'curves-circles-spirals',purpose:'تدريب التحكم المستمر في الانحناء والدوران والعودة للنقطة المرجعية ضمن حركات تمهّد للكتابة والرسم.',observation:'نعومة المنحنى، إغلاق الدائرة، ثبات الحجم، اتجاه الحركة وعدم التسرع.',progression:['أقواس كبيرة ومفتوحة.','دوائر كبيرة مع نقطة بداية واضحة.','دوائر وأقواس متتابعة.','لولبيات واتجاهات عكسية.','أنماط مركبة تجمع أقواسًا ودوائر ولولبيات بدقة أعلى.']},
{number:39,slug:'scissor-control',title:'القص والتحكم بالمقص',ages:'4-8 سنوات',duration:'5-10 دقائق',taskType:'scissor-control',purpose:'تدريب فتح وإغلاق المقص مع توجيه الورقة باليد الأخرى عبر مسارات متدرجة وآمنة بصريًا.',observation:'استمرار القص على الخط، تدوير الورقة بدل لف المعصم فقط، عدد الانحرافات والتوقفات.',progression:['خط مستقيم عريض وقصير.','خط مستقيم أطول ثم زاوية واحدة.','منحنيات واسعة.','مسار متعرج بعدة زوايا.','مسار مركب ضيق نسبيًا يجمع منحنيات وزوايا دون تقاطعات خطرة.']},
{number:40,slug:'coloring-boundaries',title:'التلوين داخل الحدود',ages:'3-7 سنوات',duration:'5-9 دقائق',taskType:'coloring-boundaries',purpose:'تدريب التحكم في مدى الحركة وتغطية مساحة محددة مع المحافظة على الحدود دون التركيز على الجمال أو السرعة.',observation:'نسبة المساحة المغطاة، الخروج عن الحدود، اتجاه الضربات وتوزيع الضغط.',progression:['مساحات كبيرة وحدود سميكة.','مساحتان كبيرتان منفصلتان.','أشكال متوسطة مع زوايا.','عدة مناطق أصغر داخل شكل واحد.','مناطق دقيقة نسبيًا متعددة الاتجاهات مع حدود واضحة.']},
{number:41,slug:'pencil-control',title:'التحكم بالقلم',ages:'4-8 سنوات',duration:'4-8 دقائق',taskType:'pencil-control',purpose:'رفع دقة توجيه القلم داخل ممرات تنخفض سعتها تدريجيًا مع تغير الاتجاه دون التضحية بالوضوح أو قابلية الإنجاز.',observation:'البقاء داخل الممر، عدد ملامسات الحدود، التوقفات، والقدرة على تعديل السرعة في الأجزاء الضيقة.',progression:['ممر عريض وقصير.','ممر أطول بانحناءات واسعة.','ممر متوسط العرض مع عدة تغيرات اتجاه.','ممر أضيق مع مقاطع مستقيمة ومنحنية.','ممر دقيق عملي للطباعة يتطلب تعديل السرعة والحركة.']},
{number:42,slug:'prewriting-patterns',title:'أنماط الاستعداد للكتابة',ages:'4-7 سنوات',duration:'5-8 دقائق',taskType:'prewriting-patterns',purpose:'تدريب أنماط حركية متكررة مرتبطة بمهارات ما قبل الكتابة العربية دون تقديمها كبديل مباشر لتعليم الحروف.',observation:'ثبات الحجم والمسافة، استمرار النمط، اتجاه الحركة، والمحاذاة على السطر.',progression:['نمط واحد كبير ومتكرر.','نمط من حركتين متناوبتين.','تكرار أقواس ونقاط وموجات على سطر.','أنماط مركبة مع مسافات أصغر.','سطر متكامل يجمع أكثر من حركة مع ثبات نسبي في الحجم والمسافة.']}
];

const labels:{kind:FineMotorKind,label:string}[]=[{kind:'training-a',label:'تدريب أ'},{kind:'training-b',label:'تدريب ب'},{kind:'test',label:'اختبار الإتقان'}];
export const fineMotorActivities:FineMotorActivity[]=fineMotorSeriesPlans.flatMap((series)=>Array.from({length:5},(_,i)=>i+1).flatMap((level)=>labels.map((x,idx)=>({
slug:`level-${level}-${x.kind}`,seriesSlug:series.slug,seriesNumber:series.number,seriesTitle:series.title,taskType:series.taskType,level,kind:x.kind,label:x.label,title:`${series.title} - المستوى ${level} - ${x.label}`,age:series.ages,duration:series.duration,purpose:series.purpose,
instruction:x.kind==='test'?'نفذ المهمة مرة واحدة باستقلال قدر الإمكان، دون نموذج إضافي أو تصحيح أثناء الأداء.':x.kind==='training-a'?'ابدأ ببطء واتبع نقطة البداية والاتجاه المحددين، وركز على الدقة قبل السرعة.':'كرر المهمة مع تقليل التلميحات وحاول الحفاظ على حركة هادئة ومستمرة.',
progression:series.progression[level-1],observation:series.observation,mastery:'أداء مستقر ودقيق نسبيًا مع تلميحات قليلة وبلا تعويضات واضحة؛ يفضّل تأكيده بمحاولة أخرى قبل الانتقال.',seed:series.number*100+level*10+idx
})))).filter(a=>!(a.seriesSlug==='basic-lines'&&a.slug==='level-1-training-b'));
export const fineMotorActivityCount=fineMotorActivities.length;
export const fineMotorTestCount=fineMotorActivities.filter((a)=>a.kind==='test').length;
export const getFineMotorSeries=(slug:string)=>fineMotorSeriesPlans.find((s)=>s.slug===slug);
export const getFineMotorActivitiesForSeries=(slug:string)=>fineMotorActivities.filter((a)=>a.seriesSlug===slug);
export const getFineMotorActivity=(series:string,slug:string)=>fineMotorActivities.find((a)=>a.seriesSlug===series&&a.slug===slug);
