import type { LanguageReadingActivity } from './language-reading-lab';
import { initialSoundBanks, rhymeBanks, syllableBanks, similarLetterGroups } from './language-reading-lab';

const W=794,H=1123,INK='#17324D',MUTED='#64748B',BLUE='#2563EB',LINE='#CBD5E1';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]||c));
const rng=(seed:number)=>{let x=seed>>>0;return()=>((x=(x*1664525+1013904223)>>>0)/4294967296)};
const shuffle=<T,>(a:T[],r:()=>number)=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const txt=(x:number,y:number,s:string,size=20,weight=600,fill=INK,anchor='middle')=>`<text x="${x}" y="${y}" text-anchor="${anchor}" direction="rtl" unicode-bidi="plaintext" font-family="Tahoma,Arial,sans-serif" font-size="${size}" font-weight="${weight}" fill="${fill}">${esc(s)}</text>`;
const wrap=(s:string,n=58)=>{const w=s.split(/\s+/),o:string[]=[];let l='';for(const q of w){const z=l?`${l} ${q}`:q;if(z.length>n&&l){o.push(l);l=q}else l=z}if(l)o.push(l);return o.slice(0,2)};
const header=(a:LanguageReadingActivity)=>{const lines=wrap(a.instruction,62);return `<rect width="${W}" height="${H}" fill="#FFFDF8"/><rect x="34" y="30" width="726" height="112" rx="24" fill="#EAF3FF" stroke="#2563EB" stroke-width="2"/>${txt(397,74,a.seriesTitle,28,800,INK)}${txt(397,112,`المستوى ${a.level} · ${a.label}`,18,600,'#31506F')}<rect x="62" y="155" width="670" height="${lines.length>1?66:48}" rx="16" fill="#F8FAFC" stroke="#E2E8F0"/>${lines.map((l,i)=>txt(397,185+i*23,l,15,600,'#334155')).join('')}`};
const footer=`<line x1="60" y1="1032" x2="734" y2="1032" stroke="#CBD5E1"/>${txt(60,1065,'الاسم: ____________  التاريخ: ____________  الدقة: ____ / ____',16,500,'#475569','start')}${txt(734,1095,'Health Renewal · مهمة تعليمية غير تشخيصية',13,500,'#64748B','end')}`;
const card=(x:number,y:number,w:number,h:number,main:string,sub='')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="18" fill="#FFFFFF" stroke="#B8C7D9" stroke-width="2"/>${txt(x+w/2,y+h/2-(sub?10:0),main,sub?34:40,800,INK)}${sub?txt(x+w/2,y+h/2+27,sub,17,500,'#475569'):''}`;

const pict=(name:string,x:number,y:number,s=74)=>{
 const stroke='#334155',fill='#E0F2FE';
 if(name.includes('شمس'))return `<g><circle cx="${x}" cy="${y}" r="${s*.26}" fill="#FDE047" stroke="#A16207" stroke-width="3"/>${Array.from({length:8},(_,i)=>{const a=i*Math.PI/4;return `<line x1="${x+Math.cos(a)*s*.34}" y1="${y+Math.sin(a)*s*.34}" x2="${x+Math.cos(a)*s*.48}" y2="${y+Math.sin(a)*s*.48}" stroke="#A16207" stroke-width="3"/>`}).join('')}</g>`;
 if(name.includes('قمر'))return `<path d="M ${x+s*.18} ${y-s*.34} A ${s*.36} ${s*.36} 0 1 0 ${x+s*.18} ${y+s*.34} A ${s*.27} ${s*.27} 0 1 1 ${x+s*.18} ${y-s*.34} Z" fill="#FDE68A" stroke="#92400E" stroke-width="3"/>`;
 if(name.includes('سمك')||name.includes('حوت'))return `<g><ellipse cx="${x}" cy="${y}" rx="${s*.32}" ry="${s*.2}" fill="#67E8F9" stroke="#155E75" stroke-width="3"/><polygon points="${x-s*.3},${y} ${x-s*.5},${y-s*.2} ${x-s*.5},${y+s*.2}" fill="#67E8F9" stroke="#155E75" stroke-width="3"/><circle cx="${x+s*.16}" cy="${y-s*.04}" r="3" fill="#0F172A"/></g>`;
 if(name.includes('كرة'))return `<circle cx="${x}" cy="${y}" r="${s*.32}" fill="#DBEAFE" stroke="#1D4ED8" stroke-width="4"/><path d="M ${x-s*.2} ${y} Q ${x} ${y-s*.22} ${x+s*.2} ${y} Q ${x} ${y+s*.22} ${x-s*.2} ${y}" fill="none" stroke="#1D4ED8" stroke-width="3"/>`;
 if(name.includes('كتاب'))return `<g><path d="M ${x} ${y-s*.28} Q ${x-s*.3} ${y-s*.38} ${x-s*.38} ${y-s*.12} L ${x-s*.38} ${y+s*.3} Q ${x-s*.15} ${y+s*.18} ${x} ${y+s*.28} Z" fill="#DBEAFE" stroke="#1D4ED8" stroke-width="3"/><path d="M ${x} ${y-s*.28} Q ${x+s*.3} ${y-s*.38} ${x+s*.38} ${y-s*.12} L ${x+s*.38} ${y+s*.3} Q ${x+s*.15} ${y+s*.18} ${x} ${y+s*.28} Z" fill="#EFF6FF" stroke="#1D4ED8" stroke-width="3"/></g>`;
 if(name.includes('بيت')||name.includes('باب'))return `<g><rect x="${x-s*.3}" y="${y-s*.05}" width="${s*.6}" height="${s*.38}" fill="#FFF7ED" stroke="#9A3412" stroke-width="3"/><polygon points="${x-s*.38},${y-s*.05} ${x},${y-s*.38} ${x+s*.38},${y-s*.05}" fill="#FDBA74" stroke="#9A3412" stroke-width="3"/><rect x="${x-s*.07}" y="${y+s*.1}" width="${s*.14}" height="${s*.23}" fill="#fff" stroke="#9A3412" stroke-width="2"/></g>`;
 if(name.includes('شجرة'))return `<g><rect x="${x-s*.06}" y="${y}" width="${s*.12}" height="${s*.32}" fill="#A16207"/><circle cx="${x}" cy="${y-s*.12}" r="${s*.28}" fill="#86EFAC" stroke="#166534" stroke-width="3"/></g>`;
 if(name.includes('تفاح')||name.includes('تمر')||name.includes('موز')||name.includes('بطيخ'))return `<g><circle cx="${x}" cy="${y}" r="${s*.28}" fill="#FCA5A5" stroke="#991B1B" stroke-width="3"/><path d="M ${x} ${y-s*.3} q 8 -18 20 -22" stroke="#166534" stroke-width="4" fill="none"/></g>`;
 if(name.includes('قلم'))return `<g transform="translate(${x} ${y}) rotate(-25)"><rect x="${-s*.32}" y="${-s*.07}" width="${s*.55}" height="${s*.14}" rx="4" fill="#FDE68A" stroke="#92400E" stroke-width="3"/><polygon points="${s*.23},${-s*.07} ${s*.38},0 ${s*.23},${s*.07}" fill="#FED7AA" stroke="#92400E" stroke-width="3"/></g>`;
 if(name.includes('قطة')||name.includes('جمل')||name.includes('حصان')||name.includes('فيل'))return `<g><circle cx="${x}" cy="${y}" r="${s*.28}" fill="#FED7AA" stroke="#9A3412" stroke-width="3"/><polygon points="${x-s*.22},${y-s*.18} ${x-s*.1},${y-s*.38} ${x},${y-s*.18}" fill="#FED7AA" stroke="#9A3412" stroke-width="3"/><polygon points="${x+s*.22},${y-s*.18} ${x+s*.1},${y-s*.38} ${x},${y-s*.18}" fill="#FED7AA" stroke="#9A3412" stroke-width="3"/><circle cx="${x-s*.1}" cy="${y}" r="3" fill="#111827"/><circle cx="${x+s*.1}" cy="${y}" r="3" fill="#111827"/></g>`;
 return `<g><circle cx="${x}" cy="${y}" r="${s*.3}" fill="${fill}" stroke="${stroke}" stroke-width="3"/><path d="M ${x-s*.16} ${y} L ${x+s*.16} ${y}" stroke="${stroke}" stroke-width="3"/></g>`;
};
const pictureCard=(x:number,y:number,w:number,h:number,name:string,label=true)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="18" fill="#FFF" stroke="#B8C7D9" stroke-width="2"/>${pict(name,x+w/2,y+h*.45,72)}${label?txt(x+w/2,y+h-18,name,16,600,'#475569'):''}`;

function rhyme(a:LanguageReadingActivity){const r=rng(a.seed),group=rhymeBanks[a.seed%rhymeBanks.length],distr=['قمر','بيت','سمك','شمس','ورد','قلم','باب'].filter(x=>!group.includes(x));const targets=group.slice(0,a.level<3?2:3);const words=shuffle([...targets,...distr.slice(0,Math.min(4,2+a.level))],r).slice(0,6);return `${txt(397,245,'استمع إلى الكلمات وحدد الكلمات التي تتشابه في النهاية الصوتية',21,700,'#334155')}${words.map((w,i)=>pictureCard(80+(i%3)*218,285+Math.floor(i/3)*220,190,165,w,a.level>=3)).join('')}${a.kind==='test'?'':txt(397,760,'قل الكلمات بصوت واضح؛ لا تعتمد على شكل الكلمة المكتوبة.',15,500,MUTED)}`;}
function initialSound(a:LanguageReadingActivity){const r=rng(a.seed),bank=initialSoundBanks[a.seed%initialSoundBanks.length],other=initialSoundBanks.filter(b=>b.letter!==bank.letter);const targetWord=bank.words[(a.seed+a.level)%bank.words.length][0];const candidates=shuffle([bank.words[(a.seed+1)%bank.words.length][0],...other.slice(0,4).map((b,i)=>b.words[(a.seed+i)%b.words.length][0])],r).slice(0,a.level<3?4:5);return `${txt(397,245,a.level<=2?`قل كلمة «${targetWord}». أي صورة تبدأ بالصوت نفسه؟`:`استمع إلى كلمة «${targetWord}» وابحث عن الكلمات التي تبدأ بالصوت نفسه`,21,700,'#334155')}${pictureCard(307,285,180,155,targetWord,false)}${candidates.map((w,i)=>pictureCard(75+(i%3)*225,500+Math.floor(i/3)*190,185,145,w,a.level>=4)).join('')}`;}
function syllables(a:LanguageReadingActivity){const r=rng(a.seed),pool=[...syllableBanks.one.map(w=>({w,n:1})),...syllableBanks.two.map(w=>({w,n:2})),...syllableBanks.three.map(w=>({w,n:3}))],chosen=shuffle(pool,r).slice(0,Math.min(6,3+a.level));return `${txt(397,245,'انطق بالفصحى، ثم صفّق أو انقر مرة لكل مقطع مسموع',21,700,'#334155')}${chosen.map((o,i)=>{const x=85+(i%2)*340,y=300+Math.floor(i/2)*200,cues=a.kind==='test'?0:a.level<=2?o.n:Math.max(0,o.n-1);return `<rect x="${x}" y="${y}" width="280" height="150" rx="18" fill="#FFF" stroke="#B8C7D9" stroke-width="2"/>${txt(x+140,y+58,o.w,32,800,INK)}${Array.from({length:cues},(_,k)=>`<circle cx="${x+110+k*36}" cy="${y+105}" r="10" fill="#DBEAFE" stroke="#2563EB" stroke-width="2"/>`).join('')}${a.kind==='test'?`<line x1="${x+55}" y1="${y+110}" x2="${x+225}" y2="${y+110}" stroke="#94A3B8" stroke-dasharray="6 5"/>`:''}</rect>`}).join('')}`;}
const contextual=(ch:string,pos:number)=>pos===0?`${ch}ـ`:pos===1?`ـ${ch}ـ`:`ـ${ch}`;
function letters(a:LanguageReadingActivity){const r=rng(a.seed),g=similarLetterGroups[a.seed%similarLetterGroups.length],target=g[a.seed%g.length],count=21+(a.level>=5?7:0),rows=4;let items:string[]=[];for(let i=0;i<count;i++){const correct=i%(5+a.level)===0,ch=correct?target:g[(i+1+Math.floor(r()*Math.max(1,g.length-1)))%g.length],pos=a.level>=4?(i+a.seed)%3:-1;items.push(pos<0?ch:contextual(ch,pos))}items=shuffle(items,r);return `${txt(397,245,a.level>=4?`ضع دائرة حول الحرف ${target} في أي موضع من الكلمة`:`ضع دائرة حول الحرف: ${target}`,21,700,'#334155')}${items.map((ch,i)=>txt(90+(i%7)*95,330+Math.floor(i/7)*115,ch,38,700,INK)).join('')}`;}
function match(a:LanguageReadingActivity){const r=rng(a.seed),n=Math.min(4,2+Math.floor((a.level+1)/2)),banks=shuffle([...initialSoundBanks],r).slice(0,n),pics=shuffle(banks.flatMap(b=>b.words.slice(0,a.level>=4?2:1).map(w=>({letter:b.letter,word:w[0]}))),r).slice(0,Math.min(6,n+(a.level>=4?2:0)));return `${txt(397,245,'سمِّ الصورة، اعزل الصوت الأول، ثم صِلها بالحرف المناسب',21,700,'#334155')}${banks.map((b,i)=>card(565,300+i*150,120,105,b.letter)).join('')}${pics.map((p,i)=>pictureCard(80+(i%2)*220,300+Math.floor(i/2)*185,185,140,p.word,a.kind!=='test')).join('')}`;}
const storySets=[
[{id:'seed',label:'زرع بذرة'},{id:'water',label:'سقى التربة'},{id:'sprout',label:'ظهرت نبتة'},{id:'flower',label:'كبرت زهرة'},{id:'bee',label:'جاءت نحلة'}],
[{id:'spill',label:'انسكب الماء'},{id:'cloth',label:'أحضر قطعة قماش'},{id:'wipe',label:'مسح الماء'},{id:'dry',label:'جف المكان'},{id:'store',label:'أعاد الأدوات'}],
[{id:'mix',label:'خلط المكونات'},{id:'pour',label:'صب الخليط'},{id:'bake',label:'دخل الفرن'},{id:'cool',label:'برد الكعك'},{id:'serve',label:'قدمه'}]
] as const;
const scene=(id:string,x:number,y:number,w=180,h=125)=>{let g=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="18" fill="#FFF" stroke="#B8C7D9" stroke-width="2"/>`;const cx=x+w/2,cy=y+52;if(id==='seed')g+=`<path d="M ${cx} ${cy+20} q 0 -28 0 -45" stroke="#166534" stroke-width="4"/><ellipse cx="${cx}" cy="${cy+25}" rx="18" ry="8" fill="#92400E"/>`;else if(id==='water')g+=`<path d="M ${cx-25} ${cy} h 42 l 8 28 h -58 z" fill="#DBEAFE" stroke="#1D4ED8" stroke-width="3"/><path d="M ${cx+25} ${cy+15} q 18 8 25 28" stroke="#38BDF8" stroke-width="4" fill="none"/>`;else if(id==='sprout'||id==='flower')g+=`<path d="M ${cx} ${cy+28} L ${cx} ${cy-10}" stroke="#166534" stroke-width="4"/><ellipse cx="${cx-12}" cy="${cy}" rx="15" ry="8" fill="#86EFAC"/><ellipse cx="${cx+12}" cy="${cy-10}" rx="15" ry="8" fill="#86EFAC"/>${id==='flower'?`<circle cx="${cx}" cy="${cy-22}" r="16" fill="#F9A8D4"/>`:''}`;else if(id==='bee')g+=`<ellipse cx="${cx}" cy="${cy}" rx="28" ry="16" fill="#FACC15" stroke="#92400E" stroke-width="3"/><line x1="${cx-8}" y1="${cy-15}" x2="${cx-8}" y2="${cy+15}" stroke="#111827" stroke-width="4"/><ellipse cx="${cx-18}" cy="${cy-18}" rx="13" ry="9" fill="#DBEAFE"/><ellipse cx="${cx+18}" cy="${cy-18}" rx="13" ry="9" fill="#DBEAFE"/>`;else if(id==='spill'||id==='wipe'||id==='dry')g+=`<ellipse cx="${cx}" cy="${cy+15}" rx="42" ry="18" fill="${id==='dry'?'#F8FAFC':'#BAE6FD'}" stroke="#0284C7" stroke-width="2"/>${id==='wipe'?`<rect x="${cx-28}" y="${cy-20}" width="56" height="34" rx="8" fill="#FDE68A" stroke="#A16207"/>`:''}`;else if(id==='cloth')g+=`<rect x="${cx-35}" y="${cy-28}" width="70" height="56" rx="10" fill="#FDE68A" stroke="#A16207" stroke-width="3"/>`;else if(id==='store')g+=`<rect x="${cx-35}" y="${cy-30}" width="70" height="60" fill="#E2E8F0" stroke="#475569" stroke-width="3"/><path d="M ${cx-45} ${cy-30} h 90" stroke="#475569" stroke-width="5"/>`;else if(id==='mix')g+=`<ellipse cx="${cx}" cy="${cy+8}" rx="42" ry="24" fill="#FED7AA" stroke="#9A3412" stroke-width="3"/><path d="M ${cx-30} ${cy-32} L ${cx+15} ${cy+8}" stroke="#475569" stroke-width="5"/>`;else if(id==='pour')g+=`<path d="M ${cx-35} ${cy-25} h 70 l -8 55 h -54 z" fill="#FED7AA" stroke="#9A3412" stroke-width="3"/>`;else if(id==='bake')g+=`<rect x="${cx-45}" y="${cy-35}" width="90" height="70" rx="8" fill="#E2E8F0" stroke="#475569" stroke-width="3"/><rect x="${cx-28}" y="${cy-10}" width="56" height="30" fill="#FDE68A"/>`;else if(id==='cool'||id==='serve')g+=`<circle cx="${cx}" cy="${cy}" r="28" fill="#FDE68A" stroke="#92400E" stroke-width="3"/>${id==='serve'?`<rect x="${cx-45}" y="${cy+32}" width="90" height="8" fill="#94A3B8"/>`:''}`;return g;};
function story(a:LanguageReadingActivity){const r=rng(a.seed),set=storySets[a.seed%storySets.length],n=Math.min(5,3+Math.floor((a.level-1)/2)),items=shuffle([...set.slice(0,n)],r);return `${txt(397,245,'رتّب المشاهد من الأول إلى الأخير، ثم احكِ ما حدث',21,700,'#334155')}${items.map((it,i)=>`${scene(it.id,90+(i%2)*320,300+Math.floor(i/2)*205,260,150)}${txt(220+(i%2)*320,475+Math.floor(i/2)*205,a.kind==='test'?'':it.label,16,600,MUTED)}`).join('')}${a.level>=5?txt(397,935,'اذكر: ماذا حدث؟ ولماذا جاء أحد الحدثين قبل الآخر؟',16,600,MUTED):''}`;}
function body(a:LanguageReadingActivity){return a.taskType==='rhyming'?rhyme(a):a.taskType==='initial-sound'?initialSound(a):a.taskType==='syllable-awareness'?syllables(a):a.taskType==='letter-discrimination'?letters(a):a.taskType==='letter-picture-match'?match(a):story(a)}
export function renderLanguageReadingWorksheet(a:LanguageReadingActivity){return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" direction="rtl" role="img" aria-label="${esc(a.title)}">${header(a)}${body(a)}${footer}</svg>`;}
