export type LanguageReadingTask='rhyming'|'initial-sound'|'syllable-awareness'|'letter-discrimination'|'letter-picture-match'|'story-sequencing';
export type LanguageReadingKind='training-a'|'training-b'|'test';
export type LanguageReadingSeries={number:number;slug:string;title:string;ages:string;duration:string;taskType:LanguageReadingTask;purpose:string;observation:string;progression:string[]};
export type LanguageReadingActivity={slug:string;seriesSlug:string;seriesNumber:number;seriesTitle:string;taskType:LanguageReadingTask;level:number;kind:LanguageReadingKind;label:string;title:string;age:string;duration:string;purpose:string;instruction:string;progression:string;observation:string;mastery:string;seed:number};

export const languageReadingSeriesPlans:LanguageReadingSeries[]=[
{number:48,slug:'rhyming',title:'القافية والوعي الصوتي',ages:'4-7 سنوات',duration:'4-7 دقائق',taskType:'rhyming',purpose:'تدريب ملاحظة التشابه الصوتي في نهاية الكلمات المسموعة، مع فصل الحكم الصوتي عن شكل الكلمة المكتوبة.',observation:'هل يختار الطفل بناءً على الصوت النهائي لا المعنى أو الشكل؟ وهل يحتاج إعادة نطق الكلمة أو إبطاءها؟',progression:['تمييز زوجين ذوي قافية واضحة مع مشتت بعيد.','اختيار كلمتين لهما النهاية الصوتية نفسها من مجموعة صغيرة.','تمييز قوافٍ متقاربة مع مشتتات تشترك في المعنى لا الصوت.','اختيار مجموعة القافية من عدة نهايات صوتية متقاربة.','تعميم القاعدة على كلمات جديدة دون نموذج سابق.']},
{number:49,slug:'initial-sound',title:'الصوت الأول',ages:'4-7 سنوات',duration:'4-7 دقائق',taskType:'initial-sound',purpose:'تدريب عزل الصوت الأول في الكلمة المسموعة وربطه بكلمات أخرى تبدأ بالصوت نفسه، دون خلط اسم الحرف بصوته.',observation:'دقة عزل الصوت الأول، الاعتماد على اسم الحرف بدل صوته، الحاجة إلى مدّ الصوت أو إعادة النطق.',progression:['صوتان أوليان متباعدان بوضوح.','اختيار صورتين تبدآن بالصوت نفسه.','مقارنة أصوات أولية متقاربة مثل س/ش أو ف/ق.','تمييز الصوت الأول داخل مجموعة أكبر مع مشتتات دلالية.','تعميم الصوت الأول على كلمات جديدة وبعض الأزواج المتقاربة بصريًا أو صوتيًا.']},
{number:50,slug:'syllable-awareness',title:'المقاطع الصوتية',ages:'4-8 سنوات',duration:'4-8 دقائق',taskType:'syllable-awareness',purpose:'تدريب تقسيم الكلمات المسموعة إلى وحدات إيقاعية/مقاطع وفق النطق الفصيح المستهدف في الورقة، باستخدام التصفيق أو العد.',observation:'عدد النقرات/التصفيقات، ثبات التقسيم، أثر اللهجة المحلية، والقدرة على إعادة الكلمة دون حذف صوت.',progression:['تمييز كلمة قصيرة من مقطع واحد مقابل كلمتين/ثلاثة.','عد مقطعين في كلمات فصيحة مألوفة.','المقارنة بين كلمتين وثلاثة مقاطع.','فرز كلمات إلى 1/2/3 مقاطع وفق النطق الفصيح المحدد.','عد المقاطع في كلمات جديدة مع دعم بصري أقل.']},
{number:51,slug:'letter-discrimination',title:'تمييز الحروف بصريًا',ages:'5-8 سنوات',duration:'4-7 دقائق',taskType:'letter-discrimination',purpose:'تدريب التمييز البصري الدقيق بين الحروف العربية المتشابهة في الهيكل والمختلفة في النقاط أو التفاصيل، مع إدخال الأشكال السياقية تدريجيًا.',observation:'نوع الخلط بين الحروف، موضع النقاط وعددها، أثر موقع الحرف في الكلمة، واستراتيجية المسح البصري.',progression:['حرف هدف بين مشتتات بعيدة بصريًا.','حرف هدف بين أفراد العائلة الشكلية نفسها.','تمييز عدد وموضع النقاط داخل صفوف أطول.','تمييز الحرف في أشكال أول/وسط/آخر الكلمة.','مسح صفوف تحتوي عائلات متقاربة متعددة مع الحفاظ على الدقة.']},
{number:52,slug:'letter-picture-match',title:'مطابقة الحرف والصورة',ages:'5-8 سنوات',duration:'4-8 دقائق',taskType:'letter-picture-match',purpose:'ربط شكل الحرف بالصوت الأول لكلمة مصورة مألوفة، مع استخدام كلمات عربية فصيحة واضحة وتجنب الاعتماد على اسم الحرف فقط.',observation:'هل يسمي الطفل الصورة أولًا؟ هل يعزل الصوت الأول؟ هل يخلط بين الحروف المتشابهة أو بين الفصحى واللهجة؟',progression:['حرفان وصورتان مألوفتان جدًا.','ثلاثة حروف وصور ذات أصوات أولية متباعدة.','حروف متقاربة بصريًا مع صور واضحة.','عدة صور لكل حرف مع مشتتات من عائلة حرفية مشابهة.','مطابقة متعددة الحروف والصور الجديدة مع تقليل التلميحات.']},
{number:53,slug:'story-sequencing',title:'التسلسل القصصي',ages:'4-9 سنوات',duration:'5-10 دقائق',taskType:'story-sequencing',purpose:'تدريب ترتيب أحداث مصورة وفق الزمن والسبب والنتيجة، ثم التعبير عن التسلسل بجمل قصيرة عند القدرة.',observation:'الترتيب الزمني، فهم السبب والنتيجة، تفسير الاختيار، استخدام روابط مثل ثم/بعد ذلك/لأن.',progression:['ثلاث صور ذات تسلسل يومي واضح.','أربع صور مع بداية ونهاية واضحتين.','أربع صور تتطلب فهم سبب ونتيجة.','خمس صور مع حدث وسيط أقل وضوحًا.','خمس/ست صور مع مشتت أو حدثين متقاربين يحتاجان استدلالًا.']}
];

const labels:{kind:LanguageReadingKind,label:string}[]=[{kind:'training-a',label:'تدريب أ'},{kind:'training-b',label:'تدريب ب'},{kind:'test',label:'اختبار الإتقان'}];
const taskInstruction=(task:LanguageReadingTask,kind:LanguageReadingKind)=>{
 const base=task==='rhyming'?'استمع إلى الكلمات التي يقرأها المرافق واختر ما يتشابه في النهاية الصوتية.':task==='initial-sound'?'سمِّ الصورة أو استمع لاسمها، ثم ركز على أول صوت في الكلمة.':task==='syllable-awareness'?'انطق الكلمة بالفصحى كما هي مكتوبة، وصفّق أو انقر مرة لكل مقطع مسموع.':task==='letter-discrimination'?'ابحث عن الحرف الهدف وعلّم عليه، وراقب عدد النقاط ومكانها وشكل الحرف.':task==='letter-picture-match'?'سمِّ الصورة أولًا، اعزل الصوت الأول، ثم صِلها بالحرف الموافق.':'رتب الصور من الحدث الأول إلى الأخير، ثم احكِ ما حدث باستخدام ثم/بعد ذلك إن أمكن.';
 return kind==='test'?`${base} نفّذ مرة واحدة دون كشف الإجابة أو تصحيحها أثناء الأداء.`:kind==='training-a'?`${base} ابدأ بمجموعة صغيرة واستخدم نطقًا واضحًا وتلميحًا واحدًا عند الحاجة.`:`${base} كرر بمثيرات جديدة وتلميحات أقل.`;
};
const masteryByTask=(task:LanguageReadingTask)=>task==='rhyming'?'دقة لا تقل عن 80% عبر مجموعة جديدة مع تلميحات قليلة، مع تفسير الاختيار صوتيًا عند القدرة.':task==='initial-sound'?'عزل الصوت الأول في معظم الكلمات الجديدة دون تحويل المهمة إلى تسمية اسم الحرف.':task==='syllable-awareness'?'عد المقاطع بدقة في أغلب الكلمات وفق النطق الفصيح المحدد، مع ثبات الأداء في محاولة ثانية.':task==='letter-discrimination'?'تمييز الهدف بدقة عالية مع أخطاء محدودة في النقاط/الموضع عبر صفوف جديدة.':task==='letter-picture-match'?'مطابقة معظم الصور بالحرف الصحيح بعد تسمية الصورة وعزل الصوت الأول، دون تخمين من اللون أو الموقع.':'ترتيب الأحداث منطقيًا مع القدرة على شرح سبب واحد على الأقل للترتيب عند مستوى اللغة المناسب.';
export const languageReadingActivities:LanguageReadingActivity[]=languageReadingSeriesPlans.flatMap(series=>Array.from({length:5},(_,i)=>i+1).flatMap(level=>labels.map((x,idx)=>({
 slug:`level-${level}-${x.kind}`,seriesSlug:series.slug,seriesNumber:series.number,seriesTitle:series.title,taskType:series.taskType,level,kind:x.kind,label:x.label,title:`${series.title} - المستوى ${level} - ${x.label}`,age:series.ages,duration:series.duration,purpose:series.purpose,instruction:taskInstruction(series.taskType,x.kind),progression:series.progression[level-1],observation:series.observation,mastery:masteryByTask(series.taskType),seed:series.number*100+level*10+idx
}))));
export const languageReadingActivityCount=languageReadingActivities.length;
export const languageReadingTestCount=languageReadingActivities.filter(a=>a.kind==='test').length;
export const getLanguageReadingSeries=(slug:string)=>languageReadingSeriesPlans.find(s=>s.slug===slug);
export const getLanguageReadingActivitiesForSeries=(slug:string)=>languageReadingActivities.filter(a=>a.seriesSlug===slug);
export const getLanguageReadingActivity=(series:string,slug:string)=>languageReadingActivities.find(a=>a.seriesSlug===series&&a.slug===slug);

export const initialSoundBanks=[
{letter:'ب',words:[['بطة','🦆'],['باب','🚪'],['بطيخ','🍉']]},{letter:'ت',words:[['تفاحة','🍎'],['تاج','👑'],['تمر','🌴']]},{letter:'ج',words:[['جمل','🐪'],['جرس','🔔'],['جبن','🧀']]},{letter:'ح',words:[['حصان','🐎'],['حليب','🥛'],['حوت','🐋']]},{letter:'س',words:[['سمكة','🐟'],['سيارة','🚗'],['ساعة','⌚']]},{letter:'ش',words:[['شجرة','🌳'],['شمس','☀️'],['شمعة','🕯️']]},{letter:'ق',words:[['قمر','🌙'],['قلم','✏️'],['قطة','🐈']]},{letter:'ف',words:[['فيل','🐘'],['فراشة','🦋'],['فنجان','☕']]},{letter:'ك',words:[['كتاب','📖'],['كرة','⚽'],['كرسي','🪑']]},{letter:'م',words:[['موز','🍌'],['مفتاح','🔑'],['مدرسة','🏫']]},{letter:'ن',words:[['نحلة','🐝'],['نجم','⭐'],['نار','🔥']]},{letter:'و',words:[['وردة','🌹'],['ورقة','📄'],['وجه','🙂']]}
] as const;
export const rhymeBanks: readonly (readonly string[])[]=[['باب','كتاب','سحاب'],['نور','سور','عصفور'],['فيل','نخيل','جميل'],['دار','نار','قطار'],['قلم','علم','حلم']];
export const syllableBanks={one:['باب','بيت','نور','نار'],two:['قمر','قلم','سمك','وردة'],three:['شجرة','مدرسة','سيارة','فراشة']} as const;
export const similarLetterGroups=[['ب','ت','ث','ن','ي'],['ج','ح','خ'],['د','ذ'],['ر','ز'],['س','ش'],['ص','ض'],['ط','ظ'],['ع','غ'],['ف','ق']] as const;