export type MathLogicTask='patterns'|'classification'|'quantity-comparison'|'ordering-sequencing'|'visual-logic';
export type MathLogicKind='training-a'|'training-b'|'test';
export type MathLogicSeries={number:number;slug:string;title:string;ages:string;duration:string;taskType:MathLogicTask;purpose:string;observation:string;progression:string[]};
export type MathLogicActivity={slug:string;seriesSlug:string;seriesNumber:number;seriesTitle:string;taskType:MathLogicTask;level:number;kind:MathLogicKind;label:string;title:string;age:string;duration:string;purpose:string;instruction:string;progression:string;observation:string;mastery:string;seed:number};

export const mathLogicSeriesPlans:MathLogicSeries[]=[
{number:54,slug:'patterns',title:'إكمال الأنماط',ages:'3-9 سنوات',duration:'4-8 دقائق',taskType:'patterns',purpose:'تدريب اكتشاف القاعدة المتكررة أو المتغيرة وتوقع العنصر التالي، مع انتقال تدريجي من نمط أحادي البعد إلى قواعد متعددة السمات.',observation:'هل يصف الطفل القاعدة؟ هل يتابع اللون فقط أم الشكل والحجم أيضًا؟ هل يكرر الوحدة كاملة أم يخمن العنصر التالي؟',progression:['نمط AB واضح بلونين أو شكلين.','نمط AAB أو ABB مع وحدة تكرار أطول.','نمط ABC أو تناوب شكل/لون.','نمط ثنائي السمة يجمع الشكل واللون أو الحجم.','نمط مركب أو متحول يتطلب استنتاج الوحدة ثم إكمال أكثر من فراغ.']},
{number:55,slug:'classification',title:'التصنيف',ages:'3-9 سنوات',duration:'4-8 دقائق',taskType:'classification',purpose:'تدريب تجميع العناصر وفق خاصية مشتركة ثم تغيير قاعدة التصنيف أو دمج معيارين، مع قبول أكثر من تصنيف صحيح عندما تكون القاعدة معلنة بوضوح.',observation:'الخاصية التي اعتمدها الطفل، الثبات على القاعدة، القدرة على تبديل القاعدة، والخلط بين اللون والشكل والحجم.',progression:['تصنيف حسب خاصية واحدة واضحة مثل الشكل.','تصنيف حسب اللون أو الحجم مع مشتتات.','تغيير القاعدة من الشكل إلى اللون في الصفحة نفسها.','تصنيف وفق معيارين معًا مثل أزرق + صغير.','اختيار مجموعة تحقق شرطين أو تفسير أكثر من طريقة تصنيف ممكنة وفق تعليمات محددة.']},
{number:56,slug:'quantity-comparison',title:'الكمية والمقارنة',ages:'3-8 سنوات',duration:'4-8 دقائق',taskType:'quantity-comparison',purpose:'تدريب مقارنة الكميات وفهم أكثر/أقل/يساوي مع فصل العدد عن حجم العنصر أو مدى انتشاره بصريًا.',observation:'هل يعد الطفل أم يعتمد على المساحة؟ دقة المطابقة واحد-لواحد، فهم أكثر/أقل/يساوي، وثبات الحكم عندما يتغير حجم العناصر أو توزيعها.',progression:['مقارنة مجموعتين صغيرتين مختلفتين بوضوح.','مقارنة كميات متقاربة مع عد اختياري.','إدخال حالة يساوي مع تغيير ترتيب العناصر.','عكس الإشارات البصرية: عناصر أكبر لكن أقل عددًا أو أكثر انتشارًا لكن أقل كمية.','مقارنة ثلاث مجموعات وترتيبها من الأقل إلى الأكثر مع فروق صغيرة نسبيًا.']},
{number:57,slug:'ordering-sequencing',title:'الترتيب والتسلسل',ages:'3-8 سنوات',duration:'4-8 دقائق',taskType:'ordering-sequencing',purpose:'تدريب ترتيب عناصر وفق بعد قابل للقياس مثل الحجم أو الطول أو الكمية، ثم استنتاج الموقع المفقود داخل سلسلة مرتبة.',observation:'هل يقارن عنصرين فقط أم يبني ترتيبًا كاملًا؟ عدد التبديلات، فهم أصغر/أكبر وأقصر/أطول، والقدرة على إدخال عنصر جديد في مكانه.',progression:['ترتيب ثلاثة عناصر من الأصغر إلى الأكبر.','ترتيب أربعة أطوال أو أحجام.','ترتيب خمس كميات مع فروق واضحة.','إدخال عنصر في سلسلة مرتبة دون إعادة بناء كل السلسلة.','ترتيب متعدد الخطوات مع عنصر مفقود أو فروق صغيرة تتطلب مقارنة منهجية.']},
{number:58,slug:'visual-logic',title:'المنطق البصري',ages:'5-10 سنوات',duration:'5-10 دقائق',taskType:'visual-logic',purpose:'تدريب الاستدلال من قواعد مصورة بسيطة عبر شبكات لا تسمح بتكرار الرمز في الصف أو العمود، مع ضمان وجود حل محدد.',observation:'استراتيجية المسح صفًا وعمودًا، اكتشاف الاستبعاد، عدد التخمينات، مراجعة الخطأ، والقدرة على شرح سبب الاختيار.',progression:['شبكة 3×3 مع فراغ واحد وقاعدة عدم التكرار.','شبكة 3×3 مع فراغين واستبعاد مباشر.','شبكة 3×3 مع عدة فراغات تتطلب ربط الصف والعمود.','شبكة 4×4 مبسطة مع رموز واضحة وعدة فراغات.','شبكة 4×4 تتطلب عدة خطوات استبعاد دون تخمين عشوائي.']}
];

const labels:{kind:MathLogicKind,label:string}[]=[{kind:'training-a',label:'تدريب أ'},{kind:'training-b',label:'تدريب ب'},{kind:'test',label:'اختبار الإتقان'}];
const instruction=(task:MathLogicTask,kind:MathLogicKind)=>{
 const base=task==='patterns'?'اكتشف قاعدة النمط ثم اختر أو ارسم العنصر المناسب في الفراغ.':task==='classification'?'اقرأ قاعدة التصنيف ثم ضع علامة على العناصر التي تحققها فقط.':task==='quantity-comparison'?'قارن المجموعات وحدد الأكثر أو الأقل أو المتساوي حسب المطلوب؛ عدّ العناصر إذا احتجت.':task==='ordering-sequencing'?'رتب العناصر وفق الخاصية المطلوبة من الأصغر إلى الأكبر أو من الأقل إلى الأكثر.':'أكمل الشبكة بحيث لا يتكرر الرمز نفسه في الصف أو العمود.';
 return kind==='test'?`${base} نفّذ مرة واحدة باستقلال، ولا تُكشف الإجابة أثناء الأداء.`:kind==='training-a'?`${base} ابدأ ببطء واشرح القاعدة بصوتك إن استطعت.`:`${base} أعد المحاولة بمثيرات جديدة وتلميحات أقل.`;
};
const mastery=(task:MathLogicTask)=>task==='patterns'?'إكمال معظم الأنماط الجديدة مع القدرة على وصف الوحدة أو القاعدة في المستويات المناسبة، لا مجرد اختيار صحيح بالصدفة.':task==='classification'?'تطبيق قاعدة التصنيف المعلنة بثبات وتبديلها عند الطلب مع أخطاء محدودة.':task==='quantity-comparison'?'أحكام أكثر/أقل/يساوي صحيحة رغم تغير الحجم أو التوزيع البصري، مع استخدام العد أو المطابقة عند الحاجة.':task==='ordering-sequencing'?'بناء ترتيب كامل صحيح وإدخال عنصر جديد في موضعه مع تلميحات قليلة.':'حل الشبكة بالاستبعاد مع أخطاء محدودة وقدرة على تفسير اختيار واحد على الأقل في المستويات العليا.';

export const mathLogicActivities:MathLogicActivity[]=mathLogicSeriesPlans.flatMap(series=>Array.from({length:5},(_,i)=>i+1).flatMap(level=>labels.map((x,idx)=>({
 slug:`level-${level}-${x.kind}`,seriesSlug:series.slug,seriesNumber:series.number,seriesTitle:series.title,taskType:series.taskType,level,kind:x.kind,label:x.label,title:`${series.title} - المستوى ${level} - ${x.label}`,age:series.ages,duration:series.duration,purpose:series.purpose,instruction:instruction(series.taskType,x.kind),progression:series.progression[level-1],observation:series.observation,mastery:mastery(series.taskType),seed:series.number*100+level*10+idx
})))).filter(a=>!(a.seriesSlug==='patterns'&&a.slug==='level-1-training-b'));
export const mathLogicActivityCount=mathLogicActivities.length;
export const mathLogicTestCount=mathLogicActivities.filter(a=>a.kind==='test').length;
export const getMathLogicSeries=(slug:string)=>mathLogicSeriesPlans.find(s=>s.slug===slug);
export const getMathLogicActivitiesForSeries=(slug:string)=>mathLogicActivities.filter(a=>a.seriesSlug===slug);
export const getMathLogicActivity=(series:string,slug:string)=>mathLogicActivities.find(a=>a.seriesSlug===series&&a.slug===slug);
