export type SensorySelfTask='what-helps-me'|'energy-state';
export type SensorySelfKind='training-a'|'training-b'|'test';
export type SensorySelfSeries={number:number;slug:string;title:string;ages:string;duration:string;taskType:SensorySelfTask;purpose:string;observation:string;progression:string[]};
export type SensorySelfActivity={slug:string;seriesSlug:string;seriesNumber:number;seriesTitle:string;taskType:SensorySelfTask;level:number;kind:SensorySelfKind;label:string;title:string;age:string;duration:string;purpose:string;instruction:string;progression:string;observation:string;mastery:string;seed:number};
export const sensorySelfSeriesPlans:SensorySelfSeries[]=[
{number:66,slug:'what-helps-me',title:'اكتشاف ما يساعدني',ages:'4-12 سنوات',duration:'5-9 دقائق',taskType:'what-helps-me',purpose:'تدريب الطفل على ملاحظة الظروف والاستراتيجيات اليومية منخفضة المخاطر التي تساعده على المشاركة أو الراحة أو التركيز، مع قبول أن ما يساعد شخصًا قد لا يساعد آخر.',observation:'هل يربط الطفل الاختيار بموقف أو هدف؟ هل يميز بين ما يساعده فعلًا وما يختاره لمجرد الشكل؟ هل يستطيع قول لا أعرف أو هذا لا يساعدني؟',progression:['اختيار تفضيل واحد واضح من خيارين في موقف بسيط.','مقارنة بيئتين أو نشاطين وذكر أيهما أنسب ولماذا.','اختيار أداة أو تغيير بيئي منخفض المخاطر لهدف محدد مثل الهدوء أو الاستعداد.','بناء خطة صغيرة من خطوتين مع بديل إذا لم تساعد الخطوة الأولى.','مقارنة عدة مواقف واختيار دعم مختلف لكل موقف مع توضيح أن التفضيل قابل للتغير.']},
{number:67,slug:'energy-state',title:'حالة الطاقة والاستعداد',ages:'4-12 سنوات',duration:'5-9 دقائق',taskType:'energy-state',purpose:'تدريب الطفل على وصف مستوى طاقته واستعداده بالنسبة للمهمة الحالية، ثم اختيار خطوة بسيطة وآمنة قد تساعده على الاستعداد دون اعتبار أي مستوى طاقة جيدًا أو سيئًا في ذاته.',observation:'هل يصف الطفل حالته بنفسه؟ هل يربطها بالمهمة الحالية؟ هل يختار خطوة مناسبة وآمنة؟ وهل يعيد التقييم بعد التجربة بدل افتراض نجاحها؟',progression:['اختيار وصف بسيط للطاقة: منخفضة/مناسبة للمهمة/مرتفعة.','ربط مستوى الطاقة بمهمتين مختلفتين قد تحتاجان استعدادًا مختلفًا.','اختيار خطوة بسيطة ثم إعادة التقييم بعدها.','التفريق بين الطاقة والانفعال والحاجة الجسدية مثل الجوع أو العطش أو التعب.','بناء خطة استعداد مرنة: لاحظ → اختر خطوة → جرّب → أعد التقييم → غيّر الخطة عند الحاجة.']}
];
const labels:{kind:SensorySelfKind,label:string}[]=[{kind:'training-a',label:'تدريب أ'},{kind:'training-b',label:'تدريب ب'},{kind:'test',label:'اختبار الإتقان'}];
const instruction=(task:SensorySelfTask,kind:SensorySelfKind)=>{const base=task==='what-helps-me'?'اقرأ الموقف واختر ما قد يساعدك أنت، ثم اكتب أو قل لماذا. يمكنك اختيار «لا أعرف بعد» أو «لا شيء من هذه الخيارات».':'لاحظ طاقتك بالنسبة للمهمة الحالية، اختر الوصف الأقرب، ثم اختر خطوة بسيطة وآمنة وجرب أن تعيد التقييم بعدها.';return kind==='test'?`${base} نفّذ باستقلال قدر الإمكان، ولا توجد إجابة شخصية واحدة يجب أن يختارها الجميع.`:kind==='training-a'?`${base} استخدم سؤالًا مساعدًا واحدًا إذا احتجت.`:`${base} أعد المحاولة بموقف جديد وتلميحات أقل.`;};
const mastery=(task:SensorySelfTask)=>task==='what-helps-me'?'يختار أو يرفض خيارًا مع سبب مرتبط بالموقف أو الهدف، ويستطيع ذكر بديل أو «لا أعرف بعد» عندما لا تكفي الخيارات.':'يصف مستوى الطاقة بالنسبة للمهمة، يختار خطوة منخفضة المخاطر، ثم يعيد التقييم ويغير الخطة إذا لم تساعد.';
export const sensorySelfActivities:SensorySelfActivity[]=sensorySelfSeriesPlans.flatMap(series=>Array.from({length:5},(_,i)=>i+1).flatMap(level=>labels.map((x,idx)=>({slug:`level-${level}-${x.kind}`,seriesSlug:series.slug,seriesNumber:series.number,seriesTitle:series.title,taskType:series.taskType,level,kind:x.kind,label:x.label,title:`${series.title} - المستوى ${level} - ${x.label}`,age:series.ages,duration:series.duration,purpose:series.purpose,instruction:instruction(series.taskType,x.kind),progression:series.progression[level-1],observation:series.observation,mastery:mastery(series.taskType),seed:series.number*100+level*10+idx})))).filter(a=>!(a.seriesSlug==='what-helps-me'&&a.slug==='level-1-training-b'));
export const sensorySelfActivityCount=sensorySelfActivities.length;
export const sensorySelfTestCount=sensorySelfActivities.filter(a=>a.kind==='test').length;
export const getSensorySelfSeries=(slug:string)=>sensorySelfSeriesPlans.find(s=>s.slug===slug);
export const getSensorySelfActivitiesForSeries=(slug:string)=>sensorySelfActivities.filter(a=>a.seriesSlug===slug);
export const getSensorySelfActivity=(series:string,slug:string)=>sensorySelfActivities.find(a=>a.seriesSlug===series&&a.slug===slug);
export const whatHelpsScenarios=[{title:'وقت القراءة',goal:'أريد أن أقرأ عشر دقائق براحة.',options:['مكان أهدأ','إبعاد المشتتات البصرية','طلب دقيقة استعداد قبل البدء','لا أعرف بعد']},{title:'بعد جلوس طويل',goal:'أحتاج أن أبدأ مهمة جديدة.',options:['حركة قصيرة وآمنة','شرب ماء إن كنت عطشانًا','ترتيب الأدوات أمامي','لا شيء من هذه الخيارات']},{title:'مكان صاخب',goal:'أريد أن أستمر في النشاط دون ألم أو إزعاج زائد.',options:['الابتعاد قليلًا عن مصدر الصوت','طلب خفض الصوت إن أمكن','استخدام حماية سمعية مناسبة ومسموح بها','طلب استراحة']},{title:'ضوء مزعج',goal:'أريد أن أرى المهمة براحة أكبر.',options:['تغيير مكاني بعيدًا عن الضوء المباشر','تقليل شدة الإضاءة إن أمكن','استخدام ورقة حاجبة للوهج','طلب مساعدة من بالغ موثوق']},{title:'انتقال بين نشاطين',goal:'أريد أن أعرف ماذا سيحدث بعد ذلك.',options:['رؤية جدول أو قائمة قصيرة','تنبيه قبل الانتقال','حمل أداة المهمة التالية','طلب شرح الخطوة التالية']}] as const;
export const energySteps=[{label:'طاقتي منخفضة',symbol:'↓',note:'قد أحتاج راحة أو ماءً أو حركة لطيفة أو وقتًا للاستعداد؛ حسب السبب والموقف.'},{label:'طاقتي مناسبة لهذه المهمة',symbol:'=',note:'يمكنني البدء أو الاستمرار، وقد تتغير حالتي لاحقًا.'},{label:'طاقتي مرتفعة لهذه المهمة',symbol:'↑',note:'قد تساعدني حركة آمنة أو تقليل المشتتات أو تقسيم المهمة؛ ليس المطلوب إخفاء النشاط.'}] as const;
export const readinessActions=['راحة قصيرة','شرب ماء عند الحاجة','حركة قصيرة وآمنة','مكان أهدأ','تقليل مشتت واحد','رؤية الخطوة التالية','طلب مساعدة','لا أحتاج تغييرًا الآن'] as const;
