import type { SensorySelfActivity } from './sensory-self-regulation-lab';
import { energySteps, readinessActions, whatHelpsScenarios } from './sensory-self-regulation-lab';
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const wrap=(s:string,n=42)=>{const w=s.split(' ');const out:string[]=[];let line='';for(const x of w){if((line+' '+x).trim().length>n){out.push(line.trim());line=x}else line=(line+' '+x).trim()}if(line)out.push(line);return out};
const textLines=(lines:string[],x:number,y:number,size=24,dy=34,anchor='middle')=>lines.map((l,i)=>`<text x="${x}" y="${y+i*dy}" text-anchor="${anchor}" font-size="${size}" font-family="Arial,Tahoma,sans-serif" fill="#0f172a">${esc(l)}</text>`).join('');
const shell=(a:SensorySelfActivity,body:string)=>`<svg xmlns="http://www.w3.org/2000/svg" width="794" height="1123" viewBox="0 0 794 1123"><rect width="794" height="1123" fill="#ffffff"/><rect x="28" y="24" width="738" height="102" rx="20" fill="#ecfeff" stroke="#0f766e" stroke-width="2"/><text x="397" y="62" text-anchor="middle" font-size="28" font-weight="700" font-family="Arial,Tahoma,sans-serif" fill="#115e59">${esc(a.seriesTitle)}</text><text x="397" y="96" text-anchor="middle" font-size="19" font-family="Arial,Tahoma,sans-serif" fill="#334155">المستوى ${a.level} · ${esc(a.label)} · ${esc(a.age)}</text>${body}<rect x="36" y="1025" width="722" height="66" rx="16" fill="#f8fafc" stroke="#cbd5e1"/><text x="397" y="1053" text-anchor="middle" font-size="16" font-family="Arial,Tahoma,sans-serif" fill="#334155">لا توجد استجابة شخصية واحدة صحيحة للجميع · اختر ما يناسبك وراجع النتيجة</text><text x="397" y="1079" text-anchor="middle" font-size="15" font-family="Arial,Tahoma,sans-serif" fill="#64748b">أداة تعليمية للملاحظة الذاتية وليست تقييمًا سريريًا أو وصفة حسية</text></svg>`;
function helps(a:SensorySelfActivity){const sc=whatHelpsScenarios[(a.seed+a.level)%whatHelpsScenarios.length];const opts=a.kind==='test'?[...sc.options].reverse():sc.options;let b=`<text x="397" y="170" text-anchor="middle" font-size="26" font-weight="700" font-family="Arial,Tahoma,sans-serif" fill="#0f172a">${esc(sc.title)}</text>`;b+=textLines(wrap(sc.goal,46),397,210,21,30);b+=`<text x="397" y="294" text-anchor="middle" font-size="20" font-family="Arial,Tahoma,sans-serif" fill="#475569">ضع علامة على ما قد يساعدك، ويمكنك اختيار أكثر من خيار.</text>`;opts.forEach((o,i)=>{const y=350+i*112;b+=`<rect x="110" y="${y}" width="574" height="82" rx="18" fill="${i%2?'#f0fdfa':'#f8fafc'}" stroke="#94a3b8" stroke-width="2"/><circle cx="145" cy="${y+41}" r="16" fill="#fff" stroke="#0f766e" stroke-width="3"/>${textLines(wrap(o,34),620,y+34,20,26,'end')}`});b+=`<text x="397" y="855" text-anchor="middle" font-size="21" font-weight="700" font-family="Arial,Tahoma,sans-serif" fill="#115e59">لماذا اخترت هذا؟</text><rect x="100" y="880" width="594" height="90" rx="16" fill="#fff" stroke="#cbd5e1" stroke-width="2"/>`;return shell(a,b)}
function energy(a:SensorySelfActivity){const task=['قراءة هادئة','الاستعداد للخروج','حل تمرين قصير','الجلوس في مجموعة','الانتقال لنشاط جديد'][(a.seed+a.level)%5];let b=`<text x="397" y="170" text-anchor="middle" font-size="24" font-weight="700" font-family="Arial,Tahoma,sans-serif" fill="#0f172a">المهمة الآن: ${esc(task)}</text><text x="397" y="212" text-anchor="middle" font-size="20" font-family="Arial,Tahoma,sans-serif" fill="#475569">أي وصف أقرب لطاقتك بالنسبة لهذه المهمة؟</text>`;energySteps.forEach((s,i)=>{const x=155+i*242;b+=`<rect x="${x-94}" y="270" width="188" height="178" rx="24" fill="${i===0?'#eff6ff':i===1?'#ecfdf5':'#fff7ed'}" stroke="#64748b" stroke-width="2"/><text x="${x}" y="328" text-anchor="middle" font-size="42" font-family="Arial,Tahoma,sans-serif" fill="#0f172a">${s.symbol}</text>${textLines(wrap(s.label,17),x,370,18,24)}`});b+=`<text x="397" y="505" text-anchor="middle" font-size="21" font-weight="700" font-family="Arial,Tahoma,sans-serif" fill="#115e59">اختر خطوة واحدة آمنة ثم أعد التقييم</text>`;readinessActions.slice((a.seed%3), (a.seed%3)+5).forEach((o,i)=>{const y=548+i*66;b+=`<rect x="130" y="${y}" width="534" height="48" rx="14" fill="#f8fafc" stroke="#cbd5e1"/><circle cx="160" cy="${y+24}" r="12" fill="#fff" stroke="#0f766e" stroke-width="2"/><text x="630" y="${y+31}" text-anchor="end" font-size="18" font-family="Arial,Tahoma,sans-serif" fill="#0f172a">${esc(o)}</text>`});b+=`<text x="397" y="915" text-anchor="middle" font-size="20" font-weight="700" font-family="Arial,Tahoma,sans-serif" fill="#115e59">بعد التجربة: هل ساعدت؟ نعم / قليلًا / لا — ماذا ستغير؟</text>`;return shell(a,b)}
export function renderSensorySelfSvg(a:SensorySelfActivity){return a.taskType==='what-helps-me'?helps(a):energy(a)}
