import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { deleteRedirect,saveRedirect } from './actions';

export const dynamic='force-dynamic';
type SearchParams=Promise<{q?:string;edit?:string;ok?:string;error?:string}>;
type RedirectRow={id:string;source_path:string;destination_path:string;status_code:number;is_active:boolean;note:string|null;created_at:string;updated_at:string};
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i;
function date(v:string){try{return new Intl.DateTimeFormat('ar',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return''}}

export default async function RedirectsPage({searchParams}:{searchParams:SearchParams}){
 const params=await searchParams;const q=String(params.q??'').trim().slice(0,200);const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const uid=claims?.claims?.sub;if(!uid)redirect('/login?next=/admin/redirects');const {data:profile}=await supabase.from('profiles').select('role,is_active').eq('id',uid).single();if(!profile?.is_active||!['owner','admin'].includes(profile.role))redirect('/account');
 const {data,error}=await supabase.rpc('admin_list_redirects',{p_query:q||null,p_limit:300,p_offset:0});const rows:RedirectRow[]=Array.isArray(data)?data as RedirectRow[]:[];const editId=String(params.edit??'');const selected=UUID_RE.test(editId)?rows.find(row=>row.id===editId)??null:null;
 return <main className="dashboard-shell"><section className="dashboard-card"><div className="admin-heading"><div><span className="eyebrow">Redirect Manager</span><h1>إدارة التحويلات</h1><p>تحويلات داخلية فقط، مع منع التحويل إلى نطاق خارجي أو إلى المسار نفسه وكشف حلقات التحويل قبل الحفظ.</p></div><div className="dashboard-actions"><Link className="button" href="/admin">لوحة الإدارة</Link><Link className="button" href="/admin/audit">Audit Log</Link></div></div>
 {params.ok&&<p className="system-message success">تم حفظ العملية وتسجيلها في Audit Log.</p>}{params.error&&<p className="system-message error">تعذر تنفيذ العملية{params.error==='loop'?' بسبب حلقة تحويل محتملة':''}.</p>}
 <div className="redirect-layout"><div><form className="directory-filters" method="get"><label>بحث<input name="q" defaultValue={q} placeholder="/old-page أو /new-page"/></label><button className="primary-action" type="submit">بحث</button>{q&&<Link href="/admin/redirects">مسح</Link>}</form><div className="redirect-list">{rows.map(row=><article key={row.id}><div><span className={`status-badge ${row.is_active?'status-verified':'status-suspended'}`}>{row.status_code} · {row.is_active?'نشط':'معطل'}</span><strong><bdi dir="ltr">{row.source_path}</bdi></strong><span>← <bdi dir="ltr">{row.destination_path}</bdi></span><small>{date(row.updated_at)}{row.note?` · ${row.note}`:''}</small></div><div className="dashboard-actions"><Link className="button" href={`/admin/redirects?edit=${row.id}${q?`&q=${encodeURIComponent(q)}`:''}`}>تعديل</Link><form action={deleteRedirect}><input type="hidden" name="id" value={row.id}/><button className="button danger" type="submit">حذف</button></form></div></article>)}{!error&&rows.length===0&&<p className="empty-state">لا توجد تحويلات مطابقة.</p>}</div></div>
 <aside className="redirect-editor"><h2>{selected?'تعديل التحويل':'تحويل جديد'}</h2><form action={saveRedirect} className="specialist-form">{selected&&<input type="hidden" name="id" value={selected.id}/>}<label>المسار القديم<input name="source_path" dir="ltr" required maxLength={1800} defaultValue={selected?.source_path??''} placeholder="/old-path"/></label><label>المسار الجديد<input name="destination_path" dir="ltr" required maxLength={1800} defaultValue={selected?.destination_path??''} placeholder="/new-path"/></label><label>نوع التحويل<select name="status_code" defaultValue={selected?.status_code??301}><option value="301">301 دائم</option><option value="308">308 دائم مع حفظ الطريقة</option><option value="302">302 مؤقت</option><option value="307">307 مؤقت مع حفظ الطريقة</option></select></label><label>ملاحظة<textarea name="note" rows={3} maxLength={1000} defaultValue={selected?.note??''}/></label><label className="check-field"><input type="checkbox" name="is_active" defaultChecked={selected?.is_active??true}/> نشط</label><button className="primary-action" type="submit">{selected?'حفظ التعديل':'إضافة التحويل'}</button>{selected&&<Link className="button" href="/admin/redirects">إلغاء التعديل</Link>}</form><p className="portal-notice"><strong>قاعدة أمان:</strong><span>المصدر والوجهة يجب أن يكونا داخل healthrenewal.org كمسارات نسبية تبدأ بـ /؛ لا روابط خارجية ولا حلقات.</span></p></aside></div>
 </section></main>;
}
