import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import KidsLabPrintButton from '@/components/kids-lab-print-button';
import { getSocialActivity, socialActivities } from '@/lib/capabilities/social-skills-lab';
import styles from '../../../kids-lab.module.css';
type Props={params:Promise<{series:string;activity:string}>};
export function generateStaticParams(){return socialActivities.map(a=>({series:a.seriesSlug,activity:a.slug}));}
export default async function ActivityPage({params}:Props){const {series,activity:slug}=await params;const a=getSocialActivity(series,slug);if(!a)notFound();const idx=socialActivities.findIndex(x=>x.seriesSlug===series&&x.slug===slug);const prev=idx>0&&socialActivities[idx-1].seriesSlug===series?socialActivities[idx-1]:null;const next=idx<socialActivities.length-1&&socialActivities[idx+1].seriesSlug===series?socialActivities[idx+1]:null;return <><SiteHeader/><main className={styles.shell}><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><Link href="/capabilities/kids-lab/social-skills/">المهارات الاجتماعية</Link><span>/</span><Link href={`/capabilities/kids-lab/social-skills/${series}/`}>{a.seriesTitle}</Link><span>/</span><span>{a.label}</span></nav><section className={styles.hero}><span className={styles.kicker}>السلسلة {a.seriesNumber} · المستوى {a.level}</span><h1>{a.title}</h1><p className={styles.lead}>{a.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>{a.age}</span><span className={styles.metaChip}>{a.duration}</span><span className={styles.metaChip}>{a.kind==='test'?'اختبار إتقان':'تدريب'}</span></div></section><section className={styles.section}><div className={styles.infoCard}><h2>التعليمات</h2><p>{a.instruction}</p><p><strong>درجة التدرج:</strong> {a.progression}</p></div><div className={styles.previewFrame}><img src={`/capabilities/kids-lab/social-skills/${series}/${slug}/image/`} alt={a.title}/></div><div className={styles.actions}><KidsLabPrintButton/><a className={styles.secondaryButton} href={`/capabilities/kids-lab/social-skills/${series}/${slug}/image/`} download>تنزيل SVG</a></div></section><section className={styles.section}><div className={styles.note}><strong>معيار الإتقان:</strong> {a.mastery}</div><div className={styles.infoCard} style={{marginTop:'1rem'}}><h2>ما الذي نلاحظه؟</h2><p>{a.observation}</p></div>{a.kind==='test'&&<div className={styles.note} style={{marginTop:'1rem'}}><strong>مهم:</strong> هذا اختبار تعلم داخل السلسلة، وليس أداة تقييم معيارية أو تشخيصية.</div>}</section><section className={styles.section}><div className={styles.actions}>{prev&&<Link className={styles.secondaryButton} href={`/capabilities/kids-lab/social-skills/${series}/${prev.slug}/`}>السابق</Link>}{next&&<Link className={styles.primaryButton} href={`/capabilities/kids-lab/social-skills/${series}/${next.slug}/`}>التالي</Link>}</div></section></main><SiteFooter/></>}
