import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata } from '@/lib/seo';
import styles from '../legacy-specialists.module.css';

export const metadata: Metadata = buildSeoMetadata({ title:'تواصل مع مختص | محادثة خاصة داخل المنصة', description:'المحتوى التاريخي لمسار التواصل مع المختص بعد نقله إلى روافد الجديدة: الخصوصية، الحد الأدنى من المعلومات، مسار الرسالة وحدود الطوارئ.', path:'/specialists-partners/contact', index:false, follow:true });

export default function LegacySpecialistContactPage(){return <><SiteHeader/><main className={styles.page}><section className={styles.hero}><div className={styles.shell}><span className={styles.eyebrow}>قناة اتصال منظمة · محتوى منقول</span><h1>ابدأ رسالة مهنية دون كشف بريد المختص</h1><p>احتفظنا بمحتوى صفحة التواصل القديمة بدل تحويل الرابط إلى دليل المختصين. تبدأ العملية باختيار ملف مهني موثّق، ثم تستخدم قناة المنصة بدل نشر البريد الشخصي أو تبادل معلومات حساسة في أول رسالة.</p></div></section><section className={`${styles.shell} ${styles.content}`}><article className={styles.card}><h2>استخدم الحد الأدنى اللازم من المعلومات</h2><p>في الرسالة الأولى يكفي وصف سبب التواصل والهدف العام. لا ترسل رقم هوية أو جواز سفر، صور تقارير طبية أو مدرسية، عنوان منزل تفصيلي، صور أطفال أو تسجيلات خاصة، كلمات مرور، بيانات مالية، أو معلومات لا يحتاجها المختص لفهم الطلب الأولي.</p></article><article className={styles.card}><h2>ماذا يحدث بعد بدء التواصل؟</h2><ol><li><strong>اختيار المختص:</strong> افتح الدليل وراجع نطاق الممارسة وحالة الملف.</li><li><strong>بدء قناة خاصة:</strong> عندما تكون المراسلة متاحة، تُستخدم المنصة بدل كشف بريد المختص للعامة.</li><li><strong>الرد والمتابعة:</strong> تحفظ الرسائل في مساحة الحساب المخصصة لها وتظهر للمستخدم وفق صلاحياته.</li><li><strong>الخدمة المهنية مستقلة:</strong> التكلفة والموعد ونطاق الخدمة وشروطها تُحدَّد بوضوح بين الطرفين ولا تُستنتج من صفحة الدليل.</li></ol></article><article className={styles.safety}><h2>ليست قناة طوارئ</h2><p>عند وجود خطر مباشر، إصابة، فقدان وعي، تهديد للنفس أو للآخرين، أو حاجة صحية عاجلة، استخدم خدمات الطوارئ المحلية المناسبة بدل انتظار رسالة داخل المنصة.</p></article><div className={styles.actions}><Link href="/specialists">اختيار مختص من الدليل</Link><Link href="/messages">فتح رسائلي</Link></div></section></main><SiteFooter/></>}
