import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata,breadcrumbJsonLd,SITE_URL } from '@/lib/seo';
import { fineMotorActivities,fineMotorActivityCount,fineMotorSeriesPlans,fineMotorTestCount } from '@/lib/capabilities/fine-motor-lab';
import styles from '../kids-lab.module.css';

export const metadata=buildSeoMetadata({title:'المهارات الحركية الدقيقة وما قبل الكتابة للأطفال | أنشطة متدرجة',description:'ست سلاسل متدرجة للخطوط والأقواس والقص والتلوين والتحكم بالقلم وأنماط الاستعداد للكتابة، بعد تنقيح التكرار مع الحفاظ على اختبارات الإتقان.',path:'/capabilities/kids-lab/fine-motor/',index:true,keywords:['المهارات الحركية الدقيقة','ما قبل الكتابة','التحكم بالقلم','القص بالمقص','التلوين داخل الحدود','الاستعداد للكتابة العربية']});
export default function FineMotorPage(){const breadcrumbs=breadcrumbJsonLd([{name:'الرئيسية',path:'/'},{name:'مختبر الأطفال',path:'/capabilities/kids-lab/'},{name:'المهارات الحركية الدقيقة',path:'/capabilities/kids-lab/fine-motor/'}]);const collection={'@context':'https://schema.org','@type':'CollectionPage','@id':`${SITE_URL}/capabilities/kids-lab/fine-motor/#collection`,url:`${SITE_URL}/capabilities/kids-lab/fine-motor/`,name:'المهارات الحركية الدقيقة وما قبل الكتابة للأطفال',inLanguage:'ar',isAccessibleForFree:true,numberOfItems:fineMotorActivityCount};return <><SiteHeader/><main className={styles.shell}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([breadcrumbs,collection]).replace(/</g,'\\u003c')}}/><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><span>الحركية الدقيقة</span></nav><section className={styles.hero}><span className={styles.kicker}>المجال السادس - المهارات الحركية الدقيقة وما قبل الكتابة</span><h1>حركة دقيقة لها هدف وظيفي، لا مجرد أوراق تلوين</h1><p className={styles.lead}>التركيز هنا على التحكم الفعلي بالقلم والمقص والحدود والنمط الحركي، مع تدرج عملي قابل للطباعة ومؤشرات أداء مرتبطة بالمهمة.</p><div className={styles.stats}><div className={styles.stat}><strong>{fineMotorSeriesPlans.length}</strong><span>سلاسل</span></div><div className={styles.stat}><strong>5</strong><span>مستويات</span></div><div className={styles.stat}><strong>{fineMotorTestCount}</strong><span>اختبار إتقان</span></div><div className={styles.stat}><strong>{fineMotorActivityCount}</strong><span>نشاطًا واختبارًا</span></div></div></section><section className={styles.section}><div className={styles.categoryGrid}>{fineMotorSeriesPlans.map(s=>{const count=fineMotorActivities.filter(a=>a.seriesSlug===s.slug).length;return <article className={styles.categoryCard} style={{'--category-color':'#F97316'} as React.CSSProperties} key={s.slug}><span className={styles.kicker}>السلسلة {s.number}</span><h3>{s.title}</h3><p>{s.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>{s.ages}</span><span className={styles.metaChip}>{s.duration}</span><span className={styles.metaChip}>{count} عنصرًا</span></div><div className={styles.actions}><Link className={styles.primaryButton} href={`/capabilities/kids-lab/fine-motor/${s.slug}/`}>افتح السلسلة</Link></div></article>})}</div></section><section className={styles.section}><div className={styles.note}><strong>قاعدة الاستخدام:</strong> هذه أنشطة تدريب وملاحظة وليست اختبارات معيارية أو تشخيصية. الصعوبة المستمرة في استخدام القلم أو المقص أو الكتابة قد تحتاج تقييمًا وظيفيًا أوسع، ولا تُفسر من ورقة واحدة.</div></section></main><SiteFooter/></>}
