import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata } from '@/lib/seo';
import { emotionalRegulationSeriesPlans,getEmotionalRegulationActivitiesForSeries,getEmotionalRegulationSeries } from '@/lib/capabilities/emotional-regulation-lab';
import styles from '../../kids-lab.module.css';
type Props={params:Promise<{series:string}>};
export function generateStaticParams(){return emotionalRegulationSeriesPlans.map(s=>({series:s.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {series:slug}=await params;const s=getEmotionalRegulationSeries(slug);if(!s)return{};const count=getEmotionalRegulationActivitiesForSeries(slug).length;return buildSeoMetadata({title:`${s.title} للأطفال | 5 مستويات و${count} عنصرًا`,description:`${s.purpose} خمسة مستويات مع تدريبات واختبارات إتقان منقحة لتقليل التكرار.`,path:`/capabilities/kids-lab/emotional-regulation/${s.slug}/`,index:true,keywords:[s.title,'التنظيم الانفعالي للأطفال','أوراق عمل المشاعر']});}
export default async function Page({params}:Props){const {series:slug}=await params;const s=getEmotionalRegulationSeries(slug);if(!s)notFound();const acts=getEmotionalRegulationActivitiesForSeries(slug);return <><SiteHeader/><main className={styles.shell}><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><Link href="/capabilities/kids-lab/emotional-regulation/">التنظيم الانفعالي</Link><span>/</span><span>{s.title}</span></nav><section className={styles.hero}><span className={styles.kicker}>السلسلة {s.number}</span><h1>{s.title}</h1><p className={styles.lead}>{s.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>{s.ages}</span><span className={styles.metaChip}>{s.duration}</span><span className={styles.metaChip}>{acts.length} عنصرًا</span></div></section><section className={styles.section}><div className={styles.flow}>{Array.from({length:5},(_,i)=>i+1).map(level=>{const items=acts.filter(a=>a.level===level);return <article className={styles.flowCard} key={level}><span className={styles.flowNumber}>{level}</span><h3>المستوى {level}</h3><p>{s.progression[level-1]}</p><div className={styles.seriesList}>{items.map(a=><Link href={`/capabilities/kids-lab/emotional-regulation/${s.slug}/${a.slug}/`} className={a.kind==='test'?styles.seriesActive:styles.seriesItem} key={a.slug}><span><strong>{a.label}</strong><small>{a.title}</small></span>{a.kind==='test'&&<span className={styles.readyBadge}>اختبار</span>}</Link>)}</div></article>})}</div></section><section className={styles.section}><div className={styles.note}><strong>الملاحظة:</strong> {s.observation}</div></section></main><SiteFooter/></>}
