import { createClient } from '@/lib/supabase/server';
import { deleteTag, upsertTag } from './actions';

export const dynamic='force-dynamic';
type SearchParams=Promise<{ok?:string;error?:string}>;
export default async function TagsPage({searchParams}:{searchParams:SearchParams}){
 const supabase=await createClient();const {data:tags}=await supabase.from('tags').select('id,slug,name_ar,description,is_active').order('name_ar');const query=await searchParams;
 return <main className="dashboard-shell"><section className="dashboard-card"><div className="admin-heading"><div><span className="eyebrow">Topical Authority</span><h1>الوسوم الدلالية</h1><p>وسوم مشتركة تربط المحتوى عبر القطاعات والأقسام دون تكرار الصفحات.</p></div></div>{query.ok&&<p className="system-message success">تم الحفظ.</p>}{query.error&&<p className="system-message error">تعذر تنفيذ العملية. لا يمكن حذف وسم مستخدم.</p>}<form className="admin-form" action={upsertTag}><div className="admin-form-grid"><label>الاسم العربي<input name="name_ar" required maxLength={240}/></label><label>Slug<input dir="ltr" name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={140}/></label><label className="wide-field">الوصف<input name="description" maxLength={1000}/></label><label className="block-check"><input type="checkbox" name="is_active" defaultChecked/> نشط</label></div><button className="primary-action" type="submit">إضافة وسم</button></form><div className="admin-list">{(tags??[]).map((tag)=><article className="admin-list-item" key={tag.id}><form className="admin-form" action={upsertTag}><input type="hidden" name="id" value={tag.id}/><div className="admin-form-grid"><label>الاسم<input name="name_ar" defaultValue={tag.name_ar} required/></label><label>Slug<input dir="ltr" name="slug" defaultValue={tag.slug} required/></label><label className="wide-field">الوصف<input name="description" defaultValue={tag.description||''}/></label><label className="block-check"><input type="checkbox" name="is_active" defaultChecked={tag.is_active}/> نشط</label></div><button className="button" type="submit">حفظ</button></form><form action={deleteTag}><input type="hidden" name="id" value={tag.id}/><button className="workflow-button danger" type="submit">حذف إذا غير مستخدم</button></form></article>)}</div></section></main>;
}
