do $$
declare
  v_sector uuid;
begin
  insert into public.sectors (
    slug,name_ar,description,accent,sort_order,is_active,seo_title,seo_description,visibility,audience,icon_key,metadata
  ) values (
    'rehabilitation-functioning','التأهيل والوظيفة والمشاركة',
    'قطاع مرجعي للتأهيل عبر مراحل الحياة يربط الوظيفة والنشاط والمشاركة والبيئة والتقييم والأهداف والقياس والأسرة والتقنيات المساعدة والمسارات السريرية والمجتمعية والمهنية.',
    '#0b8f92',27,true,
    'التأهيل والوظيفة والمشاركة | روافد',
    'مرجع عربي منظم للتأهيل والوظيفة والمشاركة: ICF والتقييم والأهداف والقياس وفريق التأهيل والأسرة والتقنيات المساعدة والتأهيل العصبي والمهني والمجتمعي.',
    'public',array['الأشخاص','الأسر','مقدمو الرعاية','المختصون','الطلبة','منسقو الخدمات'],'accessibility',
    jsonb_build_object('program','rehabilitation_functioning','taxonomy_version',1,'created_by','rawafid','editorial_scope','rehabilitation-functioning-participation')
  ) on conflict (slug) do update set
    name_ar=excluded.name_ar,description=excluded.description,accent=excluded.accent,sort_order=excluded.sort_order,
    is_active=true,seo_title=excluded.seo_title,seo_description=excluded.seo_description,visibility='public',
    audience=excluded.audience,icon_key=excluded.icon_key,metadata=public.sectors.metadata || excluded.metadata,updated_at=now()
  returning id into v_sector;

  insert into public.categories(sector_id,parent_id,slug,name_ar,description,sort_order,is_active,seo_title,seo_description,visibility,audience,icon_key,metadata)
  values
    (v_sector,null,'rehabilitation-foundations','أسس التأهيل والوظيفة','المفهوم الحديث للتأهيل وICF والتقييم والأهداف والخطة المتمركزة حول الشخص والوظيفة والمشاركة.',10,true,'أسس التأهيل والوظيفة والمشاركة','مدخل علمي إلى التأهيل وICF والتقييم الوظيفي والأهداف والمشاركة والعوامل البيئية.','public',array['الأشخاص','الأسر','المختصون','الطلبة'],'foundation',jsonb_build_object('program','rehabilitation_functioning','group','foundations')),
    (v_sector,null,'rehabilitation-service-pathways','مسارات وخدمات التأهيل','من الإحالة والتقييم إلى المستشفى والعيادة والمنزل والمدرسة والعمل والمجتمع واستمرارية الرعاية.',20,true,'مسارات وخدمات التأهيل','مسارات عملية لتنظيم خدمات التأهيل والإحالة والانتقالات والاستمرارية عبر بيئات الرعاية والحياة.','public',array['الأشخاص','الأسر','المختصون','منسقو الخدمات'],'pathway',jsonb_build_object('program','rehabilitation_functioning','group','service_pathways')),
    (v_sector,null,'rehabilitation-professions','مهن وفريق التأهيل','أدوار العلاج الطبيعي والوظيفي والنطق واللغة والبلع وطب التأهيل والتمريض وعلم النفس والخدمة الاجتماعية والأطراف والأجهزة وغيرها.',30,true,'مهن وفريق التأهيل','دليل أدوار فريق التأهيل متعدد التخصصات وكيفية التنسيق والإحالة حول أهداف الشخص.','public',array['الأشخاص','الأسر','المختصون','الطلبة'],'team',jsonb_build_object('program','rehabilitation_functioning','group','professions')),
    (v_sector,null,'rehabilitation-measurement-outcomes','القياس ونتائج التأهيل','اختيار مقاييس الأداء والاستقلال والحركة والمشاركة وجودة الحياة وPROMs وGoal Attainment ومتابعة التغير.',40,true,'القياس ونتائج التأهيل','مرجع لقياس نتائج التأهيل واختيار الأدوات وتفسير التغير وربط القياس بالقرارات والخطة.','public',array['المختصون','الأشخاص','الأسر','الطلبة'],'measurement',jsonb_build_object('program','rehabilitation_functioning','group','measurement')),
    (v_sector,null,'neurological-rehabilitation','التأهيل العصبي','مسارات السكتة وباركنسون وإصابات الدماغ والحبل الشوكي والشلل الدماغي والتصلب المتعدد والخرف وغيرها.',50,true,'التأهيل العصبي','التأهيل العصبي للوظيفة والحركة والتواصل والإدراك والمشاركة عبر الحالات العصبية.','public',array['الأشخاص','الأسر','المختصون'],'brain',jsonb_build_object('program','rehabilitation_functioning','group','neurological')),
    (v_sector,null,'musculoskeletal-rehabilitation','التأهيل العضلي الهيكلي','آلام الظهر والفصال والالتهاب المفصلي والكسور والبتر والساركوبينيا والحركة بعد الإصابات والجراحة.',60,true,'التأهيل العضلي الهيكلي','التأهيل العضلي الهيكلي للحركة والوظيفة والألم والعودة للنشاط بعد الإصابات والحالات المزمنة والجراحة.','public',array['الأشخاص','الأسر','المختصون'],'mobility',jsonb_build_object('program','rehabilitation_functioning','group','musculoskeletal')),
    (v_sector,null,'cardiopulmonary-rehabilitation','التأهيل القلبي والرئوي','التأهيل بعد أمراض القلب ومع COPD والأمراض الرئوية، التمرين المراقب، الأعراض، النشاط والعودة للحياة.',70,true,'التأهيل القلبي والرئوي','مسارات التأهيل القلبي والرئوي وتحسين القدرة الوظيفية والمشاركة وإدارة الأعراض والعودة للنشاط.','public',array['الأشخاص','الأسر','المختصون'],'heart',jsonb_build_object('program','rehabilitation_functioning','group','cardiopulmonary')),
    (v_sector,null,'developmental-rehabilitation','التأهيل النمائي وطب الأطفال','التدخل المبكر والتأهيل النمائي والحركي والتواصلي والوظيفي للأطفال والعمل داخل الروتين والأسرة والمدرسة.',80,true,'التأهيل النمائي وطب الأطفال','مرجع للتدخل المبكر والتأهيل النمائي للأطفال والأسرة والتواصل والحركة والاستقلال والمشاركة.','public',array['الأطفال','الأسر','المختصون','المعلمون'],'child',jsonb_build_object('program','rehabilitation_functioning','group','developmental')),
    (v_sector,null,'sensory-rehabilitation','التأهيل السمعي والبصري والحسي','التأهيل السمعي والبصري، الوصول للتواصل والمعلومات، الأجهزة والتقنيات والتدريب الوظيفي والمشاركة.',90,true,'التأهيل السمعي والبصري والحسي','التأهيل السمعي والبصري والوصول والتواصل والتقنيات المساعدة والمشاركة في المدرسة والعمل والمجتمع.','public',array['الأشخاص','الأسر','المختصون','المعلمون'],'sensory',jsonb_build_object('program','rehabilitation_functioning','group','sensory')),
    (v_sector,null,'cancer-rehabilitation','التأهيل مع السرطان وبعده','الحفاظ على الوظيفة والنشاط أثناء وبعد علاج السرطان، التعب والحركة والمشاركة والآثار المتأخرة والعودة للحياة.',100,true,'التأهيل مع السرطان وبعده','التأهيل أثناء وبعد السرطان للحركة والوظيفة والتعب والمشاركة والعودة للتعلم والعمل والحياة اليومية.','public',array['الأشخاص','الأسر','المختصون'],'oncology',jsonb_build_object('program','rehabilitation_functioning','group','cancer')),
    (v_sector,null,'mental-health-psychosocial-rehabilitation','التأهيل النفسي والاجتماعي','التعافي الوظيفي والمشاركة والعلاقات والتعليم والعمل والسكن والدعم بعد الاضطرابات النفسية الشديدة أو المزمنة.',110,true,'التأهيل النفسي والاجتماعي','التأهيل النفسي والاجتماعي من الأعراض إلى التعافي والوظيفة والعمل والعلاقات والمشاركة المجتمعية.','public',array['الأشخاص','الأسر','المختصون'],'mental-health',jsonb_build_object('program','rehabilitation_functioning','group','psychosocial')),
    (v_sector,null,'adult-geriatric-rehabilitation','تأهيل البالغين وكبار السن','الوظيفة والاستقلال والوقاية من التدهور والتأهيل بعد المرض والإصابة والهشاشة وتعدد الأمراض لدى البالغين وكبار السن.',120,true,'تأهيل البالغين وكبار السن','التأهيل الوظيفي للبالغين وكبار السن والاستقلال والحركة والمشاركة مع الأمراض المزمنة والهشاشة.','public',array['البالغون','كبار السن','الأسر','المختصون'],'adult',jsonb_build_object('program','rehabilitation_functioning','group','adult_geriatric')),
    (v_sector,null,'assistive-technology-rehabilitation','التقنيات والأجهزة المساعدة','التقييم والاختيار والتجربة والتدريب والمتابعة والصيانة ومنع هجر التقنية المساعدة.',130,true,'التقنيات والأجهزة المساعدة في التأهيل','اختيار وتجربة وتدريب ومتابعة التقنيات والأجهزة المساعدة بما يخدم الوظيفة والمشاركة.','public',array['الأشخاص','الأسر','المختصون'],'technology',jsonb_build_object('program','rehabilitation_functioning','group','assistive_technology')),
    (v_sector,null,'family-rehabilitation','الأسرة والتأهيل','دور الأسرة والقرار المشترك وتدريب مقدمي الرعاية ورفاههم والاستقلال والانتقال ومراجعة الخطة دون تحويل المنزل إلى عيادة.',140,true,'الأسرة والتأهيل','دليل الأسرة في التأهيل: الشراكة وتدريب مقدمي الرعاية والاستقلال ورفاه الأسرة والقرار المشترك.','public',array['الأشخاص','الأسر','مقدمو الرعاية','المختصون'],'family',jsonb_build_object('program','rehabilitation_functioning','group','family')),
    (v_sector,null,'community-vocational-rehabilitation','التأهيل المجتمعي والتعليمي والمهني','المشاركة المجتمعية والتعليم والعمل والعودة إلى العمل والتكييفات والتوظيف المدعوم والنقل والسكن والاستقلال.',150,true,'التأهيل المجتمعي والتعليمي والمهني','التأهيل للمشاركة في المجتمع والتعليم والعمل والعودة إلى العمل والتكييفات والتوظيف المدعوم.','public',array['الأشخاص','الأسر','المختصون','أصحاب العمل','المعلمون'],'community',jsonb_build_object('program','rehabilitation_functioning','group','community_vocational')),
    (v_sector,null,'telerehabilitation','التأهيل عن بُعد','استخدام الفيديو والهاتف والأدوات الرقمية والهجين في التقييم والمتابعة والتدريب، مع حدود السلامة والخصوصية والوصول.',160,true,'التأهيل عن بُعد','التأهيل عن بُعد والهجين: الاستخدام المناسب والتقييم والمتابعة والتدريب والخصوصية والوصول.','public',array['الأشخاص','الأسر','المختصون'],'remote',jsonb_build_object('program','rehabilitation_functioning','group','telerehabilitation')),
    (v_sector,null,'emergency-rehabilitation','التأهيل في الطوارئ والنزاعات والكوارث','استمرارية التأهيل والأجهزة والحركة بعد الإصابات والنزوح والكوارث والنزاعات مع ربط الرعاية الحادة بالمجتمع.',170,true,'التأهيل في الطوارئ والنزاعات والكوارث','التأهيل المبكر واستمرارية الوظيفة والأجهزة والدعم في الطوارئ والكوارث والنزاعات والنزوح.','public',array['الأشخاص','الأسر','المختصون','المنظمات'],'emergency',jsonb_build_object('program','rehabilitation_functioning','group','emergency')),
    (v_sector,null,'rehabilitation-mena-jordan','التأهيل في الأردن والمنطقة العربية','مسارات الخدمات والمهن والحقوق والإحالة والوصول والمصطلحات في الأردن والمنطقة العربية اعتمادًا على المصادر المحلية الحالية.',180,true,'التأهيل في الأردن والمنطقة العربية','مرجع للخدمات والمهن والإحالة والحقوق والوصول إلى التأهيل في الأردن والمنطقة العربية وفق المصادر الحالية.','public',array['الأشخاص','الأسر','المختصون','المنظمات'],'map',jsonb_build_object('program','rehabilitation_functioning','group','mena_jordan'))
  on conflict (slug) do update set
    sector_id=excluded.sector_id,name_ar=excluded.name_ar,description=excluded.description,sort_order=excluded.sort_order,is_active=true,
    seo_title=excluded.seo_title,seo_description=excluded.seo_description,visibility='public',audience=excluded.audience,icon_key=excluded.icon_key,
    metadata=public.categories.metadata || excluded.metadata,updated_at=now();
end $$;
