alter table public.redirects
  add column if not exists note text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null;

alter table public.redirects drop constraint if exists redirects_source_format_check;
alter table public.redirects add constraint redirects_source_format_check check (length(source_path) between 1 and 1800 and left(source_path,1)='/' and left(source_path,2)<>'//' and position('?' in source_path)=0 and position('#' in source_path)=0 and position('://' in source_path)=0);
alter table public.redirects drop constraint if exists redirects_destination_format_check;
alter table public.redirects add constraint redirects_destination_format_check check (length(destination_path) between 1 and 1800 and left(destination_path,1)='/' and left(destination_path,2)<>'//' and position('?' in destination_path)=0 and position('#' in destination_path)=0 and position('://' in destination_path)=0 and destination_path<>source_path);
alter table public.redirects drop constraint if exists redirects_note_length_check;
alter table public.redirects add constraint redirects_note_length_check check (note is null or length(note)<=1000);
create index if not exists redirects_active_source_idx on public.redirects(source_path) where is_active=true;
create index if not exists audit_logs_entity_recent_idx on public.audit_logs(entity_type,created_at desc);
create index if not exists audit_logs_action_recent_idx on public.audit_logs(action,created_at desc);
create index if not exists audit_logs_created_recent_idx on public.audit_logs(created_at desc);
alter table public.specialists drop constraint if exists specialists_user_id_unique;
revoke insert,update,delete on public.redirects from authenticated;
grant select on public.redirects to anon,authenticated;

create or replace function private.validate_redirect_chain(p_source text,p_destination text,p_ignore_id uuid default null)
returns boolean language plpgsql stable security definer set search_path=''
as $$ declare v_current text:=p_destination; v_next text; v_depth integer:=0; begin if p_source is null or p_destination is null or p_source=p_destination then return false; end if; while v_depth<25 loop if v_current=p_source then return false; end if; select r.destination_path into v_next from public.redirects r where r.source_path=v_current and r.is_active=true and (p_ignore_id is null or r.id<>p_ignore_id) limit 1; if v_next is null then return true; end if; v_current:=v_next; v_next:=null; v_depth:=v_depth+1; end loop; return false; end; $$;

create or replace function private.admin_upsert_redirect(p_id uuid default null,p_source_path text default null,p_destination_path text default null,p_status_code integer default 301,p_is_active boolean default true,p_note text default null)
returns uuid language plpgsql security definer set search_path=''
as $$ declare v_uid uuid:=private.require_active_user(); v_source text:=trim(coalesce(p_source_path,'')); v_destination text:=trim(coalesce(p_destination_path,'')); v_note text:=nullif(trim(left(coalesce(p_note,''),1000)),''); v_id uuid; v_before jsonb; begin if not private.is_admin() then raise exception 'admin required'; end if; if length(v_source)<1 or length(v_source)>1800 or left(v_source,1)<>'/' or left(v_source,2)='//' or position('?' in v_source)>0 or position('#' in v_source)>0 or position('://' in v_source)>0 then raise exception 'invalid source path'; end if; if length(v_destination)<1 or length(v_destination)>1800 or left(v_destination,1)<>'/' or left(v_destination,2)='//' or position('?' in v_destination)>0 or position('#' in v_destination)>0 or position('://' in v_destination)>0 then raise exception 'invalid destination path'; end if; if v_source=v_destination then raise exception 'redirect cannot target itself'; end if; if p_status_code not in (301,302,307,308) then raise exception 'invalid redirect status'; end if; if not private.validate_redirect_chain(v_source,v_destination,p_id) then raise exception 'redirect loop detected'; end if; if p_id is null then insert into public.redirects(source_path,destination_path,status_code,is_active,note,created_by,updated_by) values(v_source,v_destination,p_status_code,p_is_active,v_note,v_uid,v_uid) returning id into v_id; insert into public.audit_logs(actor_id,entity_type,entity_id,action,after_data) values(v_uid,'redirect',v_id::text,'redirect_created',jsonb_build_object('source_path',v_source,'destination_path',v_destination,'status_code',p_status_code,'is_active',p_is_active)); else select jsonb_build_object('source_path',r.source_path,'destination_path',r.destination_path,'status_code',r.status_code,'is_active',r.is_active) into v_before from public.redirects r where r.id=p_id for update; if v_before is null then raise exception 'redirect not found'; end if; update public.redirects set source_path=v_source,destination_path=v_destination,status_code=p_status_code,is_active=p_is_active,note=v_note,updated_by=v_uid,updated_at=now() where id=p_id returning id into v_id; insert into public.audit_logs(actor_id,entity_type,entity_id,action,before_data,after_data) values(v_uid,'redirect',v_id::text,'redirect_updated',v_before,jsonb_build_object('source_path',v_source,'destination_path',v_destination,'status_code',p_status_code,'is_active',p_is_active)); end if; return v_id; exception when unique_violation then raise exception 'source path already exists'; end; $$;

create or replace function private.admin_delete_redirect(p_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ declare v_uid uuid:=private.require_active_user(); v_before jsonb; begin if not private.is_admin() then raise exception 'admin required'; end if; select jsonb_build_object('source_path',source_path,'destination_path',destination_path,'status_code',status_code,'is_active',is_active) into v_before from public.redirects where id=p_id for update; if v_before is null then raise exception 'redirect not found'; end if; delete from public.redirects where id=p_id; insert into public.audit_logs(actor_id,entity_type,entity_id,action,before_data) values(v_uid,'redirect',p_id::text,'redirect_deleted',v_before); return true; end; $$;
create or replace function private.admin_list_redirects(p_query text default null,p_limit integer default 200,p_offset integer default 0) returns table(id uuid,source_path text,destination_path text,status_code integer,is_active boolean,note text,created_at timestamptz,updated_at timestamptz) language plpgsql stable security definer set search_path='' as $$ declare v_q text:=nullif(trim(left(coalesce(p_query,''),200)),''); begin if not private.is_admin() then raise exception 'admin required'; end if; return query select r.id,r.source_path,r.destination_path,r.status_code,r.is_active,r.note,r.created_at,r.updated_at from public.redirects r where v_q is null or r.source_path ilike '%'||v_q||'%' or r.destination_path ilike '%'||v_q||'%' order by r.updated_at desc,r.source_path limit greatest(1,least(coalesce(p_limit,200),500)) offset greatest(0,coalesce(p_offset,0)); end; $$;
create or replace function private.admin_audit_log(p_entity_type text default null,p_action text default null,p_actor_id uuid default null,p_query text default null,p_from timestamptz default null,p_to timestamptz default null,p_limit integer default 200,p_offset integer default 0) returns table(id bigint,actor_id uuid,actor_name text,entity_type text,entity_id text,action text,before_data jsonb,after_data jsonb,created_at timestamptz) language plpgsql stable security definer set search_path='' as $$ declare v_entity text:=nullif(trim(left(coalesce(p_entity_type,''),120)),''); v_action text:=nullif(trim(left(coalesce(p_action,''),160)),''); v_q text:=nullif(trim(left(coalesce(p_query,''),200)),''); begin if not private.is_admin() then raise exception 'admin required'; end if; return query select a.id,a.actor_id,p.display_name,a.entity_type,a.entity_id,a.action,a.before_data,a.after_data,a.created_at from public.audit_logs a left join public.profiles p on p.id=a.actor_id where (v_entity is null or a.entity_type=v_entity) and (v_action is null or a.action=v_action) and (p_actor_id is null or a.actor_id=p_actor_id) and (p_from is null or a.created_at>=p_from) and (p_to is null or a.created_at<=p_to) and (v_q is null or coalesce(a.entity_id,'') ilike '%'||v_q||'%' or a.action ilike '%'||v_q||'%' or a.entity_type ilike '%'||v_q||'%' or coalesce(p.display_name,'') ilike '%'||v_q||'%') order by a.created_at desc,a.id desc limit greatest(1,least(coalesce(p_limit,200),500)) offset greatest(0,coalesce(p_offset,0)); end; $$;

revoke all on function private.validate_redirect_chain(text,text,uuid),private.admin_upsert_redirect(uuid,text,text,integer,boolean,text),private.admin_delete_redirect(uuid),private.admin_list_redirects(text,integer,integer),private.admin_audit_log(text,text,uuid,text,timestamptz,timestamptz,integer,integer) from public;
grant execute on function private.validate_redirect_chain(text,text,uuid),private.admin_upsert_redirect(uuid,text,text,integer,boolean,text),private.admin_delete_redirect(uuid),private.admin_list_redirects(text,integer,integer),private.admin_audit_log(text,text,uuid,text,timestamptz,timestamptz,integer,integer) to authenticated;
create or replace function public.admin_upsert_redirect(p_id uuid default null,p_source_path text default null,p_destination_path text default null,p_status_code integer default 301,p_is_active boolean default true,p_note text default null) returns uuid language sql security invoker set search_path='' as $$ select private.admin_upsert_redirect(p_id,p_source_path,p_destination_path,p_status_code,p_is_active,p_note); $$;
create or replace function public.admin_delete_redirect(p_id uuid) returns boolean language sql security invoker set search_path='' as $$ select private.admin_delete_redirect(p_id); $$;
create or replace function public.admin_list_redirects(p_query text default null,p_limit integer default 200,p_offset integer default 0) returns table(id uuid,source_path text,destination_path text,status_code integer,is_active boolean,note text,created_at timestamptz,updated_at timestamptz) language sql stable security invoker set search_path='' as $$ select * from private.admin_list_redirects(p_query,p_limit,p_offset); $$;
create or replace function public.admin_audit_log(p_entity_type text default null,p_action text default null,p_actor_id uuid default null,p_query text default null,p_from timestamptz default null,p_to timestamptz default null,p_limit integer default 200,p_offset integer default 0) returns table(id bigint,actor_id uuid,actor_name text,entity_type text,entity_id text,action text,before_data jsonb,after_data jsonb,created_at timestamptz) language sql stable security invoker set search_path='' as $$ select * from private.admin_audit_log(p_entity_type,p_action,p_actor_id,p_query,p_from,p_to,p_limit,p_offset); $$;
revoke all on function public.admin_upsert_redirect(uuid,text,text,integer,boolean,text),public.admin_delete_redirect(uuid),public.admin_list_redirects(text,integer,integer),public.admin_audit_log(text,text,uuid,text,timestamptz,timestamptz,integer,integer) from public,anon;
grant execute on function public.admin_upsert_redirect(uuid,text,text,integer,boolean,text),public.admin_delete_redirect(uuid),public.admin_list_redirects(text,integer,integer),public.admin_audit_log(text,text,uuid,text,timestamptz,timestamptz,integer,integer) to authenticated,service_role;
