-- Retired data seed.
-- The original version of this migration was rejected by content_release_gate_v6
-- because its editorial body was below the V6 word-count contract.
-- The corrected page is now materialized and verified in Supabase under:
--   public.content.slug = 'circular-causality-family-systems'
-- It passed V6 with 2553 Arabic words, 26 H2, 4 H3, 8 structured FAQs,
-- 5 authoritative references, robots_index=true, and status='published'.
--
-- This file intentionally performs no data mutation so a future migration runner
-- cannot replay the stale seed and overwrite the verified production article.
select 1;
