-- Retired data seed.
-- The original version of this migration was rejected by content_release_gate_v6
-- because its editorial body was below the V6 word-count contract and contained
-- a body phrase that matched the site's centralized warning-language guard.
-- The corrected page is now materialized and verified in Supabase under:
--   public.content.slug = 'family-feedback-loops'
-- It passed V6 with 2624 Arabic words, 29 H2, 4 H3, 8 structured FAQs,
-- 5 authoritative references, robots_index=true, and status='published'.
--
-- This file intentionally performs no data mutation so a future migration runner
-- cannot replay the stale seed and overwrite the verified production article.
select 1;
