-- Production hardening for Rawafid community publication and moderation.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

alter table public.community_posts add column if not exists comments_locked boolean not null default false;
alter table public.community_posts add column if not exists moderation_note text;
alter table public.community_reports add column if not exists resolution_note text;
create unique index if not exists community_reports_unique_post_reporter_idx on public.community_reports(reporter_id,post_id) where post_id is not null and status in ('open','reviewing');
create unique index if not exists community_reports_unique_comment_reporter_idx on public.community_reports(reporter_id,comment_id) where comment_id is not null and status in ('open','reviewing');

create or replace function private.community_account_confirmed() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from auth.users u where u.id=auth.uid() and u.deleted_at is null and coalesce(u.email_confirmed_at,u.phone_confirmed_at) is not null and coalesce((u.raw_app_meta_data->>'provider')<>'anonymous',true)) $$;
revoke all on function private.community_account_confirmed() from public; grant execute on function private.community_account_confirmed() to authenticated;
create or replace function private.community_post_rate_ok() returns boolean language sql stable security invoker set search_path='' as $$ select count(*)<5 from public.community_posts p where p.author_id=auth.uid() and p.created_at>now()-interval '1 hour' $$;
create or replace function private.community_comment_rate_ok() returns boolean language sql stable security invoker set search_path='' as $$ select count(*)<30 from public.community_comments c where c.author_id=auth.uid() and c.created_at>now()-interval '1 hour' $$;
create or replace function private.community_contains_sensitive_contact(value text) returns boolean language sql immutable security invoker set search_path='' as $$ select coalesce(value,'') ~* '([[:alnum:]._%+-]+@[[:alnum:].-]+\.[A-Za-z]{2,}|(?:\+?[0-9][0-9 ()-]{7,}[0-9])|(?:واتساب|whatsapp|رقم الهاتف|رقم الجوال|اتصل بي|تواصل معي)[[:space:]:-]*[0-9+])' $$;
revoke all on function private.community_post_rate_ok(),private.community_comment_rate_ok(),private.community_contains_sensitive_contact(text) from public;
grant execute on function private.community_post_rate_ok(),private.community_comment_rate_ok(),private.community_contains_sensitive_contact(text) to authenticated;

create or replace function public.community_post_defaults() returns trigger language plpgsql set search_path='' as $$ declare room_mode text;sensitive boolean;begin new.title=btrim(new.title);new.summary=btrim(new.summary);new.body=btrim(new.body);select r.moderation_mode into room_mode from public.community_rooms r where r.id=new.room_id;sensitive:=private.community_contains_sensitive_contact(new.title||' '||new.summary||' '||new.body);if new.status='published' and (room_mode='pre_publish' or sensitive) then new.status='pending';new.moderation_state='needs_review';new.seo_indexable=false;new.published_at=null;if sensitive and coalesce(new.moderation_note,'')='' then new.moderation_note='Automated privacy/contact-data review';end if;elsif new.status='published' and new.published_at is null then new.published_at=now();end if;if new.seo_title is null then new.seo_title=left(new.title||' | شاركنا تجربتك - منصة روافد',65);end if;if new.seo_description is null then new.seo_description=left(new.summary,170);end if;if char_length(new.body)<350 or cardinality(new.topics)=0 or new.status<>'published' or new.moderation_state in('restricted','removed') then new.seo_indexable=false;end if;new.search_vector=setweight(to_tsvector('simple',coalesce(new.title,'')),'A')||setweight(to_tsvector('simple',coalesce(new.summary,'')),'B')||setweight(to_tsvector('simple',coalesce(new.body,'')),'C')||setweight(to_tsvector('simple',array_to_string(new.topics,' ')),'B')||setweight(to_tsvector('simple',array_to_string(new.keywords,' ')),'B');return new;end $$;

create or replace function public.community_comment_guard() returns trigger language plpgsql set search_path='' as $$ declare parent_post uuid;locked boolean;begin new.body=btrim(new.body);select p.comments_locked into locked from public.community_posts p where p.id=new.post_id;if coalesce(locked,false) then raise exception 'comments_locked';end if;if new.parent_id is not null then select c.post_id into parent_post from public.community_comments c where c.id=new.parent_id;if parent_post is distinct from new.post_id then raise exception 'parent_comment_post_mismatch';end if;end if;if private.community_contains_sensitive_contact(new.body) then new.status='hidden';end if;return new;end $$;
drop trigger if exists community_comment_guard_trigger on public.community_comments;create trigger community_comment_guard_trigger before insert or update of body,parent_id,post_id on public.community_comments for each row execute function public.community_comment_guard();

create or replace function public.community_sync_post_comment_count() returns trigger language plpgsql set search_path='' as $$ begin if tg_op='INSERT' and new.status='published' then update public.community_posts set comments_count=comments_count+1 where id=new.post_id;elsif tg_op='DELETE' and old.status='published' then update public.community_posts set comments_count=greatest(0,comments_count-1) where id=old.post_id;elsif tg_op='UPDATE' and old.status is distinct from new.status then if old.status='published' then update public.community_posts set comments_count=greatest(0,comments_count-1) where id=old.post_id;end if;if new.status='published' then update public.community_posts set comments_count=comments_count+1 where id=new.post_id;end if;end if;return coalesce(new,old);end $$;
drop trigger if exists community_comment_count_trigger on public.community_comments;create trigger community_comment_count_trigger after insert or delete or update of status on public.community_comments for each row execute function public.community_sync_post_comment_count();
create or replace function public.community_sync_post_reaction_count() returns trigger language plpgsql set search_path='' as $$ begin if tg_op='INSERT' then update public.community_posts set useful_count=useful_count+1 where id=new.post_id;elsif tg_op='DELETE' then update public.community_posts set useful_count=greatest(0,useful_count-1) where id=old.post_id;end if;return coalesce(new,old);end $$;
drop trigger if exists community_post_reaction_count_trigger on public.community_post_reactions;create trigger community_post_reaction_count_trigger after insert or delete on public.community_post_reactions for each row execute function public.community_sync_post_reaction_count();
create or replace function public.community_sync_comment_reaction_count() returns trigger language plpgsql set search_path='' as $$ begin if tg_op='INSERT' then update public.community_comments set useful_count=useful_count+1 where id=new.comment_id;elsif tg_op='DELETE' then update public.community_comments set useful_count=greatest(0,useful_count-1) where id=old.comment_id;end if;return coalesce(new,old);end $$;
drop trigger if exists community_comment_reaction_count_trigger on public.community_comment_reactions;create trigger community_comment_reaction_count_trigger after insert or delete on public.community_comment_reactions for each row execute function public.community_sync_comment_reaction_count();
create or replace function public.community_sync_room_post_count() returns trigger language plpgsql set search_path='' as $$ begin if tg_op='INSERT' and new.status='published' then update public.community_rooms set post_count=post_count+1 where id=new.room_id;elsif tg_op='DELETE' and old.status='published' then update public.community_rooms set post_count=greatest(0,post_count-1) where id=old.room_id;elsif tg_op='UPDATE' then if old.status='published' and (new.status<>'published' or new.room_id<>old.room_id) then update public.community_rooms set post_count=greatest(0,post_count-1) where id=old.room_id;end if;if new.status='published' and (old.status<>'published' or new.room_id<>old.room_id) then update public.community_rooms set post_count=post_count+1 where id=new.room_id;end if;end if;return coalesce(new,old);end $$;
drop trigger if exists community_room_post_count_trigger on public.community_posts;create trigger community_room_post_count_trigger after insert or delete or update of status,room_id on public.community_posts for each row execute function public.community_sync_room_post_count();
create or replace function public.community_sync_room_member_count() returns trigger language plpgsql set search_path='' as $$ begin if tg_op='INSERT' then update public.community_rooms set member_count=member_count+1 where id=new.room_id;elsif tg_op='DELETE' then update public.community_rooms set member_count=greatest(0,member_count-1) where id=old.room_id;end if;return coalesce(new,old);end $$;
drop trigger if exists community_room_member_count_trigger on public.community_room_members;create trigger community_room_member_count_trigger after insert or delete on public.community_room_members for each row execute function public.community_sync_room_member_count();

drop policy if exists community_posts_create on public.community_posts;create policy community_posts_create on public.community_posts for insert to authenticated with check(author_id=auth.uid() and status in('draft','pending','published') and moderation_state in('clean','needs_review') and private.community_account_confirmed() and private.community_post_rate_ok() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active) and exists(select 1 from public.community_rooms r where r.id=room_id and r.status='active'));
drop policy if exists community_comments_create on public.community_comments;create policy community_comments_create on public.community_comments for insert to authenticated with check(author_id=auth.uid() and status in('published','hidden') and private.community_account_confirmed() and private.community_comment_rate_ok() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active) and exists(select 1 from public.community_posts p where p.id=post_id and p.status='published' and not p.comments_locked));
drop policy if exists community_post_reactions_write on public.community_post_reactions;create policy community_post_reactions_write on public.community_post_reactions for insert to authenticated with check(user_id=auth.uid() and private.community_account_confirmed() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active));
drop policy if exists community_comment_reactions_write on public.community_comment_reactions;create policy community_comment_reactions_write on public.community_comment_reactions for insert to authenticated with check(user_id=auth.uid() and private.community_account_confirmed() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active));
drop policy if exists community_reports_create on public.community_reports;create policy community_reports_create on public.community_reports for insert to authenticated with check(reporter_id=auth.uid() and status='open' and private.community_account_confirmed());
drop policy if exists community_members_join on public.community_room_members;create policy community_members_join on public.community_room_members for insert to authenticated with check(user_id=auth.uid() and membership_role='member' and private.community_account_confirmed() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_active));

update public.community_posts p set comments_count=(select count(*) from public.community_comments c where c.post_id=p.id and c.status='published'),useful_count=(select count(*) from public.community_post_reactions r where r.post_id=p.id);
update public.community_comments c set useful_count=(select count(*) from public.community_comment_reactions r where r.comment_id=c.id);
update public.community_rooms r set post_count=(select count(*) from public.community_posts p where p.room_id=r.id and p.status='published'),member_count=(select count(*) from public.community_room_members m where m.room_id=r.id);
