with pairs(a,b) as (values
('traumatic-brain-injury-rehabilitation-guide','post-traumatic-amnesia-recovery-guide'),
('traumatic-brain-injury-rehabilitation-guide','attention-after-acquired-brain-injury'),
('traumatic-brain-injury-rehabilitation-guide','processing-speed-after-acquired-brain-injury'),
('traumatic-brain-injury-rehabilitation-guide','memory-after-acquired-brain-injury'),
('traumatic-brain-injury-rehabilitation-guide','executive-dysfunction-self-awareness-after-abi'),
('traumatic-brain-injury-rehabilitation-guide','cognitive-communication-after-abi'),
('traumatic-brain-injury-rehabilitation-guide','fatigue-after-acquired-brain-injury'),
('traumatic-brain-injury-rehabilitation-guide','sleep-after-acquired-brain-injury'),
('traumatic-brain-injury-rehabilitation-guide','emotional-behavioural-changes-after-abi'),
('traumatic-brain-injury-rehabilitation-guide','mental-health-after-acquired-brain-injury'),
('traumatic-brain-injury-rehabilitation-guide','family-caregiver-support-after-abi'),
('traumatic-brain-injury-rehabilitation-guide','return-to-education-after-abi'),
('traumatic-brain-injury-rehabilitation-guide','return-to-work-after-abi'),
('traumatic-brain-injury-rehabilitation-guide','identity-adjustment-after-brain-injury'),
('traumatic-brain-injury-rehabilitation-guide','relationships-intimacy-after-abi'),
('traumatic-brain-injury-rehabilitation-guide','driving-independence-community-participation-after-abi'),
('stroke-rehabilitation-guide','attention-after-acquired-brain-injury'),
('stroke-rehabilitation-guide','processing-speed-after-acquired-brain-injury'),
('stroke-rehabilitation-guide','memory-after-acquired-brain-injury'),
('stroke-rehabilitation-guide','executive-dysfunction-self-awareness-after-abi'),
('stroke-rehabilitation-guide','cognitive-communication-after-abi'),
('stroke-rehabilitation-guide','fatigue-after-acquired-brain-injury'),
('stroke-rehabilitation-guide','sleep-after-acquired-brain-injury'),
('stroke-rehabilitation-guide','emotional-behavioural-changes-after-abi'),
('stroke-rehabilitation-guide','mental-health-after-acquired-brain-injury'),
('stroke-rehabilitation-guide','family-caregiver-support-after-abi'),
('stroke-rehabilitation-guide','return-to-work-after-abi'),
('stroke-rehabilitation-guide','driving-independence-community-participation-after-abi'),
('rehabilitation-care-pathway','family-caregiver-support-after-abi'),
('rehabilitation-care-pathway','return-to-education-after-abi'),
('rehabilitation-care-pathway','return-to-work-after-abi'),
('legacy-family-guide-conditions-acquired-brain-injury','return-to-education-after-abi'),
('legacy-family-guide-conditions-acquired-brain-injury','family-caregiver-support-after-abi'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','post-traumatic-amnesia-recovery-guide'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','attention-after-acquired-brain-injury'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','processing-speed-after-acquired-brain-injury'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','memory-after-acquired-brain-injury'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','executive-dysfunction-self-awareness-after-abi'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','cognitive-communication-after-abi'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','fatigue-after-acquired-brain-injury'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','sleep-after-acquired-brain-injury'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','emotional-behavioural-changes-after-abi'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','mental-health-after-acquired-brain-injury'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','family-caregiver-support-after-abi'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','return-to-education-after-abi'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','return-to-work-after-abi'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','identity-adjustment-after-brain-injury'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','relationships-intimacy-after-abi'),
('abi-vs-tbi-stroke-hypoxic-injury-guide','driving-independence-community-participation-after-abi'),
('inclusive-school-leadership-implementation','family-engagement-inclusive-education-system'),
('inclusive-school-leadership-implementation','inclusive-academic-practices-schoolwide'),
('inclusive-school-leadership-implementation','inclusive-social-emotional-behavioral-supports-schoolwide'),
('inclusive-school-leadership-implementation','inclusive-assessment-governance-school-system'),
('inclusive-school-leadership-implementation','multidisciplinary-collaboration-inclusive-schools'),
('inclusive-school-leadership-implementation','accessibility-assistive-technology-school-system'),
('inclusive-school-leadership-implementation','inclusive-education-implementation-fidelity'),
('inclusive-school-leadership-implementation','inclusive-education-quality-indicators'),
('inclusive-school-leadership-implementation','teacher-professional-learning-inclusive-practice'),
('inclusive-school-leadership-implementation','inclusive-education-data-monitoring-improvement'),
('inclusive-school-leadership-implementation','culturally-responsive-inclusive-education-arab-context'),
('inclusive-school-self-evaluation','inclusive-education-quality-indicators'),
('inclusive-school-self-evaluation','inclusive-education-data-monitoring-improvement'),
('inclusive-school-self-evaluation','inclusive-education-implementation-fidelity'),
('inclusive-school-self-evaluation','inclusive-school-leadership-implementation'),
('legacy-special-needs-guides-education-inclusive-assessment-school','inclusive-assessment-governance-school-system'),
('legacy-special-needs-guides-education-inclusive-assessment-school','inclusive-academic-practices-schoolwide'),
('legacy-special-needs-guides-education-inclusive-assessment-school','inclusive-education-data-monitoring-improvement'),
('school-team-assistive-technology-training','accessibility-assistive-technology-school-system'),
('school-team-assistive-technology-training','inclusive-academic-practices-schoolwide'),
('school-team-assistive-technology-training','inclusive-school-leadership-implementation'),
('intervention-fidelity-education','inclusive-education-implementation-fidelity'),
('intervention-fidelity-education','inclusive-education-quality-indicators'),
('intervention-fidelity-education','inclusive-education-data-monitoring-improvement'),
('culturally-responsive-family-partnership','culturally-responsive-inclusive-education-arab-context'),
('culturally-responsive-family-partnership','family-engagement-inclusive-education-system'),
('culturally-responsive-family-partnership','inclusive-school-leadership-implementation')
), normalized as (
  select distinct least(a,b) a, greatest(a,b) b from pairs where a<>b
), directed as (
  select a source_slug,b target_slug from normalized
  union all
  select b,a from normalized
)
insert into public.content_relations(source_content_id,target_content_id,relation_type)
select s.id,t.id,'related'
from directed d
join public.content s on s.slug=d.source_slug and s.status='published'
join public.content t on t.slug=d.target_slug and t.status='published'
on conflict do nothing;