import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import KidsLabPrintButton from '@/components/kids-lab-print-button';
import { buildSeoMetadata } from '@/lib/seo';
import { getMathLogicActivity,mathLogicActivities } from '@/lib/capabilities/math-logic-lab';
import styles from '../../../kids-lab.module.css';
type Props={params:Promise<{series:string;activity:string}>};
export function generateStaticParams(){return mathLogicActivities.map(a=>({series:a.seriesSlug,activity:a.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {series,activity}=await params;const a=getMathLogicActivity(series,activity);if(!a)return{};return buildSeoMetadata({title:`${a.title} | نشاط رياضي منطقي قابل للطباعة`,description:a.purpose,path:`/capabilities/kids-lab/math-logic/${series}/${activity}/`,index:true,keywords:[a.seriesTitle,'رياضيات للأطفال','منطق بصري','أوراق عمل قابلة للطباعة']});}
export default async function ActivityPage({params}:Props){const {series,activity}=await params;const a=getMathLogicActivity(series,activity);if(!a)notFound();const idx=mathLogicActivities.findIndex(x=>x.seriesSlug===series&&x.slug===activity);const prev=idx>0&&mathLogicActivities[idx-1].seriesSlug===series?mathLogicActivities[idx-1]:null;const next=idx>=0&&idx<mathLogicActivities.length-1&&mathLogicActivities[idx+1].seriesSlug===series?mathLogicActivities[idx+1]:null;const image=`/capabilities/kids-lab/math-logic/${series}/${activity}/image/`;return <><SiteHeader/><main className={styles.shell}><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/math-logic/">الرياضيات والمنطق</Link><span>/</span><Link href={`/capabilities/kids-lab/math-logic/${series}/`}>{a.seriesTitle}</Link><span>/</span><span>{a.label}</span></nav><section className={styles.hero}><span className={styles.kicker}>السلسلة {a.seriesNumber} · المستوى {a.level}</span><h1>{a.title}</h1><p className={styles.lead}>{a.purpose}</p><div className={styles.metaRow}><span className={styles.metaChip}>{a.age}</span><span className={styles.metaChip}>{a.duration}</span><span className={styles.metaChip}>{a.kind==='test'?'اختبار إتقان':'تدريب'}</span></div></section><section className={styles.section}><div className={styles.previewCard}><img src={image} alt={a.title}/></div><div className={styles.actions}><KidsLabPrintButton/><a className={styles.secondaryButton} href={image} download={`${series}-${activity}.svg`}>تنزيل SVG</a></div></section><section className={styles.section}><div className={styles.infoGrid}><article className={styles.infoCard}><h2>التعليمات</h2><p>{a.instruction}</p></article><article className={styles.infoCard}><h2>هدف المستوى</h2><p>{a.progression}</p></article><article className={styles.infoCard}><h2>ما الذي نراقبه؟</h2><p>{a.observation}</p></article><article className={styles.infoCard}><h2>إتقان المهمة</h2><p>{a.mastery}</p></article></div>{a.kind==='test'&&<div className={styles.note}><strong>تنبيه:</strong> هذا اختبار إتقان تعليمي داخل السلسلة، وليس اختبار ذكاء أو تحصيل معياري أو أداة تشخيصية.</div>}</section><section className={styles.section}><div className={styles.actions}>{prev&&<Link className={styles.secondaryButton} href={`/capabilities/kids-lab/math-logic/${series}/${prev.slug}/`}>السابق</Link>}<Link className={styles.secondaryButton} href={`/capabilities/kids-lab/math-logic/${series}/`}>السلسلة</Link>{next&&<Link className={styles.primaryButton} href={`/capabilities/kids-lab/math-logic/${series}/${next.slug}/`}>التالي</Link>}</div></section></main><SiteFooter/></>}
