import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import KidsLabPrintButton from '@/components/kids-lab-print-button';
import { emotionalRegulationActivities,getEmotionalRegulationActivity } from '@/lib/capabilities/emotional-regulation-lab';
import styles from '../../../kids-lab.module.css';
type Props={params:Promise<{series:string;activity:string}>};
export function generateStaticParams(){return emotionalRegulationActivities.map(a=>({series:a.seriesSlug,activity:a.slug}));}
export default async function Page({params}:Props){const {series,activity}=await params;const a=getEmotionalRegulationActivity(series,activity);if(!a)notFound();const image=`/capabilities/kids-lab/emotional-regulation/${series}/${activity}/image/`;return <><SiteHeader/><main className={styles.shell}><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/emotional-regulation/">التنظيم الانفعالي</Link><span>/</span><Link href={`/capabilities/kids-lab/emotional-regulation/${series}/`}>{a.seriesTitle}</Link><span>/</span><span>{a.label}</span></nav><section className={styles.hero}><span className={styles.kicker}>السلسلة {a.seriesNumber} · المستوى {a.level}</span><h1>{a.title}</h1><p className={styles.lead}>{a.instruction}</p><div className={styles.metaRow}><span className={styles.metaChip}>{a.age}</span><span className={styles.metaChip}>{a.duration}</span><span className={styles.metaChip}>{a.kind==='test'?'اختبار إتقان':'تدريب'}</span></div></section><section className={styles.section}><div className={styles.previewFrame}><img src={image} alt={a.title}/></div><div className={styles.actions}><KidsLabPrintButton/><a className={styles.secondaryButton} href={image} download={`${a.seriesSlug}-${a.slug}.svg`}>تنزيل SVG</a></div></section><section className={styles.section}><div className={styles.infoGrid}><article className={styles.infoCard}><h2>الهدف</h2><p>{a.purpose}</p></article><article className={styles.infoCard}><h2>التدرج</h2><p>{a.progression}</p></article><article className={styles.infoCard}><h2>ما نلاحظه</h2><p>{a.observation}</p></article><article className={styles.infoCard}><h2>معيار الإتقان</h2><p>{a.mastery}</p></article></div>{a.kind==='test'&&<div className={styles.note}><strong>تنبيه:</strong> هذا اختبار إتقان للمهمة وليس اختبارًا نفسيًا معياريًا أو تشخيصًا. في تقدير شدة الشعور أو إشارات الجسم، تُحترم خبرة الطفل الذاتية ولا تُفرض «إجابة صحيحة» من الخارج.</div>}</section></main><SiteFooter/></>}
