import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { buildSeoMetadata } from '@/lib/seo';

export const metadata = buildSeoMetadata({ title:'أفكار خارج الصندوق | لنرتقي بقدراتهم', description:'أفكار عملية مبتكرة لاختبار الحواجز وكشف القدرة في التعلم والتواصل والتنظيم والطاقة والحركة والمشاركة، مع مقياس واضح وقاعدة توقف.', path:'/capabilities/ideas/', index:true, keywords:['أفكار مبتكرة','التربية الخاصة','التكييفات','اكتشاف القدرات','الدعم الوظيفي'] });

const ideas=[
['اختبر المعرفة بلا شرط الكتابة','قد تختلط معرفة الشخص بمتطلبات الكتابة أو الحركة الدقيقة.','أعد المهمة نفسها مع إجابة شفوية أو اختيار بصري أو وسيلة تواصل مع إبقاء مستوى السؤال ثابتًا.','الدقة، زمن البدء، المساعدة والجهد.','إذا تغير جوهر المهارة أو زاد الضيق.'],
['انقل الذاكرة من الرأس إلى البيئة','النسيان أو صعوبة البدء قد يخفيان القدرة على التنفيذ.','ضع الخطوة التالية في مكان حدوثها: بطاقة، صورة، قائمة قصيرة أو تذكير مرتبط بالحدث.','البدء دون تلميح، الأخطاء المنسية وزمن الإكمال.','إذا أصبحت الإشارات نفسها مصدر تشتيت.'],
['غيّر ترتيب المهمة قبل زيادة التدريب','قد تكون نقطة التعثر في ترتيب الخطوات لا في المهارة.','قدّم الجزء الأعلى كلفة في وقت الطاقة الأفضل أو جهز المواد مسبقًا أو اجمع الخطوات المتقاربة.','الوقت، الاستقلال، الأخطاء والتعب.','إذا لم يتغير الأداء بعد محاولات متكافئة.'],
['نافذة استجابة أطول بدل تكرار السؤال','قد يقطع تكرار السؤال معالجة الشخص.','اتفق على فترة انتظار مناسبة قبل إعادة السؤال مع إشارة إلى أن الدور ما يزال للشخص.','عدد الاستجابات المستقلة وجودتها.','إذا سبب الانتظار ضغطًا أو لم يلائم طريقة التواصل.'],
['مهمة واحدة بطريقتين','يصعب معرفة هل الحاجز في المهارة أم في عرضها.','قدّم نسختين متكافئتين: نص فقط ثم دعم بصري، أو تعليمات طويلة ثم خطوات قصيرة.','فرق الدقة والوقت والاستقلال.','إذا لم تكن النسختان تقيسان المهارة نفسها.'],
['قِس تكلفة النجاح','قد يبدو الأداء ممتازًا بينما يترك الشخص منهكًا أو متألمًا.','أضف للأداء قياس الألم أو التعب أو الضيق ومدة التعافي.','الأداء + كلفة الأداء + مدة التعافي.','إذا كان النجاح الظاهري يتطلب كلفة غير مقبولة.'],
['اختبر في سياق ثانٍ قبل التعميم','النجاح مرة واحدة قد يعتمد على المكان أو الشخص.','أعد المهارة في موقف مشابه مع تغيير عنصر سياقي واحد.','ثبات الدقة والاستقلال والجهد.','إذا كان النقل غير آمن أو لا يخدم هدفًا حقيقيًا.'],
['بدّل التلميح البشري بأداة يملكها الشخص','قد يبقى النجاح معتمدًا على شخص آخر.','حوّل التلميح إلى قائمة أو مؤقت أو رمز أو تسلسل صور أو تقنية مساعدة يختارها الشخص.','انخفاض التلميحات مع ثبات الجودة والرضا.','إذا كانت الأداة أصعب أو غير مرغوبة.'],
['اجعل الرفض جزءًا من القياس','قد يُفسر الامتثال على أنه نجاح رغم غياب وسيلة رفض واضحة.','وفّر وسيلة صريحة للرفض والتوقف وتغيير المهمة.','وضوح الاختيار والمبادرة والاستمرار الطوعي والضيق.','لا تستمر تجربة لا تسمح برفض مفهوم.'],
['ابدأ من الحياة الحقيقية ثم ارجع إلى التدريب','قد يتحسن تمرين معزول بلا أثر وظيفي.','اختر موقفًا يوميًا مهمًا، حدّد الجزء المتعثر، درّبه ثم أعده إلى الموقف الحقيقي.','تحسن الموقف اليومي نفسه.','إذا استمر التدريب دون انتقال ملموس.']
] as const;

export default function CapabilityIdeasPage(){return <><SiteHeader/><main className="trust-page-shell"><nav className="breadcrumbs" aria-label="مسار الصفحة"><Link href="/">الرئيسية</Link><span>/</span><Link href="/sectors/capabilities">لنرتقي بقدراتهم</Link><span>/</span><span aria-current="page">أفكار خارج الصندوق</span></nav><header style={{maxWidth:900,margin:'0 auto 2.5rem'}}><span className="eyebrow">تجارب صغيرة، لا وصفات جاهزة</span><h1>أفكار خارج الصندوق</h1><p style={{fontSize:'1.12rem',lineHeight:2}}>الإبداع هنا لا يعني تجربة أي شيء. الفكرة الجيدة تبدأ بحاجز محدد، تغيّر عنصرًا واحدًا، تقيس الأثر، وتحترم حق الشخص في الرفض. إذا لم تتحسن المشاركة أو الاستقلال، أو ارتفع الألم أو التعب أو الضيق، فالتعديل لا يصبح جيدًا لمجرد أنه مبتكر.</p></header><div style={{maxWidth:1000,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(290px,1fr))',gap:'1rem'}}>{ideas.map(([title,problem,trial,measure,stop])=><article key={title} style={{border:'1px solid rgba(7,95,97,.16)',borderRadius:20,padding:'1.4rem',background:'#fff'}}><h2 style={{fontSize:'1.25rem',marginTop:0}}>{title}</h2><p><strong>المشكلة:</strong> {problem}</p><p><strong>جرّب:</strong> {trial}</p><p><strong>قِس:</strong> {measure}</p><p style={{marginBottom:0}}><strong>توقف أو عدّل عندما:</strong> {stop}</p></article>)}</div><section style={{maxWidth:900,margin:'3rem auto',lineHeight:1.9}}><h2>حوّل الفكرة إلى تجربة آمنة</h2><ol><li>اختر هدفًا يهم الشخص.</li><li>حدد حاجزًا واحدًا.</li><li>سجّل خط أساس.</li><li>غيّر عنصرًا واحدًا.</li><li>قِس الأداء والاستقلال والجهد والرضا.</li><li>أعد التجربة في سياق ثانٍ قبل التعميم.</li><li>احتفظ بما يفيد وأوقف ما يزيد العبء.</li></ol><div style={{display:'flex',gap:'.75rem',flexWrap:'wrap'}}><Link href="/capabilities/printables/" className="button">استخدم أوراق القياس</Link><Link href="/capabilities/protocol/" className="button button-secondary">البروتوكول الكامل</Link></div></section><section style={{maxWidth:900,margin:'0 auto 3rem',lineHeight:1.9}}><h2>الأساس العلمي</h2><p>تستند الأفكار إلى مبادئ الوظيفة والمشاركة وإزالة الحواجز، التصميم الشامل للتعلم، التقنية المساعدة، القرار المشترك والتقييم الفردي المتكرر.</p><ul><li><a href="https://www.who.int/standards/classifications/international-classification-of-functioning-disability-and-health" target="_blank" rel="noreferrer">WHO — ICF</a></li><li><a href="https://www.who.int/news-room/fact-sheets/detail/assistive-technology" target="_blank" rel="noreferrer">WHO — Assistive technology</a></li><li><a href="https://udlguidelines.cast.org/" target="_blank" rel="noreferrer">CAST — UDL Guidelines 3.0</a></li><li><a href="https://www.unicef.org/education/inclusive-education" target="_blank" rel="noreferrer">UNICEF — Inclusive education</a></li><li><a href="https://www.nice.org.uk/guidance/ng197" target="_blank" rel="noreferrer">NICE — Shared decision making</a></li></ul></section></main><SiteFooter/></>}
