import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import KidsLabPrintButton from '@/components/kids-lab-print-button';
import { buildSeoMetadata } from '@/lib/seo';
import { getLanguageReadingActivitiesForSeries, getLanguageReadingActivity, getLanguageReadingSeries, languageReadingActivities } from '@/lib/capabilities/language-reading-lab';
import styles from '../../../kids-lab.module.css';

type Props={params:Promise<{series:string;activity:string}>};
export function generateStaticParams(){return languageReadingActivities.map(a=>({series:a.seriesSlug,activity:a.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {series,activity}=await params;const a=getLanguageReadingActivity(series,activity);if(!a)return{};return buildSeoMetadata({title:`${a.seriesTitle} - ${a.label} | نشاط عربي قابل للطباعة`,description:`${a.purpose} ${a.instruction}`,path:`/capabilities/kids-lab/language-reading/${series}/${activity}/`,index:true,keywords:[a.seriesTitle,'الاستعداد للقراءة','ورقة عمل عربية',a.label]});}
export default async function LanguageReadingActivityPage({params}:Props){const {series:seriesSlug,activity:activitySlug}=await params;const s=getLanguageReadingSeries(seriesSlug),a=getLanguageReadingActivity(seriesSlug,activitySlug);if(!s||!a)notFound();const items=getLanguageReadingActivitiesForSeries(seriesSlug),i=items.findIndex(x=>x.slug===a.slug),prev=i>0?items[i-1]:null,next=i<items.length-1?items[i+1]:null,imageUrl=`/capabilities/kids-lab/language-reading/${seriesSlug}/${a.slug}/image/`;return <><div className={styles.noPrint}><SiteHeader/></div><main className={styles.shell}><nav className={`breadcrumbs ${styles.noPrint}`}><Link href="/">الرئيسية</Link><span>/</span><Link href="/capabilities/kids-lab/">مختبر الأطفال</Link><span>/</span><Link href="/capabilities/kids-lab/language-reading/">اللغة والاستعداد للقراءة</Link><span>/</span><Link href={`/capabilities/kids-lab/language-reading/${s.slug}/`}>{s.title}</Link><span>/</span><span>{a.label}</span></nav><div className={styles.activityLayout}><section className={styles.worksheetFrame}><img src={imageUrl} alt={`${a.seriesTitle} - ${a.label}`}/></section><aside className={`${styles.sidePanel} ${styles.noPrint}`}><section className={styles.infoCard}><span className={styles.kicker}>{a.label}</span><h1>{a.seriesTitle}</h1><div className={styles.metaRow}><span className={styles.metaChip}>{a.age}</span><span className={styles.metaChip}>{a.duration}</span><span className={styles.metaChip}>المستوى {a.level}/5</span></div><p><strong>الهدف:</strong><br/>{a.purpose}</p><p><strong>التعليمات:</strong><br/>{a.instruction}</p><p><strong>التدرج:</strong><br/>{a.progression}</p></section><section className={styles.infoCard}><h2>المعاينة والطباعة</h2><div className={styles.actions}><KidsLabPrintButton/><a className={styles.secondaryButton} href={imageUrl} download={`${s.slug}-${a.slug}.svg`}>تنزيل SVG</a></div></section><section className={styles.infoCard}><h3>{a.kind==='test'?'معيار الإتقان':'ما الذي نراقبه؟'}</h3><p>{a.kind==='test'?a.mastery:a.observation}</p>{a.kind==='test'&&<p><strong>تنبيه:</strong> اختبار إتقان تعليمي وليس اختبار قراءة أو لغة معياريًا أو أداة تشخيص.</p>}</section><div className={styles.actions}>{prev&&<Link className={styles.secondaryButton} href={`/capabilities/kids-lab/language-reading/${s.slug}/${prev.slug}/`}>السابق</Link>}{next&&<Link className={styles.primaryButton} href={`/capabilities/kids-lab/language-reading/${s.slug}/${next.slug}/`}>التالي</Link>}</div></aside></div></main><div className={styles.noPrint}><SiteFooter/></div></>}
