import type { Metadata } from 'next';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import { createClient } from '@/lib/supabase/server';
import { buildSeoMetadata } from '@/lib/seo';
import { submitCenterApplication } from '../actions';

export const dynamic='force-dynamic';
export const metadata:Metadata=buildSeoMetadata({title:'تسجيل مركز',description:'قدّم طلب تسجيل مركز أو عيادة أو جهة تأهيلية في منصة روافد مع بيانات الخدمات والموقع والترخيص للمراجعة والتوثيق.',path:'/join/center',index:true});
type SearchParams=Promise<{status?:string;error?:string}>;
type Application={slug:string;name:string;description:string|null;email:string|null;phone:string|null;website_url:string|null;country:string|null;region:string|null;city:string|null;address:string|null;latitude:number|null;longitude:number|null;working_hours:unknown;center_type:string;services:string[];languages:string[];offers_remote:boolean;offers_in_person:boolean;license_number:string|null;regulatory_authority:string|null;license_expiry_date:string|null;verification:string;verification_note:string|null;updated_at:string};
const LABELS:Record<string,string>={pending:'قيد المراجعة',rejected:'يحتاج تصحيحًا',unverified:'غير مكتمل',suspended:'موقوف',verified:'موثق'};
const TYPES=[['center','مركز'],['clinic','عيادة'],['hospital','مستشفى'],['rehabilitation_center','مركز تأهيل'],['association','جمعية'],['school','مدرسة / مؤسسة تعليمية'],['other','أخرى']];
function hours(v:unknown){if(!v||typeof v!=='object'||Array.isArray(v))return'';return Object.entries(v as Record<string,unknown>).map(([k,val])=>`${k}: ${String(val)}`).join('\n')}

export default async function CenterJoin({searchParams}:{searchParams:SearchParams}){
 const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const uid=claims?.claims?.sub;const params=await searchParams;
 if(!uid)return <><SiteHeader/><main className="join-shell join-form-shell"><section className="join-auth-gate"><span className="eyebrow">طلب مركز</span><h1>اربط الطلب بحساب مسؤول المركز</h1><p>يُستخدم الحساب لمتابعة قرار التوثيق، وبعد الاعتماد ستتاح لمسؤول المركز مساحة إدارة الملف والخدمات.</p><div><Link className="primary-link" href="/login?next=%2Fjoin%2Fcenter">تسجيل الدخول</Link><Link className="button" href="/register?next=%2Fjoin%2Fcenter">إنشاء حساب</Link><Link className="button" href="/join">العودة لخيارات الانضمام</Link></div></section></main><SiteFooter/></>;
 const {data:profile}=await supabase.from('profiles').select('display_name,role,is_active').eq('id',uid).single();if(!profile?.is_active)redirect('/account');if(profile.role==='center_manager')redirect('/center');if(profile.role==='specialist')redirect('/specialist');if(profile.role==='owner'||profile.role==='admin')redirect('/admin');if(profile.role!=='user')redirect('/account');
 const {data}=await supabase.rpc('get_my_center_application');const app=Array.isArray(data)&&data[0]?data[0] as Application:null;
 return <><SiteHeader/><main className="join-shell join-form-shell"><nav className="breadcrumbs"><Link href="/">الرئيسية</Link><span>/</span><Link href="/join">الانضمام</Link><span>/</span><span>مركز</span></nav><section className="join-form-head"><div><span className="eyebrow">طلب تسجيل جهة</span><h1>طلب تسجيل مركز</h1><p>أدخل بيانات المنشأة والخدمات والترخيص والموقع. لن يظهر المركز في الدليل قبل اعتماد فريق التوثيق.</p></div>{app&&<div className={`application-status status-${app.verification}`}><span>حالة الطلب</span><strong>{LABELS[app.verification]??app.verification}</strong><small>آخر تحديث {new Intl.DateTimeFormat('ar',{dateStyle:'medium'}).format(new Date(app.updated_at))}</small></div>}</section>
 {params.status==='submitted'&&<div className="system-message success">تم إرسال طلب المركز للمراجعة. ستظهر ملاحظة فريق التوثيق والقرار هنا وفي الإشعارات.</div>}{params.error&&<div className="system-message error">تعذر إرسال الطلب. تحقق من البيانات وعدم وجود طلب مختص مرتبط بنفس الحساب.</div>}{app?.verification_note&&<div className="review-note"><strong>ملاحظة فريق التوثيق</strong><p>{app.verification_note}</p></div>}
 {app&&<div className="portal-notice"><strong>مستندات توثيق المنشأة</strong><span>ارفع تسجيل المنشأة والترخيص أو الوثائق الداعمة في مساحة خاصة لا تظهر للعامة.</span><Link className="button" href="/account/verification-documents">إدارة مستندات التوثيق</Link></div>}
 <form action={submitCenterApplication} className="application-form"><section className="portal-section"><div className="section-mini-heading"><h2>هوية المنشأة</h2><span>بيانات المراجعة الأساسية</span></div><div className="cms-grid"><label>اسم المركز<input name="name" required minLength={2} maxLength={220} defaultValue={app?.name??''}/></label><label>الرابط العام المقترح<input name="slug" required dir="ltr" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={140} defaultValue={app?.slug??''} placeholder="center-name"/></label><label>نوع المنشأة<select name="center_type" defaultValue={app?.center_type??'center'}>{TYPES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>اللغات<input name="languages" defaultValue={(app?.languages??[]).join(', ')} placeholder="العربية، الإنجليزية"/></label><label className="cms-wide">الخدمات<input name="services" required defaultValue={(app?.services??[]).join(', ')} placeholder="تقييم، علاج نفسي، تأهيل، تدريب..."/></label><label className="cms-wide">وصف المركز<textarea name="description" rows={7} maxLength={12000} defaultValue={app?.description??''}/></label><label className="check-field"><input name="offers_remote" type="checkbox" defaultChecked={app?.offers_remote??false}/> خدمات عن بُعد</label><label className="check-field"><input name="offers_in_person" type="checkbox" defaultChecked={app?.offers_in_person??true}/> خدمات حضورية</label></div></section>
 <section className="portal-section"><div className="section-mini-heading"><h2>الموقع وساعات العمل</h2><span>تُستخدم الخريطة بعد التوثيق فقط</span></div><div className="cms-grid"><label>الدولة<input name="country" maxLength={120} defaultValue={app?.country??''}/></label><label>المنطقة / المحافظة<input name="region" maxLength={120} defaultValue={app?.region??''}/></label><label>المدينة<input name="city" maxLength={120} defaultValue={app?.city??''}/></label><label className="cms-wide">العنوان<input name="address" maxLength={500} defaultValue={app?.address??''}/></label><label>خط العرض<input name="latitude" type="number" step="any" min="-90" max="90" dir="ltr" defaultValue={app?.latitude??''}/></label><label>خط الطول<input name="longitude" type="number" step="any" min="-180" max="180" dir="ltr" defaultValue={app?.longitude??''}/></label><label className="cms-wide">ساعات العمل — يوم: ساعات<textarea name="working_hours" rows={6} defaultValue={hours(app?.working_hours)} placeholder={'الأحد: 09:00 - 17:00\nالاثنين: 09:00 - 17:00'}/></label></div></section>
 <section className="portal-section"><div className="section-mini-heading"><h2>الترخيص والتواصل</h2><span>للتوثيق والمراجعة</span></div><div className="cms-grid"><label>رقم الترخيص / التسجيل<input name="license_number" maxLength={200} dir="ltr" defaultValue={app?.license_number??''}/></label><label>الجهة التنظيمية<input name="regulatory_authority" maxLength={240} defaultValue={app?.regulatory_authority??''}/></label><label>انتهاء الترخيص<input name="license_expiry_date" type="date" defaultValue={app?.license_expiry_date??''}/></label><label>البريد<input name="email" type="email" maxLength={254} defaultValue={app?.email??''}/></label><label>الهاتف<input name="phone" maxLength={80} dir="ltr" defaultValue={app?.phone??''}/></label><label className="cms-wide">الموقع الإلكتروني<input name="website_url" type="url" maxLength={500} dir="ltr" defaultValue={app?.website_url??''} placeholder="https://"/></label></div></section><div className="cms-actions"><button className="primary-action" type="submit">{app?'تحديث وإعادة إرسال الطلب':'إرسال طلب المركز'}</button><span>بعد الإرسال يمكنك رفع الوثائق الخاصة. بعد الاعتماد ستتاح لك مساحة المركز لإدارة الملف والخدمات.</span></div></form>
 </main><SiteFooter/></>;
}
