import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata:Metadata={title:'تدقيق إمكانية الوصول للمحتوى الرقمي | روافد',description:'قائمة تدقيق عربية عملية مستندة إلى إرشادات Sightsavers وWCAG لفحص النصوص والروابط والصور والوسائط ولوحة المفاتيح والحركة والملفات.',alternates:{canonical:'https://healthrenewal.org/accessibility/audit/'}};

const groups=[
 {title:'النص والقراءة',items:['الخط واضح وبحجم مريح ويمكن تكبيره دون فقد المحتوى.','لا نستخدم عددًا كبيرًا من الخطوط أو الأنماط المتنافسة.','النص غير مبرر بالكامل؛ المسافات بين الكلمات لا تصبح غير منتظمة.','نتجنب المقاطع الطويلة المكتوبة بأحرف كبيرة أو مائلة/مسطرة بلا ضرورة.','طول السطر والمسافة بين السطور يسمحان بالقراءة المريحة.']},
 {title:'البنية والمعنى',items:['لكل صفحة عنوان واضح وفريد.','تسلسل H1 ثم H2 ثم H3 يعكس المعنى ولا يستخدم لمجرد الشكل.','القوائم والجداول والنماذج تستخدم عناصر HTML الدلالية المناسبة.','التعليمات لا تعتمد على الموقع أو الشكل فقط مثل «الزر على اليمين».','المحتوى يبقى مفهومًا عند تكبير النص أو تغيير العرض.']},
 {title:'الصور والرسوم واللون',items:['كل صورة معلوماتية لها نص بديل يصف الغرض أو المعلومة المهمة.','الرسوم البيانية والجداول لها بديل نصي أو شرح كافٍ.','لا نعتمد على اللون وحده لتمييز الحالة أو الفئة أو الخطأ.','التباين كافٍ للنصوص والعناصر التفاعلية.','الصور الزخرفية لا تضيف ضوضاء لقارئ الشاشة.']},
 {title:'الروابط والنماذج',items:['نص الرابط يصف الوجهة أو الإجراء؛ لا نعتمد على «اضغط هنا» أو «اقرأ المزيد» وحدها.','الروابط المؤدية للوجهة نفسها تستخدم وصفًا متسقًا.','كل حقل نموذج له label واضح وتعليمات وأخطاء مفهومة.','حالة التركيز Focus ظاهرة بوضوح.','ترتيب التبويب منطقي ويتبع تسلسل الصفحة.']},
 {title:'لوحة المفاتيح والحركة',items:['يمكن الوصول لكل وظائف الصفحة بلوحة المفاتيح دون فأرة.','لا توجد مصيدة تركيز تمنع المستخدم من مغادرة عنصر.','أي محتوى يتحرك أو يمرر أو يتغير تلقائيًا يمكن إيقافه أو إخفاؤه.','لا يوجد وميض متكرر خطر.','لا يبدأ صوت تلقائيًا بما يعيق مستخدم قارئ الشاشة.']},
 {title:'الفيديو والملفات',items:['الفيديو المهم يوفر تسميات/ترجمة نصية، والنص أو الوصف عند الحاجة.','المحتوى الصوتي المهم له نص مكتوب.','PDF المهم متاح بصيغة قابلة للوصول، ويفضل توفير بديل HTML للمحتوى الأساسي.','الملفات تحمل عناوين وأسماء روابط تصف محتواها ونوعها.','يتم اختبار المواد مع قارئ شاشة وتكبير ولوحة مفاتيح حيثما أمكن.']},
];
const s={shell:{maxWidth:1120,margin:'0 auto',padding:'28px 18px 60px',lineHeight:1.9} as const,hero:{padding:24,border:'1px solid #d4e1dc',borderRadius:18,background:'#f5faf8'} as const,grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14,marginTop:18} as const,card:{border:'1px solid #d8e2de',borderRadius:16,padding:18,background:'#fff'} as const,item:{display:'grid',gridTemplateColumns:'24px 1fr',gap:8,alignItems:'start',margin:'10px 0'} as const,note:{padding:16,background:'#fff7e7',borderInlineStart:'5px solid #8a5a12',marginTop:18} as const};

export default function AccessibilityAudit(){return <main dir="rtl" style={s.shell}>
 <nav aria-label="مسار الصفحة"><Link href="/">الرئيسية</Link> · <Link href="/accessibility/">إمكانية الوصول</Link> · <span aria-current="page">أداة التدقيق</span></nav>
 <section style={s.hero}><h1>تدقيق إمكانية الوصول للمحتوى الرقمي</h1><p>قائمة عملية مستندة إلى Accessibility Pack الذي أرسلته لنا Sightsavers وإلى مبادئ WCAG التي يحيل إليها المصدر. استخدمها قبل نشر صفحة أو أداة أو PDF، ثم اختبر فعليًا بلوحة المفاتيح وقارئ الشاشة والتكبير بدل اعتبار القائمة شهادة امتثال.</p><p><a href="#checklist">ابدأ الفحص ↓</a></p></section>
 <section id="checklist" style={s.grid}>{groups.map(group=><fieldset key={group.title} style={s.card}><legend><strong>{group.title}</strong></legend>{group.items.map((item,i)=><label key={item} style={s.item}><input type="checkbox" name={`${group.title}-${i}`} /><span>{item}</span></label>)}</fieldset>)}</section>
 <section style={s.note}><h2>كيف تستخدم النتيجة؟</h2><ol><li>أي بند غير متحقق يصبح عيبًا يحتاج إصلاحًا أو توثيق استثناء.</li><li>الأخطاء التي تمنع الوصول بالمفاتيح أو قارئ الشاشة أو فهم المعلومات لها أولوية أعلى من التحسينات الجمالية.</li><li>اختبر على الهاتف وسطح المكتب، ومع تكبير النص، وباستخدام لوحة المفاتيح فقط.</li><li>وجود checklist مكتملة لا يساوي تلقائيًا WCAG 2.2 AA؛ الامتثال يحتاج فحص معايير وتقنيات واختبارًا بشريًا.</li></ol></section>
 <section style={s.card}><h2>المصدر الذي استُخدم</h2><p><a href="https://www.sightsavers.org/brand-book/accessibility-pack/" target="_blank" rel="noopener noreferrer">Sightsavers — Accessibility Pack</a></p><p><a href="https://www.w3.org/WAI/standards-guidelines/wcag/" target="_blank" rel="noopener noreferrer">W3C — Web Content Accessibility Guidelines</a></p><p>هذه الأداة إعداد مستقل من روافد، ولا تعني مراجعة Sightsavers أو اعتمادها للموقع.</p></section>
 </main>}
